### ISSUE TITLE
[Style] Enhance Palindrome Calculator UI

### ISSUE THREAD

**Issue by DiwareNamrata23** [Rakesh9100/CalcDiverse#1000]
### What's the style idea?

We need to improve the styling of palindrome calculator . By giving different animations and improving the styling of that page we can achieve the requirement

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by DiwareNamrata23** [comment]
I think ,I can improve the styling of palindrome calculator page in better way

**Comment by Rakesh9100** [comment]
Proceed @DiwareNamrata23

**Comment by Rakesh9100** [comment]
Issue 659 is already open for this, you can comment there if you want to work @DiwareNamrata23
