### ISSUE TITLE
[Feature] Implement dark mode functionality

### ISSUE THREAD

**Issue by DiwareNamrata23** [Rakesh9100/CalcDiverse#1001]
### Description

To implement dark mode functionality , involves several steps, including detecting the user's preference for dark mode, allowing users to toggle between light and dark modes, and applying the appropriate styles.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 515 is already open for this, you can comment there if you want to work @DiwareNamrata23
