### ISSUE TITLE
[Feature] Add Remove Subject option in Grade Calculator

### ISSUE THREAD

**Issue by dadigavasavipriya** [Rakesh9100/CalcDiverse#1002]
### Description

Currently, the grade calculation form allows users to dynamically add subject fields to enter marks, but it lacks the functionality to remove mistakenly added subject fields. This can lead to incorrect data entry and user frustration. We need to enhance the form by adding a remove button next to each subject field, allowing users to easily delete unwanted fields. 

--Add a remove button next to each subject field.
--Implement a removeSubjectField function to handle the removal of subject fields.

This update allows users to have a better experience with the form, as they will be able to add and remove subject fields as needed, ensuring accurate data entry.

Additionally, the current format for entering marks (e.g., "99,100") can be confusing to users. 
To improve clarity and user experience, my suggestion is to update the input format to "99/100", which is more intuitive.

To address these issues, I propose the following enhancements:
Add a remove button next to each subject field.
Update the input format for marks from "99,100" to "99/100".

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @dadigavasavipriya

**Comment by dadigavasavipriya** [comment]
@Rakesh9100 Thank you for assigning me this issue.
Can you please label level to this issue.

**Comment by Rakesh9100** [comment]
Pls provide your PR @dadigavasavipriya

**Comment by dadigavasavipriya** [comment]
@Rakesh9100, I found conflicts in my pull request. I am working on resolving them, and by tomorrow, I will provide the updated version. Thank you for your patience as I clear up this conflict.

**Comment by dadigavasavipriya** [comment]
@Rakesh9100 please check the pull request with all the conflicts resolved. Thank you for your patience.

**Comment by dadigavasavipriya** [comment]
Thankyou @Rakesh9100.I am glad to contribute to this project
