### ISSUE TITLE
[Style] Make Website Bandwidth Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#1004]
### Description

Website Bandwidth Calculator responsive should be responsive.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/579d22e3-85ba-4a6b-b0e3-5b3bd4e9b721)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @agastya3636
