### ISSUE TITLE
[Style] Make Weather Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#1005]
### Description

Weather Calculator should be responsive, I will fix it.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/2cb70ebb-195a-4ab6-9944-d9e5bfc8cabe)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @agastya3636

**Comment by Rakesh9100** [comment]
Result box is going out, do fix @agastya3636 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/e74512f3-ac1b-4747-a44d-e47d5cdaafd1)
