### ISSUE TITLE
[Style] Make Water Intake Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#1006]
### Description

It is not responsive so it is not clearly visible in mobile

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/f3098285-a5e1-43fe-a3a2-bb86133c75ee)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
I can see Water Intake Calculator is already responsive @agastya3636

**Comment by agastya3636** [comment]
It is very small not visible in mobile veiw

**Comment by Rakesh9100** [comment]
Okay, complete your assigned issues first @agastya3636

**Comment by agastya3636** [comment]
@Rakesh9100 completed all the previous issues please assign this to me

**Comment by Rakesh9100** [comment]
Proceed @agastya3636

**Comment by agastya3636** [comment]
It has been fixed by others
