### ISSUE TITLE
[Style] Make Unit Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#1007]
### Description

Unit Calculator view in mobile is not correct. I would like to fix it.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/493bc345-cd5c-4e17-8560-092a4635d5af)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by agastya3636** [comment]
@Rakesh9100 please assign it to me I  completed previous issues

**Comment by Rakesh9100** [comment]
You are assigned to issue 838 which is not completed @agastya3636

**Comment by agastya3636** [comment]
i will complete by tomorrow

**Comment by agastya3636** [comment]
@Rakesh9100 completed all the previous issues please assign this to me

**Comment by Rakesh9100** [comment]
Unit Calculator is already responsive, check once @agastya3636

**Comment by agastya3636** [comment]
it has been made responsive 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/5a133e1c-65ac-4b9a-865c-f660fb6bdcdf)

sorry I will the issue now
