### ISSUE TITLE
Adding EMI Calculator

### ISSUE THREAD

**Issue by Shreyas-SAS** [Rakesh9100/CalcDiverse#101]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Although a reference was made about this in #46 a bit but the issue is in semi close state.

I wish to create a calculator that could calculate the monthly EMI based on the principle/loan amount, the interest rate and the tenure of the loan. Apart from this it will also display the total interest you paid throughout the tenure.

Additionally it can also calculate how much time it will take for loan to be repaid with a certain EMI amount that most online calculators miss including for those who would think about extending loan or those who want to finish the loan early.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Issue #14 is already opened for the same feature. If you wish to work on, pls comment on that issue to get assigned @Shreyas-SAS
