### ISSUE TITLE
[Feature] Add Fascinating Number Calculator

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#1011]
### Description

The number(x) is fascinating if number contains all the digits from 1 to 9 exactly once and does not contain any 0's 
after Concatenating (x) with the numbers 2 * x and 3 * x.
Example : n= 192 as (192 * 2 = 384 and 192 * 3 = 576) and after concatenating it become (192384576) which contain all the digits from 1 to 9.
I want to add this calculator 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Anshika14528
