### ISSUE TITLE
[Feature] Add Ugly Number Calculator

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#1012]
### Description

An ugly number is a positive integer whose prime factors are limited to 2, 3, and 5.
I want to add this calculator
Example : 6 is a ugly number as it have only 2 and 3 as prime factor.
I want to add this calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Anshika14528
