### ISSUE TITLE
[Style] Make Trigonometric Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#1013]
### Description

In mobile view some fields are not visible i would like to fix it

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/00567a17-a337-4f25-a2e2-e207ef9fed38)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by agastya3636** [comment]
@Rakesh9100 completed all the previous issues please assign this to me

**Comment by Rakesh9100** [comment]
Go ahead @agastya3636
