### ISSUE TITLE
[Feature] Add Sentence Counter Calculator

### ISSUE THREAD

**Issue by vedanshipathak** [Rakesh9100/CalcDiverse#1017]
### Description

This Calculator would find how many number of sentences are present in the written text.
It will take the value from the text area and find how many sentences are present in a given paragraph.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @vedanshipathak
