### ISSUE TITLE
[Feature] Add Complement Calculator

### ISSUE THREAD

**Issue by its-kumar-yash** [Rakesh9100/CalcDiverse#1018]
### Description

The Complement Calculator takes a number and the base in which the number is written, and then finds the nth complement of the number as per the input.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/b841b3d9-cbdf-4de9-a982-5563c9c3e6b8)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/b41b0849-fc6b-45c7-aa3b-f81b8098a892)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @its-kumar-yash
