### ISSUE TITLE
Adding International GPA converter (10pt to 7pt to 4pt to percentage)

### ISSUE THREAD

**Issue by Shreyas-SAS** [Rakesh9100/CalcDiverse#102]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

CGPA convertor NOT Calculator (Different from the one made by kom)

Different countries have different rules of considering Grades and Grade points. Some have a 10 point system with CGPA (0 to 10) some have a 7 point GPA system (0-7) or a 4 point GPA system (0-4) and some just percentage as either full converting to 100% or just 95%.

I wish to build a convertor for this. I know there is a CGPA calculator made by kom but this is a convertor not calculator. The functions are different. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @Shreyas-SAS

**Comment by Rakesh9100** [comment]
@Shreyas-SAS Are you working

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS Are you working
yes, I am working on them one by one. was travelling yesterday due to start of academic semester so couldn't work. will push all the assigned tasks by today night I believe.

**Comment by Rakesh9100** [comment]
Okay @Shreyas-SAS

**Comment by Shreyas-SAS** [comment]
As mentioned in EMI issue. 

I am currently having some urgent and important work regarding academics. I am really sorry for the delay. Will push the PR as soon as possible before 2 days. 

Sorry for the delay. 

Thanks,
Shreyas.

**Comment by Rakesh9100** [comment]
@Shreyas-SAS Update pls

**Comment by Shreyas-SAS** [comment]
@Rakesh9100 I will push this one tonight. have some issues with the concept of converting cgpa to 4 and 7 scales. will once check the validity and accuracy of answers and will push it soon.

**Comment by Rakesh9100** [comment]
PR Update @Shreyas-SAS
