### ISSUE TITLE
[Feature] Add Cross Product Calculator

### ISSUE THREAD

**Issue by vedanshipathak** [Rakesh9100/CalcDiverse#1021]
### Description

It will calculate the cross product of the equations given along with the angle made between them.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @vedanshipathak

**Comment by Akshx09** [comment]
please assign it to me
