### ISSUE TITLE
[Feature] Add Emirp Number Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#1022]
### Description

Emirp Number: A prime number that results in a different prime when its digits are reversed. Example: 13 (which reversed is 31, also a prime).

I can add an emirp number calculator 
1. It can tell if a number is an emirp number or not
2. It can print all the emirp numbers in a given range

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by debangi29** [comment]
Please assign me the issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @debangi29

**Comment by Rakesh9100** [comment]
Pls provide your PR @debangi29
