### ISSUE TITLE
[Feature] Add Mersenne Prime Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#1023]
### Description

 A prime number that is one less than a power of two. Example: 31 (which is 2^5 - 1).
 I can add a Mersenne Prime number calculator which can check if a number is Mersenne Prime number or not and calculate Mersenne Prime numbers in a given range

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by debangi29** [comment]
Please assign me the issue @Rakesh9100

**Comment by bheemajayashreee** [comment]
Please assign this issue to me @Rakesh9100

**Comment by Rakesh9100** [comment]
Do you want to be assigned or should I assign to someone else @debangi29

**Comment by debangi29** [comment]
You can assign it to someone else @Rakesh9100 thankss

**Comment by debangi29** [comment]
Hello @Rakesh9100 

I am ready to work on it now

Sorry for the inconvenience caused
Thanks
Please assign it to me

**Comment by Rakesh9100** [comment]
Okay, go ahead @debangi29

**Comment by Rakesh9100** [comment]
Pls provide your PR @debangi29
