### ISSUE TITLE
[Feature] Add CPU Scheduling Calculator

### ISSUE THREAD

**Issue by MohiniMehta** [Rakesh9100/CalcDiverse#1024]
### Description

The Process Scheduling Calculator is used to analyze various CPU scheduling algorithms. This calculator will be useful for students studying Operating Systems. This will help to understand how different scheduling algorithms affect process execution and system performance.
The user Input will consist of a dropdown for selecting the algorithms (fcfs, sjf, roundrobin, priority, etc) and then selecting Arrival Time, Burst Time
Then after clicking on Calculate button it will calculate Finish Time, Wait time, and TurnoverTime.  
Please assign this to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @MohiniMehta
