### ISSUE TITLE
[Feature] Two Variable Linear Equation Calculator

### ISSUE THREAD

**Issue by AsmitaMishra24** [Rakesh9100/CalcDiverse#1025]
### Description

I would like to add a new feature to our project: a calculator that can solve systems of two-variable linear equations. This feature will be useful for users who need to solve equations of the form:

a1 * x + b1 * y = c1
a2 * x + b2 * y = c2

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by AsmitaMishra24** [comment]
![Screenshot 2024-06-01 211105](https://github.com/Rakesh9100/CalcDiverse/assets/146121869/ac14b3f3-8503-491c-857d-c005685791e8)

**Comment by AsmitaMishra24** [comment]
@Rakesh9100, please assign me this issue under GSSoC'24. I am really interested in working on this issue.

**Comment by AsmitaMishra24** [comment]
> ![Screenshot 2024-06-01 211105](https://private-user-images.githubusercontent.com/146121869/335811793-ac14b3f3-8503-491c-857d-c005685791e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTY4MTAsIm5iZiI6MTcxNzI1NjUxMCwicGF0aCI6Ii8xNDYxMjE4NjkvMzM1ODExNzkzLWFjMTRiM2YzLTg1MDMtNDkxYy04NTdkLWMwMDU2ODU3OTFlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxNTQxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjk2ZmVlNTc4N2FlOWI2NzJlMTI3ZmIxYmY4NWRhNTlmNzI2YTNkNzA1OTUwNTBkODNlNjA4ZDIxZmM1ZDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HoppbbhSI6ivDcxPFEu2R1zR_UPUNPSBc5bCmbSDp-U)

this an example

**Comment by AsmitaMishra24** [comment]
> ![Screenshot 2024-06-01 211105](https://private-user-images.githubusercontent.com/146121869/335811793-ac14b3f3-8503-491c-857d-c005685791e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjc0MTUsIm5iZiI6MTcxNzI2NzExNSwicGF0aCI6Ii8xNDYxMjE4NjkvMzM1ODExNzkzLWFjMTRiM2YzLTg1MDMtNDkxYy04NTdkLWMwMDU2ODU3OTFlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxODM4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWE5MjNiOGRiMGM1NTNiZThjMmE5ZDVhMjZkMDQxMGNhYWE0YzFmZDcxMzVmNDIzYzBiYjI4MDkxNjM5NGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p7vSYp3lzril9mjZxBYYYci-zC6s6y7hp5R_6_KSUNQ)

this is an example

**Comment by Rakesh9100** [comment]
We already have `Linear Equation Calculator`, pls work on new issues @AsmitaMishra24

**Comment by AsmitaMishra24** [comment]
> We already have `Linear Equation Calculator`, pls work on new issues @AsmitaMishra24

ok
