### ISSUE TITLE
Feat: Antilog Calculator

### ISSUE THREAD

**Issue by Shreyas-SAS** [Rakesh9100/CalcDiverse#103]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Standby Issue for antilog calculator post #26 completion.

Proposal: Building a method for antilog calculator in the log calculator.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @Shreyas-SAS 
You can create this as a seperate calculator and hence create a new PR.
