### ISSUE TITLE
[Feature] Add Slope Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#1031]
### Description

In this calculator we can calculate the slope of the line. If two points (in form of x and y coordinates) are given we can calculate the distance between the two points with their slope.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yuvraj960** [comment]
@Rakesh9100 I have opened one more issue #975 . Please assign both of the issues to me.

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960
