### ISSUE TITLE
[Feature] Binary to Decimal or viceversa calculator

### ISSUE THREAD

**Issue by Damini2004** [Rakesh9100/CalcDiverse#1033]
### Description

Creating a Binary to Decimal and Decimal to Binary calculator can be achieved through a simple script or a user-friendly web interface. Below are detailed descriptions of both methods and some features you might consider adding.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/119414762/b5f546aa-2ddb-4acc-bd9a-373ac1f7a235)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Number System Calculator for the same @Damini2004
