### ISSUE TITLE
[Feature] Add Cosine Formula Calculator

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#1035]
### Description

If we have given a  triangle ABC  with sides a , b, c then we can calculate angle of the triangle using cosine formula :
Cos A=(b^2+c^2-a^2)/2bc
I want to make this calculator
Please assign me this issue

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Please don't open too many issues at once. You have already opened several, complete the previous ones first @Anshika14528

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, i have completed the previous issue please assign me this issue now.

**Comment by Rakesh9100** [comment]
Go ahead @Anshika14528
