### ISSUE TITLE
[Feature] Add Word Count Calculator

### ISSUE THREAD

**Issue by Aditi22Bansal** [Rakesh9100/CalcDiverse#1036]
### Description

This tool will allow users to input their location (latitude and longitude) and the date, and it will provide them with the times of sunrise and sunset for that particular day.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142652964/53b9adfc-9dff-4ce4-aa71-d3558365e5e1)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/142652964/a0aa2dd0-e790-40e8-b712-1bfa64313277)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Kindly assign me this issue

**Comment by Rakesh9100** [comment]
We already have a Word Count Calculator @Aditi22Bansal
