### ISSUE TITLE
[Feature] Add Land Area Calculator

### ISSUE THREAD

**Issue by Damini2004** [Rakesh9100/CalcDiverse#1037]
### Description

The Land Area Calculator is designed to compute the area of land plots using different shapes and measurements. It allows users to select a shape (e.g., rectangle, triangle, circle), input the necessary dimensions, and receive the calculated area. The calculator is useful for property owners, real estate agents, surveyors, and anyone needing to determine land areas accurately.

### Screenshots

Here we can find 3 shapes area 
![Screenshot 2024-06-01 123512](https://github.com/Rakesh9100/CalcDiverse/assets/119414762/a6b40ef3-d7bd-4760-995b-7f8ca63bf2c2)
![Screenshot 2024-06-01 123531](https://github.com/Rakesh9100/CalcDiverse/assets/119414762/28b2964d-dc98-400b-9a93-b28ae8e1ec77)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This is just calculating area, which 2D Shapes Calculator is also doing @Damini2004
