### ISSUE TITLE
[Feature] Add Sunlight Hours Calculator

### ISSUE THREAD

**Issue by Aditi22Bansal** [Rakesh9100/CalcDiverse#1038]
### Description

This tool will help users estimate the number of sunlight hours in a day based on their location and the date.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142652964/4ec6f502-9303-4fd9-84bb-bc0224b04fd7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Kindly assign me this issue

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Kindly assign me this issue

**Comment by Rakesh9100** [comment]
Proceed @Aditi22Bansal

**Comment by Rakesh9100** [comment]
Pls provide your PR @Aditi22Bansal

**Comment by Aditi22Bansal** [comment]
@Rakesh9100 
Yes uploading
