### ISSUE TITLE
[Style] Make the navbar responsive

### ISSUE THREAD

**Issue by AnshuRani7781** [Rakesh9100/CalcDiverse#1042]
### What's the style idea?

observed distortion in the underline style upon resizing the website's dimensions
Screenshot before  

![Screenshot 2024-06-01 141240](https://github.com/Rakesh9100/CalcDiverse/assets/143905448/6d0d12ea-8980-4bb3-9f2d-ef44a54386c7)   
would like to provide 
 enhancement to  CSS for improved navbar  responsiveness across different screen sizes
  please assign this under gssoc'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AnshuRani7781** [comment]
@Rakesh9100
Kindly assign me this issue

**Comment by AnshuRani7781** [comment]
from the width 769 to 1041

**Comment by Rakesh9100** [comment]
Go ahead @AnshuRani7781

**Comment by Rakesh9100** [comment]
Pls provide your PR @AnshuRani7781

**Comment by m3kvt** [comment]
@Rakesh9100  I would like to work on this. Please assign me.

**Comment by Rakesh9100** [comment]
Go ahead @m3kvt
