### ISSUE TITLE
[Style] Add searching logo in Search Calculator box

### ISSUE THREAD

**Issue by shuhaki** [Rakesh9100/CalcDiverse#1043]
### Category of documentation update

Added a searching logo in "search calculator" 
<img width="434" alt="Screenshot 2024-06-01 at 2 43 17 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/145912232/f3645067-38aa-44cc-8b21-196a1d62efbf">

Added like this
<img width="515" alt="Screenshot 2024-06-01 at 2 43 43 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/145912232/d9ca226a-d5f8-4a92-993c-8c4a4bd437b5">

### Describe the change you think might work

After adding it will give good interface for user.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by nehal1222** [comment]
hey I would like to commit changes in the site like
![image](https://github.com/Rakesh9100/CalcDiverse/assets/119063830/3b34737a-79ac-41f6-a424-eeac70970e8c)
Can you please assign me the issue?
thank you.

**Comment by Rakesh9100** [comment]
Go ahead @shuhaki

**Comment by Rishikesh63** [comment]
i wants to work on it could you please assign to me

**Comment by Yuvraj960** [comment]
@Rakesh9100 Please assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @Yuvraj960

**Comment by Yuvraj960** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/146326636/f04fdee2-1f7e-4a22-8996-cb95b5ed4390)
@Rakesh9100 How's this?
