### ISSUE TITLE
[Feature] Add Banker's Algorithm Calculator

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/CalcDiverse#1047]
### Description

I want to add Banker's algorithm calculator which is use full to students who are learning operating system and wants to verify their answer i have this calculator ready i made it for my assignments this needs to some changes and it will be ready for merge !!

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/126322584/aecb03d2-89e7-40f8-b4c6-74053dbfe555)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zalabhavy** [comment]
@Rakesh9100 I have this project ready just it need to some UI changes and it's done please assign it to me i will done my work as soon as possible.

**Comment by Rakesh9100** [comment]
Go ahead @zalabhavy
