### ISSUE TITLE
Enhance The whole UI of the Home Page

### ISSUE THREAD

**Issue by CodeByRajeev** [Rakesh9100/CalcDiverse#105]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This Issue enhances the whole Interface of the Web page with magnificent colors which give user a very good impression of the user.

The before & after changes can be seen in the below Screenshots.

*Note : There are some sections which are not visible in the new screenshot as the fork was not synced. That will be solved during the PR. As the new screenshot is only for the issue purpose.

### Screenshots

Before : 

![ui home before 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/4608dd3d-732f-4396-893a-026796192656)

After : 

![ui home after 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/593c3eab-68c1-4587-83b1-28c59568a1a1)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir, please go through this and do assign the issue if this improvement can add value to the project. Also do let me know if there are any changes to be made.

**Comment by Rakesh9100** [comment]
Issue for this already exist. Pls work on other issues @CodeByRajeev
