### ISSUE TITLE
[Feature] Add Solar Power Saving Calculator

### ISSUE THREAD

**Issue by Archiesachin** [Rakesh9100/CalcDiverse#1050]
### Description

A Solar Power Savings Calculator helps users estimate the potential savings from installing solar panels on their property. This tool considers various factors such as local solar insolation (sunlight exposure), electricity consumption, current electricity rates, and the cost of solar installation to provide an estimate of both short-term and long-term financial benefits.

<h2>Key Features:</h2>

User Input Fields:

Location: To determine the average solar insolation (sunlight exposure) for the area.

Roof Area and Orientation: Size, tilt, and direction of the roof to estimate how much solar energy can be captured.

Electricity Consumption: Current monthly or annual electricity usage, often in kilowatt-hours (kWh).

Current Electricity Rate: The cost per kWh charged by the utility company.

Solar System Size: Desired size of the solar installation, typically in kilowatts (kW).

Installation Cost: Initial cost of purchasing and installing the solar panels.

Incentives and Rebates: Available government or utility rebates, tax credits, and incentives that can offset installation costs.

Financing Options: Details on how the system will be paid for (e.g., upfront payment, loan, lease).

<h2>Calculations:</h2>

Solar Energy Production: Estimates the amount of electricity the solar panels will produce annually based on location, roof characteristics, and system size.

Annual Savings: Calculates the reduction in electricity bills by multiplying the energy produced by the current electricity rate.

Payback Period: Determines the time it will take for the savings to equal the installation cost, considering incentives and financing.

Lifetime Savings: Estimates total savings over the expected life of the solar panels (typically 25-30 years).

Environmental Impact: Provides an estimate of the reduction in carbon footprint, showing the equivalent amount of CO2 emissions avoided.

<h2>Output:</h2>

Annual Energy Production: kWh generated per year.
Monthly and Annual Savings: Dollar amount saved on electricity bills.
Payback Period: Number of years to recoup the initial investment.
Total Lifetime Savings: Total savings over the lifespan of the solar panels.
Incentives and Rebates: Summary of applicable financial incentives.
Environmental Impact: Equivalent reduction in CO2 emissions and other environmental benefits.

### Screenshots

<h2>Example Use Case:</h2>

A homeowner in Los Angeles wants to install a solar power system. They input their details into the calculator:

Location: Los Angeles, CA
Roof Area and Orientation: 500 square feet, south-facing with a 30-degree tilt
Electricity Consumption: 900 kWh per month
Current Electricity Rate: $0.20 per kWh
Solar System Size: 5 kW
Installation Cost: $15,000
Incentives and Rebates: $4,500 in federal and state rebates
Financing Options: Loan with a 5% interest rate
Based on these inputs, the calculator estimates:

Annual Energy Production: 8,000 kWh
Annual Savings: $1,600
Payback Period: 6.6 years
Total Lifetime Savings: $40,000 over 25 years
Environmental Impact: Equivalent to planting 1,000 trees or removing 10 cars from the road for a year

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Archiesachin
