### ISSUE TITLE
[Feature] Add custom cursor to the website

### ISSUE THREAD

**Issue by Anjaliavv51** [Rakesh9100/CalcDiverse#1051]
### Description

Enhances of custom cursor pointer.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/154777864/a44d8015-4e2b-45b7-bdfc-a5df0673f083)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review my other PR

**Comment by Rakesh9100** [comment]
Pls provide your PR @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 by today it will be done

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR.
