### ISSUE TITLE
[Feature] Enhance Carbon Footprint Calculator

### ISSUE THREAD

**Issue by Antiquely3059** [Rakesh9100/CalcDiverse#1055]
### Description

The Carbon Footprint Calculator is a tool designed to help individuals estimate their monthly carbon emissions based on various activities and consumption habits. By inputting data such as electricity usage, gas consumption, kilometers driven, and flights taken, users can gain insight into their environmental impact and identify areas where they can reduce their carbon footprint.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have this calculator, you can enhance the UI if you want @Antiquely3059

**Comment by Antiquely3059** [comment]
The carbon footprint calculator that you already have has been done partially only taking factor of the distance travelled and that too in miles.
The calculator I will make will have all these taken into consideration, electricity usage, gas consumption, kilometers driven, and flights taken, which will make it more correct.

**Comment by Rakesh9100** [comment]
No need of same calculator again separately, you can enhance the existing one if you want @Antiquely3059

**Comment by Antiquely3059** [comment]
Ok I will enhance the existing carbon footprint calculator.
Can I go ahead ?

**Comment by Rakesh9100** [comment]
Yes @Antiquely3059
