### ISSUE TITLE
[Other] Fix the typos

### ISSUE THREAD

**Issue by NIKHIL0VERMA** [Rakesh9100/CalcDiverse#1061]
### What would you like to share?

Hey @Rakesh9100,
I found multiple typing mistakes across _**15 files**_. I could point to some if you want.
I would like to fix this under GSSOC'24. 
Kindly add the correct labels and assign me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshots @NIKHIL0VERMA

**Comment by NIKHIL0VERMA** [comment]
okay sure,
Please have a look. some are in HTML file, some are not that important.
![image](https://github.com/Rakesh9100/CalcDiverse/assets/49404370/68e64b04-86a5-4219-a1bf-83aa223dbd86)

**Comment by Rakesh9100** [comment]
Okay, proceed @NIKHIL0VERMA

**Comment by NIKHIL0VERMA** [comment]
Will do it in the evening, today
