### ISSUE TITLE
[Feature] Add Atomic Mass Calculator

### ISSUE THREAD

**Issue by bristiHalder** [Rakesh9100/CalcDiverse#1063]
### Description

The Atomic Mass Calculator is a tool designed to calculate the total atomic mass of a chemical compound based on the input of its constituent elements and their respective counts. 
Users can input the chemical formula of the compound, and the calculator will determine its atomic mass by summing the masses of the individual atoms present.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @bristiHalder

**Comment by Rakesh9100** [comment]
We already have Molecular Weight Calculator @bristiHalder
