### ISSUE TITLE
[Feature] Improve the search result based on description

### ISSUE THREAD

**Issue by aaryancodeshere** [Rakesh9100/CalcDiverse#1064]
### Description

# Search Bar is not checking the descriptions 

The search Bar on the home page does not check the description of the calculators mentioned.
It is making it harder to find the required calculator.

I faced this issue while searching for the base change/binary calculator, and the calculator's title was Number System Calculator even though 'binary' was mentioned in the description.

### Screenshots

<img width="702" alt="Screenshot 2024-06-01 at 7 45 03 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/124273822/17736353-9023-4864-acd8-2ab16bb20207">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aaryancodeshere** [comment]
@Rakesh9100 Please have a look

**Comment by aaryancodeshere** [comment]
please assign it to me @Rakesh9100

**Comment by Rakesh9100** [comment]
Issue 1014 is already open for this, you can comment there if you want to work @aaryancodeshere
