### ISSUE TITLE
[Feature] Add Periodic Table Calculator

### ISSUE THREAD

**Issue by manishh12** [Rakesh9100/CalcDiverse#1065]
### Description

The Periodic Table Calculator is a web application that provides users with:

1. **Visual Representation**: A dynamic display of the periodic table, with clickable elements for exploration.

2. **Element Information**: Detailed information about selected elements, including name, symbol, atomic number, atomic mass, and properties.

3. **Mass Calculation**: A feature to calculate the mass of a specified element based on its symbol.

4. **Educational Tool**: A valuable resource for learning about chemistry and the properties of elements.

In summary, the Periodic Table Calculator offers a user-centric, educational, and customizable solution for exploring the elements of the periodic table and conducting basic calculations related to atomic mass.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by manishh12** [comment]
@Rakesh9100 kindly assign me this.

**Comment by manishh12** [comment]
@Rakesh9100 Kindly assign me this issue.

**Comment by Rakesh9100** [comment]
Go ahead @manishh12
