### ISSUE TITLE
Enhancing heading (Calcdiverse) for making website mobile responsive 

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/CalcDiverse#107]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The h1 ("CalcDiverse") is exceeding the main container and making it unresponsive in mobile devices. The padding and font size is exceeding the inner div and is exceeding width beyond the main container, which is leading in design flaw and making is unresponsive for mobile devices

### Screenshots

![Cd_mob](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/247dd606-e90a-4cd0-80a3-aa2e87a9da70)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by pb0126** [comment]
Hi @Rakesh9100, please assign this issue to me so that I can fix this issue and create a PR.
Thanks

**Comment by Rakesh9100** [comment]
Proceed @pb0126

**Comment by Rakesh9100** [comment]
Adding an `Easy` tag in issue number 108 instead of adding `beginner` tag to both the issues @pb0126
