### ISSUE TITLE
[Feature] Add a BMI Calculator

### ISSUE THREAD

**Issue by vaishali-gupta32** [Rakesh9100/CalcDiverse#1070]
### Description

A BMI (body mass index) calculator can be added. 
It will ask for your weight and height and will tell you the correct BMI.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vaishali-gupta32** [comment]
@Rakesh9100 please assign this issue to me. I am willing to do this.

**Comment by Rakesh9100** [comment]
Go through the website and existing issues properly before creating an issue, we already have BMI calculator @vaishali-gupta32
