### ISSUE TITLE
[Feature] Add Roots Equation Calculator

### ISSUE THREAD

**Issue by sharmi4590** [Rakesh9100/CalcDiverse#1072]
### Description

I want to add an equation generator calculator for given roots. First, it will ask for the number of roots and then the user has to enter the roots, after that, the equation would be generated.
Example 1: Number of roots = 2
                  root1= 2, root2= 2
                   equation =( x^2 - 4x +4 = 0)
Example2: number of roots = 3
                  root1=1, root2=1, root3=1
                  equation = (x^3 - 3x + 3x -1 =0)
Like this, it will work for any number of roots.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open for this, you can comment on that or create new issues @sharmi4590

**Comment by sharmi4590** [comment]
@Rakesh9100 , issue #1046 the issue description states that finding roots , whereas in my description I have said that the roots will be given and they will be converted to equation. Please once check my description.

**Comment by Rakesh9100** [comment]
Okay, so do you want to work and be assigned @sharmi4590

**Comment by sharmi4590** [comment]
> Okay, so do you want to work and be assigned @sharmi4590

Yes

**Comment by Rakesh9100** [comment]
Go ahead, name it as `Roots-Equation-Calculator` @sharmi4590

**Comment by sharmi4590** [comment]
Hey @Rakesh9100 Could you please look into my PR #1673
