### ISSUE TITLE
[Feature] Add feedback button

### ISSUE THREAD

**Issue by ayushkrrana** [Rakesh9100/CalcDiverse#1073]
### Description

I can add feedback at the bottom or at the top or scrollable to whole website in which user can give their ratings 
please assign it to me @Rakesh9100 
Thank you

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you have any supporting screenshots @ayushkrrana
