### ISSUE TITLE
[Feature] Add Harshad Number Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#1075]
### Description

A number that is divisible by the sum of its digits. Example: 18 (1 + 8 = 9; 18 is divisible by 9).

I can add an harshad number calculator 
1. It can tell if a number is an harshad number or not
2. It can print all the harshad numbers in a given range

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Niven Number Calculator which is same @debangi29
