### ISSUE TITLE
[Feature] <scroll-aware-navbar>

### ISSUE THREAD

**Issue by Ketanop321** [Rakesh9100/CalcDiverse#1076]
### Description

Navbar that hides when scrolling down and shows when scrolling up 

### Screenshots

Here's a demo ⤵️, observe the movement of navbar while scrolling
https://github.com/Rakesh9100/CalcDiverse/assets/146806880/a555c4f8-1fd3-4a02-8a3c-316b45c2df79

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No, navbar will be fixed or sticky only. Pls work on good issues @Ketanop321
