### ISSUE TITLE
2d shapes card overlaps Explore calculator button in mobile screen 

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/CalcDiverse#108]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

While viewing the website on a mobile screen, the **2D shapes Calculator** card overlaps **"Explore Calculator "** button, hiding the button and creating a design flaw.

I want to make the following changes to the CSS and make it right to improve the design flaw and make the Explore Calculator button visible on the mobile screen.

### Screenshots

![cd_mob_overlap](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/e2bcb696-9fac-4e40-87c6-c4f8da61b58b)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by pb0126** [comment]
Hi, @Rakesh9100  I would like to contribute to this issue by fixing the following error. Please assign this issue to me, so that I can make the changes and request for the PR.
Thanks

**Comment by Rakesh9100** [comment]
Proceed @pb0126
