### ISSUE TITLE
[Feature] Add Euclidean Algorithm Calculator

### ISSUE THREAD

**Issue by kamalesh-og** [Rakesh9100/CalcDiverse#1080]
### Description

Hello Project Admin @Rakesh9100,
Adding an Euclidean Algorithm Calculator to CalcDiverse, enables users to estimate the GCD(greatest common divisor) and LCM of two numbers easily using Euclid's approach. Based on this information, the calculator will provide an estimated result as required.

I've already worked with CalcDiverse and imposed a calculator before and I want to contribute further to this amazing repository.

@Rakesh9100 Can you assign me this project, I would like to work on this Calculator.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/163159351/5d72e64b-e6a6-446e-81d9-234b4f511449)
This is just the outline of the page, for reference (I've worked with one such calculator before and would like to work on it to make better UI )
I'll further add the CSS and Javascript for this page to make it dynamic and more efficient.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @kamalesh-og
