### ISSUE TITLE
[Feature] Add Basic Physics Calculator

### ISSUE THREAD

**Issue by kamalesh-og** [Rakesh9100/CalcDiverse#1081]
### Description

Hello Project Admin @Rakesh9100,
Adding Basic Physics Calculator to CalcDiverse, enables users to calculate basic physics quantities like speed, acceleration, velocity, force, power, pressure, etc. It can be provided with functionality where there is a side navbar for navigating what kind of operation should take place with the appropriate parameter. Based on this information, the calculator will provide an estimated answer for the operation chosen.

I've already worked with CalcDiverse and imposed a calculator before and I want to contribute further to this amazing repository.

@Rakesh9100 Can you assign me this project, I would like to work on this Calculator.
Also, this calculator can be a one-stop solution for calculating basic physical quantities easily. So, this is a very helpful calculator.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kamalesh-og** [comment]
Will make a better UI for this one!
Can you assign me this issue @Rakesh9100 
Thank you.

**Comment by kamalesh-og** [comment]
Hi @Rakesh9100, 
can i start working on this?

**Comment by Rakesh9100** [comment]
Go ahead @kamalesh-og

**Comment by Rakesh9100** [comment]
Pls provide your PR @kamalesh-og

**Comment by kamalesh-og** [comment]
Sure @Rakesh9100, I'll make it by today 
Had university works
My apologies

**Comment by kamalesh-og** [comment]
Hi @Rakesh9100,
Done sir
