### ISSUE TITLE
[Feature] Add CGS FPS MKS Calculator

### ISSUE THREAD

**Issue by its-kumar-yash** [Rakesh9100/CalcDiverse#1087]
### Description

MKS - CGS - FPS Calculator takes a value in either of the Si unit standards and converts it into the other two Si unit standards.
Kindly assign this issue to me.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/9c0ba3f9-ec76-4812-b7fb-ad563a164343)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by its-kumar-yash** [comment]
@Rakesh9100 kindly assign this to me.

**Comment by Rakesh9100** [comment]
Proceed @its-kumar-yash
