### ISSUE TITLE
[Feature] Add Arrhenius Equation Calculator

### ISSUE THREAD

**Issue by Sara1428** [Rakesh9100/CalcDiverse#1089]
### Description

Arrhenius equation helps us to find out the activation energy (minimum energy above threshold required to start a reaction) and the rate constant of a reaction. These two are very important quantities associated with any chemical reaction.
I've made a calculator to calculate these parameters of chemical kinetics.

### Screenshots

Screenshot :-
![pic1](https://github.com/Rakesh9100/CalcDiverse/assets/146193518/65111f16-edde-4f6c-83d6-f8b528d8bf49)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Sara1428
