### ISSUE TITLE
Adding quadratic equations root calcuator

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/CalcDiverse#109]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a calculator that calculates the roots of a quadratic equation.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @saurav2208
