### ISSUE TITLE
[Feature] Add Inflation Calculator

### ISSUE THREAD

**Issue by Yashgabani845** [Rakesh9100/CalcDiverse#1094]
### Description

An inflation calculator helps you understand the effect of inflation on the value of money over time. It allows you to calculate the future value of a given amount of money based on a specified annual inflation rate. For example, you can determine how much a sum of money today will be worth in the future or how much money in the past would be worth today.

i will provide:

- basic data of future prices
- graph of infliation 
- detailed analysis

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yashgabani845** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @Yashgabani845
