### ISSUE TITLE
[Style] Enhance Complex Number Calculator UI

### ISSUE THREAD

**Issue by aaryancodeshere** [Rakesh9100/CalcDiverse#1099]
### What's the style idea?

We need to improve the design of complex number calculator.

The input bar is currently not centered, which affects the overall alignment and user experience. Additionally, the color scheme used for text selection does not provide optimal readability and aesthetics.

Please consider making adjustments to center the input bar and revise the color palette to enhance visual appeal and usability.

<img width="679" alt="Screenshot 2024-06-02 at 6 01 50 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/124273822/95d441f9-ae8d-4870-bf54-5db9a61cfe03">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aaryancodeshere** [comment]
please assign it to me @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @aaryancodeshere
