### ISSUE TITLE
Adding decimal to binary converter

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/CalcDiverse#110]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Would like to add a converter that coverts a decimal number into binary.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Same issue already exist. Pls work on other issues @bhavya-anand19
