### ISSUE TITLE
[Feature] Add Gamified Calculator

### ISSUE THREAD

**Issue by Vipullakum007** [Rakesh9100/CalcDiverse#1100]
### Brief Description
A calculator that turns math problems into a game, rewarding correct answers with points or achievements and providing hints or challenges for incorrect answers.

### Features

Basic Arithmetic Operations: Support for addition, subtraction, multiplication, and division.
Points System: Users earn points for each correct answer.
Hints: Provide hints for incorrect answers.
Achievements: Unlock achievements based on points or correct answers streaks.
Progress Tracking: Display the user's current points and achievements.

### Technology Stack
HTML: Structure of the web page.
CSS: Styling for a visually appealing UI.
JavaScript: Game logic, points system, and user interaction.

### Screenshots

Default page:
![Screenshot 2024-06-02 182103](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/4f596b0b-1bd7-4fcf-891b-30897dc94071)

After Some inputs
![image](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/0579d551-5a0a-460b-8972-0822ceadb2a7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , please assign issue to me as GSSOC'24 contributor

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , i have already made it please assign to  me

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , please assign to me i have already made it

**Comment by Rakesh9100** [comment]
Go ahead @Vipullakum007

**Comment by Vipullakum007** [comment]
hey @Rakesh9100  , add level please i have already made it.

**Comment by Rakesh9100** [comment]
Level label will be added once the PR is up and successfully merged @Vipullakum007
