### ISSUE TITLE
[Feature] Add Body Surface Area (BSA) Calculator

### ISSUE THREAD

**Issue by pankaj-bind** [Rakesh9100/CalcDiverse#1101]
### Description

Computes the body surface area using formulas like the Mosteller formula, often used in medical contexts.

Assign me this under GSSoC24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide your PR @pankaj-bind

**Comment by techbire** [comment]
> Pls provide your PR @pankaj-bind 

Assign to me! I will do.

**Comment by Rakesh9100** [comment]
Go ahead @techbire
