### ISSUE TITLE
Enhancement: 3D Shapes Volume Calculator

### ISSUE THREAD

**Issue by Lavanya-Sathya** [Rakesh9100/CalcDiverse#111]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I've noticed that the "VOLUME OF 3D SHAPES CALCULATOR" is currently not responsive for all screen sizes, and I believe there's room for improvement in the UI to make it more attractive.

### Screenshots

![volume3D](https://github.com/Rakesh9100/CalcDiverse/assets/83652986/b8c0d287-0a58-4edf-a049-61da475b9e63)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Lavanya-Sathya** [comment]
Hi, @Rakesh9100, I would like to contribute to this issue. Please assign this issue to me.
Thanks

**Comment by Rakesh9100** [comment]
Start working @Lavanya-Sathya
