### ISSUE TITLE
[Feature] Add Digital Detox Calculator

### ISSUE THREAD

**Issue by tanishaprasad** [Rakesh9100/CalcDiverse#1114]
### Description

Digital Detox Calculator calculates the amount of time you spend on digital devices and suggests a plan for a balanced digital detox.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @tanishaprasad
