### ISSUE TITLE
[Feature] Add more inputs in Water Intake Calculator

### ISSUE THREAD

**Issue by harshyadav3010** [Rakesh9100/CalcDiverse#1115]
### Description

Estimates your risk of dehydration based on activity level, climate, and personal health factor like weight.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have `Water-Intake-Calculator`, you can enhance that by including risk or any more functionality that you want @harshyadav3010

**Comment by harshyadav3010** [comment]
> We already have `Water-Intake-Calculator`, you can enhance that by including risk or any more functionality that you want @harshyadav3010

@Rakesh9100 Okay,I will combine the functionalities. Please Assign me the issue.

**Comment by Rakesh9100** [comment]
Go ahead @harshyadav3010
