### ISSUE TITLE
[Feature] Add GDP Calculator

### ISSUE THREAD

**Issue by AnandK-pm** [Rakesh9100/CalcDiverse#1117]
### Description

Gross domestic product is defined by the Organisation for Economic Co-operation and Development (OECD) as "an aggregate measure of production equal to the sum of the gross values added of all resident and institutional units engaged in production (plus any taxes, and minus any subsidies, on products not included in the value of their outputs." More simply, it can be defined as a monetary measure of the market value of final goods produced over a period of time, typically quarterly or yearly, that is often used to determine the economic performance of a region or country. Generally, growth of more than two percent indicates significant prosperous activity in the economy. On the other hand, two consecutive three-month periods of contraction may indicate that an economy is in recession.

Implementing a GDP calculator which uses Expenditure approach which takes parameters : 

* Personal Consumption
* Gross Investment
* Government Consumption
* Exports
* Imports

GDP =  personal consumption + gross investment + government consumption + net exports of goods and services

### Screenshots

Proposed protoype (UI will be improved)

![gdp](https://github.com/Rakesh9100/CalcDiverse/assets/142206618/2369ef08-fd12-4a05-b5e5-c6a81bb17cb1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AnandK-pm
