### ISSUE TITLE
Search by categories 

### ISSUE THREAD

**Issue by vverma022** [Rakesh9100/CalcDiverse#1118]
### Description

We can implement a functionality to search by categories and arrange the calculators by categories so that it is easier to navigate and choose what we want.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you have any supporting screenshots of your issue that how you want to implement @vverma022

**Comment by vverma022** [comment]
Not yet but the approach would be to make pages where the calculator components would be exported to so that those pages have the right alignment.

**Comment by jessicachawla** [comment]
Can you please find some website which has this done already just to give us an idea of how you're planning to implement. 
Just browse a bit, I'm sure you'll find them

**Comment by vverma022** [comment]
<img width="1163" alt="Screenshot 2024-07-04 at 12 07 02 AM" src="https://github.com/Rakesh9100/CalcDiverse/assets/109036913/5c20cd0d-9f0a-4d02-a903-ce43600c1a6e">

**Comment by Rakesh9100** [comment]
Pls check this @jessicachawla

**Comment by jessicachawla** [comment]
This looks good to me. 
@Rakesh9100 this issue can be assigned

**Comment by vverma022** [comment]
This can be put in the footer of the project and then can be linked it saves time of the user as well as the programmer.

**Comment by Rakesh9100** [comment]
The footer is already designed well, how will you redesign and what all things will be present in the footer? @vverma022

**Comment by Rakesh9100** [comment]
Any update on this @vverma022

**Comment by vverma022** [comment]
> Any update on this @vverma022 
My apologies, I was waiting for you to assign this issue to me. I'll start working on it asap.

**Comment by Rakesh9100** [comment]
> The footer is already designed well, how will you redesign and what all things will be present in the footer? @vverma022

?? @vverma022

**Comment by vverma022** [comment]
I'll add a category section with categories and list all calculators there. It'll not be present in the footer but a section on the website. If you have any suggestions I'm open.

**Comment by vverma022** [comment]
> <img width="1163" alt="Screenshot 2024-07-04 at 12 07 02 AM" src="https://github.com/Rakesh9100/CalcDiverse/assets/109036913/5c20cd0d-9f0a-4d02-a903-ce43600c1a6e">
> 
> 

.
