### ISSUE TITLE
[Feature] Add Standard Deviation Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#1121]
### Description

It calculates the standard deviation, variance based on the data given.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yuvraj960** [comment]
@Rakesh9100 I have request a PR for issues #1031 and #671 . Kindly assign this issue and #1120 to me.

**Comment by Yuvraj960** [comment]
@Rakesh9100 My all PRs are merged please assign issues to me

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960

**Comment by Rakesh9100** [comment]
We already have Statistics Calculator, pls work on other issues @Yuvraj960
