### ISSUE TITLE
Add Angle Between Two Lines Calculator

### ISSUE THREAD

**Issue by AMS003010** [Rakesh9100/CalcDiverse#1123]
### Description

Add a calculator to calculate the angle between two lines
Please do assign me this issue under gssoc'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Provide any supporting screenshot or reference to this type of calculator @AMS003010

**Comment by AMS003010** [comment]
So this calculator will be used to get the angle _theta_ between two lines. The angle _theta_ will be calculated using the formula in the below screenshot.

## Screenshot
![image](https://github.com/Rakesh9100/CalcDiverse/assets/111883236/1fa0e42e-dd13-4183-81d3-a34ef35e5d81)

**Comment by AMS003010** [comment]
Hello @Rakesh9100 🤗

Would be great if you could assign me this issue under gssoc'24

**Comment by AMS003010** [comment]
If the equation of a line is taken to be in the form of `ax + by  + c = 0`, then the values of `a`, `b` and `c` for the 1st line and the 2nd line each is taken as input from the user and the the slope for each line is calculated , which become `m1` and `m2`. Then `m1` and `m2` are used to calculate the inner angle between the lines using the formula below 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/111883236/2b03a5db-00e3-40ed-9040-5bc7c644f622)

Hello @Rakesh9100 🤗

Please assign me this issue under gssoc'24.

Thank you

**Comment by Rakesh9100** [comment]
What would be the name of your calculator @AMS003010

**Comment by AMS003010** [comment]
It could be called `Angle between two lines` calculator

**Comment by AMS003010** [comment]
So @Rakesh9100 can I start working on this issue
We can improvise on the name of the calculator if its too long...

**Comment by Rakesh9100** [comment]
Go ahead @AMS003010

**Comment by AMS003010** [comment]
@Rakesh9100 
I have added the angle between two lines calculator.
Please do review the PR and add the appropriate labels.

**Comment by AMS003010** [comment]
@Rakesh9100 
I have added the angle between two lines calculator and fixed all the issues.
Sorry for the delay 😅
