### ISSUE TITLE
[Feature] Add Frames Timecode Calculator

### ISSUE THREAD

**Issue by AMS003010** [Rakesh9100/CalcDiverse#1124]
### Description

To add Frames to Timecode Calculator and vice-versa.
Please do assign me this issue under gssoc'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead, and add the vice versa as well in the same calculator @AMS003010

**Comment by AMS003010** [comment]
@Rakesh9100
Please do review the PR and add the appropriate labels

**Comment by AMS003010** [comment]
@Rakesh9100 
I have added the timecode to frames calculator.
Please do review the PR and add the appropriate labels
