### ISSUE TITLE
[Style] Make Age Calculator responsive

### ISSUE THREAD

**Issue by m3kvt** [Rakesh9100/CalcDiverse#1125]
### What's the style idea?

We need to improve the responsiveness of Age Calculator. The contents of the age calculator doesn't seem to fit inside in mobile view. I would like to increase the padding inside.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/9d037b59-9b3c-4a34-bb0f-3ea116778663)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by puneet426** [comment]
I WOULD LIKE TO JOIN THE PROJECT
Please Assign it to me

**Comment by Rakesh9100** [comment]
Go ahead @m3kvt
