### ISSUE TITLE
[Style] Make AQI Calculator responsive

### ISSUE THREAD

**Issue by m3kvt** [Rakesh9100/CalcDiverse#1126]
### What's the style idea?

In mobile view the contents are displayed outside the box. Also there is an extra white space in the bottom of the screen. I would like to improve the styling of both of them.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/f4f873fe-4fc6-40ac-80e4-509f7266c330)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @m3kvt
