### ISSUE TITLE
[Feature] Add pagination to the website

### ISSUE THREAD

**Issue by Varsani2520** [Rakesh9100/CalcDiverse#1127]
### Description

we can add pagination in calcDiverse ,
in home page display all the calculator instead of that we can add pagination 
first screen display 10,2nd screen display 10...

so user easily enjoy the calcDiverse 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/137641079/360c3b6d-81b5-4857-b24e-6772f3005b3d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to work on this @Varsani2520

**Comment by Varsani2520** [comment]
Yes i want @Rakesh9100

**Comment by Varsani2520** [comment]
Assigned me please

**Comment by Rakesh9100** [comment]
Go ahead @Varsani2520
