### ISSUE TITLE
[Feature] Add Health Risk Assessment Calculator

### ISSUE THREAD

**Issue by suhanigupta23** [Rakesh9100/CalcDiverse#1128]
### Description

Assesses an individual's risk factors for common health conditions (e.g., heart disease, diabetes) based on lifestyle habits, family history, it asses the risk level. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @suhanigupta23
