### ISSUE TITLE
Adding Data size convertor calculator 

### ISSUE THREAD

**Issue by Akshansh8** [Rakesh9100/CalcDiverse#113]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This calculator will convert various data sizes like bits to bytes, bytes to megabytes, bits to megabytes etc
bits <-> bytes,
bits <-> megabytes,
bits <-> gigabytes,
bytes <-> gigabytes, etc

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @Akshansh8
