### ISSUE TITLE
[Style] Make Basic Calculator responsive

### ISSUE THREAD

**Issue by m3kvt** [Rakesh9100/CalcDiverse#1130]
### What's the style idea?

In desktop view, we have the access to switch to dark/light mode. but it is  not accessible in mobile view. Also the contents fill the whole screen, I would like to add some margin.
Mobile view:
![image](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/bcc3224f-9754-4f23-a755-78319472a22b)

Desktop view:
![image](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/63c99ef3-901d-4741-a3fb-886f082f519a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your previous issues @m3kvt

**Comment by m3kvt** [comment]
> Pls complete your previous issues @m3kvt

I have completed my previous issues. Can you assign me this now?
