### ISSUE TITLE
[Feature] Add Feedback Option in website

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/CalcDiverse#1132]
### Description

I want to add feedback page.
I will use html ,css and javascript.

**Expect level3 for this task.**

Thank you !

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/126322584/dd914270-6517-4a52-aa58-1ce011eab600)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by solanki505** [comment]
I would like to work on this issue , i would add a modal feedback form with star rating 
![Screenshot 2024-06-02 175155](https://github.com/Rakesh9100/CalcDiverse/assets/158484284/a784986d-b983-40b8-ade2-1aeaabf41485)
![Screenshot 2024-06-07 112601](https://github.com/Rakesh9100/CalcDiverse/assets/158484284/07dd9a96-5bdf-4926-847b-1b876e831acd)

**Comment by solanki505** [comment]
can you please assign me this issue , I want to work on it

**Comment by Rakesh9100** [comment]
Where and how do you want to add this, how the feedback will be received from my end @zalabhavy

**Comment by zalabhavy** [comment]
@Rakesh9100 In Navbar option i will add option of feedback after contact.
That opens another page of feedback forms.
For receive backend we need database.
I can able to design new feedback form but can't able to work with backend.
