### ISSUE TITLE
[Style] Make Black Hole Number Calculator responsive

### ISSUE THREAD

**Issue by m3kvt** [Rakesh9100/CalcDiverse#1136]
### What's the style idea?

The sides of the container is not visible.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/98ae92c6-cc89-47d1-b393-30326c342792)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by m3kvt** [comment]
Could You please assign me this issue?

**Comment by Rakesh9100** [comment]
Proceed @m3kvt

**Comment by Rakesh9100** [comment]
Provide your PR @m3kvt
