### ISSUE TITLE
[Style] Enhance Armstrong Number Calculator UI

### ISSUE THREAD

**Issue by puneet426** [Rakesh9100/CalcDiverse#1137]
### Category of documentation update

![Screenshot 2024-06-03 153743](https://github.com/Rakesh9100/CalcDiverse/assets/168094736/670de288-4201-47f0-984a-8e39ab239c48)

### Describe the change you think might work

we can make hover button and also change in background color

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by puneet426** [comment]
i think this is good
![Screenshot 2024-06-03 154952](https://github.com/Rakesh9100/CalcDiverse/assets/168094736/0b269f41-c486-4f7e-bde0-91358b2a73e0)

**Comment by puneet426** [comment]
here button is sliding when cursor is on button

**Comment by Rakesh9100** [comment]
Go ahead @puneet426

**Comment by puneet426** [comment]
hello @Rakesh9100  i done this
