### ISSUE TITLE
[Feature] Add Rent Calculator

### ISSUE THREAD

**Issue by narayani9120** [Rakesh9100/CalcDiverse#1138]
### Description

The CalcDiverse contains many calculators the addition of **Rent Calculator** would help to calculate the overall budget. If a user wants to pay Rs.X per month for a specific reason to the office and the user needs to submit the Documentation prior. At this time the calculator wouls be helpful. The addition of this calculator will enhance the feature of the website.
Kindly assign me this issue @Rakesh9100 .

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/125353066/a92e0742-87d5-415c-acaf-10e0879b3e0c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @narayani9120
