### ISSUE TITLE
Add Bitwise Operation Calculator

### ISSUE THREAD

**Issue by muskan42** [Rakesh9100/CalcDiverse#114]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey @Rakesh9100 !
Kindly assign me the issue to add a bitwise calculator.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @muskan42

**Comment by muskan42** [comment]
Thank you!

**Comment by muskan42** [comment]
@Rakesh9100 I have committed the changes.
