### ISSUE TITLE
[Bug] Fix the auto comment on PR merge workflow

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#1143]
### Description

I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message

### Screenshots

<img width="1440" alt="Screenshot 2024-06-03 at 7 01 37 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/168436423/8c89190c-d442-4878-98ab-bcb5280217ad">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Anshika14528
