### ISSUE TITLE
[Style] Make Download Time Calculator responsive

### ISSUE THREAD

**Issue by m3kvt** [Rakesh9100/CalcDiverse#1145]
### What's the style idea?

The contents are not properly visible on mobile view. I would like to align it properly.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/fab3f8e0-8ead-49ed-ad27-2f0bb8f38290)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls go ahead @m3kvt
