### ISSUE TITLE
[Style] Enhance Loan Repayment Date Calculator UI

### ISSUE THREAD

**Issue by Adv1919** [Rakesh9100/CalcDiverse#1146]
### Description

The text written in the input boxes of the Loan Repayment Calculator is not clearly visible due to the light color. 
The text color and UI can be changed to be made more user appealing and convenient.
Please assign me this isuue

### Screenshots

![Screenshot (127)](https://github.com/Rakesh9100/CalcDiverse/assets/146080896/bb8f5ab0-b2bf-46c8-986b-e3f32b5c4e7a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Adv1919
