### ISSUE TITLE
[Feature] Add Automorphic Number Calculator

### ISSUE THREAD

**Issue by Pujan-sarkar** [Rakesh9100/CalcDiverse#1148]
## Description
An automorphic number (also known as a circular number) is a number whose square ends in the same digits as the number itself. For example, 25 is an automorphic number because 25^2 = 625, and 76 is an automorphic number because 76^2 = 5776.

The Automorphic Number Calculator is a user-friendly tool designed to determine if a given number is an automorphic number. An automorphic number is one whose square ends with the number itself. This calculator takes a number input, computes its square, and checks if the square ends with the original number

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Pujan-sarkar
