### ISSUE TITLE
Add Number System Calculator

### ISSUE THREAD

**Issue by muskan42** [Rakesh9100/CalcDiverse#115]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey @Rakesh9100 !
Kindly assign me the issue to add the above calculator.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by muskan42** [comment]
@Rakesh9100 please assign me the issue.

**Comment by Rakesh9100** [comment]
I will assign you but can you just make one calculator which includes 
1. Binary to Hexadecimal and vice versa
2. Binary to octal and vice versa
3. Binary to Decimal and vice versa and so on

Making seperate calculators for all of these is not good @muskan42

**Comment by muskan42** [comment]
@Rakesh9100 Sure I'll make one that includes all these.

**Comment by Rakesh9100** [comment]
Go ahead then @muskan42

**Comment by Rakesh9100** [comment]
@muskan42 Status of your PR

**Comment by muskan42** [comment]
@Rakesh9100 I'm working on certain errors. Will generate the PR by the end of the day.

**Comment by Rakesh9100** [comment]
@muskan42 PR update pls

**Comment by muskan42** [comment]
@Rakesh9100 I've committed the changes and I'm extremely sorry for the delay. I had issues integrating all of them in one but it's done now. Kindly review my PR.
