### ISSUE TITLE
[Feature] Add Battery Life Calculator

### ISSUE THREAD

**Issue by diyaaa19** [Rakesh9100/CalcDiverse#1151]
### Description

This battery life calculator will estimate how long a battery will last, based on nominal battery capacity and the average current that a load is drawing from it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 please review and merge my PR
