### ISSUE TITLE
[Feature] Add Fuel Mileage Calculator

### ISSUE THREAD

**Issue by priyavratamohan** [Rakesh9100/CalcDiverse#1153]
### Description

The Fuel Mileage Calculator calculate gas mileage is to remember the odometer reading or to reset the mileage counter when filling up a gas tank.

The Calculator will do so by taking the **Previous Odometer Reading, Current Odometer Reading** and **Amount of Fuel** added to the Tank to the Vehicle.
It will provide an option to calculate the Mileage in **both US Units and Metric Units.**
It will also provide an option of calculating **fill expense** and **money per unit _($ per gallon, Rupees per litre etc.)_** of fuel by taking in an optional input of **Fuel Price per unit _(litre/gallon)_**

Please assign me this Issue under the Label of **GSSoC '24 and add label 'level 1'/'level 2'/'level 3'** according to your discretion. I will use HTML, CSS and JavaScript to implement it. Thank you!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Fuel Cost Calculator and Fuel Efficiency Calculator @priyavratamohan

**Comment by priyavratamohan** [comment]
Ah, sorry for that. I'll close this issue.
