### ISSUE TITLE
[Feature] Add Freelance Rate Calculator

### ISSUE THREAD

**Issue by mahek0620** [Rakesh9100/CalcDiverse#1158]
### Description

Freelance Rate Calculator: To calculate hourly or project rates for freelancers.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @mahek0620

**Comment by mahek0620** [comment]
@Rakesh9100 kindly review and also add labels
