### ISSUE TITLE
[Feature] Add Travel Budget Calculator

### ISSUE THREAD

**Issue by mahek0620** [Rakesh9100/CalcDiverse#1159]
### Description

Travel Budget Calculator: For planning travel expenses

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , you can assign me i have already made it
![image](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/ebad6f37-3e9e-4f4f-a2d6-0743463ad0ec)

**Comment by mahek0620** [comment]
@Rakesh9100 kindly assign this to me

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , this is **not enhancement** i have made it **from scratch / from zero**. _please make it level 3._
