### ISSUE TITLE
Add Binary to Octal Calculator

### ISSUE THREAD

**Issue by muskan42** [Rakesh9100/CalcDiverse#116]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey @Rakesh9100 !
Kindly assign me the issue to add the above calculator.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls complete the assigned issues first @muskan42

**Comment by muskan42** [comment]
@Rakesh9100 I have completed the previous issue now. Please assign me the above so that I can work on it.

**Comment by Rakesh9100** [comment]
As told, pls include this feature in issue 115 only @muskan42
