### ISSUE TITLE
[Feature] Add Wedding Budget Calculator

### ISSUE THREAD

**Issue by mahek0620** [Rakesh9100/CalcDiverse#1160]
### Description

Wedding Budget Calculator: For planning and tracking wedding expenses.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls don't open too many issues at once @mahek0620

**Comment by mahek0620** [comment]
@Rakesh9100 kindly assign this to me

**Comment by mahek0620** [comment]
![Screenshot 2024-06-08 130704](https://github.com/Rakesh9100/CalcDiverse/assets/136893675/21511132-4bf2-44cf-b227-3d0d4ba6baea)
![Screenshot 2024-06-08 130715](https://github.com/Rakesh9100/CalcDiverse/assets/136893675/5f7c2ecc-c13b-4f4a-82fd-62def8055dee)
@Rakesh9100 can you assign this to me as previous issue has been solved and PR was created

**Comment by mahek0620** [comment]
@Rakesh9100 can you assign this to me previous PR was created and merged

**Comment by Rakesh9100** [comment]
Go ahead @mahek0620

**Comment by bharat-c27** [comment]
Hello @Rakesh9100 , I understood the issue and I can enhance the UI with proper validation of the input.

Can you assign this issue to me ?

**Comment by Rakesh9100** [comment]
Complete your assigned issues first @bharat-c27

**Comment by bharat-c27** [comment]
Hello @Rakesh9100
I have raised the issue #1317 earlier, my coding part is done. So can you please assign to me.

I am also interested to take up this issue and I can start with this.
Can you please assign to me ?

Thank you!!

**Comment by vidhiisaxena** [comment]
Hi there!
Kindly assign this issue to me @Rakesh9100. I've submitted the PR for Blood Sugar calculator and will be able to efficiently work  on this issue.

Thankyou!!

**Comment by bharat-c27** [comment]
Hello @Rakesh9100 , I understood the issue and I can enhance the UI with proper validation of the input.

Can you assign this issue to me ?

**Comment by bharat-c27** [comment]
Also I have raise the issue in your other project.
https://github.com/Rakesh9100/Beautiify/issues/1237

**Comment by Rakesh9100** [comment]
Go ahead @bharat-c27
