### ISSUE TITLE
[Style] Enhance Binomial Distribution Calculator UI

### ISSUE THREAD

**Issue by AnandK-pm** [Rakesh9100/CalcDiverse#1161]
### What's the style idea?

We need to improve

* The primitive HTML styling to modern CSS styling.
* Animation and hover effects.
* Overall aesthetics conforming to the Style of CalcDiverse.

![Screenshot 2024-06-04 113426](https://github.com/Rakesh9100/CalcDiverse/assets/142206618/aac662ff-d9e8-4041-9596-d18c61e5742b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AnandK-pm** [comment]
Update ?

**Comment by Rakesh9100** [comment]
Go ahead @AnandK-pm
