### ISSUE TITLE
[Feature] Add Circular Motion Calculator

### ISSUE THREAD

**Issue by vedanshipathak** [Rakesh9100/CalcDiverse#1162]
### Description

It will calculate centripetal acceleration,centripetal force depending on the velocity ,mass and radius and will also calculate the angular frequency. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @vedanshipathak

**Comment by Rakesh9100** [comment]
Pls provide your PR @vedanshipathak

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, is there any point limitation on your project if not then please assign me this issue.

**Comment by Rakesh9100** [comment]
There are no limitations since you are developing your own UI, including designing and ensuring responsiveness. However, if someone is found copying the code, there will be restrictions!!

So, pls go ahead @Anshika14528

**Comment by Anshika14528** [comment]
Okay, Thankyou
