### ISSUE TITLE
[Feature] Add Free Fall Calculator

### ISSUE THREAD

**Issue by MohiniMehta** [Rakesh9100/CalcDiverse#1163]
### Description

This free fall calculator is a tool for finding the velocity of a falling object along with the distance it travels. It will calculate the time and the final velocity from the height, gravitational acceleration and initial velocity.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @MohiniMehta
