### ISSUE TITLE
[Feature] Add Narcissistic Number Calculator

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Rakesh9100/CalcDiverse#1164]
### Description

The calculator tells that whether the entered number is a narcissistic number or not

Eg : 371 = 3³ +7³ +1³

@Rakesh9100 I would like to work on this under GSSoC

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 I would like to work on this

**Comment by Rakesh9100** [comment]
Proceed @SuhainaFathimaM

**Comment by Rakesh9100** [comment]
Pls provide your PR @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 I will do that after making that readme document pr as soon as possible

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 #1457 After merging this PR i will complete this one
