### ISSUE TITLE
[Feature] Add Inflation Calculator

### ISSUE THREAD

**Issue by thenagarajanv** [Rakesh9100/CalcDiverse#1165]
### Description

Description

In this calculator we can calculate Future cost using cost Price, Rate Of Inflation Percentage and Time Period.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/89354876/145a533b-0d25-4233-8e75-f283eb4cf1ce)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/89354876/ca12d8ae-c390-4059-b87b-9e3641668101)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open for this before @thenagarajanv
