### ISSUE TITLE
[Feature] Add Weight On The Moon Calculator

### ISSUE THREAD

**Issue by Ajita369** [Rakesh9100/CalcDiverse#1166]
### Description

It is calculator which will convert the weight of object on the earth to it's corresponding weight on the moon. I will create this using html ,css and javascript . Please assign me this issue under GSSOC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Ajita369
