### ISSUE TITLE
[Feature] Add Electronegativity Calculator

### ISSUE THREAD

**Issue by aaryancodeshere** [Rakesh9100/CalcDiverse#1180]
### Description

# Calculating Electronegativity between atoms

The electronegativity calculator allows us to calculate the type of bond formed between different elements using their electronegativity values. 

This calculator can be used to calculate the electronegativity.

### Screenshots

<img width="722" alt="Screenshot 2024-06-04 at 9 14 32 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/124273822/9a1596ac-de97-42c2-a083-9ac4342ed301">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aaryancodeshere** [comment]
@Rakesh9100 Please assign it to me

**Comment by Rakesh9100** [comment]
Go ahead @aaryancodeshere
