### ISSUE TITLE
[Feature] Add Mirror Equation Calculator

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#1183]
### Description

I want to add a calculator which calculates the focal length  of the specified mirror(convex or concave mirror) if the distance of object and image from the mirror is given.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anshika14528** [comment]
@Rakesh9100 sir , I also want to make "lens focal length calculator" can i make new issue for that or should i make it together with mirror focal length calculator.

**Comment by Rakesh9100** [comment]
We have `Wave And Optics Calculator` present, is yours different from that? Pls check and let me know @Anshika14528

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, Yes , It is different from the wave and optics calculator is using focal and object distance to calculate image distance and I want to make calculator which helps us to find focal length and also the wave and optics calculator does not tell us about which lens or mirror is it finding the image distance.

**Comment by Rakesh9100** [comment]
Is this Mirror Equation Calculator @Anshika14528

**Comment by Anshika14528** [comment]
Yes , i will use mirror equation `1/v + 1/u = 1/f ` to calculate focal length(f) where u will be object distance and v will be image distance.

**Comment by Rakesh9100** [comment]
Okay, go ahead @Anshika14528

**Comment by Anshika14528** [comment]
Thankyou
