### ISSUE TITLE
[Feature] Add Prayer Time Calculator

### ISSUE THREAD

**Issue by samarsajad** [Rakesh9100/CalcDiverse#1185]
### Description

 a simple location based prayer time calculator that tells the exact time of prayer including sunset and sunrise 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by samarsajad** [comment]
Please assign me this issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @samarsajad

**Comment by Rishikesh63** [comment]
if this issue is not resolve yet @Rakesh9100  can i work on it.

**Comment by samarsajad** [comment]
> if this issue is not resolve yet @Rakesh9100 can i work on it.

@Rakesh9100  Can you please merge my pull request so that @Rishikesh63  works on the 'location undefined' bug as I couldn't solve it . Please
