### ISSUE TITLE
[Feature] Add Interplanetary Weight Calculator

### ISSUE THREAD

**Issue by Mohitbagul** [Rakesh9100/CalcDiverse#1186]
### Description

This feature helps user find their weights on different planets in our solar system. 
This issue can help users in multiple small scale project for knowing any object's weight on any other planet in our solar system.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the name of your calculator @Mohitbagul

**Comment by Mohitbagul** [comment]
Hello @Rakesh9100 ,
I would like to keep it as "Weight calculator of planets".

Suggest if you have any suggestions.

**Comment by Rakesh9100** [comment]
We already have [Astrological Age Calculator](https://calcdiverse.netlify.app/calculators/astrological-age-calculator/), is yours different from this @Mohitbagul

**Comment by Mohitbagul** [comment]
Yes sir,
My calculator calculates weights on different planets.
The one you are mentioning calculates age.

**Comment by Rakesh9100** [comment]
Okay, go ahead and keep the name as `Interplanetary-Weight-Calculator` @Mohitbagul

**Comment by Rakesh9100** [comment]
Pls provide your PR @Mohitbagul

**Comment by nandinipathak2005** [comment]
@Rakesh9100 Please assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @nandinipathak2005
