### ISSUE TITLE
Multiplication table of negative number in multiplication table calculator

### ISSUE THREAD

**Issue by Akshansh8** [Rakesh9100/CalcDiverse#119]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

we can get multiplication table of negative numbers even after the message "please enter number greater than or equal to 0 

### Screenshots

![Screenshot 2024-01-06 021404](https://github.com/Rakesh9100/CalcDiverse/assets/91936333/853bccdf-dac8-4992-bf78-a26a2116100b)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed and fix it @Akshansh8
