### ISSUE TITLE
[Feature] Binary Adder Calculator

### ISSUE THREAD

**Issue by its-kumar-yash** [Rakesh9100/CalcDiverse#1190]
### Description

A binary adder is a digital circuit or mathematical operation that combines binary numbers by adding their individual bits to produce a sum with carry-out.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/7abdc0cf-4451-4f9f-84f0-528380cbf0d1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by its-kumar-yash** [comment]
@Rakesh9100 kindly assign this issue to me.

**Comment by Rakesh9100** [comment]
Issue for this is already open @its-kumar-yash
