### ISSUE TITLE
[Feature] Add more dimensions in Matrix Calculator

### ISSUE THREAD

**Issue by DaniaZehra** [Rakesh9100/CalcDiverse#1196]
### Description

In the matrix calculator part I want to add multiplication of multiple dimensions for example 4x4 and 4x1 etc.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DaniaZehra

**Comment by Rakesh9100** [comment]
Pls provide your PR @DaniaZehra

**Comment by PDBharadwaj** [comment]
@Rakesh9100  I want to work on this issue. Please assign it to me.

**Comment by Rakesh9100** [comment]
Go ahead @PDBharadwaj
