### ISSUE TITLE
[Feature] Add Force Calculator

### ISSUE THREAD

**Issue by samarsajad** [Rakesh9100/CalcDiverse#1197]
### Description

A simple calculator that calculates force by taking user input

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by samarsajad** [comment]
Please assign this issue to me @Rakesh9100

**Comment by samarsajad** [comment]
Please assign this to me @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @samarsajad

**Comment by samarsajad** [comment]
Thank you so much for merging my pull request for my previous issue. Can you please assign this issue to me now? @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @samarsajad
