### ISSUE TITLE
[Feature] Add String Pattern Validation Calculator

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#1202]
### Description

User will enter some pattern of parenthesis and it's validity will be displayed as output.

For example, input -> {[]()}} -> not a valid parenthesis pattern similarly any other pattern of parenthesis entered by the user will be validated.!

Kindly assign this issue to me!
Thankss

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls clarify using more examples or screenshots of what is this calculator about @Aarzookhunger

**Comment by Aarzookhunger** [comment]
> Pls clarify using more examples or screenshots of what is this calculator about @Aarzookhunger

User will enter the string consisting of brackets and then does every opening bracket has a closing bracket will be matched, basically the bracket pattern will be validated.

Some examples:-  (3)[[4] -> not valid (as closing is missing)

((({}))) -> valid every opening has closing

**Comment by Aarzookhunger** [comment]
@Rakesh9100 Can you please recheck?

**Comment by Rakesh9100** [comment]
Go ahead @Aarzookhunger

**Comment by Rakesh9100** [comment]
Pls provide your PR @Aarzookhunger

**Comment by Aarzookhunger** [comment]
> Pls provide your PR @Aarzookhunger

Sorry for the delay sir I was pre-occupied somewhere. I'll generate pr within 1-2 days.
