### ISSUE TITLE
[Feature] Add Eigenvalues And Eigenvectors Calculator

### ISSUE THREAD

**Issue by AsmitaMishra24** [Rakesh9100/CalcDiverse#1203]
### Description

It would be highly beneficial to add a calculator for computing eigenvalues and eigenvectors to our project. This feature will enhance the project's functionality and provide users with a powerful tool for matrix analysis. 

**Features:**
- Input Matrix: Allow users to input a square matrix of any size.
- Compute Eigenvalues: Calculate the eigenvalues of the input matrix.
- Compute Eigenvectors: Calculate the corresponding eigenvectors for the computed eigenvalues.
- Output Display: Display the eigenvalues and eigenvectors in a clear and concise manner.
- Error Handling: Provide meaningful error messages for non-square matrices, singular matrices, or other invalid inputs.

### Screenshots

![Screenshot 2024-06-06 022141](https://github.com/Rakesh9100/CalcDiverse/assets/146121869/67510b6f-b02f-464d-a2ca-f2bb3dd1ec0e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by Nihal4777** [comment]
@Rakesh9100 **level3** label can be assigned.
