### ISSUE TITLE
[Feature] Add Mobility Calculator

### ISSUE THREAD

**Issue by vaishali-gupta32** [Rakesh9100/CalcDiverse#1204]
### Description

Mobility is the the ability or tendency to move from one position or situation to another usually better one. We can calculate is using the given electric field and velocity.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls clarify more using any example or screenshot of what this calculator is about @vaishali-gupta32

**Comment by vaishali-gupta32** [comment]
This mobility calculator will calculate mobility using the given input values of electric field and velocity. It will calculate in SI unit.

**Comment by Rakesh9100** [comment]
Go ahead @vaishali-gupta32
