### ISSUE TITLE
[Style] Make BMR Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#1217]
### Description

BMR calculator is not responsive  it should be responsive as people  will use in mobile phones also 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/498042f1-51ef-45f0-a9bc-c1d8e7455c82)

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/f68d21e6-3a87-4dd1-8674-55dee009d13d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by agastya3636** [comment]
@Rakesh9100 please assign atleast 1 issue all my issues are standby

**Comment by Rakesh9100** [comment]
Go ahead @agastya3636
