### ISSUE TITLE
[Feature] Add Kinetic And Potential Energy Calculator

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#1219]
### Description

This calculator helps us to calculate the kinetic energy using the formula  K.E. = 1/2 * m * (v^2)
and potenial energy P.E. = m * a * h
where m= mass
a=acceleration
v=velocity
I want add this calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Anshika14528
