### ISSUE TITLE
Add Fibonacci Calculator

### ISSUE THREAD

**Issue by ak4631** [Rakesh9100/CalcDiverse#122]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Calculating Fibonacci of any given number.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Okay proceed @ak4631

**Comment by Rakesh9100** [comment]
@ak4631 Status of your PR

**Comment by ak4631** [comment]
Will be submitting by tomorrow 👍
