### ISSUE TITLE
Charger Wattage Calculator Feature

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/CalcDiverse#1220]
### Description

This calculator will allow users to input the voltage (V) and current (A) of their chargers and calculate the wattage (W). This feature will be helpful for users to determine the power output of their chargers.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/118552563/86994674-02f0-492a-8321-73c1e14e392d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by divyansh-2005** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
We already have Electric Power Calculator, pls work on new issues @divyansh-2005
