### ISSUE TITLE
Friendship Calculator Feature

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/CalcDiverse#1221]
### Description

The Friendship Calculator project provides users with a delightful tool to assess their friendship compatibility with another person. This open-source project features a user-friendly interface where users can input their names and trigger the calculation process with a single click. The calculation algorithm, meticulously crafted, takes into account various factors such as shared interests, communication frequency, mutual understanding, duration of the friendship, and memorable moments shared.

Implemented in JavaScript, the calculator generates a friendship score, randomly varying between 0 and 100, reflecting the perceived compatibility between the two individuals. The result, displayed in a clear and concise manner, includes the calculated score and an accompanying message. This message dynamically adjusts based on the obtained score, offering personalized feedback ranging from "Best Friends Forever" for high scores to "Room for Improvement" for lower ones.

With a focus on accuracy and user engagement, the Friendship Calculator undergoes rigorous testing to ensure meaningful and accurate results across different input scenarios. Contributions to this project are encouraged, fostering an inclusive environment for collaboration and enhancement of the Friendship Calculator's functionality and user experience.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/118552563/343adf24-53d9-4011-b961-10d72b0137f3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need of this, try to work on to make some good useful calculators @divyansh-2005
