### ISSUE TITLE
[Feature] Add Cyclomatic Complexity Calculator

### ISSUE THREAD

**Issue by harshyadav3010** [Rakesh9100/CalcDiverse#1222]
### Description

It calculates the Cyclomatic Complexity of the code, a metric used to measure the structural complexity of software by counting the number of linearly independent paths through the code's control flow graph.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @harshyadav3010

**Comment by Rakesh9100** [comment]
Pls provide your PR @harshyadav3010

**Comment by anijit18** [comment]
@Rakesh9100  Kindly assign this issue to me. I want to work on this Calculator.

**Comment by Rakesh9100** [comment]
Do you want to work @anijit18

**Comment by vimore03** [comment]
@Rakesh9100  Please assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead @vimore03

**Comment by Rakesh9100** [comment]
Please provide your PR @vimore03

**Comment by vimore03** [comment]
@Rakesh9100 sir please review my PR .

**Comment by vimore03** [comment]
Hi sir, i have created a PR two days ago, kindly review it
