### ISSUE TITLE
[Feature] Add Geodesic Distance Calculator

### ISSUE THREAD

**Issue by pandeyji711** [Rakesh9100/CalcDiverse#1225]
### Description

@Rakesh9100 
### Outputs: Geodesic distance, path on the ellipsoid.

@Rakesh9100 please assign me on Gssoc24 level 2

### Screenshots

![Screenshot 2024-06-06 171235](https://github.com/Rakesh9100/CalcDiverse/assets/154527778/2c087898-3a03-4f59-a2d1-27c9c2a17b66)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @pandeyji711
