### ISSUE TITLE
[Feature] Add Dividend Yield Calculator

### ISSUE THREAD

**Issue by Meetjain1** [Rakesh9100/CalcDiverse#1228]
### Description

Will Add a Dividend Yield Calculator
That will display dividend yield on taking Annual dividend and Current market price as an Input.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Meetjain1

**Comment by Meetjain1** [comment]
> Go ahead @Meetjain1

@Rakesh9100 sure
