### ISSUE TITLE
[Feature] Add stack representation in Infix Prefix Postfix Calculator

### ISSUE THREAD

**Issue by its-kumar-yash** [Rakesh9100/CalcDiverse#1236]
### Description

The program converts an infix mathematical expression to both postfix and prefix forms while displaying the conversion steps. It uses stacks to manage operators and parentheses. It reverses the input expression for processing, maintains precedence rules, and generates steps for both conversions, displaying them in separate tables.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/a012c7e2-a554-4686-b207-c96ec5af3102)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/d747b437-d300-4469-9cb2-e64d1d09cad1)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/82eda768-65a2-4afd-a2b4-a10abe8664e7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Infix Prefix Postfix Calculator @its-kumar-yash

**Comment by its-kumar-yash** [comment]
@Rakesh9100 but that doesn't show the steps in form of stack

**Comment by Rakesh9100** [comment]
You can enhance that calculator then and add more features @its-kumar-yash

**Comment by Rakesh9100** [comment]
Do you want to proceed @its-kumar-yash

**Comment by its-kumar-yash** [comment]
@Rakesh9100 Yes

**Comment by Rakesh9100** [comment]
Provide your PR @its-kumar-yash

**Comment by Nishakulkarni06** [comment]
@Rakesh9100 I can do this

**Comment by Rakesh9100** [comment]
Proceed @Nishakulkarni06
