### ISSUE TITLE
Linear Equation in 2 Variables calculator

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/CalcDiverse#124]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to add a calculator that calculates the values of 2 variables from given linear equations in two variables.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @bhavya-anand19

**Comment by Rakesh9100** [comment]
@bhavya-anand19 Status of your PR pls

**Comment by bhavya-anand19** [comment]
> @bhavya-anand19 Status of your PR pls

Yes I have linked the PR just now.

**Comment by Rakesh9100** [comment]
Pls don't do any changes in main `index.html` file except just adding your calculator at the end @bhavya-anand19
