### ISSUE TITLE
[Feature] Add rank and power option in Matrix Calculator

### ISSUE THREAD

**Issue by Vipullakum007** [Rakesh9100/CalcDiverse#1242]
### Description

i want to add Matrix Rank Option in Matrix Calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , please assign to me . i have already made it

**Comment by Vipullakum007** [comment]
> hey @Rakesh9100 , please assign to me . i have already made it

hey @Rakesh9100 , please answer

**Comment by Rakesh9100** [comment]
Go ahead @Vipullakum007
