### ISSUE TITLE
[Feature] Add Relative Humidity Calculator

### ISSUE THREAD

**Issue by AmrutaJayanti** [Rakesh9100/CalcDiverse#1248]
### Description

Calculates the relative humidity given the dew point and the air temperature.

### Screenshots

N/A

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AmrutaJayanti

**Comment by Meghana-n10** [comment]
can you please assign this issue to me. I'm a newbie and i really want to contribute to the first project

**Comment by AmrutaJayanti** [comment]
@Meghana-n10 I'm already working on it.
