### ISSUE TITLE
[Feature] Add Exponential Decay Calculator

### ISSUE THREAD

**Issue by manishh12** [Rakesh9100/CalcDiverse#1249]
### Description

Calculate the Decay of substance based on the formula :
$(N(t) = N0e-kt )$(exponential decay)

I want to add this calculator.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by manishh12** [comment]
@Rakesh9100 Kindly assign me this.

**Comment by Rakesh9100** [comment]
Go ahead @manishh12

**Comment by Rakesh9100** [comment]
Pls provide your PR @manishh12

**Comment by manishh12** [comment]
@Rakesh9100 will provide till tonight! sorry for the inconvenience.
