### ISSUE TITLE
[Feature] Add Least Squares Regression Calculator

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/CalcDiverse#1250]
## Description
The Least Squares Regression Calculator is designed to fit data to a linear model using the least squares method. It calculates the best-fit line for a given set of data points and provides important regression statistics, such as the slope, intercept, R-squared value, and standard error. This tool is useful for anyone needing to analyze the relationship between two variables and make predictions based on the linear trend.

## Features
- **Data Input**: Allows users to input data points either manually or by uploading a file (e.g., CSV).
- **Best-Fit Line Calculation**: Computes the slope and intercept of the best-fit line using the least squares method.
- **Regression Statistics**: Provides additional statistics including:
  - **R-squared value**: Measures the goodness of fit.
  - **Standard error**: Estimates the accuracy of the coefficients.
  - **P-value**: Tests the hypothesis about the slope.
  - **Confidence intervals**: Provides the range within which the true slope and intercept lie with a certain level of confidence.
- **Data Visualization**: Plots the data points along with the best-fit line on a graph for visual analysis.
- **Residuals Analysis**: Displays the residuals (differences between observed and predicted values) to assess the fit.

## Alternative Solutions or Features Considered
- **Polynomial Regression**: Considered adding options for higher-order polynomial regression (quadratic, cubic, etc.) but decided to focus on linear regression for simplicity and clarity.
- **Multivariate Regression**: Thought about including multiple linear regression (more than one independent variable), but determined that it would complicate the user interface and require more advanced statistical understanding.
- **Online Data Fetching**: Considered integrating with online data sources (e.g., financial or scientific datasets) to automatically fetch data, but decided that manual input and file upload would suffice for initial implementation.
- **Interactive Graphing**: Explored the possibility of making the graph interactive (e.g., draggable points, dynamic updates), but decided to keep it static for simplicity and performance reasons.
- **Mobile Compatibility**: Ensured the calculator is mobile-friendly, allowing users to access and use it on smartphones and tablets.

The Least Squares Regression Calculator is a robust tool for performing linear regression analysis, providing both numerical and visual insights into the relationship between variables. This makes it a valuable resource for students, researchers, and professionals in various fields.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by divyansh-2005** [comment]
Please assign me this issue. I will complete it in less time

**Comment by Rakesh9100** [comment]
Go ahead @divyansh-2005
