### ISSUE TITLE
[Feature] Add Rational Fraction Analyzer Calculator

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/CalcDiverse#1251]
### Description

The Rational Function Analyzer is a specialized tool designed to provide detailed insights into the properties of rational functions, which are mathematical expressions formed by the ratio of two polynomials. This analyzer is particularly useful for students, mathematicians, and engineers who need to explore the behavior of these functions for academic, research, or practical applications.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by divyansh-2005** [comment]
Please assign me this issue.

**Comment by jessicachawla** [comment]
@divyansh-2005 this is basically a fraction analyzer, correct?

**Comment by divyansh-2005** [comment]
yes

**Comment by Rakesh9100** [comment]
Pls review this @jessicachawla

**Comment by Rakesh9100** [comment]
Exactly, hence closing the issue @divyansh-2005 @jessicachawla
