### ISSUE TITLE
[Feature] Add cross product functionality in Vector Calculator

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/CalcDiverse#1255]
### Description

Will add cross product functionality to your existing Calculator. Add will need to add three-dimensional vectors input.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/118552563/323b2a54-e36b-44d5-9542-274d2d82510c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by divyansh-2005** [comment]
Please assign me this issue.

**Comment by Rakesh9100** [comment]
Go ahead @divyansh-2005
