### ISSUE TITLE
[Feature] Add Instagram and Discord links in the footer

### ISSUE THREAD

**Issue by Kcode15** [Rakesh9100/CalcDiverse#1257]
### Description

Adding an Instagram link in the footer in place of the Facebook link so that the site looks more modern and aligned with current social media trends. 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/129003839/415c6113-2438-4cae-8917-35d52e92523c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nihal4777** [comment]
@Rakesh9100.

**Comment by Rakesh9100** [comment]
Go ahead, add instagram and discord link and also keep the facebook link @Kcode15

**Comment by mrunal1309** [comment]
@Rakesh9100 can  you please assign me this issue?
