### ISSUE TITLE
[Feature] Add CAGR (Compound Annual Growth Rate) Calculator

### ISSUE THREAD

**Issue by Skb08** [Rakesh9100/CalcDiverse#1260]
### Description

What is CAGR?
CAGR (Compound Annual Growth Rate) measures your investments' average annual growth over a given period. It shows you the average rate of return on your investments over a year. CAGR is a helpful tool for investors because it precisely measures investment growth (or decline) over time.

How to calculate?
CAGR = (FV / PV) ^ (1 / n) – 1
In the above formula, FV stands for the future value of the investment, PV stands for the present value of the investment, and n stands for the number of years of investment.

### Screenshots

![CAGR_calculator](https://github.com/Rakesh9100/CalcDiverse/assets/113046759/d00c8727-82e2-4d18-bcdf-484b78fe685f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Skb08
