### ISSUE TITLE
[Feature] Add EBITDA Calculator

### ISSUE THREAD

**Issue by Skb08** [Rakesh9100/CalcDiverse#1261]
### What is EBITDA calculator?
EBITDA calculator is a financial metric used to analyze the company’s operational performance in a given year/quarter. It provides a holistic idea of the company’s business at an operational level to every investor. It is also used as a level playing field to compare companies at an operational level and ascertain their operational profitability.

### How to use the EBITDA calculator?
EBITDA = Net sales – raw material costs – employee costs – other operating expenses.

### Screenshots

![EBIDTA_calculator](https://github.com/Rakesh9100/CalcDiverse/assets/113046759/f9b9b0c5-1685-4f52-a1cd-674a64a978f0)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Skb08
