### ISSUE TITLE
[Feature] Add Spy Number Calculator

### ISSUE THREAD

**Issue by poseidonsanket** [Rakesh9100/CalcDiverse#1262]
### Description

A number is said to be a Spy number if the sum of all the digits is equal to the product of all digits.
Input : 1412
Output : Spy Number
Explanation : 
sum = (1 + 4 + 1 + 2) = 8
product = (1 * 4 * 1 * 2) = 8
since, sum == product == 8

### Screenshots

![Capture](https://github.com/Rakesh9100/CalcDiverse/assets/112609618/2795f21c-8249-4c3e-8ef2-310f707577ab)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by poseidonsanket** [comment]
@Rakesh9100 can you please assign me this issue under Gssoc

**Comment by Harsh1737** [comment]
@Rakesh9100 can you please assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @poseidonsanket
