### ISSUE TITLE
[Feature] Add Cat Quality Of Life Calculator

### ISSUE THREAD

**Issue by swetha5157** [Rakesh9100/CalcDiverse#1270]
### Description

* This Cat Quality of Life (QOL) Calculator is used to determine a cat's quality of life 
* This is used to assess whether to proceed with hospice care or to consider euthanasia.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/123291594/3f4ba4c8-52a8-4c79-9267-7b447dc1031d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @swetha5157

**Comment by Rakesh9100** [comment]
Pls provide your PR @swetha5157

**Comment by swetha5157** [comment]
Will raise pr by today @Rakesh9100

**Comment by Rakesh9100** [comment]
You will be unassigned if PR is not up by today @swetha5157
