### ISSUE TITLE
[Feature] Add Catalan Number Calculator

### ISSUE THREAD

**Issue by Will2Jacks** [Rakesh9100/CalcDiverse#1271]
### Description

In combinatorial mathematics, the Catalan numbers are a sequence of natural numbers that occur in various counting problems, often involving recursively defined objects. They are named after the French-Belgian mathematician Eugène Charles Catalan.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Will2Jacks** [comment]
Hey @Rakesh9100 why haven't you assigned me this issue yet ?
I have already finished working on it and can't wait to pull request.
Please assign it as soon as you get time .

**Comment by Rakesh9100** [comment]
Proceed @Will2Jacks
