### ISSUE TITLE
Weighted Average Cost of Capital (WACC) Calculator

### ISSUE THREAD

**Issue by mahek0620** [Rakesh9100/CalcDiverse#1275]
### Description

used to determine a company's cost of capital, which is the average rate of return it needs to pay its investors for using their capital.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by mahek0620** [comment]
@Rakesh9100 can you assign this to me

**Comment by jessicachawla** [comment]
@mahek0620  I have a few questions. Please answer them. 
- What all inputs are you going to take from the user?
- Will this give the output for they would have to pay in the future or is it an instant kind of a thing? 
- Will it consider the other things such as some benefits or already given returns in the past while giving the output? 
- Will it give some kind indication if the return is too high or low?

**Comment by mahek0620** [comment]
@jessicachawla Inputs
Cost of Equity (Re): The return required by equity investors.
Cost of Debt (Rd): The effective rate the company pays on its borrowed funds.
Market Value of Equity (E): The total value of the company's equity.
Market Value of Debt (D): The total value of the company's debt.
Corporate Tax Rate (Tc): The company's tax rate.
Features and Functionalities
Instant Calculation: The WACC is calculated instantly based on the provided inputs.
Output: The calculator will provide the weighted average cost of capital, which represents the company's overall cost of financing.
Historical Considerations: The calculator will not consider past benefits or returns; it will focus on current values and inputs.
Return Indication: The calculator can include a feature to indicate whether the WACC is too high or too low based on industry standards or user-defined thresholds.

**Comment by mahek0620** [comment]
@Rakesh9100 can you assign this to me

**Comment by jessicachawla** [comment]
What is the point if it's not counting the benefits/other things? 
The calculation will be off then
