### ISSUE TITLE
[Feature] Add Binomial Expansion Calculator

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/CalcDiverse#1276]
### Description

This application can calculate and display the binomial expansion of given coefficients a, b and power n.

The application allows users to input values for the binomial coefficients and the power. The binomial expansion is calculated accurately using the binomial theorem. The result is displayed dynamically.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/139672976/37eaf22d-62f5-4129-8840-e7b6c10182aa)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DharshiBalasubramaniyam
