### ISSUE TITLE
[Feature] Add Debt Payoff Calculator

### ISSUE THREAD

**Issue by Manav173** [Rakesh9100/CalcDiverse#1278]
### Description

The Debt Payoff Calculator is a simple and intuitive tool designed to help you manage and plan your debt repayment effectively. Whether you're dealing with credit card debt, a personal loan, or any other type of debt, this calculator will provide you with a clear and concise repayment plan.
I would be really thankful if you assign me this issue as a part of GSSoC'24 @ra.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Manav173** [comment]
I would be really thankful if you assign me this issue as a part of GSSoC'24 @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @Manav173
