### ISSUE TITLE
[Feature] Add Special Number-2 Calculator

### ISSUE THREAD

**Issue by shreya-paul-17** [Rakesh9100/CalcDiverse#1282]
### Description

Addition of Special Number Calculator. This will show whether the input number is a special number or not.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shreya-paul-17** [comment]
@Rakesh9100 Please assign me this task

**Comment by Rakesh9100** [comment]
What is Special Number, pls provide the definition and examples @shreya-paul-17

**Comment by shreya-paul-17** [comment]
@Rakesh9100 A number is a special number if the sum of the factorial of the digits in the number is equal to the number itself. 
Example: 
145 is a special number because 1! + 4!  +5! = 145 where 1! = 1 , 4! = 24 , 5! = 120

**Comment by Rakesh9100** [comment]
Go ahead @shreya-paul-17

**Comment by Rakesh9100** [comment]
Status of your PR @shreya-paul-17

**Comment by shreya-paul-17** [comment]
Sorry for the delay @Rakesh9100 but my exams are starting from Tuesday. I need some time to complete this task. I assure you that the task will be completed by next Sunday.

**Comment by Rakesh9100** [comment]
Pls make your PR up by today @shreya-paul-17
