### ISSUE TITLE
[Feature] Relationship Health Calculator

### ISSUE THREAD

**Issue by AyushSukh** [Rakesh9100/CalcDiverse#1287]
### Description

The Personal Relationship Health Calculator is a web-based tool designed to help users assess the health of their personal relationships. By providing information about the time spent with loved ones, the quality of interactions, and communication frequency, users can gain insights into the overall health of their relationships.

### Screenshots

![Relationship_Health_Calculator](https://github.com/Rakesh9100/CalcDiverse/assets/51879443/551cd3e8-efe4-47e0-b194-4efe7bdd8721)
![Relationship_Calculator](https://github.com/Rakesh9100/CalcDiverse/assets/51879443/dd68bcc9-3a4d-412d-b645-9790900cb9b7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [x] I am a IWOC'24 contributor.
- [x] I am a JWOC'24 contributor.
- [x] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls add some good calculators instead of this @AyushSukh
