### ISSUE TITLE
[Feature] Add Frequency Calculator

### ISSUE THREAD

**Issue by Maheshwari-Love** [Rakesh9100/CalcDiverse#1288]
### Description

A Frequency Calculator is designed to compute the frequency of a periodic event or waveform. Frequency is a fundamental concept in physics, particularly in the study of waves, oscillations, and alternating current (AC) circuits. It refers to the number of cycles or oscillations that occur in a unit of time, typically measured in hertz (Hz), where 1 Hz equals one cycle per second.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142833275/827fce39-51f5-46d9-a686-c8dc3c9afd00)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 can you please assign this to me?

**Comment by Rakesh9100** [comment]
Go ahead @Maheshwari-Love
