### ISSUE TITLE
Number-of-Days-Calculator: Add more features

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/CalcDiverse#129]
### Description

Compute and show the gap in days, hours, minutes and seconds. Handy for planning and tracking.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/92045934/79d29514-c430-4a84-af98-66d9b62f2a68)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Instead of adding a new calculator, can you include these functionalities in the `Number of Days Calculator` which is already present as both has simlar functionalities @kom-senapati

**Comment by kom-senapati** [comment]
Ya can do that. So should I create a new issue or continue with this one.

**Comment by Rakesh9100** [comment]
Continue with this one only. Just edit the issue description and title accordingly and start working@kom-senapati
