### ISSUE TITLE
[Feature] Add Energy Consumption Calculator

### ISSUE THREAD

**Issue by ananyag309** [Rakesh9100/CalcDiverse#1294]
### Category of documentation update

An energy consumption calculator is a tool that helps determine how much electricity is used by a household or business over a specified period of time. It usually requires information such as the appliances used, their power usage, and the number of hours they are used. This information can then be inputted into the calculator to determine total energy consumption. Calculators can also help identify areas where energy is being wasted and suggest ways to reduce consumption.

### Describe the change you think might work

@Rakesh9100 please assign this to me under gssoc

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by PietervHa** [comment]
Can you assign me pls :)

**Comment by jessicachawla** [comment]
@Rakesh9100 this looks like a good idea, this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @ananyag309
