### ISSUE TITLE
[Feature] Add loading animation to Contributors page

### ISSUE THREAD

**Issue by pandeyji711** [Rakesh9100/CalcDiverse#1295]
### Description

@Rakesh9100
### it looks good and not look empty while api fetching contributors
please assing under  Gssoc24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @pandeyji711
