### ISSUE TITLE
[Bug] Fix the accordion in FAQ page

### ISSUE THREAD

**Issue by Amitanand0123** [Rakesh9100/CalcDiverse#1297]
### Description

The FAQ section should follow Accordion style for great user experience.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/140126906/a291828c-5c3f-48ea-a3c7-26f57174a3d0)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Amitanand0123** [comment]
@Rakesh9100 Please assign me this issue as I'm going to work on it.

**Comment by Rakesh9100** [comment]
Go ahead @Amitanand0123

**Comment by Rakesh9100** [comment]
Pls provide your PR @Amitanand0123

**Comment by anijit18** [comment]
Kindly assign this issue to me. I would like to work on it.

**Comment by siddharthbaleja7** [comment]
@Rakesh9100  I'd like to take on this issue . Please assign this issue to me.

**Comment by vidhiisaxena** [comment]
Hi there!
Kindly assign this issue to me @Rakesh9100. I will work diligently and complete it within a day.

**Comment by Rakesh9100** [comment]
Do you want to work @siddharthbaleja7

**Comment by Nishakulkarni06** [comment]
@Rakesh9100 plz assign to me

**Comment by Atharvverma1234** [comment]
Hello SIr, I would like to work on this issue. Please assign it to me. Thank you!

**Comment by Rakesh9100** [comment]
Go ahead @Nishakulkarni06
