### ISSUE TITLE
[Feature] Add Stock Profit Calculator

### ISSUE THREAD

**Issue by Meetjain1** [Rakesh9100/CalcDiverse#1298]
### Description

Will add a stock profit calculator 
Using this user just have to give input of no. of shares , purchase price in INR , sell price , buy commision , sell commission then the calculator will display purchased for , sold for and profit amount to the user to analyze their overall stock activity and help them to further invest in stock market 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Meetjain1
