### ISSUE TITLE
[Feature] Add Macro Nutrient Calculator

### ISSUE THREAD

**Issue by Antiquely3059** [Rakesh9100/CalcDiverse#1299]
### Description

The Macronutrient Calculator is a simple and effective tool designed to help users determine their daily macronutrient needs based on personal fitness goals and activity levels. By entering a few key details about themselves, users can receive a tailored recommendation for their daily caloric intake and the amount of protein, carbohydrates, and fats they should consume to achieve their fitness objectives.

### Screenshots

![Screenshot 2024-06-11 074441](https://github.com/Rakesh9100/CalcDiverse/assets/112797055/3e1a1e3f-62b6-4f4b-880b-1e84c890e0a1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Antiquely3059
