### ISSUE TITLE
Percentage Calculator

### ISSUE THREAD

**Issue by itsmeabhishek03** [Rakesh9100/CalcDiverse#13]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Calculate percentage of a given value. Useful for calculating discounts, tips, or percentage change.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sidharth2829** [comment]
Hi, @itsmeabhishek03 , I have looked into it.
Please assign this issue to me.

**Comment by Rakesh9100** [comment]
@itsmeabhishek03 Proceed!!

**Comment by JrG-One** [comment]
@Rakesh9100 , In case this issue is not resolved on time, kindly assign it to me

**Comment by Rakesh9100** [comment]
@itsmeabhishek03 Status of your work pls

**Comment by JrG-One** [comment]
@Rakesh9100, if he is not able to add this calculator, then please assign me. I'll do that.

**Comment by itsmeabhishek03** [comment]
> @itsmeabhishek03 Status of your work pls

Hey @Rakesh9100 I will raise PR today
