### ISSUE TITLE
[Feature] Add Data Structure Size Calculator

### ISSUE THREAD

**Issue by Harshitmishra001** [Rakesh9100/CalcDiverse#1300]
### Description:
It would be beneficial to have a tool that calculates the size of various data structures in memory. This tool would allow users to understand the memory footprint of their code and optimize memory usage.

### Use Cases:

- Understanding memory usage: Knowing the size of data structures can help developers understand how their code is using memory and identify potential memory leaks or inefficiencies.
- Performance optimization: By analyzing the size of data structures, developers can make informed decisions about data storage and retrieval strategies to improve performance.
- Choosing the right data structure: Different data structures have different memory requirements. A size calculator would help developers choose the most efficient data structure for their needs.

### Benefits:

- Improved code efficiency and performance
- Reduced memory usage and potential memory leaks
- Enhanced developer understanding of memory management

### Screenshots

![Screenshot 2024-06-11 113418](https://github.com/Rakesh9100/CalcDiverse/assets/131855565/f83823b6-3779-4c16-8733-6cf03385443f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Harshitmishra001** [comment]
@Rakesh9100 can you please assign me 😄

**Comment by jessicachawla** [comment]
@Harshitmishra001 will you be considering every data structure in this? Also, will you consider the architecture of the system?

**Comment by Rakesh9100** [comment]
Any update or should I close this issue @Harshitmishra001
