### ISSUE TITLE
[Style] Enhance Travel Budget Calculator with more functionality

### ISSUE THREAD

**Issue by Vipullakum007** [Rakesh9100/CalcDiverse#1301]
### Description

A calculator that helps you plan your travel budget by calculating expenses for different categories like accommodation, food, transportation, and activities.

### Screenshots

![Screenshot 2024-06-11 114613](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/9faefa85-1054-4990-96c6-1119fd9c2750)
![Screenshot 2024-06-11 114628](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/4f5c033d-0d94-42b3-9298-35463a5f441c)
![Screenshot 2024-06-11 114637](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/61a5cc43-8996-4f43-b025-2a7e8d42fd7e)
![Screenshot 2024-06-11 114647](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/cde34a4b-a25e-4f5c-b493-3359c5bbd445)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vipullakum007** [comment]
hey @Rakesh9100  , i want to add Travel Budget Calculator i have give it look of mordenized live update  , chart visibility and theme changable. please assign i have already made it only PR is remaining

**Comment by Vipullakum007** [comment]
> hey @Rakesh9100 , i want to add Travel Budget Calculator i have give it look of mordenized live update , chart visibility and theme changable. please assign i have already made it only PR is remaining

hey @Rakesh9100 , please answer

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Vipullakum007

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , this is **not enhancement** i have made it **from scratch / from zero**. _please make it level 3._
