### ISSUE TITLE
[Feature] Add Image Resolution Calculator

### ISSUE THREAD

**Issue by thevijayshankersharma** [Rakesh9100/CalcDiverse#1307]
### Description

We need to implement an Image Resolution Calculator tool that computes the resolution of an image based on its dimensions and vice versa. This tool will be helpful for users who need to determine the resolution of an image for printing or digital display purposes.

Alternative Solutions or Features Considered:

Aspect Ratio Calculation: We can add an option to calculate the aspect ratio of an image based on its dimensions.
Unit Conversion: In addition to pixels, we can allow users to input dimensions in other units such as centimeters or inches, and provide the resolution in square meters or square feet accordingly.
Advanced Options: We can explore adding advanced options such as DPI (dots per inch) calculation or support for different color spaces.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @thevijayshankersharma
