### ISSUE TITLE
[Feature] Add Interquartile Range (IQR) Calculator

### ISSUE THREAD

**Issue by bharat-c27** [Rakesh9100/CalcDiverse#1308]
### Description

@Rakesh9100

### **Description**: 

An _Interquartile Range (IQR) Calculator_ is used to measure the spread of the middle 50% of a dataset, helping to identify variability and detect outliers in a dataset. It computes the difference between the first quartile (Q1) and the third quartile (Q3), offering insights into the data's distribution without being affected by extreme values. This is particularly useful in statistical analysis and data visualization.

Interquartile range (IQR), which is the difference between Q3 and Q1

**Input**: A list of numerical data values.

**Outputs**: 

1. First quartile (Q1) value.
2. Third quartile (Q3) value.
3. Interquartile range (IQR)
4. Minimum value in dataset
5. Maximum value in dataset

@Rakesh9100 please assign me this Issue with **Gssoc24** and **level 3** label 

There is no calculator directly on the website, and no issues were found. Since an Interquartile Range (IQR) Calculator could be beneficial to users by helping them quickly measure data variability and identify outliers, it could be a valuable tool for statistical analysis and data visualization.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @bharat-c27
