### ISSUE TITLE
[Feature] Add Body Surface Area (BSA) Calculator

### ISSUE THREAD

**Issue by techbire** [Rakesh9100/CalcDiverse#1309]
### Description

 Calculates the body surface area of a person using formulas like the Du Bois or Mosteller formulas.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@techbire  i suggest you consider giving the surface area of the different parts also.

**Comment by Rakesh9100** [comment]
Issue 1101 is already open for this, you can comment there if you want to work @techbire
