### ISSUE TITLE
[Feature] Add IST To CET Calculator

### ISSUE THREAD

**Issue by GAGGZ1** [Rakesh9100/CalcDiverse#1312]
### Description

Quickly convert India Standard Time (IST) to Central European Time (CET) with this easy-to-use, modern time zone converter.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GAGGZ1** [comment]
@Rakesh9100 please assign me this issue

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by GAGGZ1** [comment]
@Rakesh9100  please assign me

**Comment by jessicachawla** [comment]
@GAGGZ1 are you a contributor for all GSSOC'24, IWOC'24, JWOC'24, SWOC'24? if yes, under what do you want us to assign this?

**Comment by Rakesh9100** [comment]
It's GSSOC only as all the other open source programs are already over @jessicachawla

**Comment by Rakesh9100** [comment]
Go ahead @GAGGZ1

**Comment by Rakesh9100** [comment]
Provide your PR @GAGGZ1

**Comment by GAGGZ1** [comment]
@Rakesh9100 i have Request PR please review it and accept it #1520

**Comment by Rakesh9100** [comment]
We already have Time Zone Calculator which does this conversion as well, you can enhance the UI of that calculator if you want @GAGGZ1
