### ISSUE TITLE
[Feature] Add PPM (Parts Per Million) Calculator

### ISSUE THREAD

**Issue by Dark-S8uL** [Rakesh9100/CalcDiverse#1314]
### Description

PPM Calculator :
The Parts Per Million (PPM) Calculator is a versatile and essential tool for accurately determining the concentration of substances in various solutions. Whether you are working in a laboratory, an industrial setting, or conducting environmental testing, this calculator simplifies the process of calculating PPM values, providing precise results quickly and efficiently.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Dark-S8uL** [comment]
@Rakesh9100 Please assign this issue to me.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by Dark-S8uL** [comment]
@sanchitkhthpalia Find more new extensions and raise a new issue as this is raised by me and assigned to me :)

**Comment by Dark-S8uL** [comment]
@Rakesh9100 Please assign this issue to me.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Dark-S8uL
