### ISSUE TITLE
[Feature] Add PIN Generator Calculator

### ISSUE THREAD

**Issue by bharat-c27** [Rakesh9100/CalcDiverse#1317]
### Description

The PIN Generator Calculator allows users to create random Personal Identification Numbers (PINs) using digits 0-9. Users can specify the desired length of the PIN (up to 100 digits) and decide whether to allow repeating digits. This tool is useful for generating secure PINs for various applications, ensuring both convenience and security.

**Input :**  
1. Number of Digits : Specify the length of the PIN (1 to 100 digits).
2. Allow Repeat Numbers : Checkbox to allow or disallow repeated numbers.

**Output :** 
1. Generated PIN : A random PIN based on the specified input criteria.

@Rakesh9100 please assign me this Issue with Gssoc24 and level 3 label

There is no calculator directly on the website, and no issues were found. Since an PIN Generator Calculator could be beneficial to users by helping them quickly generating secure PINs for various applications, ensuring both convenience and security.

Also @Rakesh9100 , please check the **Centripetal Force Calculator** which is hosted on the website which is **not responsive**. If window size is less than 1250 than the **input** of the Calculator is **not visible**.  If you think that changes should be made to the Calculator then I am ready to do it, please reply if I need to raise a new Issue.
https://calcdiverse.netlify.app/calculators/centripetal-force-calculator/

Thank you!

### Screenshots

This is the Preview of the **PIN Generator Calculator**

![Screenshot 2024-06-12 195713](https://github.com/Rakesh9100/CalcDiverse/assets/125469847/32519d2e-a5b4-4346-a896-62b6a3826ac9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 i dont think this is necessary since most of the apps have a random pin generator in them

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @bharat-c27

**Comment by bharat-c27** [comment]
Hi @Rakesh9100,

I have raised the PR for the previous issue and is now merged #1464.

Please can you assign the issue to me so that I can raise a PR.

The calculator have 

**Input :**
_Number of Digits_ : Specify the length of the PIN (1 to 100 digits).
_Allow Repeat Numbers_ : Checkbox to allow or disallow repeated numbers.

**Output :**
_Generated PIN_ : A random PIN based on the specified input criteria.

And I have also handled the error when the user select PIN length greater than 10 and not allow repeated numbers.
In this case it is not possible to create a PIN without repeated numbers so I have handled the error by displaying error message.

Thank you!!

**Comment by Rakesh9100** [comment]
Go ahead @bharat-c27

**Comment by bharat-c27** [comment]
Thank you @Rakesh9100
