### ISSUE TITLE
[Feature] Add LinkedIn icon in footer

### ISSUE THREAD

**Issue by GAVINESHWAR** [Rakesh9100/CalcDiverse#1318]
### Description

In the footer section there is missing of  Instagram and Linked in account icons, I would like to add those features to the section which makes more reach of the projects by following in the Linked in and Instagram.

Assign me this issue @Rakesh9100 to make contribution to this valuable project and add labels to my issue sir.
Thank you for the oppurtunity.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124431955/278d27a3-7386-4a78-9720-c6ea303f6e28)

In this image there is  no instagram and  Linked in accounts icons

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by iakshkhurana** [comment]
I would like to work on this. Please assign me this issue to contribute to this project

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
You can just add LinkedIn account as for Instagram, issue is already open @GAVINESHWAR
