### ISSUE TITLE
[Feature] Add Travel Packing Calculator

### ISSUE THREAD

**Issue by techbire** [Rakesh9100/CalcDiverse#1322]
### Description

Assists in planning the number and types of clothing and items to pack based on destination weather, trip length, and activities.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@techbire will this tell you the weather along with the response? also will it tell if you need a raincoat, etc?

**Comment by techbire** [comment]
Here are the features of the travel packing calculator website:

1. User Input Fields:
  - Destination: Users can enter the destination of their trip.
  - Number of Days: Users can specify the length of their trip in days.
  - Weather: Users can input the type of weather expected at the destination (e.g., Hot, Cold, Moderate).
  - Activities: Users can list the activities they plan to do (e.g., Beach, Hiking, Business, Casual).
 

2. Results Display:
  - An area to display the results of the packing calculation.
  - The packing list includes the number and types of clothing and items to pack, tailored to the user's trip details.

**Comment by jessicachawla** [comment]
No point of we are asking for the weather as an input.

**Comment by techbire** [comment]
NOPE, 
YOU GET WRONG
LET ME CLEARIFY

The key features of the travel packing calculator project summarized in five bullet points:

- Destination and Activity-Based Packing Lists: Generates tailored packing lists based on the specified destination and up to 10 selected activities, ensuring comprehensive preparation for various plans.
  
- Weather Integration: Fetches real-time weather data for the destination to provide appropriate packing suggestions based on the forecast by OpenWeatherMap.

- Smart Packing Tips: Offers detailed packing tips tailored up to 10 tips per activity along with general packing advice for efficient packing.

- Dynamic List Generation: Creates a dynamic and interactive packing list that updates based on user inputs and weather conditions.

- User-Friendly Interface: Provides a simple and intuitive interface for entering trip details, selecting activities, and viewing the generated packing list and tips.

**Comment by techbire** [comment]
![screencapture-127-0-0-1-5500-2024-06-22-17_23_00](https://github.com/Rakesh9100/CalcDiverse/assets/131269064/91ffe771-086d-4042-9ea3-2f754d323576)

**Comment by jessicachawla** [comment]
Okay. 
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @techbire

**Comment by Rakesh9100** [comment]
Status of your PR @techbire

**Comment by techbire** [comment]
> Status of your PR @techbire 

Adding Little bit styling and animation!
