### ISSUE TITLE
[Feature] Add Home button in each calculator page

### ISSUE THREAD

**Issue by shraddhha** [Rakesh9100/CalcDiverse#1324]
### Description

Currently, the project lacks a direct way for users to return to the home page after navigating to other sections of calculators. This can create a less intuitive user experience, especially for first-time users or those who are not familiar with the site structure.

**Proposed Change**:

I propose adding a 'Home' button to the interface that will be visible from every section of calculators of the project. This button will:

_Improve Navigation:_ Provide users with a consistent and easy way to return to the main page from any section.
_Enhance User Experience_: Reduce the need for users to manually navigate back to the home page, thus simplifying their interaction with the site.
_Increase Accessibility:_ Make the home page accessible from all parts of the application, ensuring users can easily find and use the main content.

**Benefits:**

- Streamlined user flow.
- Enhanced user satisfaction and engagement.
- Better overall usability of the application.

The button should be added such that it will be clearly visible and understandle by users.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shraddhha** [comment]
@Rakesh9100 please assign this issue to me under gssoc.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Do you want to add a home button to each calculator page @jessicachawla

**Comment by Rakesh9100** [comment]
Do you want to add a home button to each calculator page @shraddhha

**Comment by shraddhha** [comment]
Yes, I can add a home button to each calculator page ensuring consistent styling and functionality. Please assign this issue to me I assure you to complete it as soon as possible.

**Comment by Rakesh9100** [comment]
Since new calculators are added frequently, it's unnecessary to include a home button on each calculator page. Each calculator already opens in a new tab, allowing users to return to the previous tab if needed @shraddhha
