### ISSUE TITLE
[Feature] Add Wave And Optics Calculator

### ISSUE THREAD

**Issue by shraddhha** [Rakesh9100/CalcDiverse#1325]
### Description

Implementing wave and optics calculations involves creating a calculator that can handle various physics formulas and concepts related to waves and optics.

**Wave and Optics Calculator
Project Description:**

The Wave and Optics Calculator is a versatile and user-friendly tool designed to assist students and professionals in performing various calculations related to wave and optics phenomena. This web-based application allows users to compute key parameters such as wave speed, frequency, and wavelength, as well as solve problems involving Snell's Law, interference patterns, and lens/mirror equations.

**Key Features:**

- Wave Properties Calculations: Compute wave speed, frequency, and wavelength with ease.
- Snell's Law: Calculate angles of incidence and refraction for different media.
- Interference Patterns: Analyze double-slit and other interference phenomena.
- Lens and Mirror Equations: Determine focal lengths, object distances, and image distances.
- User-Friendly Interface: Intuitive input fields and clear results display.

**Additional Features Considered:**

_Equation Library:_

Including a library of common equations and formulas related to waves and optics, with explanations and examples of how to use them.

_Customizable Parameters:_

Allowing users to input custom parameters and save their own calculation templates for repeated use, making the tool more flexible for different use cases.

_Unit Converter:_

Integrating a unit converter to help users easily convert between different units of measurement (e.g., meters to nanometers, Hertz to kilohertz).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@shraddhha will you be giving some kind of diagram or graph as well?

**Comment by shraddhha** [comment]
Yes, I will add the graph as well based on user input for parameters like amplitude, frequency, and phase shift.

**Comment by jessicachawla** [comment]
Okay. Good 
@Rakesh9100 the issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @shraddhha
