### ISSUE TITLE
[Feature] Add Work Calculator

### ISSUE THREAD

**Issue by kauxp** [Rakesh9100/CalcDiverse#1326]
### Description

`W=F×d cosθ`
where:
W ->Work done;
F -> Force applied to the object; and
d  -> Displacement about which you moved the object.
cosθ -> Angle between Force and the Displacement.

The force can be decomposed like this:
F=m×a
where:
m -> Mass of the object; and
a -> Acceleration it experiences 
When the object is being lifted at a constant speed (a typical school problem), the acceleration on the object is g (caused by the gravitational force.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sanjay-kv** [comment]
Hi I need access to this repo to manage labels, lot of spam is happening.

**Comment by Rakesh9100** [comment]
Go ahead @kauxp

**Comment by kauxp** [comment]
I'll start working on it

**Comment by Rakesh9100** [comment]
Pls provide your PR @kauxp

**Comment by kauxp** [comment]
I'll raise the PR today
