### ISSUE TITLE
[Feature] Add CO2 Emissions Calculator

### ISSUE THREAD

**Issue by coderiksenthil** [Rakesh9100/CalcDiverse#1327]
### Description

I want to add a CO2 emissions calculator to CalcDiverse website to help users estimate their carbon footprint from various modes of transport, including cars, flights, buses, and trains. This tool will feature a user-friendly interface with dynamic input fields, accurate emissions estimation using standard factors, and an option to generate detailed PDF reports. By raising awareness of the environmental impact of different transportation methods, this calculator supports our sustainability goals and encourages user engagement with actionable insights into their personal contributions to carbon emissions.

**Additionally, the code is already prepared and ready for implementation, I kindly request to be assign me to the issue**

### Screenshots

Working Picture of the Calculator 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/66522620/d02c8ffd-6249-45b6-be6b-f129f79583e8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @coderiksenthil
