### ISSUE TITLE
[Feature] Add Root Mean Square Calculator

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/CalcDiverse#1328]
### Description

This calculator will allow users to input a set of numbers and compute the Root Mean Square (RMS) value.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/137754636/fd2d6335-e51f-4bda-82d0-2764541f40df)

I will style it afterwards. This is the working model

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Proceed @Praneeth-2602
