### ISSUE TITLE
[Feature] Cryptocurrency Investment Calculator

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/CalcDiverse#1329]
### Description

This calculator will allow users to input their initial investment amount, the purchase price of a cryptocurrency, the current price of the cryptocurrency, and calculate the current value of the investment and the profit/loss.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/137754636/8a9840ef-5a35-4c4e-b563-3633d4266d9b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
very basic calculation, not required according to me

**Comment by Rakesh9100** [comment]
Pls work on your assigned issue and also open issues to add some good calculators @Praneeth-2602
