### ISSUE TITLE
[BUG] Negative BMI

### ISSUE THREAD

**Issue by Akshansh8** [Rakesh9100/CalcDiverse#133]
### Description

negative inputs for height and weight which outputs negative bmi but bmi can't be negative

### Screenshots

![Screenshot 2024-01-06 205323](https://github.com/Rakesh9100/CalcDiverse/assets/91936333/c74928a0-59fb-488f-959c-01c10c3167dc)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)"

**Comment by Rakesh9100** [comment]
Go ahead @Akshansh8
