### ISSUE TITLE
[Feature] Add Partial Derivative Calculator

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/CalcDiverse#1330]
### Description

This calculator allows you to compute partial derivatives of multivariable functions.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/137754636/77936c61-6e8b-4999-bfd8-d62c3569d1c3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Praneeth-2602** [comment]
@Rakesh9100 please assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @Praneeth-2602

**Comment by Praneeth-2602** [comment]
Thanks
