### ISSUE TITLE
[Style] Improve the design of contact us form

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/CalcDiverse#1332]
### What's the style idea?

I want to  improve the contact us form design 
### Previous design 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/6f08b8b9-9eb1-463e-97d1-7c5d7e29d1a9)

### My design 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/cda841fd-5bf1-4f30-afc5-ea6242a427e8)

Assign me this issue under GSSOC24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by guneetdewangan9** [comment]
I would like to work on this issue. Please assign me this issue under GSSoC'24 to contribute to this project.

**Comment by guneetdewangan9** [comment]
I would like to work on this issue. Please assign me this issue under GSSoC'24 to contribute to this project.

**Comment by jessicachawla** [comment]
@SaiyamTuteja  Design looks too basic, dont you think?

**Comment by Rakesh9100** [comment]
The contact form is already designed, and you are showing your design totally without CSS, so closing the issue @SaiyamTuteja
