### ISSUE TITLE
[Feature] Add Trisection Point Calculator

### ISSUE THREAD

**Issue by SumithThota** [Rakesh9100/CalcDiverse#1333]
### Description

Trisection points are used to divide a line segment into three equal parts or dividing a line segment in the ratio 1:2 and 2:1 internally. This calculator is used in various fileds of geometry & in coordinate systems

### Screenshots

This caluculator will find the points P & Q

![Example](https://github.com/Rakesh9100/CalcDiverse/assets/108344062/eaa56685-3160-4b22-b21d-c837c3d63d53)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SumithThota** [comment]
Hello @Rakesh9100 Please let me know abou this issue

**Comment by jessicachawla** [comment]
@SumithThota asking the user for the ration will be more effective. we would be able to find out the trisection point in that only

**Comment by SumithThota** [comment]
Yes @jessicachawla, user is supposed to enter the ratio of coordinates x1,y1,x2,y2 so that this calculator will give the 2 points which are equally divided (Trisection points)

**Comment by SumithThota** [comment]
Hello PA, please assign me this issue as a gssoc24 contributor

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @SumithThota
