### ISSUE TITLE
[Feature] Add Caesar Cipher Encryption Calculator

### ISSUE THREAD

**Issue by Archiesachin** [Rakesh9100/CalcDiverse#1339]
### Description

This Encryption calculator allows users to encrypt plaintext into cipher text. 
It use the Caesar cipher encryption technique each letter in the plaintext is shifted a certain number of places down or up the alphabet.
When the user inputs plaintext and selects a shift key, clicking the "Encrypt" button will display the ciphertext in the designated textarea.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Archiesachin
