### ISSUE TITLE
[Feature] Add Molarity Calculator

### ISSUE THREAD

**Issue by GAVINESHWAR** [Rakesh9100/CalcDiverse#1340]
### Description

 The molarity calculator calculates the mass of compound required to achieve a specific molar concentration and volume. To dilute a solution of known molarity. This results the mass.
 
 Assign me this issue @Rakesh9100 to make a contribution sir 
 Thank You

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124431955/80a233c7-3394-4e27-8104-78567cc0b3b8)

This is the basic layout of the calculator assign this issue to make more attractive as well sir. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue @GAVINESHWAR

**Comment by GAVINESHWAR** [comment]
> Pls complete your assigned issue @GAVINESHWAR

@Rakesh9100 please do add assign label  sir, so that contribution can be counted by GSSOC sir.
like this
![image](https://github.com/Rakesh9100/CalcDiverse/assets/124431955/82b19a1c-4563-4212-bedb-aa3a1eb204ef)

Thank you sir
