### ISSUE TITLE
adding instagram and discord in social media

### ISSUE THREAD

**Issue by dnyandeepchute** [Rakesh9100/CalcDiverse#1341]
### What would you like to share?

adding instagram and discord in social media

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by IshaanXCoder** [comment]
Heyy! Please assign this to me, Thank you!

**Comment by Nihal4777** [comment]
@Rakesh9100 Issue #1257 already exists. Can be marked as duplicate & closed.

**Comment by Rakesh9100** [comment]
Pls do not create a PR until you have been assigned to an issue @Nihal4777
