### ISSUE TITLE
[Feature] : Optics Calculator For Physics Calculations

### ISSUE THREAD

**Issue by GAVINESHWAR** [Rakesh9100/CalcDiverse#1344]
### Description

It is an calculator to find the focal length of the mirrors like concave and convex mirrors . It is also can be used for find focal length of lenses like Concave and Convex lenses. These calculator  help to find the focal length easily. It is very useful for physics optics calculation problems.

Assign me this issue @Rakesh9100 sir to make contribution to this amazing project.

Thank you 

### Screenshots

![Screenshot 2024-06-15 104748](https://github.com/Rakesh9100/CalcDiverse/assets/124431955/8b21e2ae-0717-4b47-9fca-eab2ced48af5)
![Screenshot 2024-06-15 104801](https://github.com/Rakesh9100/CalcDiverse/assets/124431955/5a10c4a6-51f4-436b-8b63-36b6cf3a552f)

In this calculator observer that customization  for mirrors and lens, it gives the actual focal length with the sign as well .

I Hope this calculator helps the user very well.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
issue already exits #1325

**Comment by GAVINESHWAR** [comment]
> issue already exits #1325

@jessicachawla if it is already exits please assign the issue to them or me and close the issue mam
Thank you

**Comment by jessicachawla** [comment]
Will be assigned to them.
