### ISSUE TITLE
[Style] Make Sleep Cycle Calculator responsive

### ISSUE THREAD

**Issue by anagha-chaudhari** [Rakesh9100/CalcDiverse#1345]
### Description

I would like to work on the responsiveness of the sleep cycle calculator on other devices. Please assign me this issue under GSSOC'24 

### Screenshots

![Screenshot_2024-06-15-11-21-35-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Rakesh9100/CalcDiverse/assets/143149376/1e97b8f9-35e5-4cbf-90ef-1853f7bd32e2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by anagha-chaudhari** [comment]
@Rakesh9100 please assign this under GSSOC'24

**Comment by jessicachawla** [comment]
@anagha-chaudhari how will you make it more responsive? give some idea

**Comment by Rakesh9100** [comment]
I can see that it is already responsive, pls show the issue you are facing with the help of screenshot @anagha-chaudhari

**Comment by anagha-chaudhari** [comment]
Originally:

https://github.com/Rakesh9100/CalcDiverse/assets/143149376/bb1ea373-3fbc-46f6-a8b6-46c14807888f

However on small devices, the results box is not appropriately displayed:

![sleep1](https://github.com/Rakesh9100/CalcDiverse/assets/143149376/cea93246-caec-41f5-a6a4-39d43ae606bf)

![sleep2](https://github.com/Rakesh9100/CalcDiverse/assets/143149376/dc2bee01-f558-473a-a438-d9eae7333f8e)

**Comment by Rakesh9100** [comment]
Okay proceed @anagha-chaudhari
