### ISSUE TITLE
[Feature] Add vice versa functionality in String To Integer Calculator

### ISSUE THREAD

**Issue by ImmidiSivani** [Rakesh9100/CalcDiverse#1346]
### Description

Given input  integer is converted to an alphabetical string.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Do you want to work @ImmidiSivani

**Comment by Rakesh9100** [comment]
We already have `String To Integer Calculator`, so you can add your vice versa functionality in the same calculator, and then rename the folder to `Decimal String Calculator` @ImmidiSivani

**Comment by anijit18** [comment]
I want to work on this issue.
@Rakesh9100 Please assign this project to me under GSSOC.

**Comment by Rakesh9100** [comment]
Go ahead @anijit18

**Comment by anijit18** [comment]
@Rakesh9100  Could you please add the Level tag to this Issue.

**Comment by anijit18** [comment]
@Rakesh9100  I have made the changes. Please the level tag, I would like to create a PR for this issue.

![image](https://github.com/user-attachments/assets/bb56472e-e445-46dc-abfb-1fb6765c2cc2)

**Comment by Rakesh9100** [comment]
Provide your PR then, what are you waiting for @anijit18 

Label will be added once the PR is successfully merged.

**Comment by anijit18** [comment]
Okay, I will provide the PR by today itself.
