### ISSUE TITLE
[Feature] Add Crop Yield Calculator

### ISSUE THREAD

**Issue by Shivanipandey31** [Rakesh9100/CalcDiverse#1349]
### Description

A crop yield calculator is a tool or application designed to estimate the amount of crop produced per unit area of land. It takes various inputs related to farming practices, soil conditions, weather data, and crop characteristics to predict the expected yield. The purpose of such calculators is to help farmers plan their production, manage resources effectively, and make informed decisions to maximize their agricultural output. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Shivanipandey31

**Comment by Rakesh9100** [comment]
Pls provide your PR @Shivanipandey31
