### ISSUE TITLE
[BUG] Content overflowing from card on mobile screen

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/CalcDiverse#135]
### Description

The content inside the card is overflowing on the mobile screen. The "Try Now" button and GitHub icon are overflowing from the bottom and the Heading "Trigonometric Functions " is overflowing from the top.

Changes need to be implemented:-

1. Padding of the inner paragraph.
2. Margin of the button element to align it with the paragraph to avoid overflowing.
3. Making every card mobile responsive.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/ad7e6d6a-ae28-4149-b1c2-d82c5b82637f)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)"

**Comment by pb0126** [comment]
Hi @Rakesh9100 ,
Please Assign this issue to me, I have carefully examined the issue and I'm willing to fix it and contribute. Allow me to fix this issue and create a PR by assigning this issue to me asap.
Thanks

**Comment by Rakesh9100** [comment]
Okay, proceed @pb0126
