### ISSUE TITLE
[Feature] Add Earthquake Impact Calculator

### ISSUE THREAD

**Issue by kosuri-indu** [Rakesh9100/CalcDiverse#1350]
### Description

**Purpose**: Estimates the potential impact of an earthquake in terms of ground shaking intensity, damage, and affected population based on earthquake magnitude and distance from the epicenter.

**Input**:

- Earthquake magnitude (Richter scale)
- Distance from the epicenter (km)
- Local population density
- Building types (optional)

**Output**:

- Peak ground acceleration (PGA)
- Modified Mercalli Intensity (MMI)
- Estimated damage levels
- Estimated affected population

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kosuri-indu** [comment]
@Rakesh9100
Please assign this issue to me
Thank you :)

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @kosuri-indu
