### ISSUE TITLE
[Feature] Add Nutritional Needs Calculator

### ISSUE THREAD

**Issue by kosuri-indu** [Rakesh9100/CalcDiverse#1351]
### Description

**Purpose**: Determines the daily caloric and macronutrient needs based on an individual's age, sex, weight, height, activity level, and fitness goals.

**Input**:

- Age
- Sex
- Weight
- Height
- Activity level (sedentary, lightly active, moderately active, very active)
- Fitness goals (lose weight, maintain weight, gain weight)

**Output**:

- Daily caloric needs
- Recommended intake of carbohydrates, proteins, and fats

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kosuri-indu** [comment]
@Rakesh9100
Please assign this issue to me
Thank you :)

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @kosuri-indu
