### ISSUE TITLE
[Feature] Add Parcel Shipping Calculator

### ISSUE THREAD

**Issue by Mayureshd-18** [Rakesh9100/CalcDiverse#1352]
### Description

Calculate the shipping cost based on the distance, weight, size.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Mayureshd-18  how will you be considering the price? will the price be according to fedex, delhivery or some other service?

**Comment by Mayureshd-18** [comment]
@jessicachawla Yeah based on the Fedex Rate chart

**Comment by Rakesh9100** [comment]
Go ahead @Mayureshd-18

**Comment by Rakesh9100** [comment]
Pls provide your PR @Mayureshd-18

**Comment by nandinipathak2005** [comment]
Please assign this issue to me

**Comment by Rakesh9100** [comment]
I have assigned you one issue, pls complete that first @nandinipathak2005
