### ISSUE TITLE
[Feature] Add Transpose Matrix Calculator

### ISSUE THREAD

**Issue by Maheshwari-Love** [Rakesh9100/CalcDiverse#1353]
### Description

I would like to have a "Transpose of Matrix Calculator" feature in our project. This feature should allow users to input a matrix of any size and receive the transposed matrix as the output. The calculator should be easy to use, providing a clear input method for the matrix and displaying the transposed matrix in an understandable format.

The feature aims to solve the problem of manual matrix transposition, reducing the time and effort required while minimizing the chances of making errors in the calculations.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142833275/e7f548ca-d5ef-43a3-80a5-fa988b107ef8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 please assign me this task...

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 please assign me this task

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
We already have Matrix-Calculator and Transpose feature is already present in that @Maheshwari-Love
