### ISSUE TITLE
[Feature] Add Sugar Intake Calculator

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Rakesh9100/CalcDiverse#1354]
### Description

This sugar intake calculator provides a simple way for users to calculate their total sugar consumption over a specified period based on their daily intake.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100  please assign me the issue

**Comment by sanjay-kv** [comment]
@Rakesh9100 Need access to this repo, please invite me to the repo.
Lot of spam is happening here.

**Comment by jessicachawla** [comment]
will you be taking into account if the sugar consumed is brown sugar or white sugar or jaggery?

**Comment by Saipradyumnagoud** [comment]
> king into account if the sugar consumed is brown sugar or white sugar or jagge

Yes before giving input we option to choose

**Comment by jessicachawla** [comment]
Okay. Seems good 
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Saipradyumnagoud

**Comment by Nihal4777** [comment]
@Saipradyumnagoud Please add an indication of which sugar is currently selected.
![image](https://github.com/Rakesh9100/CalcDiverse/assets/65150640/247ae167-e44e-4ec1-a5e7-6d02d7f47ef9)

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud Please add an indication of which sugar is currently selected. ![image](https://private-user-images.githubusercontent.com/65150640/344553115-247ae167-e44e-4ec1-a5e7-6d02d7f47ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjQyMTEsIm5iZiI6MTcxOTgyMzkxMSwicGF0aCI6Ii82NTE1MDY0MC8zNDQ1NTMxMTUtMjQ3YWUxNjctZTQ0ZS00ZWMxLWE1ZTctNmQwMmQ3ZjQ3ZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4NTE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMjFiMzJmZDIyMDg1YWVjNmU0MjEzYzJjOTg1YzVmMTBjMTc2YThjMWViNDYzNmZjOGUzZTk2OWExOTFjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xs1IgqsGMkMQIxFiBc26nFedF0PXQrwFA5KYYo7nLGA)

i have made the changes @Nihal4777
