### ISSUE TITLE
[Feature] Add Rate Us page

### ISSUE THREAD

**Issue by sailaja-adapa** [Rakesh9100/CalcDiverse#1357]
### Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

![emoji](https://github.com/Rakesh9100/CalcDiverse/assets/161804629/9ec93eec-b98f-434d-95aa-9a7eac93ceca)

Can you please assign me this issue under gssoc'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by sailaja-adapa** [comment]
@Rakesh9100 can you assign me this issue under GSSOC'24

**Comment by Rakesh9100** [comment]
Where and how do you want to add this, how the feedback will be received from my end @sailaja-adapa

**Comment by sailaja-adapa** [comment]
![IMG_20240706_122058](https://github.com/Rakesh9100/CalcDiverse/assets/161804629/acd7af8e-c5d6-4f90-9f9a-05695d51f5fb)

As you can see in this way I will add option

**Comment by jessicachawla** [comment]
Instead of emojis, put stars. They look more professional

**Comment by sailaja-adapa** [comment]
Yeah okk @jessicachawla

**Comment by Rakesh9100** [comment]
This is fine, but I am asking about the backend database that you will use so that I can receive the feedback on my end or my email, clarify this @sailaja-adapa

**Comment by sailaja-adapa** [comment]
I can only do Frontend @Rakesh9100 I am new to Contributions

**Comment by Rakesh9100** [comment]
Okay, go ahead @sailaja-adapa

**Comment by sailaja-adapa** [comment]
Yeah okk @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls provide your PR @sailaja-adapa

**Comment by sailaja-adapa** [comment]
By tomorrow I will provide you @Rakesh9100 
Sorry for the Late
