### ISSUE TITLE
[Feature] Add Value Added Tax Calculator

### ISSUE THREAD

**Issue by kamalesh-og** [Rakesh9100/CalcDiverse#1359]
### Description

Hello Project Admin @Rakesh9100,
Adding a Value Added Tax (VAT) Calculator to CalcDiverse will enable users to easily calculate the VAT on products or services. The calculator will feature two input fields: one for the amount and another for the VAT rate. It will also include two output fields: one for the VAT amount and another for the VAT Inclusive amount. This tool will provide users with an efficient way to compute VAT-related values, making it a valuable addition to the CalcDiverse project.

I've previously contributed to CalcDiverse by implementing a calculator and would love to further enhance this amazing repository with the addition of the VAT Calculator.

@Rakesh9100 Can you assign me this project? I am eager to work on this calculator and make it a one-stop solution for calculating VAT easily and accurately.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/163159351/cc5ce40f-8198-459e-bdb5-3162783c410d)
This is just the outline of the calculator and will be upgrading the UI using CSS and adding the real functionality using JS.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @kamalesh-og

**Comment by Rakesh9100** [comment]
Status of your PR @kamalesh-og

**Comment by kamalesh-og** [comment]
Will report my today @Rakesh9100 
Almost done

**Comment by kamalesh-og** [comment]
done sir @Rakesh9100
