### ISSUE TITLE
[Feature] Calorie intake calculator

### ISSUE THREAD

**Issue by Akshansh8** [Rakesh9100/CalcDiverse#136]
### Description

Estimate daily caloric needs based on factors like age, gender, weight, and activity level.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Proceed @Akshansh8 

And yes, pls don't put the label yourself from next time you are opening an issue!!

**Comment by Rakesh9100** [comment]
Proceed @Akshansh8
