### ISSUE TITLE
[Feature] Add Fraction Calculator

### ISSUE THREAD

**Issue by kamalesh-og** [Rakesh9100/CalcDiverse#1360]
### Description

Hello Project Admin @Rakesh9100,

Adding an Operational Fraction Calculator to CalcDiverse will enable users to perform basic arithmetic operations (addition, subtraction, division, multiplication) on fractions. The calculator will allow users to click on the "+" button to select different operators and then click on "=" to get the result. This tool will provide a straightforward way to handle fraction calculations, making it an invaluable addition to the CalcDiverse project.

I've previously contributed to CalcDiverse by implementing other calculators and would love to further enhance this amazing repository with the addition of the Fraction Calculator. This is a simple yet handy calculator for this repo.

@Rakesh9100 Can you assign me this project? I am eager to work on this calculator and make fraction calculations easy and accessible for all users.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/163159351/76ef2844-ced8-4c64-948b-0c575f786fb1)
Here I just used HTML code, should add CSS for better UI, and should add JS for the functionality of the respective inputs given.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @kamalesh-og

**Comment by kamalesh-og** [comment]
done sir @Rakesh9100
