### ISSUE TITLE
[Feature] Add Matrix Calculator

### ISSUE THREAD

**Issue by animex007** [Rakesh9100/CalcDiverse#1361]
### Description

The **Matrix Operations Calculator** will allow users to perform various operations on matrices, including but not limited to:

- Matrix Addition and Subtraction
- Matrix Multiplication (both scalar and matrix)
- Calculation of Determinants
- Finding Inverses of Matrices
- Computing Eigenvalues and Eigenvectors
- Transpose of a Matrix
- Special Matrices (Identity, Diagonal, Zero)

1. *Features:*
  - User Input: Users can input matrices manually or upload a file (e.g., CSV).
  - Operation Selection: Users can choose from a list of available operations.
  - Detailed Output: Results are provided in both textual and graphical formats, where applicable.
  - Visualization: For operations like multiplication and finding eigenvalues, provide visual aids such as graphs or step-by-step solutions.
  - Error Handling: Ensure robust error handling for invalid inputs (e.g., non-square matrices for determinant calculation).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
issue for transpose already exists #1353, please collaborate, rest is fine

**Comment by Rakesh9100** [comment]
We already have Matrix-Calculator, check out if you want to add more features into that @animex007
