### ISSUE TITLE
[Feature] Add Set Operations Calculator

### ISSUE THREAD

**Issue by bhumii-ka** [Rakesh9100/CalcDiverse#1362]
### Description

This calculator can perform basic set operations between two or three sets like finding : 
 - Union
 -  Intersection
 -  Cross Product 
 -  Difference
 -  Power set
 - Cardinality

Please assign me this issue under GSSoC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , please assign under GSSSOC
i have already made it.
![Uploading image.png…]()

**Comment by bhumii-ka** [comment]
> hey @Rakesh9100 , please assign under GSSSOC i have already made it. ![image](https://private-user-images.githubusercontent.com/127659443/342028783-b2d8bf37-f4b9-4298-b382-d3a61c319544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjMzOTIsIm5iZiI6MTcxOTEyMzA5MiwicGF0aCI6Ii8xMjc2NTk0NDMvMzQyMDI4NzgzLWIyZDhiZjM3LWY0YjktNDI5OC1iMzgyLWQzYTYxYzMxOTU0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNjExMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmVjNTcyNDQ4MGE0OGM2N2I2NGJiZjU3OTYyMjYyZDZiZWQ0ZTcyOTliOTBmMWZiODlhMGRlYTBmYWI4YzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qW19OBdYvWsb9Wp2gqsbulwSRLkE46ic6IvuyRwdArQ)


I have raised this issue and I've more features to add in my mind and I'm working on it

**Comment by Rakesh9100** [comment]
Go ahead @bhumii-ka

**Comment by Rakesh9100** [comment]
Status of your PR @bhumii-ka

**Comment by bhumii-ka** [comment]
Hi @Rakesh9100 the calculator part is done I just have to write a readme file for it .  I'll be creating PR in a hour or so
