### ISSUE TITLE
[Style] Enhance the hover effect in Bouncy Number Calculator

### ISSUE THREAD

**Issue by puneet426** [Rakesh9100/CalcDiverse#1365]
### Category of documentation update

there is much more transition due to which it looks unutractive

https://github.com/Rakesh9100/CalcDiverse/assets/168094736/212f4f03-a719-4f42-9cc3-24bb97da1a10

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@puneet426 what change do you have in mind?

**Comment by puneet426** [comment]
@jessicachawla I wanted to change the UI

**Comment by jessicachawla** [comment]
What kind of change? Please elaborate

**Comment by puneet426** [comment]
i want to change the duration of transition and font size after transition and also change page colors

**Comment by jessicachawla** [comment]
Okay. 
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @puneet426

**Comment by puneet426** [comment]
@jessicachawla can i add explaination in it ??

**Comment by Rakesh9100** [comment]
Provide your PR @puneet426
