### ISSUE TITLE
[Feature] Add explanation to Armstrong Number Calculator

### ISSUE THREAD

**Issue by puneet426** [Rakesh9100/CalcDiverse#1366]
### Description

Before
without explanation, if new one comes to know that what it is they face some problems

https://github.com/Rakesh9100/CalcDiverse/assets/168094736/40ded364-0f13-4e17-8e1b-b75c92497173

### Screenshots

After
https://github.com/Rakesh9100/CalcDiverse/assets/168094736/0f4e1b17-bdd7-47aa-8c76-3e70b21046d0

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by puneet426** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/168094736/5b39f8d3-9003-418e-845c-7f253a5b4826

**Comment by puneet426** [comment]
hello @Rakesh9100 please assign this issue to me i can the explaination part in each calculator so that it is more understandable

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by puneet426** [comment]
hello @Rakesh9100  can i proceed to add explaination in each calculator
