### ISSUE TITLE
[Bug] Fix input validation in BMI Calculator

### ISSUE THREAD

**Issue by puneet426** [Rakesh9100/CalcDiverse#1368]
### Description

In the BMI calculator there is no effect of age on the calculator  when i put the age 6 year and height 180cm and weight 80kg it shows result but it is not possible so we have to set some limitations or shows result Unhealthy

https://github.com/Rakesh9100/CalcDiverse/assets/168094736/5c212806-e944-4a83-985b-5620f2b5037d

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by kauxp** [comment]
Assign me this issue.

**Comment by Rakesh9100** [comment]
Go ahead @kauxp

**Comment by shawnsd69** [comment]
Subject: Request for Issue Assignment

Dear @Rakesh9100 ,

I hope this message finds you well. I’m eager to contribute to the CalcDiverse and would like to take on a task that could help move the project forward. If possible, could you please assign me this issue that aligns with my skills? I’m particularly interested in working on recent open source project, but I’m open to anything that needs attention.

Thank you for considering my request. I’m looking forward to your guidance and contributing to the project.

Best regards,
Shawn

**Comment by shaina123786** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Vijitverm1234** [comment]
please assign me this issue 
i can make it more user friendly and more informative by generating the description according to values
