### ISSUE TITLE
[Feature] Add Hashing Message Calculator 

### ISSUE THREAD

**Issue by ShreeluSantosh** [Rakesh9100/CalcDiverse#1369]
### Description

Proposal for adding a Hashing Message Calculator to the collection of calculators for this project.

## Proposed Features
* User input for message
* Drop down menu for available hash functions (like MD5, SHA1, SHA256)
* a field box with the generated message hash
* a field below the output, explaining about the selected hash function

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @ShreeluSantosh

**Comment by ShreeluSantosh** [comment]
Linked PR: #1438
