### ISSUE TITLE
[Feature] Back to Top Button for Website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/CalcDiverse#137]
### Description

I would like to create a back to top button for the website.

### Screenshots

- Smooth functioning
- Easy to scroll
- With Animations
- Glowing and neon light effect
- Responsive to the small devices, etc.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this task to me to work on it and contribute under SWOC'24

**Comment by Rakesh9100** [comment]
Go ahead @Avdhesh-Varshney
