### ISSUE TITLE
[docs] Improving Contributing Guidelines Readme File

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/CalcDiverse#138]
### Category of documentation update

- I would like to design the contributing guidelines readme file.
- By providing each and every step to the contributors.
- Adding coloring and designing to make it more readable and got attention of the contributors.

### Describe the change you think might work

- Adding all the commands with example.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)"

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this task to me to work on it and contribute under SWOC'24

**Comment by Rakesh9100** [comment]
Proceed @Avdhesh-Varshney
