### ISSUE TITLE
[Feature] Add Sunrise Sunset Calculator

### ISSUE THREAD

**Issue by ananyag309** [Rakesh9100/CalcDiverse#1389]
### Description

Provides sunrise and sunset times based on location and date. moreover, a Sunrise-Sunset Calculator determines the exact times of sunrise and sunset based on geographical location and date. It's invaluable for photographers, outdoor enthusiasts, and anyone planning activities dependent on natural lighting conditions. This tool ensures precise planning for optimal photography sessions or outdoor events.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SHRAVANIc01** [comment]
I want to contribute,can you assign me this?

**Comment by Rakesh9100** [comment]
We already have this calculator, https://calcdiverse.netlify.app/calculators/sunrise-sunset-calculator/ @ananyag309
