### ISSUE TITLE
[Feature] Matrix Calculator

### ISSUE THREAD

**Issue by Gitesh08** [Rakesh9100/CalcDiverse#139]
### Description

Matrix calculator is calculator which can perform matrix operations such as Addition, Subtraction and Multiplication very efficiently.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct]

**Comment by Gitesh08** [comment]
Hello @Rakesh9100, Please assign this task to me.

**Comment by Rakesh9100** [comment]
Issue number 37 already exist for this. Pls open up new issues or comment on the issues with tag `up-for-grab` to get assigned @Gitesh08

**Comment by Rakesh9100** [comment]
@Gitesh08 Do you want to work on this?

**Comment by Gitesh08** [comment]
> @Gitesh08 Do you want to work on this?

Yes. Working on it.

**Comment by Gitesh08** [comment]
> @Gitesh08 Do you want to work on this?

Sure I would like to work on it
