### ISSUE TITLE
[Feature] Add Dream Journal Calculator

### ISSUE THREAD

**Issue by ananyag309** [Rakesh9100/CalcDiverse#1390]
### Description

this is quite an interesting calculator Analyzes dream entries based on keywords and emotions to generate insights or interpretations about recurring themes or patterns in dreams.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@ananyag309 please elaborate the use case, inputs you will ask and outputs

**Comment by ananyag309** [comment]
@jessicachawla  user will input Inputs:
Dream Entries: like - Title: Brief title of the dream.
Date: The date when the dream occurred.
Description: Detailed text entry describing the dream.
Emotions: List of emotions experienced during the dream, provided as comma-separated values.

Outputs:
Keyword Analysis:
Word Cloud: Visual representation of the most frequently occurring words in the dream descriptions.
Recurring Words: List of keywords that appear multiple times across different entries.
Emotion Analysis:
Emotion List: Display of emotions tagged by the user.
Insights and Interpretations:
Summary of recurring themes based on the keyword and emotion analysis.
Basic interpretation of the patterns identified in the dream entries.

**Comment by jessicachawla** [comment]
Okay seems fine 
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @ananyag309
