### ISSUE TITLE
[Feature] <Add Degree Celsius to Farhenite Calculator>

### ISSUE THREAD

**Issue by AnshikaAg03** [Rakesh9100/CalcDiverse#1395]
### Description

i want to add this calculator which will convert temperature given in Degree celsius to Farhenite.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AnshikaAg03** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
We already have Temperature Calculator for this, pls work on new issues @AnshikaAg03
