### ISSUE TITLE
[Feature] Add Hailstone Series Calculator

### ISSUE THREAD

**Issue by pavitraag** [Rakesh9100/CalcDiverse#1398]
### Description

A Hailstone series is defined as follows: start with any integer value greater than 0, say x. If x is even, then the next value in the series is x/2; if x is odd, then the next value in the series is 3x + 1. Now apply the same rules to create the next value in the series, and so on.

In input, the first line of input is the starting number of the series and the next line consists of the number of terms to generate in the series.

Ex:
Input :17
           5

Output: 17 52 26 13 40 

Input : 26
            6

Output: 26 13 40 20 10 5 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by pavitraag** [comment]
Hey @Rakesh9100 ,assign this to me under gssoc24.

**Comment by Rakesh9100** [comment]
Go ahead @pavitraag
