### ISSUE TITLE
Loan EMI (Equated Monthly Installment) Calculator

### ISSUE THREAD

**Issue by itsmeabhishek03** [Rakesh9100/CalcDiverse#14]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Input loan amount, interest rate, and tenure to calculate the monthly installment for a loan. Please assign this to me under SWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by gautamkhokhar0001** [comment]
Please assign me this issue. I want to contribute.

**Comment by Rakesh9100** [comment]
@itsmeabhishek03 Assigning, Proceed!!

**Comment by Rakesh9100** [comment]
@itsmeabhishek03 Update of your work pls

**Comment by itsmeabhishek03** [comment]
Hey @Rakesh9100 I will raise PR today

**Comment by Rakesh9100** [comment]
Hey @itsmeabhishek03 Your PR?

**Comment by Shreyas-SAS** [comment]
yeah sure, please assign this to me.

**Comment by Shreyas-SAS** [comment]
I am sorry, I guess I missed this issue and created a new one. Please close one of the issues, either this one or #101

**Comment by Rakesh9100** [comment]
Closing the issue #101, you can continue to work on this issue and integrate your more functionalities mentioned there in this issue only.

Also update this issue description accordingly @Shreyas-SAS

**Comment by VivekYadav7272** [comment]
This issue is still labelled up-for-grab. Is it?

**Comment by Shreyas-SAS** [comment]
No sorry, I started working.

**Comment by Rakesh9100** [comment]
@Shreyas-SAS Status of your PR

**Comment by Shreyas-SAS** [comment]
Have completed most of the work but will take about 2 days for all my assigned issues. 

Sorry for the delay. Have some urgent and important work with academics. Will put up the PR asap. 

Thanks,
Shreyas.

**Comment by Rakesh9100** [comment]
@Shreyas-SAS Provide the update of your PR pls

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS Provide the update of your PR pls

this one is a major issue, will take a bit more time with the added features i talked about.

I tried to display a pi chart but couldn't work it out well.

**Comment by Rakesh9100** [comment]
Alright, needed an update that you are working!

Try to create PR asap @Shreyas-SAS

**Comment by Shreyas-SAS** [comment]
> Alright, needed an update that you are working!
> 
> Try to create PR asap @Shreyas-SAS

yeah! sorry, it was difficult than I though but worth the learning.

**Comment by Rakesh9100** [comment]
No issues, Open source is for learning and then contributing so don't worry and try to give your best @Shreyas-SAS

**Comment by SoumyadevSaha** [comment]
HI @Rakesh9100, if this issue gets 'up for grab' again or may be there remains something to be updated/implemented, I would like to ork on this issue under JWOC'24

**Comment by Shreyas-SAS** [comment]
> HI @Rakesh9100, if this issue gets 'up for grab' again or may be there remains something to be updated/implemented, I would like to ork on this issue under JWOC'24

not a stale issue, currently on progress under different issue ID. 
If I feel I cannot do it, will place a message accordingly tagging you.

Thanks,
Shreyas.

**Comment by Rakesh9100** [comment]
Do you want to work @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Do you want to work @SoumyadevSaha

Yes, please assign me this under IWOC

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha

**Comment by Rakesh9100** [comment]
Were you ready with your PR waiting to push instantly 🤔❓ @SoumyadevSaha

**Comment by Rakesh9100** [comment]
Were you ready with your PR waiting to push instantly after getting assigned 🤔❓ @SoumyadevSaha
