### ISSUE TITLE
Add Event Countdown Calculator

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/CalcDiverse#1403]
### Description

Calculates the countdown to a specific event based on the current date and time.
Displays days, hours, minutes, and seconds remaining until the event.

### Screenshots

NA

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zalabhavy** [comment]
@Rakesh9100 Please assign me this task !

**Comment by jessicachawla** [comment]
@zalabhavy please tell the need for this? Also how is it better than the normal ones available on Google or other apps?

**Comment by zalabhavy** [comment]
@jessicachawla It is like reverse counter if there is any event or birthday of my friend so i can set that Countdown at that time of birthday when countdown becomes 00:00:00 it gives effects showing celebration that i think to create.

**Comment by jessicachawla** [comment]
That is the normal already existing countdown calculators. So no point making the same thing.

**Comment by zalabhavy** [comment]
@jessicachawla Yes it is already existing in google but not existing in CalcDiverse.I will try to make that unique !
I think it is normal but very usefull.
Thank You !

**Comment by jessicachawla** [comment]
@Rakesh9100 please see if you want this.

**Comment by Rakesh9100** [comment]
No need of this much basic calculator, pls create issues to add some good and useful calculators @zalabhavy
