### ISSUE TITLE
[Feature] Add Event Budget Planner Calculator

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/CalcDiverse#1404]
### Description

Plans and estimates budgets for events (e.g., weddings, parties) based on guest count, venue, catering, and other expenses.

Breaks down costs and compares with budget allocations.

### Screenshots

NA

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zalabhavy** [comment]
@Rakesh9100 Please assign me !

**Comment by jessicachawla** [comment]
@zalabhavy are you willing to put a piechart as well to enforce the breakup of the cost?

**Comment by zalabhavy** [comment]
@jessicachawla Sure I will add piechart to breakup the cost !

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned. 
@zalabhavy please mention the price in both USD and INR

**Comment by zalabhavy** [comment]
@jessicachawla Ok fine !

**Comment by Rakesh9100** [comment]
Go ahead @zalabhavy
