### ISSUE TITLE
[Feature] Gauss Elimination Solver 

### ISSUE THREAD

**Issue by AbheetHacker4278** [Rakesh9100/CalcDiverse#1411]
### Description

Here I want to Add gauss Elimination Solver , using the power of HTML , CSS and JAVASCRIPT , with Cool and Asthetic desgines and best UI-UX.

@Rakesh9100 please assign this Task to me Under GSSOC24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbheetHacker4278** [comment]
@jessicachawla please assign this PR to me as soon as possible

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
