### ISSUE TITLE
[Style] Enhance Conductivity And Resistivity Calculator UI

### ISSUE THREAD

**Issue by aaryancodeshere** [Rakesh9100/CalcDiverse#1414]
### What's the style idea?

# Design issue in the Conductivity and Resistivity Calculator.

We need to improve the design of the conductivity and resistivity calculator. There is no heading, and neither the input bar nor submit is placed properly.

<img width="1430" alt="Screenshot 2024-06-24 at 10 05 15 AM" src="https://github.com/Rakesh9100/CalcDiverse/assets/124273822/224e2684-9350-4ee3-9c4b-b92696d64952">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @aaryancodeshere
