### ISSUE TITLE
[Feature] Add AC/DC Power Calculator

### ISSUE THREAD

**Issue by SiriAmarlapudi** [Rakesh9100/CalcDiverse#1417]
### What would you like to share?

The AC/DC Power Converter Calculator is a web-based tool designed to help users convert power values between alternating current (AC) and direct current (DC). 
This calculator allows users to input either AC parameters to obtain the equivalent DC power or DC parameters to get the equivalent AC power, depending on their needs.
This web based tool is designed by html,css,javascript.

### Additional information

The app allows users to select the type of conversion they want to perform: either AC to DC or DC to AC.
This selection is handled by a dropdown menu in the form.
Depending on the user's choice, the appropriate input fields (either for AC or DC parameters) are displayed.

--For AC to DC conversion, the user needs to input:

1.AC Voltage (V)
2.AC Current (A)
3.Power Factor (a value between 0 and 1)

--For DC to AC conversion, the user needs to input:

1.DC Voltage (V)
2,DC Current (A)
The converted AC/DC power is displayed as output power.

Screenshot:
![1](https://github.com/Rakesh9100/CalcDiverse/assets/133572565/1d479ce0-6362-4d94-886e-e1c622190662)
![2](https://github.com/Rakesh9100/CalcDiverse/assets/133572565/2b1526c4-f054-49a2-ac98-1c3a46fb60fb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@SiriAmarlapudi will you provide graphs?

**Comment by SiriAmarlapudi** [comment]
Only for output power or input also
Can u please specify.
I can add graphs

**Comment by jessicachawla** [comment]
Both input and output.

**Comment by SiriAmarlapudi** [comment]
Yes,I can add graphs

**Comment by jessicachawla** [comment]
Okay good 
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @SiriAmarlapudi

**Comment by Rakesh9100** [comment]
Pls provide your PR @SiriAmarlapudi

**Comment by SiriAmarlapudi** [comment]
Hey...sorry for being unavailable. I have completed . if u will assign me i'll submit the PR

**Comment by Rakesh9100** [comment]
Okay, provide your PR today itself @SiriAmarlapudi
