### ISSUE TITLE
[Docs] Add the missing Open Source Program name

### ISSUE THREAD

**Issue by solanki505** [Rakesh9100/CalcDiverse#1419]
### Category of documentation update

![Screenshot 2024-06-24 120646](https://github.com/Rakesh9100/CalcDiverse/assets/158484284/6d496ebf-ad06-4552-8c87-961b0971684c)
in this question we can add GSSOC'24 name also

### Describe the change you think might work

I shall modify the answer by adding GSSOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @solanki505
