### ISSUE TITLE
Body Surface Area (BSA) Calculator 

### ISSUE THREAD

**Issue by susmithavarma02** [Rakesh9100/CalcDiverse#1420]
### Description

The calculation of BSA is an important tool in the medical field, providing a standardized way to measure and dose patients accurately. It accounts for individual differences in body size, which can be critical for effective and safe medical treatment. To create a Body Surface Area (BSA) Calculator, we must implement the formula used to calculate BSA based on height and weight. One of the most commonly used formulas is the Mosteller formula.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Issue already exits. Please close
