### ISSUE TITLE
[Feature] Add Gauss-Jordan Elimination Calculator

### ISSUE THREAD

**Issue by Vipullakum007** [Rakesh9100/CalcDiverse#1421]
### Description

user can solve systems of simultaneous linear equations using Gauss-Jordan Elimination Calculator

### Screenshots

![Screenshot 2024-06-24 172131](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/24ec08c8-9480-4979-a00f-b905d2ce22c6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 , please assign to i have made it already.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Vipullakum007** [comment]
I have raised this issue and I've more features to add in my mind and I'm working on it.
@Rakesh9100 please assign this issue to me.

**Comment by jessicachawla** [comment]
Will be assigned soon.

**Comment by Rakesh9100** [comment]
Go ahead @Vipullakum007

**Comment by PDBharadwaj** [comment]
@Rakesh9100 I want to work on this issue. Please assign me.

**Comment by Rakesh9100** [comment]
Go ahead @PDBharadwaj
