### ISSUE TITLE
[Feature] Add Eye Power Calculator

### ISSUE THREAD

**Issue by SHANMUGAPRIYA-1** [Rakesh9100/CalcDiverse#1423]
### Description

I will create a eye power calculator in which right eye power and left eye power are inputted from user and total eye power is calculated.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Please tell the need for this

**Comment by SHANMUGAPRIYA-1** [comment]
An eye power calculator is a practical tool designed for both individuals
and eye care professionals. It allows users to quickly and accurately
determine their combined eye power by inputting the power values of the
right and left eyes. This can be particularly useful for patients
conducting self-assessments at home, ensuring they have accurate
information when purchasing eyewear or consulting with optometrists.
Additionally, it helps optometrists and opticians reduce calculation
errors, facilitating better patient care. The calculator also serves
educational purposes, helping students and trainees understand the
importance of precise eye power calculations in vision correction.

**Comment by jessicachawla** [comment]
@Rakesh9100  this issue can be assigned

**Comment by SHANMUGAPRIYA-1** [comment]
Thanks a lot.

**Comment by SHANMUGAPRIYA-1** [comment]
can you please assign eye calculator

**Comment by Rakesh9100** [comment]
Go ahead @SHANMUGAPRIYA-1
