### ISSUE TITLE
[Style] Make Centripetal Force Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#1426]
### Description

 Centripetal-Force-Calculator is not responsive

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/7e483e5d-3f08-4913-88ca-2a51ea999df5)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/7e483e5d-3f08-4913-88ca-2a51ea999df5)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@agastya3636 please tell how are you planning to fix

**Comment by Rakesh9100** [comment]
Go ahead @agastya3636

**Comment by Rakesh9100** [comment]
Go ahead @agastya3636 

It will be made responsive for every screen size @jessicachawla

**Comment by Rakesh9100** [comment]
Provide your PR @agastya3636

**Comment by kauxp** [comment]
If no one is working on this, please assign me this issue.

**Comment by Rakesh9100** [comment]
Go ahead @kauxp
