### ISSUE TITLE
[Feature] Add Loan Comparison Calculator

### ISSUE THREAD

**Issue by Manav173** [Rakesh9100/CalcDiverse#1431]
### Description

This tool allows users to compare different loan options side-by-side, considering interest rates, loan terms, and monthly payments.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/117214680/8e2b5e03-d530-4c06-8bf5-c7c3ceece672)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Please change the ui a bit. Make it similar to the website colors

**Comment by Manav173** [comment]
Yes, I will change the UI to match that of the website when the issue is assigned to me. 
I would be really thankful if you assign me this issue as a part of GSSoC'24 @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @Manav173
