### ISSUE TITLE
[Feature] Add Lorentz Force Calculator

### ISSUE THREAD

**Issue by GAVINESHWAR** [Rakesh9100/CalcDiverse#1432]
### Description

It is an physics related calculator used to find the force on a moving charge.
Inputs
Formula: 
𝐹=𝑞𝑣𝐵sin(𝜃)
Inputs: Charge (q), Velocity (v), Magnetic field strength (B), Angle between velocity and magnetic field (𝜃)
Output: Magnetic force (F)

It is very useful for the physics calculations in magnetic field chanpters
@Rakesh9100 sir, I would be happy to contribute to the project. Could you please assign me this issue so that I can work on it?

Thank you

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124431955/d7c90e49-7603-48a0-9a06-c1cc025a103e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
What will be the name of your calculator in short and specific @GAVINESHWAR

**Comment by GAVINESHWAR** [comment]
@Rakesh9100 Lorentz Force calculator sir ,

**Comment by GAVINESHWAR** [comment]
@Rakesh9100 assign me this issue to make contribution sir.

Thank you

**Comment by Rakesh9100** [comment]
Pls go ahead @GAVINESHWAR
