### ISSUE TITLE
[Feature] Add Capacitance Calculator

### ISSUE THREAD

**Issue by GAVINESHWAR** [Rakesh9100/CalcDiverse#1436]
### Description

The capacitance of a parallel plate capacitor with a dielectric is given by  𝐶=𝜅𝜖0𝐴/𝑑  where 𝜅 is the dielectric constant, 𝜖0 is the permittivity of free space, 𝐴 is the area of the plates, and d is the distance between the plates. This formula accounts for the increased capacitance due to the dielectric material, which enhances the capacitor's ability to store charge.

Formula: 
𝐶=𝜅𝜖0𝐴/𝑑
 
Inputs: Dielectric constant (κ), 
Permittivity of free space (𝜖0),
 Area of the plates (A), 
Distance between the plates (d)
Output: Capacitance (C)

@Rakesh9100, please assign me this issue to make contribution to the project sir.

Thank you

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124431955/9dd868ca-05ba-430e-9abf-c159889205cd)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@GAVINESHWAR consider giving output for both series and parallel. You can ask in input if it's parallel or series connection

**Comment by GAVINESHWAR** [comment]
@jessicachawla  mam, parallel plate capacitors are a type of capacitor that have an arrangement of electrodes and insulating material (dielectric). This calculator determines the capacitance of a single capacitor.

If required, I can add another calculator for finding the equivalent capacitance of capacitors connected in parallel and series combinations.

Thank you mam

**Comment by jessicachawla** [comment]
Looks good
@Rakesh9100 this issue can be assigned

**Comment by GAVINESHWAR** [comment]
@Rakesh9100 assign me this issue to make contribution to the project sir.

Thank you

**Comment by GAVINESHWAR** [comment]
@Rakesh9100 assign me this issue to make contribution to the project sir, It was checked the jessicachawla .

Thank you

**Comment by Rakesh9100** [comment]
Go ahead @GAVINESHWAR
