### ISSUE TITLE
[Feature] Decimal to binary calculator

### ISSUE THREAD

**Issue by Komal73** [Rakesh9100/CalcDiverse#144]
### Description

to add a calculator for converting decimal/integer to binary format for learning for coding purpose.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Issue and PR already exist for this. Pls work on other good issues @Komal73

**Comment by Komal73** [comment]
okay @Rakesh9100
