### ISSUE TITLE
[Feature] Implementation of pagination on the website

### ISSUE THREAD

**Issue by pandeyji711** [Rakesh9100/CalcDiverse#1445]
### Description

@Rakesh9100 
###  makes it easier for users to locate their calculator.

**Implementing pagination on your website not only improves its visual appeal but also significantly enhances user experience. By dividing content into manageable sections, users can easily navigate through the site without feeling overwhelmed by an excess of information on a single page. This organized structure helps users quickly find specific tools or features, such as a calculator, without getting lost in a sea of content.**

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@pandeyji711 please give a rough idea of how the ui will look. You can try making a low-fi on figma

**Comment by pandeyji711** [comment]
@jessicachawla @Rakesh9100 
### I impliment this on footer 
![Screenshot 2024-06-26 152737](https://github.com/Rakesh9100/CalcDiverse/assets/154527778/b13c207f-c1eb-4f8a-948a-5414033e8d80)

**Comment by jessicachawla** [comment]
Okay 
@Rakesh9100 this issue can be assigned

**Comment by pandeyji711** [comment]
@Rakesh9100  please assign this issue to me

**Comment by pandeyji711** [comment]
@Rakesh9100 @jessicachawla please assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @pandeyji711
