### ISSUE TITLE
[Feature] Add T-Score Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1446]
### Description

A T-score calculator is a tool commonly used in statistics and medicine for various purposes.

Student's T-Test: It is used to determine if there is a significant difference between the means of two groups. The T-score helps in understanding if the observed differences are due to chance or a real effect.

T-Distribution: It is particularly useful when dealing with small sample sizes (typically n < 30) where the population standard deviation is unknown.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/7d5575f1-1f05-4cca-9e21-5d7f1cc1cac4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned. 
@TBorundia keep the ui colors similar to the website.

**Comment by TBorundia** [comment]
@jessicachawla  
Yes, I will ensure that the UI design of calculator matches to the theme of the website. Please assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead @TBorundia
