### ISSUE TITLE
[Feature] Add EPF (Employee Provident Fund) Calculator

### ISSUE THREAD

**Issue by AsmitaMishra24** [Rakesh9100/CalcDiverse#1447]
### Description

An Employee Provident Fund (EPF) calculator is a financial tool designed to help employees estimate their provident fund savings over time. This tool considers the employee's basic salary, contribution percentages from both the employee and employer, and the interest rate to compute the accumulated amount in the EPF account at the end of a specified period.

### Screenshots

![Screenshot 2024-06-25 233736](https://github.com/Rakesh9100/CalcDiverse/assets/146121869/892d2101-afed-4b5c-bcdd-3138b5aae642)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@AsmitaMishra24 instead of the dragging option, ask for inputs and pls change the color from green to purple so that it matches with the website.

**Comment by jessicachawla** [comment]
Okay great 
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @AsmitaMishra24

**Comment by Rakesh9100** [comment]
Pls provide your PR @jessicachawla

**Comment by AsmitaMishra24** [comment]
> Pls provide your PR @jessicachawla

i will make PR by the EOD
