### ISSUE TITLE
[Calculator] <Daily Water Intake Calculator>

### ISSUE THREAD

**Issue by Vipullakum007** [Rakesh9100/CalcDiverse#1449]
### Description

A calculator that suggests the amount of water one should drink daily based on weight, activity level, and climate.

### Screenshots

Home Page
![image](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/7d82f33d-aa27-482e-bb63-d65c1d9c92f3)
After Result
![image](https://github.com/Rakesh9100/CalcDiverse/assets/127659443/7d82f33d-aa27-482e-bb63-d65c1d9c92f3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vipullakum007** [comment]
hey @Rakesh9100 @jessicachawla , please assign to me i have already made it.

**Comment by jessicachawla** [comment]
@Vipullakum007 please change the color to match with the website.

**Comment by Vipullakum007** [comment]
hey @jessicachawla , what do you mean to say i not be able to understand can you explain more?

**Comment by jessicachawla** [comment]
The screenshots you have given are not going with the UI of the existing website. Please consider that and change the ui a bit.

**Comment by Rakesh9100** [comment]
We already have [Water Intake Calculator](https://calcdiverse.netlify.app/calculators/water-intake-calculator/) @Vipullakum007 @jessicachawla
