### ISSUE TITLE
[Style] Enhance the About Us page

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/CalcDiverse#1451]
### Description

I want to improve the **About Us** page as its written in the simple text will put it into the box and when it will be hover then it will show  the details and also its a responsive too and matches the color theme 

Assign me this issue under **GSSOC24**

### Before Hover 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/665f91c8-76fc-41e2-aec3-ec86f1482e56)

### After Hover 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/a41ff87c-a2ea-440a-991f-6926b76ff579)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Provide the example screenshot of how it will look after your changes @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
I have added the screenshot above which shows that it will be in simple and clean heading in rectangular box and after we hover on it it will change the state to the paragraph of the mission , vision , goal 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/99cf7d9d-a1d1-43c6-833f-4eae8fcdf378)

After Hover 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/7a52a2e9-9765-4892-b952-e946fc5f1841)

after hovering the light purple color shows the transaction and shows the text and its responsive too

**Comment by Rakesh9100** [comment]
I need the screenshot example of how the actual page of website will look after your changes, it is not clear from your screenshot that what will you do @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/74767abb-c854-4cca-8d7c-69a0edcf720f)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/119167105/082473d3-eb49-4d31-aae7-f8ffd48ad9d8)


This is the Overview after putting this into the about us page

**Comment by Rakesh9100** [comment]
Okay go ahead @SaiyamTuteja

**Comment by Rakesh9100** [comment]
Any update on this @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
Working on it

**Comment by SaiyamTuteja** [comment]
Check this PR #1799 i have solved the issue which you are facing
