### ISSUE TITLE
[Feature] Add more inputs in GST Calculator

### ISSUE THREAD

**Issue by Svastik73** [Rakesh9100/CalcDiverse#1453]
### Description

Adding options for multiple GST options on different items . This feature can be usefull for traders.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Svastik73 what all inputs will you be taking from the user?

**Comment by Svastik73** [comment]
Price: The base price of the product ,
GST Rate, 
Discounts: Any discounts ,
Quantity,
HSN/SAC Code: to determine correct GST rate based on the product/service category.
State/UT: for state-specific GST rates if any.

**Comment by Rakesh9100** [comment]
We already have GST Calculator, you can enhance and add more functionality in that if you want @Svastik73

**Comment by Svastik73** [comment]
okay sure...

**Comment by Rakesh9100** [comment]
What kind of enhancement will you do, pls specify @Svastik73

**Comment by Svastik73** [comment]
Like: asking for product/service category, state and an option of add gst / remove gst options and quantity too.

**Comment by Rakesh9100** [comment]
Okay proceed @Svastik73
