### ISSUE TITLE
[Feature] Add country flag beside country codes in Currency Calculator

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1456]
### Description

I can add a feature in currency calculator which also displays the country's flag of the country selected in both from and to countries.
![Screenshot (529)](https://github.com/Rakesh9100/CalcDiverse/assets/143121854/cbe7176e-4530-452c-99c5-c914fca02311)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @meetarora10

**Comment by PDBharadwaj** [comment]
I wanted to work on this issue. @Rakesh9100 Please assign me this issue.

**Comment by Rakesh9100** [comment]
Go ahead @PDBharadwaj
