### ISSUE TITLE
[Feature] Add 404 error page

### ISSUE THREAD

**Issue by PratikMane0112** [Rakesh9100/CalcDiverse#1459]
### Description

When unknown URL is visited, 404 error page is missing for better user interaction -

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/153143167/50c4fac3-9e0b-4f48-a5f3-f7c09416e56f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100  this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @PratikMane0112
