### ISSUE TITLE
[Feature]: Currency Convertor Calculator 

### ISSUE THREAD

**Issue by codercake** [Rakesh9100/CalcDiverse#1461]
### Description

A currency converter calculator is a tool that allows users to convert amounts from one currency to another based on current exchange rates. This tool can be particularly useful for travelers, businesses, and anyone dealing with multiple currencies.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Currency Calculator, pls create new issues @codercake
