### ISSUE TITLE
[Feature] Add Color Code Calculator

### ISSUE THREAD

**Issue by codercake** [Rakesh9100/CalcDiverse#1462]
### Description

Convert color values between HEX, RGB, and HSL formats. This can be v useful for web developers and designers. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Color Code Calculator, pls create new issues after checking the website and existing issues thoroughly @codercake

**Comment by codercake** [comment]
so do i create one or not?


> We already have Color Code Calculator, pls create new issues after checking the website and existing issues thoroughly @codercake
