### ISSUE TITLE
[Feature] Add Cooking Measurement Calculator

### ISSUE THREAD

**Issue by codercake** [Rakesh9100/CalcDiverse#1463]
### Description

A calculator that pretty much converts between different cooking measurements (e.g., cups to grams, tablespoons to milliliters).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Will you be doing for pounds as well?

**Comment by Rakesh9100** [comment]
Any update on this @codercake

**Comment by Rakesh9100** [comment]
Why did you create a pull request directly without being assigned to the issue? You should have first answered the question asked by the mentor above @codercake
