### ISSUE TITLE
[Feature] Add Cryptocurrency Calculator

### ISSUE THREAD

**Issue by Meetjain1** [Rakesh9100/CalcDiverse#1465]
### Description

Want to Add a cryptocurrency calculator that will display latest value using api .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Elaborate. Insufficient for us to understand what you want to do. Tell us the inputs, outputs, what quilt the ui be like, etc

**Comment by Meetjain1** [comment]
> Elaborate. Insufficient for us to understand what you want to do. Tell us the inputs, outputs, what quilt the ui be like, etc

sure have a look , 

https://github.com/Rakesh9100/CalcDiverse/assets/133582566/cf5c9c94-c1fc-42d3-8cad-84db987c657f

**Comment by Meetjain1** [comment]
please assign me @jessicachawla @Rakesh9100

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Meetjain1
