### ISSUE TITLE
[Feature] Add more functionality in Fraction Calculator

### ISSUE THREAD

**Issue by Dark-S8uL** [Rakesh9100/CalcDiverse#1467]
### Description

Fraction Converter Calculator
A Fraction Converter Calculator is a specialized tool designed specifically for converting fractions into their various forms: mixed fractions, proper fractions, and improper fractions. This calculator simplifies the process of understanding and working with different types of fractions by allowing users to input a fraction and instantly see its equivalent in other forms.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
This will one convert fraction to sine other kind of fraction? 
Consider conversion to other formats as well and tell if it's real or not as well

**Comment by Dark-S8uL** [comment]
@jessicachawla I don't think I fully understand what you were saying about… Could you tell me a bit more?

**Comment by jessicachawla** [comment]
Instead of changing just to other kinds of fractions, consider converting to decimals and in the output telling if the input is a real number or not. Please lmk if you have any other doubts

**Comment by Dark-S8uL** [comment]
ok @jessicachawla

**Comment by Rakesh9100** [comment]
We already have `Fraction-Calculator`, can you integrate your functionality to the existing calculator only @Dark-S8uL

**Comment by Dark-S8uL** [comment]
@Rakesh9100 Yes, I will do it

**Comment by Dark-S8uL** [comment]
@Rakesh9100 Assign this issue to me.

**Comment by Rakesh9100** [comment]
Okay, go ahead @Dark-S8uL

**Comment by Rakesh9100** [comment]
Pls provide your PR @Dark-S8uL
