### ISSUE TITLE
[Feature]: Period Date Calculator

### ISSUE THREAD

**Issue by vidhiisaxena** [Rakesh9100/CalcDiverse#1471]
### Description

Creating a period calculator which will take input the first date of last periods cycle of a girl and output the date of the beginning of the next period cycle as well as the ovulation date.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/144513634/90d6cdb8-cf43-441b-a5fc-84236bfaaf1c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
There are specific aids and websites for this which give much more info along with this. Why do you think we need this?

**Comment by vidhiisaxena** [comment]
CalcDiverse is a website which includes a diversity of calculators. A period date calculator will add to the inclusivity of this website and as it is frequently searched on web, will contribute to the web presence of CalcDiverse.

**Comment by vidhiisaxena** [comment]
please assign this issue to me so that I can start working on it.

**Comment by jessicachawla** [comment]
@Rakesh9100 please see if you think this should be in calcdiverse

**Comment by Rakesh9100** [comment]
No need of this, pls open issues to add some good calculators @vidhiisaxena
