### ISSUE TITLE
[Style] Enhance buttons in 5 Band Resistance Calculator

### ISSUE THREAD

**Issue by AnandK-pm** [Rakesh9100/CalcDiverse#1473]
### What's the style idea?

I intend to fix the :
* Primitive UI styling -  As the UI doesn't look appealing since it uses primitive HTML Styling.
* Need for scrolling and fitting the whole into the viewport -  Currently the users will have to Scroll down in order to view the full 
  features / options.  I intend to remove this by fixing the alignment and thereby ensuring a user friendly experience

![Screenshot 2024-06-28 114557](https://github.com/Rakesh9100/CalcDiverse/assets/142206618/5a55fd2c-ab40-4df9-9937-2e3cc30cab34)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100  please have a look at this

**Comment by AnandK-pm** [comment]
@Rakesh9100 Please Assign me the issue.

**Comment by Rakesh9100** [comment]
UI is already looking cool, what enhancements do you want to do @AnandK-pm

**Comment by AnandK-pm** [comment]
As i stated in the second point of the issue :
"Need for scrolling and fitting the whole into the viewport - Currently the users will have to Scroll down in order to view the full
features / options". I intend to remove this by fixing the alignment and thereby ensuring a user friendly experience

**Comment by Rakesh9100** [comment]
Okay proceed @AnandK-pm
