### ISSUE TITLE
[Feature] Add Gratitude Journal Calculator

### ISSUE THREAD

**Issue by ananyag309** [Rakesh9100/CalcDiverse#1483]
### Description

This calculator allows users to log daily gratitude points in a concise format.

User inputs their gratitude points for the day, separated by commas or semicolons.
The calculator processes the input and displays all logged points in a single, formatted line.

basically you can enter the gratitude words daily people said to you and accordingly it will calculate your gratitude points

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Why do we need this?

**Comment by ananyag309** [comment]
A gratitude journal calculator helps individuals track and quantify their expressions of gratitude over time. It provides a structured way to measure and reflect on gratitude, promoting mindfulness and enhancing overall well-being by encouraging regular acknowledgment of positive experiences and relationships.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @ananyag309
