### ISSUE TITLE
[Feature] Add Fractal Generator Calculator

### ISSUE THREAD

**Issue by ananyag309** [Rakesh9100/CalcDiverse#1484]
### Description

A Fractal Generator Calculator is a tool that allows users to create and visualize complex geometric patterns known as fractals. Here’s a brief overview of its input and output:

Input:

Fractal Type: Selects the type of fractal to generate (e.g., Mandelbrot set, Julia set).
Parameters: Adjusts parameters specific to the selected fractal type (e.g., scaling factor, rotation angle).
Resolution: Sets the resolution or detail level of the fractal image.

Output:

Fractal Image: Generates a visual representation of the selected fractal.
Interactive Exploration: Allows users to zoom in/out and navigate through different parts of the fractal for detailed exploration.
Color Palette: Optionally, applies color schemes to enhance visual appeal and distinguish different elements of the fractal.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned. 

@ananyag309 keto the ui similar to the already existing website

**Comment by ananyag309** [comment]
@Rakesh9100 sir please assign this issue to me under gssoc

**Comment by Rakesh9100** [comment]
Pls go ahead @ananyag309
