### ISSUE TITLE
[Feature] Add Centroid Of A Triangle Calculator

### ISSUE THREAD

**Issue by SumithThota** [Rakesh9100/CalcDiverse#1488]
### Description

This calculator aims to find centroid of a triangle 

# Importance of centroid
1. Centroid divides each median in a 2:1 ratio.
2. Centroid is the center of mass or balance point of the triangle.
3. The centroid is the intersection point of the three lines that divide the triangle into three equal areas.

# Used in:
1. Mechanics:
2. Geometry
3. Engineering

### Screenshots

# Note:
Here A,B,C are the three vertices of a triangle
Point G  is the centroid of that triangle

![Screenshot 2024-06-28 164857](https://github.com/Rakesh9100/CalcDiverse/assets/108344062/e9816c62-58bf-4e92-8024-de8dd4e9a0c8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
All you give a picture with your output? If yes, will the sides have length written along with it? Also will you be taking coordinates as input or length of the sides?

**Comment by SumithThota** [comment]
Yes the user need to enter co-ordinates as input 
User need to enter 3 coorinates (x ,y) as the triangle as 3 vertices

**Comment by jessicachawla** [comment]
Are you giving some sort of a diagram?

**Comment by SumithThota** [comment]
Sorry no, 
As the user enters data then centroid points will be the output

**Comment by bharat-c27** [comment]
@jessicachawla According to my understanding he is trying to tell that

**Inputs :** 
1) Take inputs for 3 vertices of the triangle A(x1,y1) , B(x2,y2), C (x3, y3)

**Calculations :**
1) x = ( x1 + x2+ x3 ) / 3
2) y = ( y1 + y2+ y3 ) / 3

The centroid coordinates will be G (x,y)

**Output :**
1) The output will be centroid coordinates G(x,y) 

@Rakesh9100 I am excited to contribute to the issue which have been assigned a label `up for grab` please can you assign it to me https://github.com/Rakesh9100/CalcDiverse/issues/1095

**Comment by jessicachawla** [comment]
@SumithThota pls consider giving a diagram as well

**Comment by SumithThota** [comment]
@jessicachawla Yes ok I will try my level best

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by SumithThota** [comment]
@jessicachawla Check this output
![Screenshot 2024-07-03 064227](https://github.com/Rakesh9100/CalcDiverse/assets/108344062/bcf24146-bfe7-4380-a900-b76fdec2cbc1)

**Comment by jessicachawla** [comment]
Mention the centroid coordinates on the side of the triangle in the diagram. Rest looks good. Well done!

**Comment by SumithThota** [comment]
@jessicachawla ok fine I will do it now.

**Comment by SumithThota** [comment]
@jessicachawla I am stilling waiting for your response 
Please assign me this issue and let me proceed.

**Comment by Rakesh9100** [comment]
Pls go ahead @SumithThota

**Comment by SumithThota** [comment]
Hello, @Rakesh9100
I have successfully completed the task 
check it over here #1548 and Please add appropriate labels to it
