### ISSUE TITLE
[Feature] Add Synchronous Speed Calculator

### ISSUE THREAD

**Issue by AkshatBujethiya** [Rakesh9100/CalcDiverse#1491]
### Description

A synchronous speed calculator is a tool which can be used to calculate the synchronous speed of an alternator using the value of frequency of current and number of poles. Alternatively, it can also calculate frequency and number of poles using the other two values.

We can utilize the following equation to implement this calculator:
$$N_s = \frac{120f}{P}$$

where $N_s$ is the Synchronous speed,
$f$ is the frequency and,
$P$ is the number of poles

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @AkshatBujethiya

**Comment by Rakesh9100** [comment]
Provide your PR @AkshatBujethiya
