### ISSUE TITLE
[Feature] Add more functionalities in Typing Speed Calculator

### ISSUE THREAD

**Issue by Nidhi-Satyapriya** [Rakesh9100/CalcDiverse#1493]
### Description

ISSUES:-
1) The result of this calculator **disappears in 1.5 secs**, leading to **inconvenience in readability** to the users and thus, **failing the purpose of taking the test.**
2) The **parameter** of determining the speed by only one line is **insufficient.** 

MY IMPLEMENTATIONS:-
1) Introduce a **'Retake Test'  button.** After taking the test, the results will be shown for as long as the 'Retake Test' button  is not clicked.
2) Introduce:-
     a) **3 levels of difficulty**- easy, medium, hard. Introducing digits, special characters based on difficulty level.
     b) **Test duration** of 1min, 3mins, 5 mins- to analyze better
     c) Display the result in **standard units- wpm**(words per minute) .
I would like to fix this bug and add this feature for accuracy. Kindly assign this to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100 Kindly assign this to me under GSSoC'24 with an appropriate tag.

**Comment by jessicachawla** [comment]
@Rakesh9100  this issue can be assigned

**Comment by Nidhi-Satyapriya** [comment]
Agreed @jessicachawla . @Rakesh9100 , kindly assign this one, since this covers both.

**Comment by Nidhi-Satyapriya** [comment]
any updates? @Rakesh9100 @jessicachawla

**Comment by Rakesh9100** [comment]
Pls go ahead @Nidhi-Satyapriya

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100 I made a PR. Kindly review it at your convenience.
