### ISSUE TITLE
[Feature] Add more functionalities in Typing Speed Calculator

### ISSUE THREAD

**Issue by Nidhi-Satyapriya** [Rakesh9100/CalcDiverse#1494]
### Description

The parameter of determining the speed by only one line is insufficient.

MY IMPLEMENTATIONS:-
1) Introduce:-
a) A 'Retake Test' button. After taking the test, the results will be shown for as long as the 'Retake Test' button is not clicked.
a) 3 levels of difficulty- easy, medium, hard. Introducing digits, special characters based on difficulty level.
b) Test duration of 1min, 3mins, 5 mins- to analyze better
c) Display the result in standard units- wpm(words per minute) .
I would like to add this feature for accuracy. Kindly assign this to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100 Kindly assign this to me.

**Comment by jessicachawla** [comment]
In the issue number #1493 you have mentioned the same implementation. Why create two separate issues?

**Comment by Nidhi-Satyapriya** [comment]
I was of the opinion that these additions might not come under 'Bug' .

**Comment by jessicachawla** [comment]
Yes these are not bugs. But if you have already mentioned it before there is no point in creating a new issue. You are just trying to get two issues completed from one problem. 
@Rakesh9100 please close either this issue or issue number #1493

**Comment by Rakesh9100** [comment]
It is under the Feature only, but no need to create same issue again. You can edit the previous issue title to Feature which I have done, pls take care from the next time @Nidhi-Satyapriya
