### ISSUE TITLE
Compound Interest Calculator

### ISSUE THREAD

**Issue by itsmeabhishek03** [Rakesh9100/CalcDiverse#15]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Calculate compound interest based on the principal amount, interest rate, and time period.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by gautamkhokhar0001** [comment]
Please assign me this issue. I want to contribute.

**Comment by MonuGit9** [comment]
Claim

**Comment by Yuvraj960** [comment]
Hello @itsmeabhishek03 , I want to work on this issue

**Comment by Rakesh9100** [comment]
Do you want to work @Yuvraj960

**Comment by Yuvraj960** [comment]
Yes @Rakesh9100 , I would like to work on this issue.

**Comment by Rakesh9100** [comment]
Okay, go ahead for the Compound Interest Calculator @Yuvraj960
