### ISSUE TITLE
[Feature] Fuel Efficiency Calculator

### ISSUE THREAD

**Issue by Akshansh8** [Rakesh9100/CalcDiverse#150]
### Description

input distance  and fuel consumed 
output the efficiency of the vehicle

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Carry on @Akshansh8
