### ISSUE TITLE
[Feature] Add Scientific Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#1500]
### Description

It helps us find the trigonometric and inverse trigonometric function, log values, sq root, cube root and many more.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Log-anti log both will be given? 
Also give some more features this is going to have

**Comment by Yuvraj960** [comment]
I am planning to add arctan, arcsin, arccos, cube root, natural log, natural antilog, log base 10, antilog base 10, pi, x inverse. If you have some other suggestions you can add as I am developing JavaScript code first. @jessicachawla

**Comment by Yuvraj960** [comment]
@Rakesh9100 Kindly assign this issue and view the PR for CPU scheduling calc #1472

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Pls go ahead, but before this resolve the discussions in CPU Scheduling Calculator @Yuvraj960

**Comment by Rakesh9100** [comment]
Kindly complete your assigned issues soon @Yuvraj960

**Comment by crazyshrut** [comment]
hey @Rakesh9100 @Yuvraj960, I want to work on this.
Can you assign this to me?
And one more thing, can I code it in javaScript?

**Comment by Rakesh9100** [comment]
Do you currently want to work on this and resolve it @crazyshrut

**Comment by Nishakulkarni06** [comment]
@Rakesh9100 can you assign it to me

**Comment by Rakesh9100** [comment]
Complete your assigned issue first @Nishakulkarni06

**Comment by Shashikumar-ezhilarasu** [comment]
Hi, I would like to work on this issue. Could you please assign it to me? @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @Shashikumar-ezhilarasu
