### ISSUE TITLE
[Style] Highlight the active menu item in navbar

### ISSUE THREAD

**Issue by KajalBhatt123** [Rakesh9100/CalcDiverse#1503]
### What's the style idea?

When hovering over the navigation links (Home, About, Calculators etc.), they turn pink as intended. However, once a link is clicked and the user navigates to that page, the color reverts to white, making it indistinguishable from inactive links. The current page link should remain pink in the navbar while inactive links should be white.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/133188585/071437d6-97c6-44c2-9f5e-62cd3be4abad)

#### This should remain 👇
![Screenshot 2024-07-06 204811](https://github.com/Rakesh9100/CalcDiverse/assets/133188585/c31d5cdd-c8cd-47ec-993f-13ff321066ca)
 **This will improve the user experience by clearly indicating the current page in the navigation bar**.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Pls attach the supporting screenshot in the issue description @KajalBhatt123

**Comment by KajalBhatt123** [comment]
@Rakesh9100  ok added

**Comment by Rakesh9100** [comment]
Go ahead @KajalBhatt123
