### ISSUE TITLE
[Feature] Add Savings Goal Calculator

### ISSUE THREAD

**Issue by Manav173** [Rakesh9100/CalcDiverse#1507]
### Description

Helps set and achieve savings goals by calculating the monthly savings needed.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/117214680/936e1eaa-852a-4e6c-980a-75947e690978)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Will the ui be the same as the screenshot? If yes, then please consider changing it to be more like the ui of the website

**Comment by Manav173** [comment]
That picture is just for the reference, I will change the css when I add this to the website.

**Comment by jessicachawla** [comment]
Okay 
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Manav173
