### ISSUE TITLE
[Feature] Add Thermal Expansion Calculator

### ISSUE THREAD

**Issue by aadium** [Rakesh9100/CalcDiverse#1509]
### Description

Any material undergoes thermal expansion according to the formula ΔL = αLΔT, where ΔL is the change in length, α is the thermal expansion coefficient, L is the initial length, and ΔT is the change in temperature. I can add this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @aadium

**Comment by aadium** [comment]
I just created a PR
