### ISSUE TITLE
[Feature] Add Zodiac Sign Calculator

### ISSUE THREAD

**Issue by nadarmega** [Rakesh9100/CalcDiverse#1512]
### Description

The Zodiac Calculator allows users to input their birthdate and receive their corresponding zodiac sign. This tool is perfect for those interested in astrology and looking to discover their astrological sign based on their date of birth.

Tech Stack:
HTML: For the structure of the web page.
CSS: For styling the calculator interface.
JavaScript: For calculating the zodiac sign based on the birthdate input.

### Screenshots

![zodiac calc](https://github.com/Rakesh9100/CalcDiverse/assets/127432792/864cddf3-95af-43ba-bedd-7e8144f5764f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by nadarmega** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by jessicachawla** [comment]
@nadarmega this can be found online. People just need to input their birthdate in Google and they will get to know about their zodiac signs.

**Comment by nadarmega** [comment]
hello @jessicachawla, my calculator will be providing personality descriptions as well as 


the most compatible signs for them. It would also benefit them by finding all this information in one place that is CalcDiverse. What other features would you like me to add?

**Comment by Rakesh9100** [comment]
Yes, we can add one to our website! Go ahead @nadarmega
