### ISSUE TITLE
[Feature] Add Special Number Calculator

### ISSUE THREAD

**Issue by pavitraag** [Rakesh9100/CalcDiverse#1517]
### Description

To check if the given number is a special number or not.

For example, 1729 is a special number since, when its digits are added together, produces a sum that, when multiplied by its reversal, yields the original number:

1 + 7 + 2 + 9 = 19

19 × 91 = 1729

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhiSharmaNIT** [comment]
I would like to work on this project please assign it to me.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by jessicachawla** [comment]
@pavitraag please consider the time complexity while writing the code. Do not write in O(n^2)

**Comment by pavitraag** [comment]
yeah ok @jessicachawla

**Comment by Rakesh9100** [comment]
Is this Special Number as A number is a special number if the sum of the factorial of the digits in the number is equal to the number itself.
Example:
145 is a special number because 1! + 4! +5! = 145 where 1! = 1, 4! = 24, 5! = 120 @pavitraag

**Comment by pavitraag** [comment]
No both mean different
The first definition which I gave involves digit sum manipulation and reversing.
The second definition which you gave involves the sum of factorials of the digits.

**Comment by pavitraag** [comment]
i found this question in a competitive exam

<img width="871" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/100479594/f46898ba-da29-41c0-93da-5fa5eb1480f2">

<img width="710" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/100479594/9450214f-1d07-4c97-b076-053adfd05e00">

**Comment by Rakesh9100** [comment]
Okay, go ahead @pavitraag
