### ISSUE TITLE
[Feature] Add Meal Calorie Calculator

### ISSUE THREAD

**Issue by ananyag309** [Rakesh9100/CalcDiverse#1518]
### Description

Add Meal Calorie Calculator
Input: Selection of foods or dishes with their portion sizes.
Output: Total calorie count for the entire meal.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhiSharmaNIT** [comment]
If we have unit count for calorie as per size then we calculate, You have any references for particular dishes.

**Comment by AbhiSharmaNIT** [comment]
But I like this concept and I would like to work on this project . please assign it to me.

**Comment by jessicachawla** [comment]
@ananyag309 the lost for the food will have to be pretty extensive. How are you planning on achieving that?

**Comment by jessicachawla** [comment]
@AbhiSharmaNIT please create your own issue or find an issue which has the tag 'up for grabs'. Commenting on other people's issues is not your job. We will ask the appropriate questions needed before assigning.

**Comment by jessicachawla** [comment]
Okay seems good. Try finding the most comprehensive list available online. You can try searching for 2 lists for dishes , one can be of Indian food and the other of continental and separate lists for fruits, veggies, sodas, etc. This will increase the number of dishes you have.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Please complete your assigned issues first, and if needed, we can discuss further or directly assign you, as @jessicachawla have already handled the discussion @ananyag309

**Comment by ananyag309** [comment]
@Rakesh9100 sir as i have completed the previous issue can you please assign this issue to me

**Comment by Rakesh9100** [comment]
Please go ahead @ananyag309
