### ISSUE TITLE
[Feature] Add Echo Time Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1521]
### Description

An Echo Time Calculator is a tool used in the field of Magnetic Resonance Imaging (MRI) to calculate the time between the delivery of a radiofrequency pulse and the reception of the echo signal. This time interval is known as the "Echo Time" (TE).

Purpose of Echo Time in MRI
In MRI, the Echo Time is a critical parameter that influences the contrast and quality of the images produced. Adjusting the TE can help differentiate between various types of tissues and abnormalities in the body.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/31d826a3-dac5-4ece-a9f9-3dae79cf40cf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TBorundia** [comment]
> @TBorundia who will be the target audience for this calculator? Will it be the doctors?

@jessicachawla Mam,
The primary target audience for an Echo Time Calculator indeed includes doctors, but it's not limited to them.
It also includes:
1.Cardiologists and Radiologists
2.Sonographers and Ultrasound Technician
3.Medical Students and Residents
4.Researchers in Cardiology and Medical Imaging

**Comment by TBorundia** [comment]
@Rakesh9100 @jessicachawla  please assign this issue to me.
Thank You!

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @TBorundia
