### ISSUE TITLE
[Feature] Add Endothermic Reaction Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1522]
### Description

An Endothermic Reaction Calculator is a tool used to determine various parameters associated with endothermic reactions. In an endothermic reaction, the system absorbs energy from its surroundings, usually in the form of heat. These reactions are characterized by a positive enthalpy change (ΔH).

Purpose of the Endothermic Reaction Calculator:
1.Calculate the change in enthalpy (ΔH) for a given reaction.
2.Determine the amount of heat absorbed during the reaction.
3.Understand the relationship between reactants, products, and energy absorbed.
4.Perform stoichiometric calculations involving energy changes.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/a52f376d-de93-472f-848a-bb702309c356)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhiSharmaNIT** [comment]
I would like to work on this project. please assign it to me.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by TBorundia** [comment]
@Rakesh9100 Sir, please assign this issue to me under GSSoC'24.
Thank You!

**Comment by Rakesh9100** [comment]
Pls complete your assigned issues first @TBorundia

**Comment by TBorundia** [comment]
> Pls complete your assigned issues first @TBorundia

@Rakesh9100 Sir,
I have completed my previous task and it also approved by the @Nihal4777. 
Now can you assign me this issue so that I can start working on it.

**Comment by TBorundia** [comment]
@Rakesh9100 Sir, you have merged my previous task.
So can I start working on this?
