### ISSUE TITLE
[Feature] Implement multilingual support

### ISSUE THREAD

**Issue by Ojas-Arora** [Rakesh9100/CalcDiverse#1524]
### Description

@Rakesh9100 I want to add multilanguage facility to the website. Kindly assign this issue to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Ojas-Arora** [comment]
@jessicachawla English,hindi,punjabi.marathi,urdu,french and any other u require

**Comment by jessicachawla** [comment]
Urdu not needed, add Spanish and german as well.

**Comment by Ojas-Arora** [comment]
Ok

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Ojas-Arora** [comment]
@jessicachawla @Rakesh9100 Can I start working on this issue?

**Comment by Rakesh9100** [comment]
Issue 873 is already open for this, you can comment there if you want to work @Ojas-Arora
