### ISSUE TITLE
[Feature] Add UV Index Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1527]
### Description

A UV Index Calculator is a tool designed to estimate the ultraviolet (UV) radiation level from the sun at a specific place and time. The UV Index is a standardized measure indicating the risk of harm from unprotected sun exposure, which helps individuals take appropriate precautions to protect their skin and eyes.

Uses and Benefits:
Health and Safety: Helps individuals avoid harmful UV exposure, reducing the risk of skin cancer, sunburn, and eye damage.
Planning Outdoor Activities: Assists in planning safe outdoor activities by providing information on the best times to be outside.
Education: Educates users about the dangers of UV radiation and the importance of sun protection.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TBorundia** [comment]
@Rakesh9100 @jessicachawla please assign this issue to me.
Thank You!

**Comment by jessicachawla** [comment]
@TBorundia please open one issue at a time

**Comment by TBorundia** [comment]
@jessicachawla 
Ok Mam , I will ensure to open one issue at a time .
Sorry for inconvenience!

**Comment by TBorundia** [comment]
@Rakesh9100 Sir, my previous issue is merged.
Now can you assign me this issue.

**Comment by Rakesh9100** [comment]
Pls review this @jessicachawla

**Comment by TBorundia** [comment]
@Rakesh9100 sir,
My previous issues are completed and successfully merged by you.
Now can I start working on it?
