### ISSUE TITLE
[Feature] Add Volume Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1528]
### Description

A Volume Calculator is a tool used to determine the volume of different geometric shapes and objects. It is commonly used in fields such as mathematics, physics, engineering, and construction. The volume of an object is a measure of the amount of space it occupies.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/895a0960-47d1-41e1-9ff8-cd5764580969)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TBorundia** [comment]
@Rakesh9100 @jessicachawla please assign this issue to me.
Thank You!

**Comment by jessicachawla** [comment]
@TBorundia please don't open a lot of issues at once.

**Comment by Rakesh9100** [comment]
Yes, please don't open too many issues at once. Maintain the decorum of open source @TBorundia

**Comment by Rakesh9100** [comment]
We already have 3D Shapes Calculator in which we can calculate the volume of different shapes @TBorundia
