### ISSUE TITLE
[Feature] Vehicle Loan Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1529]
### Description

A Vehicle Loan Calculator is a tool that helps users calculate the monthly payments, total cost, and other financial details associated with a vehicle loan. It's particularly useful for individuals considering taking out a loan to purchase a car, truck, or other types of vehicles.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/fe2a5c56-c79e-45ed-a987-3856e353e32e)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/2af6b67d-355f-4aa3-b292-1e4df4fb7eff)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/38d40ca2-4e6d-4722-a78a-c6a46e7560b7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TBorundia** [comment]
@Rakesh9100 @jessicachawla please assign this issue to me.
Thank You!

**Comment by jessicachawla** [comment]
There are already issues for loan calculators.

**Comment by jessicachawla** [comment]
@Rakesh9100 please close this issue.
