### ISSUE TITLE
[Feature] Add Net Promoter Score (NPS) Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1530]
### Description

The Net Promoter Score (NPS) Calculator is a tool used to measure customer loyalty and satisfaction. The NPS is based on a single survey question: "How likely are you to recommend our company/product/service to a friend or colleague?" Respondents give a rating on a scale from 0 to 10, with 0 being "not at all likely" and 10 being "extremely likely."

NPS=%Promoters−%Detractors

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/168854094/5de9a650-e285-46b9-a151-a7e2fb0dba6b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TBorundia** [comment]
@Rakesh9100 @jessicachawla please assign this issue to me.
Thank You!

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Please avoid opening too many issues at once and help maintain the decorum of the open source program @TBorundia

**Comment by TBorundia** [comment]
> Please avoid opening too many issues at once and help maintain the decorum of the open source program @TBorundia

Sorry Sir for this.
@Rakesh9100 , my previous issue is merged.
Now can you assign me this issue.

**Comment by Rakesh9100** [comment]
Go ahead @TBorundia
