### ISSUE TITLE
[Feature] Add more functionality in Number System Calculator

### ISSUE THREAD

**Issue by PDBharadwaj** [Rakesh9100/CalcDiverse#1533]
### Description

I wanted to add a convertor for binary to decimal numbers and vice-versa.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by PDBharadwaj** [comment]
Sure, I can add base 7, 8 and 16 formats. Please suggest any other conversions.
I would like to work on this issue.

**Comment by jessicachawla** [comment]
2, 7, 8, 10, 16 bases should be enough.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
We already have Number System Calculator which does this @jessicachawla pls look that Lmk further @PDBharadwaj

**Comment by PDBharadwaj** [comment]
> 2, 7, 8, 10, 16 bases should be enough.

I can work on these bases. Should I work on any other also?

**Comment by jessicachawla** [comment]
@Rakesh9100  the number system calculator does not covert to 7,8,10 and 16 bases according to my understanding

**Comment by jessicachawla** [comment]
Yes. @PDBharadwaj will you add it as a functionality instead of creating a new one?

**Comment by PDBharadwaj** [comment]
Yes, I can add it as functionality.

**Comment by PDBharadwaj** [comment]
@Rakesh9100 Please assign this to me.

**Comment by Rakesh9100** [comment]
Okay, go ahead @PDBharadwaj
