### ISSUE TITLE
[Feature] Add Voltage Calculator

### ISSUE THREAD

**Issue by AnshikaAg03** [Rakesh9100/CalcDiverse#1534]
### Description

Calculate voltage using current and resistance.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AnshikaAg03** [comment]
@Rakesh9100 PLEASE ASSIGN ME THIS ISSUE

**Comment by jessicachawla** [comment]
give some explanation, too vague

**Comment by jessicachawla** [comment]
Shouldn't you give the option of calculating resistance first. There can be multiple resistors in series or parallel connections.

**Comment by Rakesh9100** [comment]
We already have Ohms Law Calculator, which calculates the Voltage @AnshikaAg03
