### ISSUE TITLE
[Feature] Add PH Calculator

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Rakesh9100/CalcDiverse#1537]
### Description
Hi @Rakesh9100 . pls assign this issue to me.
In pH calculator, you can determine the pH of a solution in a few ways. It can convert pH to H+, as well as calculate pH from the ionization constant and concentration.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
What will be the input and output?

**Comment by Khushi-Pushkar** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/142687709/8efda4b3-b06b-4de8-becf-e482c50cc7a3)

**Comment by Khushi-Pushkar** [comment]
@Rakesh9100 pls assign this issue to me

**Comment by Khushi-Pushkar** [comment]
@jessicachawla @Rakesh9100 pls assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @Khushi-Pushkar
