### ISSUE TITLE
[Feature] Add Garden Planning Calculator

### ISSUE THREAD

**Issue by aditya-bhaumik** [Rakesh9100/CalcDiverse#1539]
### Description

Create a garden planning website with a calculator-like interface where users can accurately calculate the maximum number of plants that can fit based on garden dimensions and plant spacing. Include a cost calculation feature to determine the financial implications of planting, showing potential profit or loss.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/92214013/0f3821ef-9059-482d-b6ba-6032f0ad2e71)

This is the website i have made so far for the calculator i still have to improve the ui and the mathematics behind the calculator but this is how it is going to work 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please assign me this issue under Gssoc'24

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned. 
@aditya-bhaumik keep the ui similar to the existing website

**Comment by aditya-bhaumik** [comment]
@jessicachawla okay sure i will keep it similar to this website

**Comment by Rakesh9100** [comment]
What will be the name of your Calculator @aditya-bhaumik

**Comment by Rakesh9100** [comment]
Go ahead @aditya-bhaumik

**Comment by Rakesh9100** [comment]
Pls provide your PR @aditya-bhaumik

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 Sorry for the delay; I’ve been quite ill for last 3-4 days. I’ll upload the pull request by tommorrow evening.

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 i have provided the pull request in #1626
