### ISSUE TITLE
[Feature] Add Binary To Decimal Calculator

### ISSUE THREAD

**Issue by shrreya24** [Rakesh9100/CalcDiverse#1540]
### Description

I wish to add a calculator which would convert binary number to decimal number system.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shrreya24** [comment]
@Rakesh9100 please assign me the above issue .

**Comment by jessicachawla** [comment]
Issue already exists #1533 
@Rakesh9100 please close this issue

**Comment by Rakesh9100** [comment]
We already have Number System Calculator which does this task @jessicachawla, pls create new issues @PDBharadwaj
