### ISSUE TITLE
[Feature] Add Surface Tension Calculator

### ISSUE THREAD

**Issue by kauxp** [Rakesh9100/CalcDiverse#1542]
### Description

Surface tension is a function of the surface's force and length. The surface tension calculator will help you determine the surface tension for liquid in various forms like water droplets, bubbles, and floating objects. 
For flat objects :  
`T = 0.5 x F/L`
For droplets:
`T = P × D/4`
For hollow bubble:
`T = P × D/8`

T -> Surface tension
F -> Force
L -> Length
P -> Pressure
D -> Diameter

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kauxp** [comment]
Please assign this issue to me.

**Comment by kauxp** [comment]
Can I start working on this issue?

**Comment by Rakesh9100** [comment]
Yes, go ahead @kauxp
