### ISSUE TITLE
[Feature] Add Population Prediction Calculator

### ISSUE THREAD

**Issue by vansh-codes** [Rakesh9100/CalcDiverse#1549]
### Description

This is a calculator to predict the population bsaed on current population, birth rate and death rate

## This is dummy UI for temporary purpose. UI will be enchanced while creating PR.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/114163734/f9f841c8-70c1-4e1d-8336-ae5ce6935192)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vansh-codes** [comment]
@Rakesh9100 Please assign me this issue.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @vansh-codes
