### ISSUE TITLE
[Style] Enhance the UI of Temperature Calculator

### ISSUE THREAD

**Issue by vansh-codes** [Rakesh9100/CalcDiverse#1550]
### What's the style idea?

We need to improve the UI ⏬ 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/114163734/03c48efd-7917-4210-aec8-0b9b392c8ec9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Please open one issue at a time. Once you complete the previous issue, then open the next one

**Comment by vansh-codes** [comment]
@Rakesh9100 Please assign me this issue now as my last issue has been closed and its PR is merged.
You can refer here: PR #1637

**Comment by Rakesh9100** [comment]
What kind of enhancements you want to do @vansh-codes

**Comment by vansh-codes** [comment]
> What kind of enhancements you want to do @vansh-codes
As seen in the screenshot, we have selected both the parameters as celsius
So I will add a disable feature that when user selects a option from 'convert from' options, the respective option in the 'convert to' will be disabled enhancing the UX. Also the result should be displayed above the submit button with a message like 
'100 degree celcius is 212 Fahreneits' 
@Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @vansh-codes
