### ISSUE TITLE
[Feature] Add Logical Micro Operations Calculator

### ISSUE THREAD

**Issue by vansh-codes** [Rakesh9100/CalcDiverse#1551]
### Logical Micro-operations is a topic in Engineering subject - Computer Architecture and Design

![image](https://github.com/Rakesh9100/CalcDiverse/assets/114163734/d44742e9-3c01-48f8-a87a-1ec9db9a87a5)

### This is a example of how this operations work ⏬ 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/114163734/695856bc-6035-4e07-892f-16acfa1b7b7c)

### Screenshots

Attached above ⬆️ 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vansh-codes** [comment]
@Rakesh9100 Please assign this issue to me ✅

**Comment by jessicachawla** [comment]
Do not open more than one issue at a time
