### ISSUE TITLE
[Feature] Add Strong Number Calculator

### ISSUE THREAD

**Issue by KajalBhatt123** [Rakesh9100/CalcDiverse#1556]
### Description

 I propose integrating a strong number calculator.

Details:
A Strong number (also known as a KrishnaMurthy number) is a number whose sum of the factorial of its digits equals the number itself. For instance, 145 is a Krishnamurthy number because 
1!+4!+5!=145.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by BagchiShreya** [comment]
Hii @Rakesh9100 
I would like to work on this issue and it would be great if you assign this issue to me.

**Comment by jessicachawla** [comment]
@KajalBhatt123 keep the name as strong number.

**Comment by Rakesh9100** [comment]
Go ahead @KajalBhatt123
