### ISSUE TITLE
[Feature] Add Wavelength Calculator

### ISSUE THREAD

**Issue by kauxp** [Rakesh9100/CalcDiverse#1563]
### Description

The relationship between wavelength and frequency is described by this simple equation:
λ = v/f
where:
λ -> wavelength
v->  velocity
f -> frequency

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kauxp** [comment]
Please assign this issue to me

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by kauxp** [comment]
@Rakesh9100 could you please assign this?

**Comment by Rakesh9100** [comment]
We already have `Torque Calculator`, check and lmk further @kauxp

**Comment by kauxp** [comment]
okay then I'll change the calculator.

**Comment by Rakesh9100** [comment]
Do you want to work @kauxp

**Comment by kauxp** [comment]
Yes, I want to work on it.

**Comment by Rakesh9100** [comment]
Proceed @kauxp

**Comment by Rakesh9100** [comment]
Provide your PR @kauxp

**Comment by kauxp** [comment]
Done, please review the PR.
