### ISSUE TITLE
[Feature] Add SWP(Systematic Withdrawal Plan) Calculator

### ISSUE THREAD

**Issue by AsmitaMishra24** [Rakesh9100/CalcDiverse#1568]
### Description

An SWP (Systematic Withdrawal Plan) calculator is a financial tool that helps investors plan and manage the regular withdrawal of funds from their investment corpus, typically mutual funds. SWP is used to generate a steady income stream, often for retirees or those looking to supplement their income.

### Screenshots

For Example:
![Screenshot 2024-07-07 221940](https://github.com/Rakesh9100/CalcDiverse/assets/146121869/bd8cbd6a-e6cb-44e8-b954-e1732053e0a1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @AsmitaMishra24
