### ISSUE TITLE
[Feature] Add Electrostatic Force Calculator

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#1571]
### Description

I want to add an Electrostatic Force Calculator which helps us to calculate Electrostatic Force given the value of two point charges and the distance between them.

### Screenshots
Using Formula:
<img width="213" alt="Screenshot 2024-07-08 at 10 13 48 AM" src="https://github.com/Rakesh9100/CalcDiverse/assets/168436423/f5a777f4-9e72-4b49-b33b-bf743c84ba74">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Anshika14528
