### ISSUE TITLE
[Feature] Add Boyle Temperature Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Rakesh9100/CalcDiverse#1574]
### Description

A calculator that helps to measure the boyle temperature

### Screenshots

https://github.com/Rakesh9100/CalcDiverse/assets/138589633/05b05585-224a-4287-950f-e962024b1dc7

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Ishitamukherjee2004  this ui does not look very professional, are you willing to change it?

**Comment by Ishitamukherjee2004** [comment]
@jessicachawla  Yes definitely......but can you please explain where to change it?

**Comment by jessicachawla** [comment]
- keep the color scheme similar to  website. 
- the change in the window size does not look good. Keep it fixed. 
- the answer should be clearly present in bold

**Comment by Ishitamukherjee2004** [comment]
@jessicachawla  Is it ok? {lease Check
![Screenshot 2024-07-13 190523](https://github.com/user-attachments/assets/9060eaac-b62b-43c1-a6e3-71d837483521)

![Screenshot 2024-07-13 190543](https://github.com/user-attachments/assets/7bd4774a-b707-4740-9e04-f5bb3d8225fb)

**Comment by jessicachawla** [comment]
Yes good

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @Ishitamukherjee2004
