### ISSUE TITLE
WAIST TO HIP RATIO CALCULATOR

### ISSUE THREAD

**Issue by Vikashchou-dhary** [Rakesh9100/CalcDiverse#1575]
### Description

WAIST TO HIP RATIO measurement is important as higher ratios can mean you have more fat around your waist. This can lead to a higher risk for heart disease or diabetes. So these can help us to keep aware of your health.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
instead of just adding waist to hip, why not create a complete body analysis calculator with body fat%, BMI, waist to hp ratio, and any other body analysis you can think?
Also we already have a BMI calculator, so you can reuse the code

**Comment by Rakesh9100** [comment]
Any update on this @Vikashchou-dhary

**Comment by 2016archana** [comment]
@Rakesh9100  Could you please assign this issue to me?

**Comment by Rakesh9100** [comment]
Have you understood the proper requirement of this issue that @jessicachawla mentioned @2016archana

**Comment by jessicachawla** [comment]
@Rakesh9100 this is helpful for people who track their body ratios, specifically the people who gym. 
I had already told someone else to do this - issue #1686 as @Vikashchou-dhary  was not replying

**Comment by 2016archana** [comment]
> Have you understood the proper requirement of this issue that @jessicachawla mentioned @2016archana

yes sir

**Comment by 2016archana** [comment]
> @Rakesh9100 this is helpful for people who track their body ratios, specifically the people who gym. I had already told someone else to do this - issue #1686 as @Vikashchou-dhary was not replying

okay ma'am

**Comment by Rakesh9100** [comment]
Okay then, you can create new issues or take any `up-for-grab` issues @2016archana
