### ISSUE TITLE
[Feature] Add Annulus Calculator

### ISSUE THREAD

**Issue by Damini2004** [Rakesh9100/CalcDiverse#1576]
### Description

The Annulus Calculator is a tool designed to calculate the area of an annulus, which is the region between two concentric circles. This feature will help users quickly and accurately determine the area of an annulus given the radii of the two circles.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/119414762/d31e9202-2e39-44d9-98fb-eb3073ab89c1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
will you provide a diagram with the output as well?

**Comment by Damini2004** [comment]
![image](https://github.com/user-attachments/assets/1a919898-fed8-41a8-a466-97e31975c81a)

sure @jessicachawla  Kindly assign this issue to me i will carried out it within one day.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Pls go ahead @Damini2004
