### ISSUE TITLE
[Feature] Add Chi-Square Calculator

### ISSUE THREAD

**Issue by Damini2004** [Rakesh9100/CalcDiverse#1577]
### Description

The Chi-Square Calculator is a tool designed to calculate the chi-square statistic, which is used to determine whether there is a significant difference between the expected and observed frequencies in one or more categories. This feature will help users perform chi-square tests efficiently and accurately.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/119414762/3a3ac8d1-8e13-49b9-aa40-7dd0011af94a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Damini2004** [comment]
@Rakesh9100 @jessicachawla Kindly assign this issue to me

**Comment by Rakesh9100** [comment]
Proceed @Damini2004
