### ISSUE TITLE
[Feature] Add FD Calculator

### ISSUE THREAD

**Issue by AsmitaMishra24** [Rakesh9100/CalcDiverse#1579]
### Description

A fixed deposit is a type of term investment offered by several banks and NBFCs. These deposits typically offer a higher rate of interest, subject to certain terms and conditions. The amount you deposit in these deposits is locked for a predetermined period which can vary between 7 days and 10 years.

An FD calculator can be used to determine the interest and the amount that it will accrue at the time of maturity.

### Screenshots
Example:-
![Screenshot 2024-07-08 220523](https://github.com/Rakesh9100/CalcDiverse/assets/146121869/c6214e38-c3be-4cc3-8c02-4e7ba251b324)

### Checklist
- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct
- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by prachi0701** [comment]
Hey @AsmitaMishra24 , Assign this issue to me!!

**Comment by AsmitaMishra24** [comment]
Hey, @prachi0701, I am not a PA. Also, the issue was created by me, and I am interested in working on it. It is assigned on a FCFS basis, so it should be assigned to me. You can create your issue to work on.

**Comment by jessicachawla** [comment]
@AsmitaMishra24  is this going to be the ui or will you change it?

**Comment by jessicachawla** [comment]
@prachi0701 please look for an issue which has the tag 'up for grabs' or create your own issue to work on. For any doubt pls free free to reach out

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 is this going to be the ui or will you change it?

I will change the ui according to the website theme like other calculators.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @AsmitaMishra24
