### ISSUE TITLE
[Feature] Add RD Calculator

### ISSUE THREAD

**Issue by AsmitaMishra24** [Rakesh9100/CalcDiverse#1580]
### Description

Recurring deposits (RDs) are an investment instrument almost similar to fixed deposits. However, you have to make fixed monthly deposits in RDs, unlike a lump sum amount in FDs. RDs create a habit of regular investment among earning individuals. These also instil discipline when it comes to savings. Recurring deposits are offered by the majority of banks and financial institutions.

RD returns calculation can be quite complicated for an average investor to figure out accurately every time. This is where an RD calculator can prove to be immensely beneficial.

### Screenshots

![Screenshot 2024-07-08 222758](https://github.com/Rakesh9100/CalcDiverse/assets/146121869/10241eb2-4881-4065-9157-5374a3430e57)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@AsmitaMishra24 how about we merge the two calculators into one and give an option to the user if it is RD or FD?

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 how about we merge the two calculators into one and give an option to the user if it is RD or FD?

@jessicachawla, I don't think it's a good idea because both have different formulas and managing the UI for two calculators will be a lot of work. The interest rate for RD is quarterly, whereas for FD it is annually.

**Comment by jessicachawla** [comment]
@Rakesh9100 please let see what you think

**Comment by Rakesh9100** [comment]
Adding both calculators separately can be beneficial for users who are specifically looking for one type of calculation without any confusion, @jessicachawla so proceed for this as well @AsmitaMishra24

**Comment by Rakesh9100** [comment]
Pls provide your PR @AsmitaMishra24
