### ISSUE TITLE
[Bug] instead of search image use search icon for better user experience 

### ISSUE THREAD

**Issue by chandannekya** [Rakesh9100/CalcDiverse#1581]
### Description

There is search emoji is used in placeholder of search input it's not looking good from pov of user for making user experience better replace it with search icon.

### Screenshots

![Screenshot_2024-07-08-23-41-02-456_com linkedin android](https://github.com/Rakesh9100/CalcDiverse/assets/121476456/664b48ec-1e34-4c9d-a826-ceb86fe7dc2c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 pls see if you want this modification

**Comment by Rakesh9100** [comment]
The present search emoji is totally fine, adding search image will now need separate CSS which is not so beneficial, pls work on other good issues @chandannekya
