### ISSUE TITLE
[Feature] Add Blood Sugar Calculator

### ISSUE THREAD

**Issue by vidhiisaxena** [Rakesh9100/CalcDiverse#1583]
### Description

This will take the Random blood sugar test results and Fasting blood sugar rests and provide the user with the analysis whether it is normal, high or low and provide with useful links on how to control the range.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vidhiisaxena** [comment]
@Rakesh9100 Kindly assign me this issue under GSSOC.

**Comment by jessicachawla** [comment]
what are the inputs you will be taking? will it be just one time result of sugar or 4-5 results?

**Comment by vidhiisaxena** [comment]
It will take one time results otherwise the user will need to login to store their result.

**Comment by jessicachawla** [comment]
give some explanation about the calculator, the inputs, outhputs, other constrains, calculations if any.

**Comment by vidhiisaxena** [comment]
This calculator will input age and blood sugar level for the patient. It will then give output as to what range it falls into. Now there are two types of blood sugars (fasting and random) so the calculator will have two modes and will work accordingly. It's a good addition as many calculators do not consider the age factor and hence are somewhat misleading.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Khushi-Pushkar** [comment]
Hey @jessicachawla @Rakesh9100 sir please assign this issue to me

**Comment by Rakesh9100** [comment]
This issue is opened by another contributor who wants to work, you can take on `up-for-grab` labeled issues or create your new issues @Khushi-Pushkar

**Comment by Rakesh9100** [comment]
Go ahead @vidhiisaxena
