### ISSUE TITLE
[Feature] Add Water Hardness Calculator

### ISSUE THREAD

**Issue by mahek0620** [Rakesh9100/CalcDiverse#1586]
### Description

A Water Hardness Calculator helps users determine the hardness of their water supply. Water hardness is typically measured in parts per million (ppm) or grains per gallon (gpg), indicating the concentration of calcium and magnesium ions. This calculator can be useful for homeowners, aquarium enthusiasts, and anyone interested in maintaining water quality.

Key Features
Input Fields: Users can input the concentration of calcium and magnesium ions in their water sample.
Unit Selection: Option to choose between ppm and gpg for the input and output values.
Calculation: Converts ion concentration to water hardness and provides results in both ppm and gpg.
Hardness Categories: Displays the water hardness category (soft, moderately hard, hard, very hard) based on the calculated value.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
with hardness, consider mentioning that it is safe for ......
you can find this kind of explanation on the internet, you can hardcode it while coding 
for example:
if (ppm< x amt){
     print" hard water
     hard water is not safe for ......";
}

**Comment by Rakesh9100** [comment]
Do you want to be assigned @mahek0620

**Comment by mahek0620** [comment]
> Do you want to be assigned @mahek0620

Yes

**Comment by Rakesh9100** [comment]
Go ahead @mahek0620
