### ISSUE TITLE
[Feature] Add Numerology Calculator

### ISSUE THREAD

**Issue by mahek0620** [Rakesh9100/CalcDiverse#1587]
### Description

A Numerology Calculator helps users discover their core numerology numbers based on their birth date and full name. These numbers can provide insights into personality traits, life purpose, and potential future outcomes.

Key Features
Life Path Number: Calculates the Life Path Number based on the user's birth date.
Expression Number (Destiny Number): Calculates the Expression Number based on the user's full name.
Soul Urge Number (Heart's Desire Number): Calculates the Soul Urge Number based on the vowels in the user's full name.
Personality Number: Calculates the Personality Number based on the consonants in the user's full name.
Compatibility: Option to compare numerology numbers for compatibility analysis.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by mahek0620** [comment]
@Rakesh9100 can you assign this to me

**Comment by Rakesh9100** [comment]
Go ahead @mahek0620
