### ISSUE TITLE
[Feature] Add Sum Of Digits Calculator

### ISSUE THREAD

**Issue by Sravyasaka** [Rakesh9100/CalcDiverse#1590]
### Description

Sum of digits Calculator  is used to find sum of all digits in a given number

Input number: 1244

Output will be 1+2+4+4 = 11

Please assign me under GSSOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhinavKRN** [comment]
Assign this issue to me!

**Comment by prachi0701** [comment]
Hello @Sravyasaka , Plss assign this issue to me!!

**Comment by jessicachawla** [comment]
@Sravyasaka describe the need of this?

**Comment by Sravyasaka** [comment]
> @Sravyasaka describe the need of this?

The sum of digits is used in various methodologies like:
Digital Root Calculation
Checksum Algorithms
Budgeting and Finance.

So I thought of working on this.

**Comment by Sravyasaka** [comment]
@jessicachawla @Rakesh9100 please assign this issue to me
