### ISSUE TITLE
[Feature] Add SVD (Singular Value Decomposition) Calculator

### ISSUE THREAD

**Issue by manasdeshpande** [Rakesh9100/CalcDiverse#1594]
### Description

The Singular Value Decomposition (SVD) of a matrix is a factorization of that matrix into three matrices. It has some interesting algebraic properties and conveys important geometrical and theoretical insights about linear transformations. It also has some important applications in data science. In this article, I will try to explain the mathematical intuition behind SVD and its geometrical meaning. 
The SVD of  mxn matrix A is given by the formula  A = U\Sigma V^T  

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @manasdeshpande

**Comment by Rakesh9100** [comment]
Pls provide your PR @manasdeshpande

**Comment by Naresh-kumar-Thodupunoori** [comment]
hey @Rakesh9100 can I work on this!?

**Comment by Rakesh9100** [comment]
You want to contribute just normally as GSSOC is over now @Naresh-kumar-Thodupunoori

**Comment by Rakesh9100** [comment]
Okay, go ahead if you want to @Naresh-kumar-Thodupunoori

**Comment by shawnsd69** [comment]
Subject: Request for Issue Assignment

Dear @Rakesh9100 ,

I hope this message finds you well. I’m eager to contribute to the CalcDiverse and would like to take on a task that could help move the project forward. If possible, could you please assign me this issue that aligns with my skills? I’m particularly interested in working on recent open source project, but I’m open to anything that needs attention.

Thank you for considering my request. I’m looking forward to your guidance and contributing to the project.

Best regards,
Shawn

**Comment by Rakesh9100** [comment]
Do you want to currently work on this and resolve it @Naresh-kumar-Thodupunoori @shawnsd69

**Comment by Atharvverma1234** [comment]
Hello Sir, I would like to work upon this issue. Please assign it to me. Thank you.

**Comment by Rakesh9100** [comment]
Go ahead @Atharvverma1234
