### ISSUE TITLE
[Feature] Add Kinematics Calculator

### ISSUE THREAD

**Issue by shraddhha** [Rakesh9100/CalcDiverse#1595]
### Description

Solves problems related to motion with constant acceleration. It can calculate displacement, initial velocity, final velocity, acceleration, and time.
**Description:**
The Kinematic Equations Calculator is a powerful tool designed to solve problems related to the motion of objects under constant acceleration. This calculator can compute various parameters of motion including displacement, initial velocity, final velocity, acceleration, and time, making it an essential resource for students and professionals dealing with kinematic equations in physics.

**Features:**
Displacement Calculation: Determines the distance traveled by an object over a given period of time under constant acceleration.
Initial Velocity Calculation: Computes the starting speed of an object before it undergoes acceleration.
Final Velocity Calculation: Calculates the speed of an object after a certain period of acceleration.
Acceleration Calculation: Finds the rate at which an object’s velocity changes over time.
Time Calculation: Determines the time taken for an object to reach a certain velocity or displacement under constant acceleration.

**Use Cases:**

- Physics Homework: Assists students in solving kinematics problems typically found in high school and college physics assignments.

- Engineering Applications: Helps engineers analyze the motion of objects in various fields such as automotive engineering, aerospace, and robotics.

- Sports Science: Utilized by sports scientists to analyze the motion of athletes and equipment.

- Animation and Gaming: Used by developers to simulate realistic motion in animations and video games.

Kinematic Equations:
The calculator uses the following fundamental kinematic equations, where:

𝑢
u = initial velocity
𝑣
v = final velocity
𝑎
a = acceleration
𝑠
s = displacement
𝑡
t

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
will you consider only 1D kinematics or 2D and 3D as well?

**Comment by shraddhha** [comment]
1D, 2D and 3D also.

**Comment by shraddhha** [comment]
@jessichawla i would like to work on this issue.

**Comment by Rakesh9100** [comment]
Go ahead @shraddhha

**Comment by Rakesh9100** [comment]
Provide your PR @shraddhha
