### ISSUE TITLE
[Feature] Add scroll progress indicator bar

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1597]
### Description

I want to add a progress bar on the top of the navbar which progresses as the page scrolls up or down.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by meetarora10** [comment]
Hi @Rakesh9100 kindly consider this issue .

**Comment by jessicachawla** [comment]
@Rakesh9100 pls see if you want this

**Comment by reena1417** [comment]
Hello @Rakesh9100 I want to help you with this issue how do I access this repo

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot of your issue @meetarora10

**Comment by meetarora10** [comment]
https://github.com/user-attachments/assets/a92a3025-21ab-45e2-9955-b102e7b906f1
@Rakesh9100 this progress bar , if you want I can change the color of this bar.
Kindly assign this to me .

**Comment by meetarora10** [comment]
@Rakesh9100 please have a look .

**Comment by meetarora10** [comment]
@Rakesh9100 please check this .

**Comment by meetarora10** [comment]
@Rakesh9100 can I work on this ?
Please assign this to me .

**Comment by meetarora10** [comment]
Hi @Rakesh9100 please assign me if you need this .
