### ISSUE TITLE
[Feature] Add Distance Calculator

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1598]
### Description

I want to add a distance measuring calculator which calculates the distance based on the given values of speed and time using the formula distance=speed X time.
Please assign this task to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by meetarora10** [comment]
Hi @Rakesh9100 please assign this issue to me.

**Comment by jessicachawla** [comment]
issue already open for this #1595

**Comment by jessicachawla** [comment]
@Rakesh9100 please close this issue
