### ISSUE TITLE
[Feature] Add Isogram Calculator

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1599]
### Description

I want to add a new isogram calculator that is used to calculate whether a string entered by the user is isogram or not. A string is said to be an isogram if no letter of the alphabet occurs more than once. 
I will use HTML,CSS and JavaScript for this .
Kindly assign this task to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhinavKRN** [comment]
Hey @meetarora10 , can you assign this issue to me!

**Comment by meetarora10** [comment]
@Rakesh9100 please assign this issue to me .

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by meetarora10** [comment]
@jessicachawla @Rakesh9100 when the issue will be assigned?

**Comment by Rakesh9100** [comment]
Go ahead @meetarora10
