### ISSUE TITLE
Square Root Calculator

### ISSUE THREAD

**Issue by itsmeabhishek03** [Rakesh9100/CalcDiverse#16]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Calculate the square root of a given number.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sidharth2829** [comment]
I have checked all the prerequisites.
Please assign me this issue under SWOC.

**Comment by Rakesh9100** [comment]
Pls complete the previously assigned issue first @itsmeabhishek03 

Assigning you, proceed!! @sidharth2829
