### ISSUE TITLE
[Feature] Add Dudeney Number Calculator

### ISSUE THREAD

**Issue by Sravyasaka** [Rakesh9100/CalcDiverse#1601]
### Description

A Dudeney number is a positive integer that is a perfect cube, and the sum of its digits is equal to the cube root of the number

Input number: 512

Output will be Yes (because cube root is 8 and 5+1+2=8)

Please assign me under GSSOC'24

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/137039979/a5927243-04f1-416b-a51f-81ebe9866dde)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
