### ISSUE TITLE
[Feature] Speed measure Calculator

### ISSUE THREAD

**Issue by AnshRehan04** [Rakesh9100/CalcDiverse#1603]
### Description

Want to create a speed measure calculator where inputs are distance to be travelled and time to reach the destination . The average speed for the journey will be calculated based on these inputs.
Please assign me this under GSSoC'24.
Thank You.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
issue #1595 already open 
@Rakesh9100 pls close this issue
