### ISSUE TITLE
[Feature] Add OWASP Risk Assessment Calculator

### ISSUE THREAD

**Issue by Maheshwari-Love** [Rakesh9100/CalcDiverse#1606]
### Description

🧮 An online calculator to assess the risk of web vulnerabilities based on OWASP Risk Assessment

### Screenshots

![image](https://github.com/user-attachments/assets/6a92dee7-d5be-4f48-9fd8-8b6e3a959f1b)
![image](https://github.com/user-attachments/assets/ad75690b-8c14-469e-af91-4a7d4657d6ac)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 please assign me this issue

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned 
@Maheshwari-Love please keep the ui similar to the website

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 please assign me

**Comment by Rakesh9100** [comment]
What will be the name of your calculator @Maheshwari-Love
