### ISSUE TITLE
[Feature] Add Plant Care Calculator

### ISSUE THREAD

**Issue by anagha-chaudhari** [Rakesh9100/CalcDiverse#1607]
### Description

The Plant care calculator will help plant owners create a schedule according to their specific plants needs. Users input details will be like plant type, size, location, season, watering frequency etc. The output will be a dedicated **schedule** for watering, fertilizing, and repotting. Please assign this issue under GSSOC'24 @Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
