### ISSUE TITLE
[Bug] Fix the incorrect output in Palindrome Calculator

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1609]
### Description

The output of Palindrome Calculator is wrong . For instance for the string "Eye" output is that it is not a palindrome , but we know that it is a palindrome string , and many other strings like this .
Kindly assign me and I will fix this issue .

### Screenshots

![Screenshot (684)](https://github.com/user-attachments/assets/cf8f8093-c267-440e-8df3-f7c2574efa22)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by meetarora10** [comment]
Then assign me @Rakesh9100

**Comment by Rakesh9100** [comment]
This is not any bug since palindrome checks for the case as well, so `Eye` is not palindrome but `eye` or `EyE` is plaindrome @meetarora10 @jessicachawla
