### ISSUE TITLE
[Feature] Add Pythagorean Triples Calculator

### ISSUE THREAD

**Issue by Komal-bora** [Rakesh9100/CalcDiverse#1612]
### Description

the pythagorean triples calculator verifies if three user-inputted side lengths form a Pythagorean triplet or not.

### Screenshots

![image](https://github.com/user-attachments/assets/c3bf9abd-1a91-41cf-ac46-b099f9eb0d94)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Komal-bora** [comment]
@Rakesh9100 I am interested in working on it, please assign me this issue under gssoc labels.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by siddharthbaleja7** [comment]
@Rakesh9100  please assign this issue to me under gssoc labels.

**Comment by jessicachawla** [comment]
@siddharthbaleja7 please do not ask to assign the issue to you if I have already commented something on that issue. 
Create your own issue or look for ones that are up for grabs, we will assign them to you if we are satisfied with your idea.
