### ISSUE TITLE
[Feature] Add Lottery Odds Calculator

### ISSUE THREAD

**Issue by anijit18** [Rakesh9100/CalcDiverse#1613]
### Description

A calculator that calculates the odds of winning the lottery jackpot based on several inputs provided by the users such as the number of tickets purchased and numbers chosen by the user.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
how will the user know the number of tickets sold?

**Comment by anijit18** [comment]
The total number of tickets sold of an organization is made public.
A user can decide how many tickets to buy if he wants to meet his desired chances of winning the lottery.

**Comment by jessicachawla** [comment]
Okay got it 
@Rakesh9100 this issue can be assigned
