### ISSUE TITLE
[Style] Add hover effect to the menu items in footer

### ISSUE THREAD

**Issue by ahinagangopadhyay** [Rakesh9100/CalcDiverse#1619]
### What's the style idea?

There is no hover effect in the Home,About,Calculators,Contributors,FAQ,Contact links in the  footer section.I would like to add a color change hover effect to these links.Please assign me this issue under GSSOC'24
![Screenshot (15)](https://github.com/user-attachments/assets/2c5495a1-b72d-464b-9281-1063c0b8d983)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by siddharthbaleja7** [comment]
Please assign this issue to me.

**Comment by jessicachawla** [comment]
@siddharthbaleja7 please create a new issue or find one which has the tag 'up for grabs'

**Comment by Rakesh9100** [comment]
Go ahead @ahinagangopadhyay
