### ISSUE TITLE
[Feature] Add IT Income Tax Calculator

### ISSUE THREAD

**Issue by pavitraag** [Rakesh9100/CalcDiverse#1620]
### Description

The IT Income Tax Calculator is a tool designed to help individuals accurately calculate their income tax liabilities based on their earnings. This user-friendly calculator takes into account various income sources, deductions, and tax credits to provide an estimate of the total tax payable. It is particularly useful for individuals who need to understand their tax obligations and plan their finances accordingly.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
will take into consideration if people are not from india?

**Comment by pavitraag** [comment]
I am going to use this formula to calculate income taxes: Gross Salary - Deductions = Taxable Income; Income Tax = (Taxable Income x Applicable Tax Rate) - Tax Rebate.
This is used in India and almost similar to this US, UK and Australia also has this formula to calculate.

**Comment by jessicachawla** [comment]
Not what I meant. 
The percent of tax to be deducted are different for different brackets of salaries.

**Comment by pavitraag** [comment]
Each country has its own set of income ranges and corresponding tax rates.
I am working on India only for now
-Income up to ₹250,000: No tax
-Income from ₹250,001 to ₹500,000: 5%
-Income from ₹500,001 to ₹1,000,000: 20%
-Income above ₹1,000,000: 30%

**Comment by jessicachawla** [comment]
Ok. Then mention that you're given taxes as pe Indian tax laws

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @pavitraag
