### ISSUE TITLE
[Feature] Add Luminous Flux Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1624]
### Description

A Luminous Flux Calculator calculates the total visible light emitted by a source, measured in lumens (lm). This is useful for understanding the brightness of light sources, such as LEDs, bulbs, or any other lighting fixtures. The calculation takes into account the luminous efficacy of the light source and the power consumed.

### Screenshots

![image](https://github.com/user-attachments/assets/f150b4bf-9a2a-4883-bb72-2b7a448923fd)
![image](https://github.com/user-attachments/assets/7c48eb7c-adf1-46d6-993e-f21a33bd65b2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@TBorundia are your previous issues completed already?

**Comment by TBorundia** [comment]
> @TBorundia are your previous issues completed already?

@jessicachawla 
Yes Mam, my all previous issues are completed and merged.

**Comment by TBorundia** [comment]
@jessicachawla 
Yes Mam, my all previous issues that are assigned are completed .
Now can you assign me this issue.
