### ISSUE TITLE
[Feature] Add Lattice Energy Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1625]
### Description

A Lattice Energy Calculator calculates the lattice energy of an ionic compound. Lattice energy is the energy released when one mole of an ionic crystalline compound is formed from its gaseous ions. It's a measure of the bond strength in ionic compounds and is usually expressed in kilojoules per mole (kJ/mol).

### Screenshots

![image](https://github.com/user-attachments/assets/229444ed-7fb6-4bea-b68b-1f4aa23304c4)

![image](https://github.com/user-attachments/assets/9e3011e7-44bc-43df-ae36-3a652df1156f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100  this issue can be assigned

**Comment by TBorundia** [comment]
@Rakesh9100 Sir,
I have completed my previous issues so I can start working on it?
