### ISSUE TITLE
[Feature] Add Orthocenter Of A Triangle Calculator

### ISSUE THREAD

**Issue by 07-priyanshu** [Rakesh9100/CalcDiverse#1627]
### Description

want to add orthocentre coordinates calculator which takes in input the coordinates of the vertices and calculates the coordinates of the orthocentre.

Expected Level: Level 3

@Rakesh9100  Please assign this issue to me under GSSoC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by 07-priyanshu** [comment]
@jessicachawla @Rakesh9100 Please assign this issue as soon as possible under GSoC

**Comment by 07-priyanshu** [comment]
@Rakesh9100 Please add the Level Tag/Label for GSSoc for this issue.
