### ISSUE TITLE
[Feature] Add Work unit conversion in Unit Calculator

### ISSUE THREAD

**Issue by techy4shri** [Rakesh9100/CalcDiverse#1632]
### Description

Convert the unit of work from Joules to ElectronVolt, Calorie, Kilocalorie, Foot-pound, Kilowatt-hour.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Pls include this Work conversion section in the existing `Unit-Calculator` itself @meetarora10

**Comment by Rakesh9100** [comment]
Pls include this Work conversion section in the existing `Unit-Calculator` itself @techy4shri

**Comment by techy4shri** [comment]
> Pls include this Work conversion section in the existing `Unit-Calculator` itself @techy4shri

Will do, thanks!
