### ISSUE TITLE
Add Boyle's temperature Calculator

### ISSUE THREAD

**Issue by Sravyasaka** [Rakesh9100/CalcDiverse#1633]
**DESCRIPTION**
The Boyle's temperature is the temperature at which a real gas behaves most like an ideal gas over a range of pressures. For a gas described by the van der Waals equation, the Boyle temperature can be calculated using the van der Waals constants 
𝑎 and  𝑏.
The Boyle temperature Tb is denoted by the formula:
Tb= a / Rb where R is the universal gas constant and a & b are the van der Waals Constants.

**CHECKLISTS**
- [x] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.

**SCREENSHOTS**
![Screenshot (169)](https://github.com/user-attachments/assets/26a6b0b2-7a70-4fad-9fb8-12c3d13df5df)
![Screenshot (170)](https://github.com/user-attachments/assets/2c167f84-efce-4e0e-828c-aa8a11349f43)

**Comment by jessicachawla** [comment]
Give an idea of the UI and the inputs and outputs
