### ISSUE TITLE
[Feature] Add more functionality in Harmonic Progression Calculator

### ISSUE THREAD

**Issue by bhumii-ka** [Rakesh9100/CalcDiverse#1636]
### Description

Currently the Harmonic Progression Calculator only calculates the nth term of the series I want to add two more features to calculate sum and harmonic mean of n terms.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
