### ISSUE TITLE
[Feature] Add Custom Temperature Unit Calculator

### ISSUE THREAD

**Issue by bhumii-ka** [Rakesh9100/CalcDiverse#1638]
### Description

This calculator will make a custom thermometer that can be used for conversions
It will take the following inputs:
- Name of the custom temperature unit 
- Boiling point of water in that unit
- Freezing point of water in that unit
- Conversion from temp value with unit (Custom unit/ Celsius / Fahrenheit / Kelvin)
- Convert to unit (Custom unit/ Celsius / Fahrenheit / Kelvin)

Please assign the issue to me under GSSoC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhinavKRN** [comment]
@Rakesh9100 , could you assign this issue to me!

**Comment by bhumii-ka** [comment]
> @bhumii-ka what all will you be giving in the output

Conversion of temperature from new unit to standard units (°C/F/K) and vice versa.
This can be used when user has non-standard or not well known temperature units for conversion

**Comment by jessicachawla** [comment]
We already have Celsius to Farhenite one. 
@Rakesh9100 please see
