### ISSUE TITLE
[Feature] Add Pokemon Calculator

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1639]
### Description

I want to add a Pokemon Calculator which displays the details and image of the pokemon entered by the user .
This is built using HTML,CSS,JavaScript and uses the PokeAPI Proxy to fetch the details of various pokemons .

### Screenshots

https://github.com/user-attachments/assets/7cb18f86-e23f-4c1e-a41a-2cc59c39a0fb

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by meetarora10** [comment]
@Rakesh9100  @jessicachawla  kindly have a look at this .

**Comment by jessicachawla** [comment]
@Rakesh9100 please see if this is needed

**Comment by meetarora10** [comment]
@Rakesh9100 assign me this .

**Comment by Rakesh9100** [comment]
Hey, Pls don't open issues to add silly calculators, open issue to add calculator which has some good logic such that it is helpful to others @meetarora10
