### ISSUE TITLE
[Feature] Add Zodiac Sign Calculator

### ISSUE THREAD

**Issue by anijit18** [Rakesh9100/CalcDiverse#1641]
### Description

A calculator that tells us the Zodiac Sign from the user input value which will be Date of Birth.
It will display several fields such as Zodiac Sign, Element, Ruling Planet and Traits.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by anijit18** [comment]
@Rakesh9100  @jessicachawla please assign this issue to me under gssoc

**Comment by jessicachawla** [comment]
Already one issue for this. 
@Rakesh9100 please close
