### ISSUE TITLE
[Feature] Add Gauss Law Calculator

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Rakesh9100/CalcDiverse#1644]
### Description

Gauss law calculator allows you to compute the magnitude of the electric flux generated by the electric field of an electric charge.

Input :
- Electric charge (Q)
- vacuum permittivity

Output
- Electric flux 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Khushi-Pushkar** [comment]
@Rakesh9100 pls assign this isuue

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
