### ISSUE TITLE
[Feature]  Add Friction Calculator

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Rakesh9100/CalcDiverse#1645]
### Description

Friction calculator to calculate the friction force between an object and the ground. It is based on a simple principle: friction is proportional to the normal force acting between the object and the ground.

INPUT
- Friction coefficient 
- Normal Force

OUTPUT
Friction Force

### Screenshots

.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Khushi-Pushkar** [comment]
pls @Rakesh9100 sir assign this issue to me

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
