### ISSUE TITLE
[Feature] Add Half-Life Calculator

### ISSUE THREAD

**Issue by AnandK-pm** [Rakesh9100/CalcDiverse#1648]
### Description

Half-life is defined as the amount of time it takes a given quantity to decrease to half of its initial value. The term is most commonly used in relation to atoms undergoing radioactive decay, but can be used to describe other types of decay, whether exponential or not. The metrics used are :
* Quantity remains
* Initial quantity
* Time
The formula used is : N(t) = N<sub>0</sub>*(1/2)<sup>t/t<sub>1/2</sub></sup>
where 
    N<sub>0</sub> is the initial quantity
    N<sub>t</sub> is the remaining quantity after time, t
    t<sub>1/2</sub> is the half-life

### Screenshots

![Screenshot 2024-07-15 114106](https://github.com/user-attachments/assets/c4d8b2b9-7b09-4d24-ad52-864fd20b4477)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Provide your PR @AnandK-pm

**Comment by Atharvverma1234** [comment]
Hello Sir, I would like to work on this issue, Please assign it to me. Thank you

**Comment by Rakesh9100** [comment]
Go ahead @Atharvverma1234
