### ISSUE TITLE
[Feature] Add Uncertainty Calculator

### ISSUE THREAD

**Issue by ananyag309** [Rakesh9100/CalcDiverse#1649]
### Description

An Uncertainty Calculator typically helps in determining the uncertainty in measurements, combining various sources of error and expressing the final uncertainty

Inputs:
Measured Value (X): The value obtained from the measurement.
Instrument Uncertainty (U1): The uncertainty related to the precision of the measuring instrument.
Calibration Uncertainty (U2): The uncertainty due to the calibration of the measuring instrument.
Environmental Uncertainty (U3): The uncertainty due to environmental factors such as temperature, humidity, etc.
Repeatability Uncertainty (U4): The uncertainty due to the variations when repeating the measurement under the same conditions.

Output:
Combined Standard Uncertainty (Uc): The square root of the sum of the squares of the individual uncertainties.
Expanded Uncertainty (Ue): The combined standard uncertainty multiplied by the coverage factor.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@ananyag309 pls open one issue at a time

**Comment by Rakesh9100** [comment]
Do you want to be assigned @ananyag309

**Comment by ananyag309** [comment]
i guess there are some points restrictions on this repo....

**Comment by Rakesh9100** [comment]
If anyone found copying the code and doing the spams, then there are restrictions for every repo, not if you are doing the genuine own contributions @ananyag309

**Comment by ananyag309** [comment]
okay i will surely complete it
