### ISSUE TITLE
[Feature] Add Pet Care Cost Calculator

### ISSUE THREAD

**Issue by ANKeshri** [Rakesh9100/CalcDiverse#1650]
### Description

Calculates the lifetime cost of owning different types of pets, including food, healthcare, and other expenses, based on current market prices.

### Screenshots

![image](https://github.com/user-attachments/assets/667952ab-b09e-4366-a112-05c2de68fb0c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhinavKRN** [comment]
Hey @Rakesh9100 ,can you assign this issue to me!

**Comment by jessicachawla** [comment]
@ANKeshri for the ui, keep the background which is friendly for all kinds of pets.

**Comment by ANKeshri** [comment]
> @ANKeshri for the ui, keep the background which is friendly for all kinds of pets.

sure

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
