### ISSUE TITLE
Fitness Calculator : It calculates  BMI, BMR, body fat percentage, and caloric needs.

### ISSUE THREAD

**Issue by 2016archana** [Rakesh9100/CalcDiverse#1652]
### Description

 It calculates BMI, BMR, body fat percentage, and caloric needs based on personalized inputs.

INPUT PARAMETERS:

1.  Height
2. Weight
3. Age
4. Gender
5. Activity Level

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhinavKRN** [comment]
hey @Rakesh9100 , could you assign this issue to me!

**Comment by jessicachawla** [comment]
Issue #1575 is open. If the contributor doesn't reply, it will be assigned to you. Also we already BMI calculator so you can reuse the code. 
@Rakesh9100 please advise

**Comment by 2016archana** [comment]
> Issue #1575 is open. If the contributor doesn't reply, it will be assigned to you. Also we already BMI calculator so you can reuse the code. @Rakesh9100 please advise
Ma'am, should I start working on this ?? 
Please assign this to me.

**Comment by 2016archana** [comment]
@jessicachawla , Please assign this to me. I was waiting for your response. Thank you. I am new to open source, please guide me whenever required.

**Comment by 2016archana** [comment]
> @jessicachawla , Please assign this to me. I was waiting for your response. Thank you. I am new to open source, please guide me whenever required.

??

**Comment by Rakesh9100** [comment]
> Issue #1575 is open. If the contributor doesn't reply, it will be assigned to you. Also we already BMI calculator so you can reuse the code. @Rakesh9100 please advise

Yes, correct @jessicachawla 
You can comment in the previous opened issue itself that you want to work so that it can be assigned to you @2016archana
