### ISSUE TITLE
Adding Geometric Progression Calculator

### ISSUE THREAD

**Issue by dfghjkbd** [Rakesh9100/CalcDiverse#1655]
### Description

I want to make calculator helps determine the nth term and the sum of the first n terms of a geometric progression.
**Input**
a : The first term of the geometric progression.
r : The common ratio of the geometric progression.
n : The term number to calculate and sum up to.
**Output**
t_n : The nth term of the geometric progression.
S_n : The sum of the first n terms of the geometric progression.

formula for nth term is tn=ar^n-1 
 sum  of first n terms 

when r!=1 Sn=a(r^n -1)/r-1 and r=1 Sn=na

### Screenshots

![image](https://github.com/user-attachments/assets/8dd865e5-021d-4427-8aa3-97e3bfb7cfeb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by dfghjkbd** [comment]
@Rakesh9100 I would like to build a new calculator that will support determining the nth term and the sum of the first n terms of a geometric progression. This tool will be really helpful for students and math enthusiasts.

Kindly assign me this issue.

Thank you!

**Comment by dfghjkbd** [comment]
@Rakesh9100  please assign me this issue .

**Comment by Rakesh9100** [comment]
We already have `Geometric Progression Calculator` @dfghjkbd
