### ISSUE TITLE
circle's area & circumference calculator

### ISSUE THREAD

**Issue by dfghjkbd** [Rakesh9100/CalcDiverse#1656]
### Description

I want to make calculator that calculates area and  circumference of circle
**Input**
r : radius of circle
**Output**
C: circumference of circle
A: Area of circle
**Formula** 
C=2 *pi* r
A=pi*r^2

### Screenshots

![image](https://github.com/user-attachments/assets/b9d8c990-224b-4538-bab3-db4b5f91754e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@dfghjkbd please open one issue at a time.

**Comment by dfghjkbd** [comment]
@Rakesh9100 I would like to build a new calculator that will support determining circle's area & circumference . This tool will be really helpful for students and math enthusiasts.

Kindly assign me this issue.

Thank you!

**Comment by dfghjkbd** [comment]
@Rakesh9100  please assign me this issue .

**Comment by jessicachawla** [comment]
@dfghjkbd you will not be assigned more than one issue at a time. You must only open one issue at a time and please don't ask Rakesh to assign you an issue I explicitly did not tell him to assign.

**Comment by dfghjkbd** [comment]
@jessicachawla  
![image](https://github.com/user-attachments/assets/741777f3-cb6f-44e2-8b2a-861929544ae0)
This tool is designed to calculate the area and circumference of a circle based on user input. Additionally, it includes functionality for displaying and managing a history of calculations.

**Comment by dfghjkbd** [comment]
@jessicachawla 
![image](https://github.com/user-attachments/assets/ac9b5ab7-0f54-4d0a-b7a5-6f0b2cbddba2)
In this  also way, I can make this calculator

**Comment by dfghjkbd** [comment]
@Rakesh9100 I would like to build a new calculator that will support determining circle's area & circumference . This tool will be really helpful for students and math enthusiasts.

Kindly assign me this issue.

Thank you!

**Comment by Rakesh9100** [comment]
No need to create a separate calculator, you can add the Circumference calculation in the existing 2D Shapes Calculator when we select shapes as Circle, let me know @dfghjkbd

**Comment by dfghjkbd** [comment]
@Rakesh9100 yes I am ready to add   circumference and area  calculation feature for circles to the existing 2D Shapes Calculator.

**Comment by Rakesh9100** [comment]
It is already calculating Area and Perimeter, and I think circumference is same as perimeter right @dfghjkbd
