### ISSUE TITLE
[Feature] Add Heat Transfer Calculator

### ISSUE THREAD

**Issue by pavitraag** [Rakesh9100/CalcDiverse#1657]
### Description

The Heat Transfer Calculator estimates the rate of heat transfer through various materials based on input parameters such as material type, thickness, temperature difference, and surface area. This tool is essential for engineers, architects, and students to design efficient thermal systems and understand heat transfer phenomena in different applications.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by pavitraag** [comment]
@Rakesh9100 can you please assign me this

**Comment by Rakesh9100** [comment]
Pls provide your PR @pavitraag

**Comment by Shuvra-Da-CodER** [comment]
@Rakesh9100  I can work on this project.....

**Comment by Rakesh9100** [comment]
Go ahead @Shuvra-Da-CodER
