### ISSUE TITLE
[Feature] Add Isomorphic String Calculator

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1665]
### Description

I want to add an Isomorphic string calculator which calculates and returns result whether two strings entered by user are isomorphic or not .
Two strings are said to be isomorphic if characters in one of the string can be replaced to get the second string .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by meetarora10** [comment]
@Rakesh9100 please assign me this so that I can start working on it.
