### ISSUE TITLE
[Feature] Add Complex Seismographic Impact Calculator

### ISSUE THREAD

**Issue by Sravyasaka** [Rakesh9100/CalcDiverse#1667]
### Description

Assessing the potential impact of an earthquake is vital for preparedness and response efforts. At present, there is no unified tool that combines earthquake magnitude, distance from the epicenter, local population density, and building types to deliver a comprehensive estimate of ground shaking intensity, damage levels, and affected population.

A tool that determines the potential effects of an earthquake using user-provided data like earthquake magnitude, distance from the epicenter, local population density, and optionally, building types. The results should encompass:

Ground Acceleration
Mercalli Intensity 
damage levels
affected population

### Screenshots

![image](https://github.com/user-attachments/assets/f46a8866-e58a-48d4-bfe2-f6c0cd55b857)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Sravyasaka the ui in the screenshot doesn't look very nice. Can you keep it similar to the website

**Comment by Sravyasaka** [comment]
Sure

**Comment by jessicachawla** [comment]
@Rakesh9100 this issued can be assigned

**Comment by Sravyasaka** [comment]
> @Sravyasaka the ui in the screenshot doesn't look very nice. Can you keep it similar to the website

@jessicachawla , could you please check new UI now?

**Comment by jessicachawla** [comment]
yes better 
@Rakesh9100 this issue can be assigned
