### ISSUE TITLE
[Feature] Add Lease Calculator

### ISSUE THREAD

**Issue by Meetjain1** [Rakesh9100/CalcDiverse#1674]
### Description

Add Lease calculator that will take Asset Value, Residual Value, Lease Term (in Years), Interest rate(in percentage) and will calculate and display Monthly Lease Payments, Total Payments, Total Interest.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Meetjain1** [comment]
@Rakesh9100 sir please assign

**Comment by jessicachawla** [comment]
Hi, you can create the PR, Rakesh will look at it and assign the issue as well as start looking at merging PRs from Monday.

**Comment by Meetjain1** [comment]
> Hi, you can create the PR, Rakesh will look at it and assign the issue as well as start looking at merging PRs from Monday.

Ohk Sure @jessicachawla
