### ISSUE TITLE
[Feature] Add Sudoku Calculator

### ISSUE THREAD

**Issue by vansh-codes** [Rakesh9100/CalcDiverse#1675]
### Description

Sudoku is a old game which is very hard to play. This calculator would give answers to the sudoku problem in real time with user inputs. Its calculator works on complex algorith. Assign under GSSoC'24

### Screenshots

![image](https://github.com/user-attachments/assets/ee40ff0a-32c4-4c38-ae28-0680cf08f5d9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by vansh-codes** [comment]
Hello @Rakesh9100, you have assigned @jessicachawla for this? If its done bymistake so please assign me and if not then let me know the reason to assign her
Thank you!

**Comment by Rakesh9100** [comment]
It is assigned by mistake, she is the mentor of this project and not the contributor @vansh-codes

**Comment by Rakesh9100** [comment]
Pls provide your PR @vansh-codes

**Comment by vansh-codes** [comment]
> Pls provide your PR @vansh-codes 

Please merge PR #1761 so that I can create new PR
