### ISSUE TITLE
Sleep Quality Calculator

### ISSUE THREAD

**Issue by surendar-05** [Rakesh9100/CalcDiverse#1676]
### Description

The Sleep Quality Calculator is a user-friendly tool designed to help individuals assess the quality of their sleep based on various factors and receive personalized tips for improvement. Users can get a comprehensive Sleep Quality Score and insights into the factors affecting their sleep by inputting details about their sleep patterns and environment.

### Screenshots

![Screenshot (143)](https://github.com/user-attachments/assets/5a864ae4-809d-439a-a189-4613f7dc63c2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by surendar-05** [comment]
Assign this issue under GSSOC'24 @Rakesh9100

**Comment by surendar-05** [comment]
@Rakesh9100

**Comment by jessicachawla** [comment]
@Rakesh9100 please see if this is needed

**Comment by Rakesh9100** [comment]
No need, pls create issues to add some good calculators @surendar-05
