### ISSUE TITLE
[Style] Remove the paragraph from the footer

### ISSUE THREAD

**Issue by solanki505** [Rakesh9100/CalcDiverse#1677]
### Description

Fixing UI of the about page and placing the detail of CalcDiverse above the footer rather than placing it in the footer.

### Screenshots

![Screenshot 2024-07-19 094129](https://github.com/user-attachments/assets/ab4e478e-4405-415b-9c42-735e643dbc0c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ishika6124** [comment]
I would like to work on this project .Please assign me this task.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
No need of this, footer looks good, pls work on some good issues @solanki505
