### ISSUE TITLE
[Feature] Add dynamic loading of calculators from JSON

### ISSUE THREAD

**Issue by Kiran-pande-30** [Rakesh9100/CalcDiverse#1681]
### Description

I want to accumulate all the calculators in a JSON File.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
open one issue at a time

**Comment by Kiran-pande-30** [comment]
Hello @jessicachawla I have split this issue into two.

**Comment by Rakesh9100** [comment]
Do you want to solve this issue @Kiran-pande-30
