### ISSUE TITLE
[Feature] Add Cost Of Living Calculator

### ISSUE THREAD

**Issue by abhay-sen** [Rakesh9100/CalcDiverse#1682]
### Description

Implement a Cost of Living Calculator that allows users to compare the cost of living between two cities or locations. The calculator should take into account various factors such as housing, food, transportation, and other living expenses to provide a comprehensive comparison.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
can you please give some idea of the ui

**Comment by abhay-sen** [comment]
> can you please give some idea of the ui


for the ui i have thought of first in the landing page having city selection for city 1(current city) and city 2(comparision city)
then there would be a expense selection system which would have labels and input for each expense category and in the input fields there would be sliders and text fields and then i would display the a summary of the overall cost difference between two cities and the percentage differences between the cost of living in the two cities

**Comment by abhay-sen** [comment]
@jessicachawla maam?

**Comment by jessicachawla** [comment]
@Rakesh9100  this issue can be assigned

**Comment by abhay-sen** [comment]
sir @Rakesh9100 ???

**Comment by jessicachawla** [comment]
Hi, you can create the PR, Rakesh will look at it and assign the issue as well as start looking at merging PRs from Monday.

**Comment by abhay-sen** [comment]
> Hi, you can create the PR, Rakesh will look at it and assign the issue as well as start looking at merging PRs from Monday.

@jessicachawla ma'am ihave raised the pr regarding this could you please review it and merge it as gssoc is soon about to end and pr merged after 31st July 11:59 pm won't be counted

**Comment by jessicachawla** [comment]
GSSOC period extended till 11 August. 
@Rakesh9100 will merge it soon

**Comment by abhay-sen** [comment]
> GSSOC period extended till 11 August. @Rakesh9100 will merge it soon

okay maam thank you
