### ISSUE TITLE
[Feature]  Astrological Compatibility Calculator

### ISSUE THREAD

**Issue by sweta-singh28** [Rakesh9100/CalcDiverse#1683]
### Description

Implement an Astrological Compatibility Calculator that determines the compatibility between individuals based on their astrological signs. The calculator should analyze the zodiac signs of two individuals and provide insights into their potential compatibility in various aspects such as love, friendship, and work relationships.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 pls see if this is needed

**Comment by sweta-singh28** [comment]
@jessicachawla ma'am, Could you please provide an update on this project so I can get started on it ASAP?

**Comment by sweta-singh28** [comment]
> @Rakesh9100 pls see if this is needed


@jessicachawla ma'am, Could you please provide an update on this project so I can get started on it ASAP?

**Comment by jessicachawla** [comment]
Hi, you can go ahead and create the PR, Rakesh will look at it and assign the issue as well as start looking at merging PRs from Monday.

**Comment by Rakesh9100** [comment]
No need of this calculator, pls add calculator with some good logics @sweta-singh28

**Comment by sweta-singh28** [comment]
okay @Rakesh9100 sir.
