### ISSUE TITLE
[Feature] Add Word-Letter-Symbol Analysis Calculator

### ISSUE THREAD

**Issue by ShreeluSantosh** [Rakesh9100/CalcDiverse#1684]
### Description

**Features**
* Accepts text input from user in form of a word, sentence or a paragraph.
* Displays frequency of words, individual letters, as well as special characters in a neat table
* Displays the above data in a visual form - bar graph of top 10 used words/letters
* Export option in CSV file format

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
We already have `Word Count Calculator`, you can enhance and add more functionality to that, lmk @ShreeluSantosh
