### ISSUE TITLE
[Feature] Add Money Counter Calculator

### ISSUE THREAD

**Issue by anagha-chaudhari** [Rakesh9100/CalcDiverse#1685]
### Description

This calculator will allow user to calculate the total amount of money based on the number of various denominations of banknotes and coins they have. Users input the quantities of Rs 2000, 500, 200, 100, 50, 20, 10 notes, and Rs 20, 10, 5, 2, 1 coins they have, and the calculator returns the total amount of money. Can you assign this issue under GSSOC'24?

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
give some idea of the ui

**Comment by anagha-chaudhari** [comment]
There will be fields to input the number of respective notes and coins. The user can type the number of notes/coins and increment or decrement the count. After hitting calculate, the total amount of money will be displayed along with calculations. There will be an option to switch the currency if the user wants to. I am planning to use the neumorphic styling.

**Comment by anagha-chaudhari** [comment]
@jessicachawla There will be fields to input the number of respective notes and coins. The user can type the number of notes/coins and increment or decrement the count. After hitting calculate, the total amount of money will be displayed along with calculations. There will be an option to switch the currency if the user wants to. I am planning to use the neumorphic styling.

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Proceed, keep the name as `Money-Counter-Calculator` @anagha-chaudhari

**Comment by Rakesh9100** [comment]
Pls provide your PR @anagha-chaudhari
