### ISSUE TITLE
[Feature] Add Pace Calculator

### ISSUE THREAD

**Issue by Maheshwari-Love** [Rakesh9100/CalcDiverse#1689]
### Description

Pace Calculator is designed to help athletes and fitness enthusiasts accurately calculate their pace and total time for swimming, cycling, and running activities. It can be used to plan training sessions, races, or track progress over time.

### Screenshots

![image](https://github.com/user-attachments/assets/ec97cbde-8749-4942-875b-830f1cd5e1ab)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 can you please assign me this issue

**Comment by Maheshwari-Love** [comment]
@Nihal4777 can you please assign me this task untill my pr get merged, so that i can start working on this issue

**Comment by Nihal4777** [comment]
> @Nihal4777 can you please assign me this task untill my pr get merged, so that i can start working on this issue

@jessicachawla

**Comment by jessicachawla** [comment]
Go ahead and create the PR, Rakesh will assign the issue and merge your PR soon.

**Comment by Maheshwari-Love** [comment]
> Go ahead and create the PR, Rakesh will assign the issue and merge your PR soon.

kindly add labels on PR raised and and also tomorrow is last day for pr to be merged
