### ISSUE TITLE
[Feature] Add Macro Calculator

### ISSUE THREAD

**Issue by thevijayshankersharma** [Rakesh9100/CalcDiverse#1694]
### Description

Achieve your fitness goals with precision using our Personalized Daily Macros Calculator. Input your gender, age, weight, height, activity level, and desired fitness goal to receive tailored recommendations for protein, fat, and carbohydrate intake. Whether you're maintaining, losing weight, or gaining muscle, this tool calculates your ideal daily caloric needs and macronutrient distribution, empowering you to optimize your nutrition and maximize your results. Start your journey to better health and fitness today!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
instead of just adding, why not create a complete body analysis calculator with body fat%, BMI, waist to hp ratio, and any other body analysis you can think?
Also we already have a BMI calculator, so you can reuse the code

**Comment by thevijayshankersharma** [comment]
Yeah I am taking about complete calculator.

**Comment by jessicachawla** [comment]
Will you mention all these as well?

**Comment by thevijayshankersharma** [comment]
Go through the description you will get to know it.

**Comment by jessicachawla** [comment]
It is not clear. That's why I am asking. You should have been clearer

**Comment by Rakesh9100** [comment]
You have not mentioned in the description clearly whether it will be complete body calculator or not, rather just calorie needs is mentioned @thevijayshankersharma 

Is this the same one assigned in #1686 @jessicachawla

**Comment by thevijayshankersharma** [comment]
@Rakesh9100 

![image](https://github.com/user-attachments/assets/d502a4ec-6d5f-42d9-88ac-f1949a56d99f)

**Comment by jessicachawla** [comment]
@Rakesh9100 yes this is same
