### ISSUE TITLE
[Feature] Add scroll progress indicator bar

### ISSUE THREAD

**Issue by Anjaliavv51** [Rakesh9100/CalcDiverse#1695]
### Description

On this website, the scroll-down progress bar is absent on home page while present on all the page

![image](https://github.com/user-attachments/assets/51451686-8121-4061-abc0-93c6d733aa48)

### Screenshots

i would like to add the below progress bar.

![image](https://github.com/user-attachments/assets/4dbfea0f-c13c-4318-813c-881fffca6ab4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please assign me this issue

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please assign me this issue , and preview the PR.

**Comment by Rakesh9100** [comment]
This is already added now @Anjaliavv51
