### ISSUE TITLE
[Feature]Implement Energy Calculator

### ISSUE THREAD

**Issue by UtkershBasnet** [Rakesh9100/CalcDiverse#1697]
### Description

Feature Description:
Develop a web-based Kinetic and Potential Energy Calculator that allows users to compute the potential and kinetic energy of an object. The calculator will require inputs for mass, height, and velocity, and will output the calculated energy values in Joules. This tool is designed to help students and enthusiasts understand and apply basic principles of physics related to energy.

### Screenshots

<img width="1440" alt="Screenshot 2024-07-24 at 1 23 08 AM" src="https://github.com/user-attachments/assets/8477340d-3acc-4437-b6e5-c8e68e5c8b89">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have `Kinetic And Potential Energy Calculator`, pls create new issues @UtkershBasnet
