### ISSUE TITLE
[Feature] Add Chinese Zodiac Calculator

### ISSUE THREAD

**Issue by nadarmega** [Rakesh9100/CalcDiverse#1699]
### Description

Chinese Zodiac calculator that allows users to input their birth year and receive their corresponding Chinese Zodiac sign. The feature should also provide a brief description of the characteristics associated with each Zodiac sign.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by nadarmega** [comment]
@Rakesh9100 please assign it to me!

**Comment by jessicachawla** [comment]
Please go ahead and create the PR, Rakesh will start assigning the issues and merging PRs soon. 

Please keep the UI similar to the zodiac sign calculator to have some harmony.
