### ISSUE TITLE
Unit converion from kg to punds and vice versa.

### ISSUE THREAD

**Issue by maadi7** [Rakesh9100/CalcDiverse#17]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I will implement an unit convertor of pound to weight and vice versa.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sanketshinde3001** [comment]
i'll make it , can you assign it to me

**Comment by Rakesh9100** [comment]
Assigning you, Procees!! @maadi7

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @maadi7

**Comment by Rakesh9100** [comment]
Assigned you, Proceed!! @maadi7

**Comment by Shaba1406** [comment]
@maadi7 what's the update, how the work is going on ?
