### ISSUE TITLE
[Docs] Automatic addition of GSSOC , Bug , Enchancement label's to Issues and PR.

### ISSUE THREAD

**Issue by Anjaliavv51** [Rakesh9100/CalcDiverse#1700]
### Issue Description

Automatic addition of GSSOC , Bug , Enchancement label's to Issues and PR.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please assign me this issue.

**Comment by jessicachawla** [comment]
Please elaborate.

**Comment by Anjaliavv51** [comment]
@jessicachawla if the person belows to gssoc the label will be automatically added by the github actions

**Comment by jessicachawla** [comment]
Explain your issue first.

**Comment by Anjaliavv51** [comment]
@jessicachawla their is no automatic addition of label in the repo.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please assign me this issue

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
I can instantly add the automated workflow for adding the certain labels as GitHub action is doing the commenting while opening and closing the issues and PRs, but I want to do it manually after carefully reviewing the issue @Anjaliavv51
