### ISSUE TITLE
[Feature] Add Octal Calculator

### ISSUE THREAD

**Issue by sharmi4590** [Rakesh9100/CalcDiverse#1701]
This has arithmetic operations for both binary and hexadecimal but not for octal . I would like to add it.
![Screenshot_20240725-232548](https://github.com/user-attachments/assets/65d53390-6fab-4627-b18b-c52a1f87dd8d)
![Screenshot_20240725-232534](https://github.com/user-attachments/assets/86b316d5-9037-4eef-9e4f-55e574edc107)

**Comment by jessicachawla** [comment]
Issue #1533 already exits

**Comment by jessicachawla** [comment]
Please close this issue

**Comment by Rakesh9100** [comment]
That issue is different and done @jessicachawla
Go ahead @sharmi4590
