### ISSUE TITLE
[Feature] Add Catenary Curve Calculator

### ISSUE THREAD

**Issue by samarsajad** [Rakesh9100/CalcDiverse#1702]
### Description

Calculates the shape of a catenary curve (the curve formed by a hanging chain or cable)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by samarsajad** [comment]
Please assign this issue to me @Rakesh9100

**Comment by jessicachawla** [comment]
Please elaborate. The input, output, working, calculation, etc

**Comment by samarsajad** [comment]
> Please elaborate. The input, output, working, calculation, etc

The catenary curve calculator computes and displays a catenary curve, which is the shape assumed by a perfectly flexible chain suspended by its ends and acted upon by gravity. The equation for a catenary curve is:

𝑦
=
𝑎
cosh
⁡
(
𝑥
𝑎
)
y=acosh( 
a
x
​
 )

Where:

𝑦
y is the vertical position.
𝑥
x is the horizontal position.
𝑎
a is a parameter that determines the shape of the catenary.

Inputs would include
Parameter (a): This is a constant that defines the shape of the catenary curve.
Start Point (x1): The starting horizontal position of the curve.
End Point (x2): The ending horizontal position of the curve.
Output would include 
Catenary Curve Calculation

**Comment by samarsajad** [comment]
> > Please elaborate. The input, output, working, calculation, etc
> 
> The catenary curve calculator computes and displays a catenary curve, which is the shape assumed by a perfectly flexible chain suspended by its ends and acted upon by gravity. The equation for a catenary curve is:
> 
> 𝑦=𝑎cosh(𝑥/𝑎) Where y is the vertical position and x is the horizontal position and a is a parameter that determines the shape of the catenary. Inputs would include (a): This is a constant that defines the shape of the catenary curve. Start Point (x1): The starting horizontal position of the curve. End Point (x2): The ending horizontal position of the curve. Output would include Catenary Curve Calculation

Can you please assign this issue to me @jessicachawla

**Comment by jessicachawla** [comment]
Go ahead with the PR, Rakesh will assign this issue and merge your PR soon.
