### ISSUE TITLE
[Feature] Add character count field in Contact page

### ISSUE THREAD

**Issue by Vaishnavigunti2801** [Rakesh9100/CalcDiverse#1704]
### Description

Hello PA,
In Contact Us page at Message Field I will add text like saying minimum character count should be 50 and also a bar which counts the characters when user enters a character so that user will be comfortable in reaching the minimum criteria . I think it will be good rather that pop-up message.

### Screenshots

![image](https://github.com/user-attachments/assets/3e6fab54-136c-4b45-b4e7-2d5dfeca2345)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vaishnavigunti2801** [comment]
@Rakesh9100 
Please assign me this work .
Thank you.

**Comment by jessicachawla** [comment]
Please go ahead and create the PR, Rakesh will start assigning the issues and merging PRs soon.
