### ISSUE TITLE
[Feature] Add Heat Capacity Calculator

### ISSUE THREAD

**Issue by Utsavladia** [Rakesh9100/CalcDiverse#1710]
### Description

It should also be there in the website

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls describe your calculator properly about the functioning, inputs and output @Utsavladia

**Comment by Utsavladia** [comment]
@Rakesh9100 

This is the calculator for physics problems
Input Parameters:
- Heat energy (Q)
- Mass of the substance (m)
- Change in temperature (Δ𝑇)
Formula:  𝑐=𝑄/𝑚Δ𝑇
 
Output: The specific heat capacity of the substance.

**Comment by Rakesh9100** [comment]
Go ahead @Utsavladia

**Comment by Utsavladia** [comment]
@Rakesh9100 Kindly review this one before GSSOC ends

**Comment by Utsavladia** [comment]
@Rakesh9100 
Kindly merge this PR before GSSOC ends 😌
