### ISSUE TITLE
[Feature] Add Inductance Calculator

### ISSUE THREAD

**Issue by Utsavladia** [Rakesh9100/CalcDiverse#1712]
### Description

It is good one for the physics students 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ishag8** [comment]
Please assign this issue to me

**Comment by Utsavladia** [comment]
@ishag8  i already wanna work on it under GSSOC 
find other issues or create you own..

**Comment by Rakesh9100** [comment]
Pls don't open too many issues at once @Utsavladia

**Comment by Utsavladia** [comment]
@Rakesh9100  Please review this before the gssoc ends 😌
