### ISSUE TITLE
[Feature] Add Confusion Matrix Calculator

### ISSUE THREAD

**Issue by nandinipathak2005** [Rakesh9100/CalcDiverse#1718]
### Description

Description:
I want to add a Confusion Matrix Calculator. This calculator allows users to calculate essential machine learning metrics. The calculator takes user inputs for the quantities of true positives, false positives, false negatives, and true negatives, and returns the calculated accuracy, precision, recall, and F1 score. These metrics are critical for evaluating the performance of classification models in machine learning.

Features:
-->User Input Fields:
-->True Positive (TP)
-->False Positive (FP)
-->False Negative (FN)
-->True Negative (TN)

Calculated Metrics:
-->Accuracy
-->Precision
-->Recall
-->F1 Score

### Screenshots

![image](https://github.com/user-attachments/assets/d2c9aef7-8f33-41ce-b371-4dbe4577943d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by nandinipathak2005** [comment]
@Rakesh9100 Please assign this issue to me. I have completed my previous PR (PR#1618) and it has been merged.

**Comment by nandinipathak2005** [comment]
@jessicachawla This is the only issue I have opened after my first PR was merged.

**Comment by jessicachawla** [comment]
Sorry for the misunderstanding

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned.
