### ISSUE TITLE
Enhance the Contributors Section

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#172]
Create a seperate page for the contributors section. Design it by enclosing in a box or some good UI design, add anmations and hover effects as well. Do share your ideas.

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir I would like to work on this.

**Comment by CodeByRajeev** [comment]
The changes before and after can be as below :

At present : 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/5fe3bc34-d04c-435e-84b0-61072e651e8d)


**After making improvements :**

![image](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/4ccd7868-7556-41fd-9ea8-1259c02624af)


**Hover Effects :** 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/0516f261-ccce-480a-a9f5-18f11cc71e30)

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir please go through the above changes and let me know if any more improvements can be done and I hope I get this issue assigned.

**Comment by Rakesh9100** [comment]
Not only this small change. Go through the issue description properly and work accordingly @CodeByRajeev

**Comment by Parth4git** [comment]
I want to work on this issue .please  assign this issue to me .I will a  create a separate page for the contributors section, where contributor profile photo of github is present and also uses hover effect and animation to make it look great.
@Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @Parth4git

**Comment by Rakesh9100** [comment]
@Parth4git Status of your PR

**Comment by rishiiiidha** [comment]
![Scroll gif](https://github.com/Rakesh9100/CalcDiverse/assets/126899168/e542ab05-0350-4007-bde2-573ed6ba3a74)

Infinite Scrolling effect :
The current static contributors block, when faced with a growing number of contributors, consumes more screen space, potentially leading to a less optimal user interface. By incorporating infinite scrolling, we can address this issue and create a more seamless and user-friendly browsing experience.

**Comment by Rakesh9100** [comment]
We don't need scrollable effect, pls go through the issue description and let me know your thoughts @rishiiiidha

**Comment by rishiiiidha** [comment]
In alignment with my concept, which prioritizes space efficiency and visual attractiveness, we aim to incorporate features such as pausing on mouseover and enabling image zoom upon hovering. I'm interested in hearing additional ideas that align with these principles.

**Comment by Parth4git** [comment]
@rishiiiidha I am working on this issue. So ,Kindly wait or look up different issue

Uploading Contributors - CalcDiverse - Google Chrome 2024-01-10 17-47-31.mp4…

**Comment by Parth4git** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/99666524/3482d42c-b8a7-49ac-9e7c-2b370c52d9ca

**Comment by Parth4git** [comment]
@Rakesh9100 My work is almost done just fixing files conflict

**Comment by Rakesh9100** [comment]
Okay then, try to create your PR asap @Parth4git
