### ISSUE TITLE
[Feature] Add Electric Vehicle Savings Calculator

### ISSUE THREAD

**Issue by sweta-singh28** [Rakesh9100/CalcDiverse#1723]
### Description

Estimates savings from using an electric vehicle versus a gasoline vehicle.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Please elaborate. 
Also tell the inputs outputs and calculations

**Comment by sweta-singh28** [comment]
@jessicachawla maam I am thinking to include inputs such as average of your current petrol vehical in (kms/l) total battery capacity, range of your electrical vehical, and the cost of electricity per unit which then would output per km cost of petrol vehicle and electric vehicle.

**Comment by sweta-singh28** [comment]
@jessicachawla ma'am, Could you please provide an update on this project so I can get started on it ASAP?

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by sweta-singh28** [comment]
@Rakesh9100 sir

**Comment by sweta-singh28** [comment]
@Rakesh9100 sir and @jessicachawla maam,  Could you please provide an update on this project so I can get started on it ASAP?

**Comment by Rakesh9100** [comment]
Go ahead @sweta-singh28
