### ISSUE TITLE
[Style] Improve the background in 3D Distance Calculator

### ISSUE THREAD

**Issue by Unnati-Gupta24** [Rakesh9100/CalcDiverse#1726]
### What's the style idea?

We need to improve the background of calculators in caldiverse.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [x] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Unnati-Gupta24** [comment]
Actually a lot of calculators in caldiverse don't have a proper background. They either have repeated images or simply don't have a background at all.
for eg 3d calculator background is white ,
1st calculator's background have a repeated image throughout.

**Comment by Rakesh9100** [comment]
3D Shapes Calculator already has a background @Unnati-Gupta24

**Comment by Unnati-Gupta24** [comment]
3D distance calculator do not have a background @Rakesh9100 
If you allow me then i can work on that issue and modify the pull request

**Comment by Unnati-Gupta24** [comment]
<img width="860" alt="gitpr" src="https://github.com/user-attachments/assets/be8eca35-de4d-4b87-bf2c-310796a8b78d">
