### ISSUE TITLE
[Style] Add scroll to top button in Contact page

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1727]
### Description

I want to add a scroll to top button similar to other pages on the Contact us page also.

### Screenshots

![Screenshot (896)](https://github.com/user-attachments/assets/2018ffe1-5be5-4072-a82f-4fb81439d9e7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by meetarora10** [comment]
@jessicachawla @Rakesh9100  kindly consider this issue .

**Comment by meetarora10** [comment]
@Rakesh9100 please assign this issue to me .

**Comment by Rakesh9100** [comment]
Go ahead @meetarora10
