### ISSUE TITLE
[Feature] Add Paper Weight Calculator

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Rakesh9100/CalcDiverse#1728]
### What would you like to share?

This paper weight calculator will help you determine the weight of a sheet of paper of any size, grammage, or basis weight. You can also use this calculator for paper weight conversion between grammage and basis weight and to find what the grammage of paper is.

In this calculator, you will learn about the measure of weight per unit area that is used to determine the weight of paper, as well as what the basis weight of paper is. 

### Additional information

![image](https://github.com/user-attachments/assets/07299723-e424-4cc7-ba1b-c0e82a53d25d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Khushi-Pushkar** [comment]
@Rakesh9100 Sir , Please assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @Khushi-Pushkar
