### ISSUE TITLE
[Feature] Add Sales Tax Calculator

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Rakesh9100/CalcDiverse#1729]
### What would you like to share?

This online sales tax calculator solves multiple problems around the tax imposed on the sale of goods and services. It can calculate the gross price based on the net price and the tax rate, or work the other way around as a reverse sales tax calculator. 

### Additional information

![image](https://github.com/user-attachments/assets/f9d614b0-0ea9-45fc-a054-7f41071fffa7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Please don't open too many issues at once, you are already assigned to 2 issues before, complete them first @Khushi-Pushkar

**Comment by Khushi-Pushkar** [comment]
@Rakesh9100 Ok sir

**Comment by arjun-shettigar1605** [comment]
Can I please be assigned to add this feature?
