### ISSUE TITLE
[Feature] Add Vote Eligibility Calculator

### ISSUE THREAD

**Issue by meetarora10** [Rakesh9100/CalcDiverse#1730]
### Description

I want to add a Vote Eligibility Calculator which takes age entered by the user , calculates and displayes message whether the user is eligible to vote or not .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
I don't think this is needed. 
@Rakesh9100 please see

**Comment by meetarora10** [comment]
@jessicachawla @Rakesh9100 I think this can be useful to check if one is eligible to vote or not just by entering their age .

**Comment by Rakesh9100** [comment]
We already know that voting age eligibility is 18 years, we don't need this as no calculation is required in this @meetarora10
