### ISSUE TITLE
[Feature] Add KInetic Energy Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Rakesh9100/CalcDiverse#1732]
### Description

This Calculator is used to determine kinetic energy of a moving object by taking the input as mass and velocity from the user.

KE = (1/2)m*v^2

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Already have this.
