### ISSUE TITLE
[Feature] Add a Rate Us page

### ISSUE THREAD

**Issue by sailaja-adapa** [Rakesh9100/CalcDiverse#1738]
### Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by satyamyadav979** [comment]
@Rakesh9100  please assign this issue to me , I would like to work on this

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @Rakesh9100

**Comment by Rakesh9100** [comment]
You have already opened this issue before if I am not wrong, why opening it again @sailaja-adapa

**Comment by sailaja-adapa** [comment]
Ohh sorry I didn't seen it @Rakesh9100

**Comment by sailaja-adapa** [comment]
.
