### ISSUE TITLE
[Feature] Exponent Calculator

### ISSUE THREAD

**Issue by Parmesh119** [Rakesh9100/CalcDiverse#174]
### Description

I wan to add the fourth power caculator.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Parmesh119** [comment]
I am working on this issue.

**Comment by Rakesh9100** [comment]
We already have one Square and Cube calculator. So you can add `Exponent Calculator` which takes x and y in the form of x<sup>y</sup> @Parmesh119

**Comment by Parmesh119** [comment]
ok
