### ISSUE TITLE
[Feature] Add Hexadecimal Calculator

### ISSUE THREAD

**Issue by arunimaChintu** [Rakesh9100/CalcDiverse#1745]
### Description

This will create index.html, styles.css , and  script.js and readme.md

### Screenshots

<img width="553" alt="Screenshot 2024-07-31 at 10 28 14 PM" src="https://github.com/user-attachments/assets/dd593880-3c4c-42f1-8d11-80ce06d36171">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by arunimaChintu** [comment]
@Rakesh9100 Please assign me this issue...

**Comment by Indrajeety993648** [comment]
@Rakesh9100  please assign this issue to me .

**Comment by jessicachawla** [comment]
@Rakesh9100 please see the ui

**Comment by arunimaChintu** [comment]
@Rakesh9100 Please assign me this issue...

**Comment by Rakesh9100** [comment]
We already have this added @arunimaChintu
