### ISSUE TITLE
[Feature] Add Discriminant Calculator

### ISSUE THREAD

**Issue by Indrajeety993648** [Rakesh9100/CalcDiverse#1747]
### Description
A discriminant calculator is a valuable tool for quickly determining the nature of the roots of a quadratic equation. By calculating the discriminant (\(b^2 - 4ac\)), users can easily understand whether the roots are real and distinct, real and equal, or complex.

#### Benefits:
1. **Educational Value**: Helps students and educators easily understand quadratic equations.
2. **Time-Saving**: Provides quick results, reducing the time spent on manual calculations.
3. **Versatility**: Can be integrated into mathematical or educational software.

### Proposed Solution
We propose adding a simple interface where users can input the coefficients \(a\), \(b\), and \(c\) of a quadratic equation. The calculator will then compute and display the discriminant, along with an interpretation of the nature of the roots.

#### Additional Features:
- **Step-by-Step Explanation**: Option to show the steps involved in calculating the discriminant.
- **Graphical Representation**: Visual representation of the quadratic equation's graph based on the discriminant result.

### Conclusion
Implementing a discriminant calculator will enhance the utility of our platform, making it more appealing for users interested in mathematical tools and education.

### Screenshots

![Screenshot from 2024-08-01 01-25-56](https://github.com/user-attachments/assets/798e8741-4a4d-4565-9543-1eb765130b97)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Indrajeety993648** [comment]
@Rakesh9100  please assign this issue to  me . As I already working on  the issue and almost about to done

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned
