### ISSUE TITLE
[Feature] Ratio Calculator

### ISSUE THREAD

**Issue by Parmesh119** [Rakesh9100/CalcDiverse#175]
### Description

I want to add the ratio calculator and solver whether the ratio calculation is true or not. It is used to student whether the equation is equal or not both the side.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
FIrst, work on the issue 174, check the comment there and complete that @Parmesh119

**Comment by Rakesh9100** [comment]
Do you want to get assigned @Parmesh119

**Comment by Rakesh9100** [comment]
Okay, go ahead @Parmesh119
