### ISSUE TITLE
[Feature] Add Factorion Calculator

### ISSUE THREAD

**Issue by suhanipaliwal** [Rakesh9100/CalcDiverse#1753]
### Description

A Factorion is a number which is equal to the sum of the factorials of its digits. A Factorion will show whether the input number is a Factorion or not.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
We already have Strong Number Calculator @suhanipaliwal
