### ISSUE TITLE
[Feature] Chatbot Addition

### ISSUE THREAD

**Issue by Ojas-Arora** [Rakesh9100/CalcDiverse#1754]
### Description

@Rakesh9100 @jessicachawla  I want to add chatbot to the website. kindly assign me this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Ojas-Arora** [comment]
@jessicachawla For asking anything related to the website.

**Comment by jessicachawla** [comment]
@Rakesh9100 please see if this is needed

**Comment by Rakesh9100** [comment]
No need, pls work on other issues @Ojas-Arora
