### ISSUE TITLE
[Feature] Add Decimal Roman Calculator

### ISSUE THREAD

**Issue by nagalakshmi08** [Rakesh9100/CalcDiverse#1757]
### Description

Hi, I want to add a calculator which converts the given decimal number into its corresponding roman number. Please assign me this task, I would like to contribute to this project under GSSOC'24. Thank you.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead, keep the name as Decimal Roman Calculator and implement vice versa functionality as well in the same @nagalakshmi08

**Comment by Rakesh9100** [comment]
Go ahead, keep the name as `Decimal-Roman-Calculator` and implement vice versa functionality as well in the same @nagalakshmi08
