### ISSUE TITLE
[Feature] Add RMR Calculator

### ISSUE THREAD

**Issue by suhanipaliwal** [Rakesh9100/CalcDiverse#1758]
### Description

A RMR calculator can be added to calculate the Resting Metabolic Rate of a person. Resting Metabolic Rate is the number of calories that your body burns while at rest.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jessicachawla** [comment]
Issue #1686 is doing something along the same lines. Can you collaborate and add RMR in that only?

**Comment by suhanipaliwal** [comment]
> Issue #1686 is doing something along the same lines. Can you collaborate and add RMR in that only?

This issue is quite different actually and the assignee has already raised a pr for their issue. So I think it will be difficult to collaborate now.

**Comment by Rakesh9100** [comment]
Go ahead @suhanipaliwal

**Comment by Rakesh9100** [comment]
Provide your PR @suhanipaliwal

**Comment by suhanipaliwal** [comment]
I will raise the pr by tomorrow.
