### ISSUE TITLE
[style] UI Enhancement of LCM calculator 

### ISSUE THREAD

**Issue by Shaba1406** [Rakesh9100/CalcDiverse#176]
### What's the style idea?

We need to improve the UI of LCM calculator, it need to be more attractive with a little bit Description of the solution finding process 

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)"

**Comment by Lavanya-Sathya** [comment]
Hi @Rakesh9100, I would like to work on this issue. Please assign this to me, 
Thanks

**Comment by Rakesh9100** [comment]
Assigning you, Proceed @Lavanya-Sathya
