### ISSUE TITLE
[Feature] Add Z-Spray Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1765]
### Description

A Z-Spray Calculator is used in agriculture to calculate the spray coverage and efficiency. It helps farmers and agricultural professionals determine the optimal amount of spray solution required for a given area, ensuring effective pest and weed control while minimizing waste.

### Screenshots

This implementation allows users to input the area to be sprayed and the spray rate, then calculates the total spray required based on these inputs. The result is displayed in a simple and user-friendly interface.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TBorundia** [comment]
@jessicachawla @Rakesh9100 ,
Please assign this issue under GSSoC'24. Thank You!

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned

**Comment by Rakesh9100** [comment]
Go ahead @TBorundia
