### ISSUE TITLE
[Feature] Add Titration Calculator

### ISSUE THREAD

**Issue by mahek0620** [Rakesh9100/CalcDiverse#1768]
### Description

A Titration Calculator is a valuable tool in chemistry that helps determine the concentration of an unknown solution by using a solution of known concentration (the titrant). The process of titration involves adding the titrant to the analyte (the solution with unknown concentration) until a reaction is complete, which is usually indicated by a color change (if an indicator is used) or reaching an endpoint measured by a pH meter or other means.

Key Components of a Titration Calculator
Titrant Concentration (C₁): The concentration of the solution of known concentration, usually expressed in moles per liter (M).
Volume of Titrant (V₁): The volume of the titrant added to reach the endpoint of the titration, measured in liters (L) or milliliters (mL).
Analyte Volume (V₂): The volume of the solution with the unknown concentration being titrated, also measured in liters (L) or milliliters (mL).
Reaction Stoichiometry: The balanced chemical equation of the reaction between the titrant and the analyte. It provides the mole ratio between the reactants.
Endpoint: The point in the titration process where the reaction is complete, often indicated by a color change or pH change.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by mahek0620** [comment]
@Rakesh9100 sir, can you please assign this to me

**Comment by Rakesh9100** [comment]
Go ahead @mahek0620
