### ISSUE TITLE
[Feature] Add mean functionality in Arithmetic Progression Calculator

### ISSUE THREAD

**Issue by bhumii-ka** [Rakesh9100/CalcDiverse#1770]
### Description

Currently the Arithmetic Progression Calculator calculates nth term and sum of n terms I want to add one more feature such that it calculates arithmetic mean of n terms as well.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @bhumii-ka
