### ISSUE TITLE
[Feature] Add Sine Formula Calculator

### ISSUE THREAD

**Issue by sharmi4590** [Rakesh9100/CalcDiverse#1777]
There's only cosine calculator but not sine calculator . I would like to add it.

![Screenshot (679)](https://github.com/user-attachments/assets/7935072a-9471-4f3f-bfd6-0f5234516a5f)

Like this it will give sine value at different vertices in a triangle . Below is of cosine.

![Screenshot (680)](https://github.com/user-attachments/assets/b18bc058-9a85-4d61-bf5b-151ae369bfb1)

**Comment by charanbhatia** [comment]
@sharmi4590 i want to work on this issue. Can you please assign this issue to me.

**Comment by sharmi4590** [comment]
Hey @Rakesh9100 please assign me this issue I will make sure to complete it within a day.

**Comment by Rakesh9100** [comment]
Go ahead @sharmi4590
