### ISSUE TITLE
[Feature] Add Zener Diode Calculator

### ISSUE THREAD

**Issue by TBorundia** [Rakesh9100/CalcDiverse#1780]
### Description

A Zener Diode Calculator is a tool designed to assist in the analysis and design of circuits involving Zener diodes. Zener diodes are a type of semiconductor device that allows current to flow not only in the forward direction like a typical diode but also in the reverse direction when the voltage exceeds a certain value known as the Zener breakdown voltage. This calculator helps engineers and hobbyists determine the necessary values for various components in Zener diode circuits.

### Screenshots

A Zener Diode Calculator is an essential tool for anyone working with electronic circuits involving Zener diodes, simplifying the design and ensuring accurate and efficient circuit operation.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Don't you understand a simple thing that you are being told from starting, to not open too many issues at once.

Your issues and PRs will not be reviewed now @TBorundia

**Comment by TBorundia** [comment]
@Rakesh9100 , Sorry Sir
But I have completed my previous issues and now I have opened only 2 new issues.

**Comment by TBorundia** [comment]
@Rakesh9100 Sorry Sir,
I will not repeat this again!

**Comment by Rakesh9100** [comment]
4 issues are still open, repeating the same thing of opening multiple issues at once @TBorundia 

https://github.com/Rakesh9100/CalcDiverse/issues/created_by/TBorundia

**Comment by TBorundia** [comment]
@Rakesh9100 ,
I had completed one of that issue and opened PR.
Please give me last chance I will not repeat that.
Sorry Sir

**Comment by TBorundia** [comment]
@Rakesh9100 , Sorry Sir 
I have completed one of the issues and opened a pull request for it. I sincerely apologize and request to give one last chance to make things right. 
I assure you that I will not repeat any mistakes. From now on, I will close all the current issues and open only one at a time.
Thank you for your understanding and support.
Sorry Sir!

**Comment by Rakesh9100** [comment]
Okay fine, no need to close. Complete them one by one and don't open any issue until all of them are completed @TBorundia

**Comment by TBorundia** [comment]
@Rakesh9100 ,
Yes Sir, Thank You So much!

**Comment by Rakesh9100** [comment]
Go ahead @TBorundia
