### ISSUE TITLE
[Feature] Add Projectile Motion Calculator

### ISSUE THREAD

**Issue by sreevidya-16** [Rakesh9100/CalcDiverse#1781]
### Description

I want to add Projectile Motion Calculator

It solves problems related to projectile motion, including range, height, and time of flight.

@Rakesh9100, please assign me this issue under GSSOC

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sreevidya-16** [comment]
@Rakesh9100, please assign me this issue

**Comment by Rakesh9100** [comment]
We already have this [Projectile Motion Calculator](https://calcdiverse.netlify.app/calculators/projectile-motion-calculator/) @sreevidya-16
