### ISSUE TITLE
[Feature] Add Buoyancy Calculator

### ISSUE THREAD

**Issue by sreevidya-16** [Rakesh9100/CalcDiverse#1782]
### Description

I want to add Buoyancy Calculator

Calculates the buoyant force on an object submerged in a fluid

@Rakesh9100, assign me this issue under GSSOC

### Screenshots

![image](https://github.com/user-attachments/assets/d80a7284-afa9-43c6-94af-7f272e85b062)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sreevidya-16** [comment]
@Rakesh9100, please assign me this issue under GSSOC

**Comment by sreevidya-16** [comment]
@Rakesh9100, please assign me this issue

**Comment by sreevidya-16** [comment]
@Rakesh9100, please assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @sreevidya-16
