### ISSUE TITLE
[Feature] Add Linear Regression Calculator

### ISSUE THREAD

**Issue by vivekvardhan2810** [Rakesh9100/CalcDiverse#1783]
### Description

Linear Regression calculator will take a set of data points, compute the best-fit line using linear regression, and display the slope, intercept, and a plot of the data points with the regression line.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vivekvardhan2810** [comment]
@Rakesh9100 Please assign this issue Under GSSOC 24

**Comment by charanbhatia** [comment]
@vivekvardhan2810 can you please assign this issue to me? I want to work on this issue.

**Comment by vivekvardhan2810** [comment]
No @charanbhatia I have already completed the above issue, waiting it for assigning

**Comment by charanbhatia** [comment]
okay

**Comment by vivekvardhan2810** [comment]
@Rakesh9100 @jessicachawla please assign me this issue

I have already made the calculator just need to create the pull request quickly

**Comment by Rakesh9100** [comment]
Go ahead @vivekvardhan2810

**Comment by Rakesh9100** [comment]
May I know why have you closed the issue @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Sir @Rakesh9100 I don't know how to add some basic validations. so that's why

**Comment by Rakesh9100** [comment]
Have you told this to me or the mentor, is directly closing the PR and the issue appropriate in open source, no right @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Sorry @Rakesh9100

**Comment by Rakesh9100** [comment]
And you just have to handle NaN validation that means if no values are entered and Calculate button is clicked, then it should say Please enter valid values, this is just the basics of JavaScript @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Okay @Rakesh9100 got it, can i reopen and solve this issue

**Comment by Rakesh9100** [comment]
Make the new commit in that same PR, don't create a new one @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
okay @Rakesh9100

**Comment by vivekvardhan2810** [comment]
@Rakesh9100 I have made the changes, can you check and merge the PR
