### ISSUE TITLE
[Feature] Add Restaurant Planning Calculator

### ISSUE THREAD

**Issue by aditya-bhaumik** [Rakesh9100/CalcDiverse#1788]
### Description

The Restaurant Planning Calculator is a comprehensive tool designed to estimate and manage the expenses involved in setting up and running a restaurant. The calculator provides:

    Initial Setup Costs:
        One-time Equipment Costs: The total cost for purchasing necessary kitchen and restaurant equipment.

    Monthly Operating Costs:
        Rent: The monthly cost for leasing the restaurant space.
        Utilities: The monthly cost for essential services such as electricity, water, and gas.
        Staff Salaries: The total monthly salary expenditure based on the number of staff and their average salary.

    User Inputs:
        Available Space: The square footage of the restaurant space.
        Number of Staff: The total number of employees required.
        Monthly Rent: The cost of renting the space per month.
        Monthly Utilities: The cost of utilities per month.
        Equipment Costs: The one-time cost for equipment.
        Average Salary per Staff: The average monthly salary for each staff member.

    Expense Calculation:
        Total Initial Cost: Calculates the total one-time setup cost based on equipment expenses.
        Total Monthly Cost: Calculates the recurring monthly expenses, including rent, utilities, and staff salaries.

    Insights for Managing Expenses:
        Provides actionable insights based on the input data to help manage and optimize expenses effectively. For example:
            Suggestions for managing high monthly costs.
            Recommendations for making efficient use of smaller spaces.
            Advice on handling a large number of staff.

The calculator is presented within a visually appealing interface, making it easy to input data and receive detailed financial insights quickly. This tool is ideal for aspiring restaurateurs and existing business owners looking to optimize their financial planning and management.

### Screenshots

![image](https://github.com/user-attachments/assets/b53077ab-f112-43e0-9edc-a473a69c26d0)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please assign me this issue 

I have already made the calculator just need to create the pull request quickly

**Comment by aditya-bhaumik** [comment]
@Rakesh9100 please assign me this issue as only 4 days are left for gssoc to get over and i need to create the pull request also

**Comment by Rakesh9100** [comment]
Go ahead, give the currency as INR and not in dollar @aditya-bhaumik
