### ISSUE TITLE
[Style] Add hover effect to the pagination buttons

### ISSUE THREAD

**Issue by TaeMochi12** [Rakesh9100/CalcDiverse#1796]
### What's the style idea?

I'll add hover effect on "previous" and "next" buttons.
![Screenshot 2024-08-05 002417](https://github.com/user-attachments/assets/fbe0abeb-13d9-45ca-9d1e-58069b761962)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TaeMochi12** [comment]
@Rakesh9100 Please assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead, give some good hover effect matching the UI @TaeMochi12

**Comment by TaeMochi12** [comment]
@Rakesh9100 Sure sir  I'll do it!
