### ISSUE TITLE
[Feature] Add Pendulum Calculator

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/CalcDiverse#1797]
### Description

pendulum calculator that calculates below properties as possible based on the length of the pendulum(l) and the gravitational acceleration (g), Amplitude (A), Mass of the Bob (m) .

Period of the Pendulum (T)
Frequency of the Pendulum (f)
Angular Frequency (w)
Maximum Speed
Maximum Acceleration
Kinetic Energy at the Lowest Point
Potential Energy at the Highest Point

### Screenshots

![image](https://github.com/user-attachments/assets/25969dfe-f6c7-4a10-ad76-052d483f405b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by BarryByte** [comment]
@Rakesh9100 will you please assign me this issue.

**Comment by Rakesh9100** [comment]
Do not create a PR until you have been assigned to an issue @BarryByte

**Comment by Rakesh9100** [comment]
Go ahead @DharshiBalasubramaniyam
