### ISSUE TITLE
[Feature] Add Mass Spring Calculator

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/CalcDiverse#1798]
### Description

calculate below properties if  know the mass of the object (m)and the spring constant(k), and Amplitude (A) 

Period of Oscillation (T)
Frequency of Oscillation (f)
Angular Frequency (w)
Maximum Speed (v_max)
Maximum Acceleration (a_max)
Kinetic Energy at Maximum Speed (KE)
Potential Energy at Maximum Displacement (PE)

### Screenshots

![image](https://github.com/user-attachments/assets/ba7e75c5-5cc6-482a-b9ff-44a1a9738a0a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by BarryByte** [comment]
@Rakesh9100 Please assign this issue to me, i made a sample.

**Comment by Rakesh9100** [comment]
Go ahead @DharshiBalasubramaniyam

**Comment by Rakesh9100** [comment]
Are you providing your PR @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
> Are you providing your PR @DharshiBalasubramaniyam

No sir. Sorry...

**Comment by BarryByte** [comment]
If he instead willing to take this issue forward, please will you @Rakesh9100 give me one more chance and assign this issue to me ?
