### ISSUE TITLE
Integer to Binary Conversion

### ISSUE THREAD

**Issue by maadi7** [Rakesh9100/CalcDiverse#18]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I will be implementanting an Integer to Binary conversion. Please assign me this under SWOC.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls work on previously assigned issue first @maadi7

**Comment by rnavaneeth992** [comment]
@Rakesh9100 I want to work on this , can you assign me

**Comment by Rakesh9100** [comment]
@mavaneeth992 Assigned you!!

**Comment by Rakesh9100** [comment]
Assigned you, Proceed!! @rnavaneeth992

**Comment by GarvVirmani** [comment]
@Rakesh9100 please assign me this issue,Under SWOC

**Comment by Shaba1406** [comment]
@rnavaneeth992 Hey, How the Work is going on any updates ?

**Comment by rnavaneeth992** [comment]
@Shaba1406 Hey I got struck with some other work
Can you unassign me

**Comment by Rakesh9100** [comment]
@maadi7 Do you want to work?

**Comment by GarvVirmani** [comment]
@Rakesh9100 please assign me

**Comment by maadi7** [comment]
> @maadi7 Do you want to work?

hii @Rakesh9100, sure.

**Comment by Rakesh9100** [comment]
Proceed @maadi7
