### ISSUE TITLE
 Carbon Footprint Calculator

### ISSUE THREAD

**Issue by surendar-05** [Rakesh9100/CalcDiverse#1806]
### Description

Carbon Footprint Calculator is a web-based application designed to help users estimate their annual carbon emissions based on their lifestyle choices and daily activities. This project aims to raise awareness about personal carbon footprints and encourage individuals to adopt more sustainable practices. 

### Screenshots

![Screenshot (146)](https://github.com/user-attachments/assets/40bb34d6-1686-4ee0-937f-8de007b00460)

![Screenshot (147)](https://github.com/user-attachments/assets/32c2aabd-8a70-4d3f-9050-5ab9da1f5d80)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by surendar-05** [comment]
Assign this issue under @Rakesh9100

**Comment by surendar-05** [comment]
We have Less time whenever you see  reply as soon as possible

**Comment by surendar-05** [comment]
@Rakesh9100

**Comment by Rakesh9100** [comment]
We already have this [Carbon Footprint Calculator](https://calcdiverse.netlify.app/calculators/carbon-footprint-calculator/) added @surendar-05

**Comment by surendar-05** [comment]
Can I create another issue ?
