### ISSUE TITLE
[Feature] Add Prime Number Calculator

### ISSUE THREAD

**Issue by rugved0102** [Rakesh9100/CalcDiverse#1808]
### Description

Calculates whether given number is Prime or not

### Screenshots

![Prime-Number-Finder](https://github.com/user-attachments/assets/3b429b3d-452d-45cd-b762-b69790293a5c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ankur-kalita** [comment]
Hey @pb0126  @NaveenChandraAdhikari, I have raised a pr for this issue...can you please check it?

**Comment by Rakesh9100** [comment]
Go ahead @rugved0102
