### ISSUE TITLE
[Bug] Fix the zero calculation in Pythagorean Theorem Calculator

### ISSUE THREAD

**Issue by srilekha279** [Rakesh9100/CalcDiverse#1811]
### Description

The current implementation of the hypotenuse calculator has a bug where it incorrectly calculates the hypotenuse when one of the sides is entered as zero.
## Steps to Reproduce:
- Open the calculator and input 0 as one of the sides (e.g., side a).
- Enter a non-zero value as the other side (e.g., side b).
- The calculator incorrectly calculates the hypotenuse.
## What I want to improve
- Fix the bug
### Input Handling: 
Allow users to input values into three fields: side a, side b, and hypotenuse.
Calculations: Implement logic to:
- Calculate the hypotenuse if two sides are given.
- Calculate the missing side if the hypotenuse and one side are given.
- Validate the triplet if all three sides are given.

### Screenshots

![Screenshot (922)](https://github.com/user-attachments/assets/fc41ce79-628c-4c10-8b74-599c6680268b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @srilekha279

**Comment by srilekha279** [comment]
> Go ahead @srilekha279
Should I fix the bug first and then raise a separate issue for the enhancement?

**Comment by Rakesh9100** [comment]
What kind of enhancement @srilekha279

**Comment by Rakesh9100** [comment]
You just fix the bug in this issue by creating a PR, we already have [Pythagorean Triples Calculator](https://calcdiverse.netlify.app/calculators/pythagorean-triples-calculator/) @srilekha279

**Comment by srilekha279** [comment]
> You just fix the bug in this issue by creating a PR, we already have [Pythagorean Triples Calculator](https://calcdiverse.netlify.app/calculators/pythagorean-triples-calculator/) @srilekha279

I understand that the current Pythagorean Triples Calculator validates triplets, but I believe adding the following feature will significantly enhance its functionality

Calculate Missing Side: If the hypotenuse and one side are given.

The current Pythagorean Triplet Calculator only checks whether a triplet is valid. I propose to calculate any side of a right triangle, not just the hypotenuse. 

![Screenshot (924)](https://github.com/user-attachments/assets/c25d3d42-5fbe-4307-88d5-67f331a612bf)

**Comment by srilekha279** [comment]
@Rakesh9100 
Please accept my pull request.
