### ISSUE TITLE
Add LCD and GCD calculator for 2 numbers

### ISSUE THREAD

**Issue by dfghjkbd** [Rakesh9100/CalcDiverse#1814]
### Description

calculates LCD and GCD of two number

### Screenshots

![Screenshot 2024-08-08 112936](https://github.com/user-attachments/assets/62a008d9-3b90-47dd-afe0-e4703d254382)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Don't create duplicate issues, check the repo and the website thoroughly before creating the issues, we already have LCM Calculator, GCD Calculator @dfghjkbd
