### ISSUE TITLE
[Feature] Add Photosynthesis Rate Calculator

### ISSUE THREAD

**Issue by surendar-05** [Rakesh9100/CalcDiverse#1821]
### Description

The Photosynthesis Rate Calculator is a simple tool designed to estimate the rate of photosynthesis in plants based on key environmental factors. The rate at which this process occurs is influenced by several factors, including light intensity, carbon dioxide (CO₂) concentration, and temperature.

### Screenshots

![Screenshot (150)](https://github.com/user-attachments/assets/077b019b-fcc3-4b0a-8540-34ece01c3bfc)

### Checklist

- [X] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by surendar-05** [comment]
Assign this issue under GSSOC'24 @Rakesh9100

**Comment by surendar-05** [comment]
@Rakesh9100

**Comment by Rakesh9100** [comment]
Do you want to solve this issue @surendar-05

**Comment by surendar-05** [comment]
Yes

**Comment by Rakesh9100** [comment]
Go ahead @surendar-05

**Comment by Rakesh9100** [comment]
Any update of your PR @surendar-05

**Comment by surendar-05** [comment]
It's going on i will update you as soon as possible

**Comment by Atharvverma1234** [comment]
Hi, I would like to work on this issue. Please assign it to me. Thank you!

**Comment by Rakesh9100** [comment]
Go ahead @Atharvverma1234

**Comment by Rakesh9100** [comment]
Provide your PR now, it has been so long @surendar-05

**Comment by R2-STAR** [comment]
@Rakesh9100 Assign this issue to me under KWOC

**Comment by Rakesh9100** [comment]
Go ahead @Atharvverma1234
