### ISSUE TITLE
[Feature] Add Factor Calculator

### ISSUE THREAD

**Issue by Maana-Ajmera** [Rakesh9100/CalcDiverse#1824]
### Description

A Factor Calculator is a tool that calculates all the factors (or divisors) of a given number. It determines all the integers that evenly divide into the specified number

### Screenshots

![image](https://github.com/user-attachments/assets/bf1b1bd5-59b6-4b5f-8cb8-12b8a3e20a70)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maana-Ajmera** [comment]
@Rakesh9100 Please assign it to me

**Comment by shawnsd69** [comment]
Subject: Request for Issue Assignment

Dear @Rakesh9100 ,

I hope this message finds you well. I’m eager to contribute to the CalcDiverse and would like to take on a task that could help move the project forward. If possible, could you please assign me this issue that aligns with my skills? I’m particularly interested in working on recent open source project, but I’m open to anything that needs attention.

Thank you for considering my request. I’m looking forward to your guidance and contributing to the project.

Best regards,
Shawn

**Comment by Rakesh9100** [comment]
Do you want to work and solve this issue @Maana-Ajmera @shawnsd69

**Comment by Atharvverma1234** [comment]
Hi, I would like to work on this issue. Please assign it to me. Thank you!

**Comment by Rakesh9100** [comment]
Go ahead @Atharvverma1234

**Comment by Rakesh9100** [comment]
No, you are free to redesign it as you wish @Atharvverma1234
