### ISSUE TITLE
[Feature] Add Tangent Formula Calculator

### ISSUE THREAD

**Issue by nagalakshmi08** [Rakesh9100/CalcDiverse#1836]
### Description

I would like to add a tan calculator which gives tan value of a angle based on the sides given by user.

### Screenshots

![Screenshot_20240809_173118](https://github.com/user-attachments/assets/1e3fa7ee-b145-450d-9c71-2dbb3572e961)
I want to add a Tan calculator which is similar to this cosine calculator.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by isid555** [comment]
@nagalakshmi08 @Rakesh9100 
Kindly assign this issue to me.

**Comment by shawnsd69** [comment]
Subject: Request for Issue Assignment

Dear @Rakesh9100 ,

I hope this message finds you well. I’m eager to contribute to the CalcDiverse and would like to take on a task that could help move the project forward. If possible, could you please assign me this issue that aligns with my skills? I’m particularly interested in working on recent open source project, but I’m open to anything that needs attention.

Thank you for considering my request. I’m looking forward to your guidance and contributing to the project.

Best regards,
Shawn
