### ISSUE TITLE
Add more shapes to the 2d Calculators & Enhance UI.

### ISSUE THREAD

**Issue by CodeByRajeev** [Rakesh9100/CalcDiverse#185]
### Description

The present 2d Calculator has only 5 shapes .

This issue add more shapes and finds their values such as Perimeter & Area .

This issue also enhances the UI of the 2d Calculator.

The improvements before and after can be seen below :

### Screenshots

**Before :** 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/6b28c0c6-e4a0-4808-b50e-43866bcf1ca9)

**After making Improvements :** 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/406ce4ff-81fd-417f-9190-b544ea2e5fcf)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir, I want to work on this issue, Pls go through it and kindly do assign.

**Comment by Rakesh9100** [comment]
Proceed @CodeByRajeev
