### ISSUE TITLE
[Bug] Fix the calculation in GST Calculator

### ISSUE THREAD

**Issue by shawnsd69** [Rakesh9100/CalcDiverse#1852]
### Description

There is a bug in GST calculator, with displaying the gst amount in rupees it also shows calculation of dollars which on conversion does not sum up to the same amount I had entered, we can either remove the dollar conversion feature and just display the gst amount in rupees or we can fix the conversion of Indian rupees to US dollars, so that it provides a proper output. If issue is assigned to me, I will make the required changes 

### Screenshots

![image](https://github.com/user-attachments/assets/7fe6c371-69b6-4ab9-802c-5d55ada6185b)
![gst](https://github.com/user-attachments/assets/a3a60bd4-cbaa-4cbd-b4ae-cf6959e4ea9a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shawnsd69** [comment]
Subject: Request for Issue Assignment

Dear @Rakesh9100 ,

I hope this message finds you well. I’m eager to contribute to the CalcDiverse and would like to take on a task that could help move the project forward. If possible, could you please assign me this issue that aligns with my skills? I’m particularly interested in working on recent open source project, but I’m open to anything that needs attention.

Thank you for considering my request. I’m looking forward to your guidance and contributing to the project.

Best regards,
Shawn

**Comment by Rakesh9100** [comment]
Do you want to get assigned and solve this issue @shawnsd69

**Comment by saurabhhsinghh** [comment]
Dear @Rakesh9100 , Kindly assign this issue to me. I want to fix this bug. 

Best regards,
Saurabh

**Comment by Rakesh9100** [comment]
Go ahead @saurabhhsinghh
