### ISSUE TITLE
[Feature] Add Ballistic Coefficient Calculator

### ISSUE THREAD

**Issue by Akashoa** [Rakesh9100/CalcDiverse#1856]
### Description

Ballistic coefficient calculator is a tool used in ballistics to determine the ballistic coefficient  of a projectile, such as a bullet. The ballistic coefficient is a measure of a projectile's ability to overcome air resistance during flight. It is an essential factor in understanding how a projectile will behave over long distances, including its trajectory, velocity, and the degree of wind drift.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to solve this issue @Akashoa

**Comment by wildcraft958** [comment]
@Rakesh9100 Can you please assign me this?

**Comment by Rakesh9100** [comment]
Go ahead @wildcraft958

**Comment by Rakesh9100** [comment]
PR status please @wildcraft958

**Comment by wildcraft958** [comment]
Sorry for late reply  due to some circumstances  i wasn't  able to work i will complete  it by tomorrow.

**Comment by Rakesh9100** [comment]
Any update @wildcraft958

**Comment by wildcraft958** [comment]
i will raise PR today after i complete the bug in your other project.

**Comment by Rakesh9100** [comment]
Provide your PR @wildcraft958

**Comment by wildcraft958** [comment]
![Screenshot from 2024-12-28 02-48-55](https://github.com/user-attachments/assets/a5bfcd70-1488-476a-b591-c8991d85cbd7)
![Screenshot from 2024-12-28 02-49-25](https://github.com/user-attachments/assets/b949db64-a272-48d4-8927-16439db5f20e)
