### ISSUE TITLE
[Feature] Add Laser Linewidth And Bandwidth Calculator

### ISSUE THREAD

**Issue by Akashoa** [Rakesh9100/CalcDiverse#1857]
### Description

A Laser Linewidth and Bandwidth Calculator is used to calculate the linewidth and bandwidth of a laser, which are critical parameters in determining the performance and applications of a laser system such as in fibre optics 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to solve this @Akashoa

**Comment by SanikaBhalerao1345** [comment]
@Rakesh9100 I would like to work on this. Can u assign it to me

**Comment by Rakesh9100** [comment]
Go ahead @SanikaBhalerao1345

**Comment by SanikaBhalerao1345** [comment]
@Rakesh9100 i have raised pr pls check
