### ISSUE TITLE
[Feature] Add Modulation Calculator

### ISSUE THREAD

**Issue by Akashoa** [Rakesh9100/CalcDiverse#1858]
### Description

A modulation calculator is a tool used to calculate various parameters involved in the modulation process, typically in the context of communication systems. Modulation is the process of varying one or more properties of a carrier signal (such as amplitude, frequency, or phase) according to a message signal. This process is fundamental in transmitting information over distances, whether through radio waves, fiber optics, or other mediums.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shaina123786** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Rakesh9100** [comment]
Do you want to solve this issue @shaina123786

**Comment by saurabhhsinghh** [comment]
@Rakesh9100  Kindly assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead @saurabhhsinghh
