### ISSUE TITLE
[Feature] Add Air Fuel Ratio (AFR) Calculator

### ISSUE THREAD

**Issue by Akashoa** [Rakesh9100/CalcDiverse#1872]
### Description

An Air-Fuel Ratio (AFR) Calculator is a tool used to calculate the ratio of air to fuel used in an internal combustion engine. The ratio of air to fuel is critical in determining the efficiency and emissions of the engine. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 would like to work on this

**Comment by Rakesh9100** [comment]
Go ahead @abhirajadhikary06
