### ISSUE TITLE
[Feature] Add Recoil Energy Calculator

### ISSUE THREAD

**Issue by Akashoa** [Rakesh9100/CalcDiverse#1875]
### Description

A Recoil Energy Calculator is a tool that helps estimate the recoil energy experienced by a shooter when a firearm is discharged. This energy is a result of the conservation of momentum and is influenced by the mass of the projectile, the velocity of the projectile as it leaves the barrel, and the mass of the firearm itself.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nishakulkarni06** [comment]
@Rakesh9100 plz assign to me

**Comment by Rakesh9100** [comment]
Go ahead @Nishakulkarni06

**Comment by Nishakulkarni06** [comment]
@Rakesh9100 Done plz check!
