### ISSUE TITLE
Add Acoustic Impedance Calculator

### ISSUE THREAD

**Issue by Akashoa** [Rakesh9100/CalcDiverse#1876]
### Description

An Acoustic Impedance Calculator is a tool that helps calculate the acoustic impedance of a medium based on its density and sound speed. Acoustic impedance is a critical property in fields such as acoustics, audio engineering, and materials science, as it influences how sound waves propagate through different materials.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nishakulkarni06** [comment]
@Rakesh9100 i had  added this feature plz check it out.
