### ISSUE TITLE
[Style] Enhance the text visibility in light mode

### ISSUE THREAD

**Issue by isid555** [Rakesh9100/CalcDiverse#1885]
### Description

The text on the page appears faint and is difficult to read against the light background. This impacts readability, especially in light mode. Below are the observations and recommendations:

#### Observations:
 The descriptive text and button text appear too light to be easily readable.

#### Expected Outcome:
Improved readability and better user experience, especially for users with visual impairments or viewing the page in bright environments.

### Screenshots

![image](https://github.com/user-attachments/assets/680c8ed8-8050-4590-b3e4-e09435316847)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by isid555** [comment]
@Rakesh9100 Kindly assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @isid555
