### ISSUE TITLE
[Feature] Add auto scroll to top when clicked on pagination buttons

### ISSUE THREAD

**Issue by Nishakulkarni06** [Rakesh9100/CalcDiverse#1888]
### Description

when we click on next or previous the page button does not auto scroll to top. 
I want to work on this 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nishakulkarni06** [comment]
@Rakesh9100 plz assign to me

**Comment by Rakesh9100** [comment]
Please complete your assigned issue first @Nishakulkarni06

**Comment by Rakesh9100** [comment]
Go ahead @Nishakulkarni06
