### ISSUE TITLE
[Style] Enhance the pagination buttons

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Rakesh9100/CalcDiverse#1897]
### What's the style idea?

On your website, at the bottom of the calculators section, the UI of the 'previous' and 'next' buttons is not very appealing. Improving the UI of these buttons would be more effective in capturing user interest.

### Screenshots:

![WhatsApp Image 2024-12-10 at 01 27 44_e089b6bf](https://github.com/user-attachments/assets/2a703251-dfad-44f4-8033-1ec8bfdcf077)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @biswajit-sarkar-007
