### ISSUE TITLE
NaN handling in the calculators

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Rakesh9100/CalcDiverse#19]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

While going through all the applications for calculating age. I found out that there is no `NaN` handling. I want to work on this issue where I will use regex or input validations that will only allow numeric values.

### Screenshots

![image](https://github.com/opencodeiiita/CalcDiverse/assets/55249639/732e9c6c-5256-4b82-96b1-90b779550041)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Anubhab-03** [comment]
I want to work on this issue and add a NaN handling section in your code.Please assign this to me under SWOC'24

**Comment by Rakesh9100** [comment]
Assigning you, Go ahead!! @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
> Assigning you, Go ahead!! @Sanchitbajaj02

I would like to, but currently I am a Project Admin as well. So it would be better if you assign this to a contributor :blush:

**Comment by Rakesh9100** [comment]
Sure, no issues @Sanchitbajaj02

**Comment by Anubhab-03** [comment]
Done
