### ISSUE TITLE
[Style] Improve the footer UI

### ISSUE THREAD

**Issue by Archi-shaw** [Rakesh9100/CalcDiverse#1901]
### Description

Spacing is required betwen about section and footer part ..
 It would look better if Contact Us is in the middle, quick links on the left and the description on the right...

### Screenshots

![Screenshot 2024-12-11 031210](https://github.com/user-attachments/assets/03e7b076-4ff8-472d-833e-a8198f7ed2ad)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Archi-shaw** [comment]
@Rakesh9100  Please assign this issue to mee.

**Comment by Rakesh9100** [comment]
I don't think we need this change, please work on other good issues @Archi-shaw
