### ISSUE TITLE
[Feature] Add Calculator for Proportional Values

### ISSUE THREAD

**Issue by Prutha-Upadhyay** [Rakesh9100/CalcDiverse#192]
### Description

The goal is to enhance the calculator by adding a single-file calculator functionality for quickly finding the right value in a proportion. Users should be able to fill in three fields, and upon pressing Enter, the calculator should instantly reveal the value of the fourth field.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Prutha-Upadhyay** [comment]
Yes , I would like to add Proportionality Calculator! @Rakesh9100

**Comment by Rakesh9100** [comment]
@Prutha-Upadhyay PR status

**Comment by Prutha-Upadhyay** [comment]
Almost done!PR will be done by tomorrow or tonight!
