### ISSUE TITLE
[Feature] Add more options in Binary Calculator

### ISSUE THREAD

**Issue by SHRUTISINHA250714** [Rakesh9100/CalcDiverse#1920]
### Description

Description:
I noticed that the functionality for converting Binary to Gray Code and Gray Code to Binary is missing.

These features will allow users to:
Input a binary number and convert it to its corresponding Gray code.
Input a Gray code and convert it back to a binary number.

Steps:
Add a form with two inputs: one for binary input and the other for Gray code.
Implement conversion algorithms for:
Binary to Gray code conversion.
Gray code to Binary conversion.
Display the result after the user submits the input.

Benefits:
Extends the functionality of the current calculator.
Helps users working with digital systems and encoding.
I would like to work on this feature and contribute to the project. Please let me know if I can proceed!

### Screenshots

![image](https://github.com/user-attachments/assets/9610408d-2d43-4184-9539-cf41d3a5834d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We have `Number System Calculator` which converts binary to decimal, octal, hexadecimal and vice versa. Can we integrate this calculation in that calculator itself @SHRUTISINHA250714

**Comment by SHRUTISINHA250714** [comment]
I'd like to work on adding Binary to Gray Code conversion to the existing calculator and integrate it with the current features! Please assign it to me.

**Comment by Rakesh9100** [comment]
Go ahead @SHRUTISINHA250714
