### ISSUE TITLE
[Style] Enhance the cursor color in dark mode

### ISSUE THREAD

**Issue by isid555** [Rakesh9100/CalcDiverse#1921]
### What's the style idea?

We need to improve

The current cursor color does not suit the dark mode background, resulting in odd visibility . I'm requesting a more suitable color that complements the cursor in dark mode theme , and toggling between colors is expected within cursor , when theme is altered from dark to light modes.

![image](https://github.com/user-attachments/assets/75d46e68-9b0e-4b63-b642-f0da634e7689)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by isid555** [comment]
@Rakesh9100 Kindly assign this issue to me

**Comment by Rakesh9100** [comment]
Which color do you want to implement, will it go well with the theme @isid555

**Comment by isid555** [comment]
I would like to implement the same background color to the cursor ,whenever the theme is changed ...
Currently my view is like this in the image
![image](https://github.com/user-attachments/assets/552276ab-9471-4118-beb4-160dccac5933)

![image](https://github.com/user-attachments/assets/5dbcc230-faac-4c93-a820-3866acaacefe)

**Comment by Rakesh9100** [comment]
Go ahead @isid555
