### ISSUE TITLE
[Feature] Add Signup Login page 

### ISSUE THREAD

**Issue by Nishakulkarni06** [Rakesh9100/CalcDiverse#1923]
### Description

Add signup and login to the project to provide personalized experience for users. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What is the need of this, any user can go through website and use the calculators as it is already open-source @Nishakulkarni06

**Comment by Nishakulkarni06** [comment]
Once user log in then we can store their previous calculation history

**Comment by Rakesh9100** [comment]
Which tech stacks are you going to use and will it be full fledge @Nishakulkarni06

**Comment by Rakesh9100** [comment]
Any update or should I close this issue @Nishakulkarni06

**Comment by Nishakulkarni06** [comment]
yes you can close
