### ISSUE TITLE
[Style] Enhance the navbar menu items hover effect

### ISSUE THREAD

**Issue by isid555** [Rakesh9100/CalcDiverse#1927]
### What's the style idea?

We need to improve

Currently the components in the navbar becomes pink color when hovered  , no matter what the theme is in ....ie in both dark and light mode the hover effect is in same color

I expect it to be different colors according to the theme change

# Screeenshots
![image](https://github.com/user-attachments/assets/19027484-de7d-40ae-b6d5-e31d6db50bc5)

![image](https://github.com/user-attachments/assets/b6057cd7-a961-4857-83a5-7b5da4a1bc66)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by isid555** [comment]
@Rakesh9100  Kindly assign this issue to me

**Comment by Rakesh9100** [comment]
I see that it is not the same, it's pink in one theme and purple in another, lmk further @isid555

**Comment by isid555** [comment]
But Still It does'nt suit well to the background , the pink in blue background and purple(similar pink shade) in pink background ....That's why I have raised It @Rakesh9100 
It can be more dynamic and suitable to the backgrounds I guess

**Comment by Rakesh9100** [comment]
Okay, proceed @isid555
