### ISSUE TITLE
[Style] Enhance the scroll to top button for both the themes

### ISSUE THREAD

**Issue by Ajai-Sharan** [Rakesh9100/CalcDiverse#1929]
### What's the style idea?

Description
While scrolling down, the progress wheel in the bottom right corner uses the same color scheme for both Dark and Light modes. This can make the UI less intuitive and reduce visual clarity, particularly when switching between modes.

Screenshots:
![image](https://github.com/user-attachments/assets/dc3bf3be-ffb5-4d86-b1e8-9b1c1b52f527)
![image](https://github.com/user-attachments/assets/ce997670-df82-4957-a623-7471a2ece072)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Ajai-Sharan** [comment]
@Rakesh9100 I would like to work on this. please assign this issue to me.

**Comment by Rakesh9100** [comment]
I don't think we need to change this as the present one goes fine with both the themes, lmk @Ajai-Sharan

**Comment by Ajai-Sharan** [comment]
But still the color used in the progress bar in the wheel is not going well with the theme of the light mode . We can different color pattern for different mode, which is why I raised the issue @Rakesh9100.

**Comment by Rakesh9100** [comment]
Okay, will see, complete your previous assigned issue @Ajai-Sharan

**Comment by Rakesh9100** [comment]
Can you provide the screenshot of how it will look in both the themes @Ajai-Sharan

**Comment by Ajai-Sharan** [comment]
Hello @Rakesh9100 ,

Screenshots:
![image](https://github.com/user-attachments/assets/fc2c84a3-eaee-4b15-8e16-e41f593578a7)
![image](https://github.com/user-attachments/assets/ef0435bd-c69a-45e7-8ddc-a5f6d237f16e)

These are the screenshots. please review it.

**Comment by Rakesh9100** [comment]
Looks fine, okay proceed @Ajai-Sharan
