### ISSUE TITLE
[Style] Enhance the mic button color scheme

### ISSUE THREAD

**Issue by Ajai-Sharan** [Rakesh9100/CalcDiverse#1930]
### What's the style idea?

We need to improve

Description:
The mic button next to the search bar is looks same in both the dark and light mode. I would be better if we use different color scheme for different mode

Screenshots:
![image](https://github.com/user-attachments/assets/a6ac66da-9375-456d-8615-0a6622dd0413)
![image](https://github.com/user-attachments/assets/eddf7241-7948-4490-904a-3a42d6c1bc90)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Atharvverma1234** [comment]
Hello Sir, I would like to work on this issue, Please assign it to me. Thank you.

**Comment by Rakesh9100** [comment]
Can you provide the screenshot of how it will look in both the themes @Ajai-Sharan

**Comment by Ajai-Sharan** [comment]
Hello sir @Rakesh9100 ,

Screenshots:

![image](https://github.com/user-attachments/assets/883d7a24-014b-4b5c-8c31-2a32b79f0e17)
![image](https://github.com/user-attachments/assets/9b17e124-4ddc-479a-a51e-cdd729ed7b76)
![image](https://github.com/user-attachments/assets/61136b80-3172-471f-92df-43b055abe324)
![image](https://github.com/user-attachments/assets/56fed14c-3d91-410a-946c-48e43762107c)


These are the screenshots. Please review it.

**Comment by Rakesh9100** [comment]
Okay, go ahead with the 2nd option of both @Ajai-Sharan

**Comment by Ajai-Sharan** [comment]
@Rakesh9100 I've designed it so that, without hovering over the button, it will look like the first image for both themes, and while hovering, it will look like the second image for both themes.

`When we're not hover (in both the themes)`

![image](https://github.com/user-attachments/assets/883d7a24-014b-4b5c-8c31-2a32b79f0e17)
![image](https://github.com/user-attachments/assets/61136b80-3172-471f-92df-43b055abe324)
---
`When we're hovering (in both the themes)`

![image](https://github.com/user-attachments/assets/9b17e124-4ddc-479a-a51e-cdd729ed7b76)
![image](https://github.com/user-attachments/assets/56fed14c-3d91-410a-946c-48e43762107c)


Should I implement it this way, or should I make the second image the default instead?

**Comment by Rakesh9100** [comment]
Okay, I got confused, you can go ahead with your implementation @Ajai-Sharan
