### ISSUE TITLE
[Style] Enhance the pagination buttons according to the theme

### ISSUE THREAD

**Issue by isid555** [Rakesh9100/CalcDiverse#1933]
### What's the style idea?

We need to improve
The guiding buttons for directing to the *next* and *prev* buttons are not dynamic in hover effect when there is a change in the dark and llight theme.
And also I expect to style the buttons more modern and suitable for CalcDiverse.

## Screenshots
![image](https://github.com/user-attachments/assets/9bb376d5-b8a8-4172-bfcd-fff91f875fe2)
<br>
![image](https://github.com/user-attachments/assets/ff6fb83c-2621-488e-8033-e7078357e456)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by isid555** [comment]
@Rakesh9100  Kindly assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @isid555

**Comment by Rakesh9100** [comment]
PR update pls @isid555

**Comment by isid555** [comment]
Kindly review the PR 
@Rakesh9100
