### ISSUE TITLE
[Feature] Add Density Calculator

### ISSUE THREAD

**Issue by saurabhhsinghh** [Rakesh9100/CalcDiverse#1936]
### Description

A Density Calculator is a tool or application designed to compute the density of a substance based on its mass and volume. Density is a fundamental physical property of matter, defined as the mass per unit volume.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @saurabhhsinghh
