### ISSUE TITLE
[Feature] Add initial height option in Projectile Motion Calculator

### ISSUE THREAD

**Issue by saurabhhsinghh** [Rakesh9100/CalcDiverse#1940]
### Description

The projectile calculator in the website does not consider if the object is being thrown from an initial height. Initial height option can be added to the calculator.

### Screenshots

![Screenshot 2024-12-23 171939](https://github.com/user-attachments/assets/25ba797d-a0c2-406f-8e88-e82bc2543001)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @saurabhhsinghh
