### ISSUE TITLE
[Style] Enhance the hover color of heading in contributors page

### ISSUE THREAD

**Issue by Ajai-Sharan** [Rakesh9100/CalcDiverse#1943]
## Description
In both themes, while hovering over the heading in the Contributors section, the text changes to a pink color. This does not align well with the dark mode theme and disrupts the visual consistency of the design.

## Expected Behavior
The hover color should complement the dark mode theme. For instance, a shade of blue or a lighter variant of the text color would maintain coherence with the overall dark mode aesthetic.

## Steps to Reproduce
1. Navigate to the Contributors section in dark mode.
2. Hover over the heading text.
3. Observe that the hover color changes to pink, which clashes with the dark mode theme.

## Proposed Solution
Change the hover text color to a theme-appropriate shade, such as light blue or another color that better suits the dark mode palette.

## Screenshots/References
![image](https://github.com/user-attachments/assets/a880ced5-0c11-405c-934e-cee7d33eca88)
![image](https://github.com/user-attachments/assets/fa718239-07ee-441d-9869-f30e943d4c45)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Ajai-Sharan** [comment]
@Rakesh9100 I would like to work on this issue. Kindly assign this issue to me.

**Comment by Rakesh9100** [comment]
Okay, go ahead, you can enhance the heading color with and without hover properly for both the themes accordingly @Ajai-Sharan
