### ISSUE TITLE
[Feature] Adding compound interest  calculator

### ISSUE THREAD

**Issue by Komal73** [Rakesh9100/CalcDiverse#195]
### Description

Adding a calculator to find compound interest with a convenient UI.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Compound Interest calculator is already present on the website. Pls work on other new issues @Komal73
