### ISSUE TITLE
[Feature] :Rectangular to polar form calculator

### ISSUE THREAD

**Issue by Yatin12527** [Rakesh9100/CalcDiverse#197]
### Description

This calculator will take values in rectangular form and convert them into polar form. These calculations are very important for students who are studying electrical or electronics engineering and any engineering that has network problems.

### Screenshots

Interface will vaguely look like this
![image](https://github.com/Rakesh9100/CalcDiverse/assets/134225415/a65e2cd2-e88d-431b-9ac3-5251b5afaa74)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Carry on @Yatin12527
