### ISSUE TITLE
[Feature] : Basic Calculator

### ISSUE THREAD

**Issue by Yatin12527** [Rakesh9100/CalcDiverse#198]
### Description

Calcdiverse has various calculators except the main basic calculator that can perform some complex tasks. I'd like to add that.

### Screenshots

This is how it will look altho the css will be improved:-
![image](https://github.com/Rakesh9100/CalcDiverse/assets/134225415/a83bed0e-b596-4590-8c5a-daa1cc58c444)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Good catch, go ahead @Yatin12527 
Name this as `Basic-Calculator`.
