### ISSUE TITLE
Percentage Calculator

### ISSUE THREAD

**Issue by Shreyansh-333** [Rakesh9100/CalcDiverse#20]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I can add a percentage calculator to CalcDiverse. Kindly assign me this under SWOC.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by gautamkhokhar0001** [comment]
Please assign me this issue. I want to contribute.

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @Shreyansh-333

**Comment by Rakesh9100** [comment]
Same issue already exist @Shreyansh-333
