### ISSUE TITLE
[BUG] Content Overflow in footer on mobile devices

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/CalcDiverse#200]
### Description

The list content in the footer is overflowing out of the box on mobile devices making it unresponsive. The li needs to be fixed to maintain the website's responsiveness throughout every device. 

### Screenshots

![cd](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/77239ac2-304e-489a-bdf3-dd0fd7d1aace)

### Any additional information?

Extra CSS properties which is pushing the content out of the box making it unresponsive.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)"

**Comment by Rakesh9100** [comment]
Pls do work on other good issues @pb0126
