### ISSUE TITLE
Search Bar / Tab for searching calculator

### ISSUE THREAD

**Issue by actron-git** [Rakesh9100/CalcDiverse#201]
### Description

Hey Rakesh I hope this feature make use of this project more efficiently.I think  adding a search bar  will give better user experience,
So I am planning for adding this feature using text search or keyword search and also you can suggest for any searching technique that can work efficiently for our application. I hope you will allow to contribute with this feature. Waiting for positive response. 
Also I am participating in JWOC if this project is part of it then you can assign this as task from JWOC. Regards.   

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Hey, this feature seems good. This project is up for SWOC as for now. If you are participant of SWOC, then will assign you this issue.

But if you have registered for JWoC, selected projects for JWoC are not confirmed yet. Let's see what response comes from JWoC team @actron-git

**Comment by actron-git** [comment]
Ok ,will wait for tomorrow because I am not participating in Swoc. Can you keep this feature hold until announcement of jwoc please @Rakesh9100

**Comment by Rakesh9100** [comment]
Sure, don't worry @actron-git

**Comment by actron-git** [comment]
Thank you so much. Hoping for project selection ..

**Comment by actron-git** [comment]
@Rakesh9100  Congratulations 🎉  I think 3 projects got selected I'll try to explore other also, can we proceed with the issue / Feature.Can you assign this part under jwoc now...

**Comment by abhyuday1212** [comment]
Hey @Rakesh9100 , I am a participant of SWOC and want to contribute to this issue of search bar . Can you please assign it to me.

**Comment by actron-git** [comment]
@abhyuday1212  This feature issue is opened by me itself. I already started with issue please look into other issue for your contribution.

**Comment by Rakesh9100** [comment]
@actron-git 

> @Rakesh9100 Congratulations 🎉 I think 3 projects got selected I'll try to explore other also, can we proceed with the issue / Feature.Can you assign this part under jwoc now...

Thanks ✨ @actron-git Yes, 3 projects are selected and you can explore all of them now and contribute from 15 Jan, 2024. Issues will be assigned from 15th Jan only. Till then, keep exploring!!

**Comment by Rakesh9100** [comment]
> Hey @Rakesh9100 , I am a participant of SWOC and want to contribute to this issue of search bar . Can you please assign it to me.

Pls open up new issues if you want to contribute and get it assigned. This issue is for JWoC program @abhyuday1212

**Comment by Rakesh9100** [comment]
You have to create this issue again after 15th Jan if you want to work, as this is treated as invalid @actron-git

**Comment by actron-git** [comment]
@Rakesh9100  Ok i'll open same issue on 15 jan.
