### ISSUE TITLE
[Feature] :Percentage to Fraction Calculator

### ISSUE THREAD

**Issue by Parth4git** [Rakesh9100/CalcDiverse#206]
### Description

There are various calculator in CalcDiverse but [Percent to fraction] Calculator is missing. So ,It will be good addition of Feature Percent to Fraction Calculator.
I willing to work on this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Rakesh9100** [comment]
Go ahead @Parth4git

**Comment by Parth4git** [comment]
@Rakesh9100 I have made PR on this issue

**Comment by Rakesh9100** [comment]
Hey @Parth4git Create your PR properly and pls don't spam it continuously by creating invalid PRs!!
