### ISSUE TITLE
[Feature] CSS Unit Calculator

### ISSUE THREAD

**Issue by Akshansh8** [Rakesh9100/CalcDiverse#208]
### Description

input will be in px and the converted output will be in rem based on 1rem = 16px

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by arrx-03** [comment]
I would like to contribute to this issue, from part of jwoc

**Comment by Rakesh9100** [comment]
You can name this calculator  as `CSS Unit Calculator` and just not Px to Rem but include some more conversions by using dropdowns.
Example:-
1. px to rem
2. rem to px
3. px to em
4. em to px
5. em to rem and so on @Akshansh8

**Comment by Rakesh9100** [comment]
You can name this calculator  as `CSS Unit Calculator` and just not Px to Rem but include some more conversions by using dropdowns.
Example:-
1. px to rem
2. rem to px
3. px to em
4. em to px
5. em to rem and so on!!

Should I assign you? @Akshansh8

**Comment by Akshansh8** [comment]
@Rakesh9100 yes you can assign it to me

**Comment by Rakesh9100** [comment]
Okay go ahead @Akshansh8
