### ISSUE TITLE
[Bug] Center Alignment for Title in Permutations and Combinations Calculator

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Rakesh9100/CalcDiverse#209]
### Description

This bug report addresses a UI issue in the Permutations and Combinations Calculator where the title alignment is not centered, impacting the overall user interface experience. 

### Screenshots

![Screenshot from 2024-01-11 01-59-45](https://github.com/Rakesh9100/CalcDiverse/assets/44281971/ed0d854c-ed0c-452f-b03a-9342cda789b9)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)"

**Comment by Rakesh9100** [comment]
When I am opening this calculator from the website, it is showing perfectly @NaveenChandraAdhikari 

![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/2a82b9f2-e072-47c6-9287-731c4a239086)
