### ISSUE TITLE
Create Contact Us Section

### ISSUE THREAD

**Issue by pulkitgarg04** [Rakesh9100/CalcDiverse#21]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The link for 'Contact' section is not there. I can create the contact page for the website. Kindly assign me this under SWOC.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It is already present. Pls create another unique issue and I will assign you @pulkitgarg04
