### ISSUE TITLE
[Style] Fix Padding and Margins of Contact Form

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/CalcDiverse#219]
### What's the style idea?

**We need to improve the padding and margins of the contact form**
**The components collide with the form bottom and top**

**I am an IWOC contributor
Please assign this issue to me under IWOC**

![image](https://github.com/Rakesh9100/CalcDiverse/assets/140608790/3f2d9a1f-5c6a-454d-b632-53cb406811f8)

### Checklist

- [X] I have checked the existing issues
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)"

**Comment by hemant933** [comment]
assign it to me

**Comment by Rakesh9100** [comment]
UI is changed totally and spaces are fixed now. Pls work on other issues @JiyaGupta-cs
