### ISSUE TITLE
I want to add Mass Converter in the calculator App

### ISSUE THREAD

**Issue by kumar007ambi** [Rakesh9100/CalcDiverse#22]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100  I want to add mass converter basically converts that kilo to gram ,miligram etc. please assign this issue to me

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by kumar007ambi** [comment]
@Rakesh9100 Can I start working on this issue ?

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @kumar007ambi
