### ISSUE TITLE
[Feature] Implement Infinite Scrolling for Contributors Block

### ISSUE THREAD

**Issue by rishiiiidha** [Rakesh9100/CalcDiverse#222]
### What's the style idea?

<h2>Overview</h2>

I propose enhancing the current contributors block by introducing an infinite scrolling effect. Currently, the contributors block is static, and as the number of contributors increases, it occupies more space. I believe implementing infinite scrolling could significantly enhance the user experience.

<h2>Reasoning</h2>

The current static contributors block, when faced with a growing number of contributors, consumes more screen space, potentially leading to a less optimal user interface. By incorporating infinite scrolling, we can address this issue and create a more seamless and user-friendly browsing experience.

<h2>Idea </h2>

![image](https://github.com/Rakesh9100/CalcDiverse/assets/126899168/b82d52be-2b1b-4ffd-aa13-773acccb0f9b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a SWOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rishiiiidha** [comment]
@Rakesh9100 Please assign me this issue.

**Comment by Rakesh9100** [comment]
Can you pls checkout issue #172 and provide your idea there if you want to work @rishiiiidha

**Comment by Rakesh9100** [comment]
Hey @rishiiiidha The contributors page is now seperated, so you can share your idea here if you want to enhance it!!
