### ISSUE TITLE
Addition of AP and GP Calculator

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/CalcDiverse#224]
### Description

It will allow user to calculate the sum of terms, given the first term, common difference, and number of terms in the given Arithmetic Progression(AP) or Geometric Progression(GP).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to create AP and GP merged in one calculator ? @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
No it will have two different div one for AP calculations and one for GP calculations @Rakesh9100

**Comment by Rakesh9100** [comment]
What will be the short name of this calc you will keep @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
AP Calculator and GP Calculator respectively @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay proceed @Dhairya1Gupta

**Comment by Ananyamishra08** [comment]
assign me this task under swoc 24
