### ISSUE TITLE
[Feature] Contact us section of Navbar

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/CalcDiverse#225]
### Description

On clicking **Contact Us** option of Navbar a Contact us form appears but there is **no option to close it**.
I want to **add a button** with ❌ icon on top of contact us form which will **close the form** and take you to home page.
Kindly assign this issuse to me under **IWOC2024**.

### Screenshots

![Screenshot 2024-01-13 000045](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/5be0fad5-74e6-46da-84d7-7c7284ee8ddc)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
I don't think we need an extra button as we already have navbar present. Pls work on other good issues @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
ok👍
