### ISSUE TITLE
[Feature] : Make the NavBar sticky

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/CalcDiverse#227]
### Description

I will fix the Navbar position so that after scrolling the nevbar will still visible

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This calculator is already present on the website. Pls check first and then create your new issues @Prince-kushwaha-2004 

You can think of adding a new calculator which is not present on the website and then edit this issue title and description!!

**Comment by Prince-kushwaha-2004** [comment]
i had checked it include linear equation calculator and cubic equation calculator there is no such calculator for quadratic equation

**Comment by Rakesh9100** [comment]
[Check this](https://calcdiverse.netlify.app/calculators/quadratic-calculator/) @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
ok sir this was not visible in lists of calculator on website so i dident see

**Comment by Rakesh9100** [comment]
Maybe you didn't update your branch of your forked repo @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
sir one que can i create a calculator like mobile calculator which can perform task like aditon subtraction and some mathematical expressions

**Comment by Rakesh9100** [comment]
That issue is also raised and PR is already created,  I just have to merge it @Prince-kushwaha-2004 

[Check this](https://github.com/Rakesh9100/CalcDiverse/pull/215)

**Comment by Prince-kushwaha-2004** [comment]
ok sir i will uppdate my branch

**Comment by Prince-kushwaha-2004** [comment]
i am going to close this issue if i get new idea then i will share

**Comment by Prince-kushwaha-2004** [comment]
yes sir i will can fix the navbar

**Comment by Prince-kushwaha-2004** [comment]
should i create new issue or edit this issue?

**Comment by Rakesh9100** [comment]
Edit this issue title and description accordingly so that I can assign you, no need to create a new one @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
ok sir

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Kindly check.

**Comment by Rakesh9100** [comment]
Go ahead @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Thankyou sir 😊
I will complete it soon.

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Kindly Check.

**Comment by Shiv10122003** [comment]
Please assign me this issue under iwoc @Rakesh9100
