### ISSUE TITLE
Temperature Conversion Calculator

### ISSUE THREAD

**Issue by kumar007ambi** [Rakesh9100/CalcDiverse#23]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100  I want to add Temperature converter that converts celcius to Fahrenheit,kelvin etc.Please assign this issue to me.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by JrG-One** [comment]
I'm confident that I can resolve this issue. Kindly assign it to me, as I am a contributor participating in the Social Winter of Code 2024.

**Comment by kumar007ambi** [comment]
@Rakesh9100 Can I start working on this issue ?

**Comment by Bhuvangoyal466** [comment]
Can I work on it?

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @kumar007ambi

**Comment by JrG-One** [comment]
@Rakesh9100, In case this issue is not resolved on time, kindly assign it to me

**Comment by Rakesh9100** [comment]
@kumar007ambi Status of your PR

**Comment by kumar007ambi** [comment]
@Rakesh9100 I have started working on this issue
