### ISSUE TITLE
[Bug] Fix Title logo

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#230]
### Description

There is missing of title logo in almost all pages of calculator @Rakesh9100 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/b6ebc7c8-2f10-4618-9155-5e2e92a1038a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by prasukjain07** [comment]
Hey mentor, I like to contribute in this issue, please assign this issue to me.

**Comment by hemant933** [comment]
sir , plz assign it to me

**Comment by Rakesh9100** [comment]
Which pages you are talking about @AbhineshJha

**Comment by AbhineshJha** [comment]
About all individual pages of calculators  @Rakesh9100 
eg : 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/077d4b3c-6899-49ec-9436-353ce3e5bc00)

**Comment by Rakesh9100** [comment]
No need to put logos to each calculator page since new calculators are continuously being added to the website. Pls work on other good issues @AbhineshJha
