### ISSUE TITLE
[Feature] Add a new Compound Interest Calculator

### ISSUE THREAD

**Issue by zul132** [Rakesh9100/CalcDiverse#235]
### Description

I would like to add a Compound Interest Calculator which would input the Principal amount, Interest rate and Time (number of years) from the user and display the compound interest. The proposed calculator would be created using HTML, CSS, and Javascript and can be added to the website as per the given guidelines.

### Screenshots

![issue_compound_interest_calc](https://github.com/Rakesh9100/CalcDiverse/assets/98112914/7db95f65-a3a0-4371-a2fe-ae7b726fbd8e)
Disclaimer: The screenshot is not of my own calculator. It is just a sample to show how the final calculator may look  like

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zul132** [comment]
@Rakesh9100 kindly assign me this issue under JWoC  (after the coding phase starts)

**Comment by Rakesh9100** [comment]
Compound Interest calculator is already present on the website. Pls raise new issues only after checking the website, repository, and the issues for the existing ones @zul132

**Comment by zul132** [comment]
Hey @Rakesh9100 i checked the website but I could only see a Simple Interest calculator
