### ISSUE TITLE
[Feature] Add an Amstrong Number Calculator

### ISSUE THREAD

**Issue by zul132** [Rakesh9100/CalcDiverse#236]
### Description

I would like to add a Armstrong Number Calculator which would input the number of digits 'n' from the user and calculates the Armstrong Number(s) for n-digit numbers. The proposed calculator would be created using HTML, CSS, and Javascript and can be added to the website as per the given guidelines.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zul132** [comment]
@Rakesh9100 please assign me this issue under JWoC (after the coding phase starts)

**Comment by Rakesh9100** [comment]
Sure @zul132

**Comment by AftabMankapure** [comment]
Assign me this issue under jwoc

**Comment by Rakesh9100** [comment]
You have to create this issue again after 15th Jan, as this is treated as invalid @zul132
