### ISSUE TITLE
[Feature] Add a backspace button

### ISSUE THREAD

**Issue by SilviuPe** [Rakesh9100/CalcDiverse#237]
### Description

Hello Rakesh!  I would like to add a new button in the [Basic Calculator](https://github.com/Rakesh9100/CalcDiverse/tree/main/Calculators/Basic-Calculator).
A backspace button that delete digits or characters written by mistake. An clear button already exists, but instead of delete the whole paragraph, the backspace button can delete one character at a time. 
I think this feature will improve the user experience when they use Basic Calculator.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [x] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls tick the program in the descripton for which you have created the issue for @SilviuPe

**Comment by SilviuPe** [comment]
> Pls tick the program in the descripton for which you have created the issue for @SilviuPe

**Done** ✅
