### ISSUE TITLE
[Feature] Add a Binary to decimal Converter

### ISSUE THREAD

**Issue by Smritigit1202** [Rakesh9100/CalcDiverse#239]
### Description

A HTML,CSS,JavaScript based program to convert Binary Number to Decimal Number

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Smritigit1202** [comment]
Please assign me the issue

**Comment by Rakesh9100** [comment]
Pls create you issues after 15th Jan, 2024 otherwise issue will be invalid @Smritigit1202
