### ISSUE TITLE
Length Converter 

### ISSUE THREAD

**Issue by kumar007ambi** [Rakesh9100/CalcDiverse#24]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100  I want to add Length converion from km to m, m to cm etc.Please assign issue to me

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by kumar007ambi** [comment]
@Rakesh9100 Can I start working on this issue ?

**Comment by Rakesh9100** [comment]
Two issues are already assigned to you, please complete those first @kumar007ambi 

Assigning you, Proceed!! @JrG-One

**Comment by Rakesh9100** [comment]
Which permission do you need since pushing some changes and creating a PR don't need any permission to anyone @JrG-One

**Comment by JrG-One** [comment]
@Rakesh9100 Actually i do changes While pushing my changes to git I got the error 
if possible could you please tell me thewhole process to push and craete pull request

**Comment by JrG-One** [comment]
@Rakesh9100,  I appreciate your assistance. I'm thankful for successfully creating my initial pull request in my open-source project.

**Comment by Rakesh9100** [comment]
Good, Appreciated that you are able to!! @JrG-One
