### ISSUE TITLE
[Feature] : Add Degree to Radian Calculator

### ISSUE THREAD

**Issue by rahat2134** [Rakesh9100/CalcDiverse#240]
### Description

Enhance the website's functionality by implementing a Degree to Radian calculator. This tool will allow users to easily convert angles from degrees to radians and vice versa.

### Screenshots

.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rahat2134** [comment]
@Rakesh9100  assign me this when coding phase will start

**Comment by Rakesh9100** [comment]
Don't create issues before 15th Jan as it is treated as invalid @rahat2134

**Comment by rahat2134** [comment]
@Rakesh9100 why you havent closed other issue?

**Comment by rahat2134** [comment]
also i had a conversation with u regarding same,

**Comment by Rakesh9100** [comment]
Mentors had a meeting today in which it was told that it will be considered invalid, so I am closing every issue today and create it after 15th Jan @rahat2134

**Comment by Rakesh9100** [comment]
Mentors had a meeting today in which it was told that it will be considered invalid which was not the case before, so I am closing every issue today and create it after 15th Jan @rahat2134 

Hope you understand!!
