### ISSUE TITLE
Time Zone Calculator

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Rakesh9100/CalcDiverse#241]
### Description

Kindly allow me to contribute in your project by building a time zone calculator under SWOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls describe your issue as if what this calculator will do @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
> Pls describe your issue as if what this calculator will do @Suchitra-Sahoo

User will Input a specific time and date in one time zone. Choose another time zone and get the equivalent time and date in the selected time zone.

**Comment by Rakesh9100** [comment]
Okay proceed @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Kindly check the pull request made.

**Comment by Rakesh9100** [comment]
Pls check the comment on the PR @Suchitra-Sahoo
