### ISSUE TITLE
[Bug] : Fix the working of some buttons in Basic Calculator

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/CalcDiverse#242]
### Description

**Problems:**
1) buttons like **(√, ^, sin, cos )** not working because **closing brackets are missing.** Because of which it is showing **error**.
2) All buttons are not arranged properly.
3) It is **not responsive** as shown in screenshot.

**Sollution:**
1) I will add bracket buttons **[  '('   ,   ')'  ]** so that we can complete our input and use the feature of  **(√, ^, sin, cos )** and it will not show error.
2) I will work on css to **arrange buttons** and make **website resposnsive** so that it look beautifull.

Kindly assign this issue to me under IWOC2024

### Screenshots

![Screenshot 2024-01-13 234836](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/a7076d70-34cf-45e7-b168-47158d00a6df)
![Screenshot 2024-01-14 000127](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/8fd24e40-cfff-460a-9366-1448eca613aa)
![Screenshot 2024-01-13 234724](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/848cf3f7-a43e-41b1-9f25-013dd99e1e62)
![Screenshot 2024-01-13 234746](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/ebc505d2-f399-45f1-b294-bf02512ec672)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Prince-kushwaha-2004

**Comment by Sakshamjain98** [comment]
@Rakesh9100 sir assign this issue to me as i want to work on this issue

**Comment by AftabMankapure** [comment]
Assign me this issue 
I want to work on this 
I already work on this type of issue
