### ISSUE TITLE
[Feature] Add Arithmetic Mean Calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#243]
### Description

We would like to request the addition of an Arithmetic Mean Calculator feature on the CalcDiverse website. This calculator will allow users to input a set of numbers, and the application will calculate and display the arithmetic mean (average) of those numbers.

1. Describe the Feature:
           The Arithmetic Mean Calculator should include:

          1.  An input field for users to enter a set of numbers (comma-separated).
          2. A "Calculate Mean" button to trigger the calculation.
          3. Display the calculated mean prominently on the webpage.
         
2. Justification:
    The Arithmetic Mean Calculator will provide users with a quick and convenient way to calculate the average of a set of 
     numbers directly on the website. This feature aligns with the goal of enhancing user engagement and providing valuable 
     tools.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me this issue

**Comment by Rakesh9100** [comment]
We already have `Statistics Calculator` which calculates mean as well. Pls work on new issues @AftabMankapure
