### ISSUE TITLE
[Feature] Number System Converter

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#248]
### Description

The Number System Converter should provide a user-friendly interface allowing users to input a number in any base (binary, octal, decimal, hexadecimal) and convert it to other bases seamlessly

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue already exist for this @AftabMankapure

**Comment by Rakesh9100** [comment]
You can open up new issues if you want to @AftabMankapure
