### ISSUE TITLE
[Feature] Decimal to Binary Calculator

### ISSUE THREAD

**Issue by Parth4git** [Rakesh9100/CalcDiverse#249]
### Description

It is helpful for all student related to computer science as well as electronics 

### Screenshots

![Screenshot 2024-01-14 160400](https://github.com/Rakesh9100/CalcDiverse/assets/99666524/7ab784fb-54ed-4a86-89c0-f187803fdfec)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue already exist for this. Pls work on new issues @Parth4git
