### ISSUE TITLE
Pressure Convertor

### ISSUE THREAD

**Issue by Japneet001** [Rakesh9100/CalcDiverse#25]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Converts pressure from one unit to another

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sidharth2829** [comment]
I have seen the code, and i can add this feature.
So please assign this issue to me.

**Comment by krishnagitcontri** [comment]
Assign this to me.

**Comment by Rakesh9100** [comment]
Assigning you, Go ahead!! @Japneet001
