### ISSUE TITLE
[Feature] Add Search Bar for Dynamic Calculator Selection

### ISSUE THREAD

**Issue by abhyuday1212** [Rakesh9100/CalcDiverse#251]
## Problem
The current implementation lacks a search bar feature for dynamically selecting calculators from the provided list. This absence makes it challenging for users to quickly find and select specific calculators from an extensive list.

## Proposal
I propose the addition of a search bar that enables users to search for calculators dynamically. This feature would enhance the user experience by facilitating quicker and more convenient access to specific calculators.

## Desired Features
- ### Search Input Field:
A search input field should be prominently displayed, allowing users to enter keywords or phrases related to the calculator they are looking for.

- ### Real-time Filtering:
As users type in the search bar, the list of calculators should be dynamically filtered in real-time, displaying only the relevant results.

- ### Intuitive User Interface:
The addition of this search bar should seamlessly integrate with the current user interface, ensuring a smooth and intuitive experience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already opened by other contributor. Pls work on new other new issues @abhyuday1212

**Comment by abhyuday1212** [comment]
I opened this issue after you closed the previous one of the other contributor. Rest If you want to do partiality by re-opening the previous issue then no worries, you both can continue working on it.
![IMG_20240114_173149.jpg](https://github.com/Rakesh9100/CalcDiverse/assets/115206840/453a45b4-b400-48c7-bacc-ebe43f827fe0)

**Comment by Rakesh9100** [comment]
Its not about partiality, I will close that issue again because it is invalid before 15th and he has to open it again. And so that issue is already kept for JWoC program not for SWOC!! @abhyuday1212

**Comment by abhyuday1212** [comment]
Okay no worries. I just wanted to solve some bigger issues That's why I opened this one. I will close it myself.

**Comment by Rakesh9100** [comment]
You can open new issues anytime and get it assigned if that issue is already taken up for some other program!! Not only that issue is a big one! @abhyuday1212

**Comment by abhyuday1212** [comment]
Can you suggest some bigger changes regarding M.E.R.N or advance javascript that you need or want to incorporate?

**Comment by Rakesh9100** [comment]
One of the issue I am thinking to open up is to Add a eye catching preloader to the website. If you want to work on this, open up an issue @abhyuday1212

**Comment by abhyuday1212** [comment]
I am good with the logical part of the code. I can work on this but I know someone who is absolute best at designing animations. I will tell her to create the issue So please assign it to @navya1212 .

**Comment by Rakesh9100** [comment]
If she wants to work and opens an issue now then will assign for sure else I will open this issue in some time and the one who comments will be assigned @abhyuday1212 

You can think of issues with the logical part yourself and open them if you want to!!

**Comment by abhyuday1212** [comment]
Okay, thanks.
