### ISSUE TITLE
[Bug] : Contributers section of footer not working

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/CalcDiverse#252]
### Description

**Contributers option** in nevbar of **footer** is showing no response on clicking.
As shown in Screenshot.
kindly assign this issue to me under **IWOC24.**

### Screenshots

![Screenshot 2024-01-14 171243](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/67216d01-ddf7-49ad-a80e-d9e92724f292)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed and also fix that for the contact page @Prince-kushwaha-2004
