### ISSUE TITLE
[Feature] Enable Loaders to the Website

### ISSUE THREAD

**Issue by Navya-1212** [Rakesh9100/CalcDiverse#254]
## Feature Request:
I suggest implementing loaders with dynamic animations to be displayed at the beginning and in-between transitions on our website. These loaders would not only serve a functional purpose by indicating the loading process but also add a visually pleasing element that contributes to a more modern and interactive user interface.

## Why is this important?

User Engagement: Dynamic loaders can capture user attention and provide visual feedback, reducing the perceived wait time during loading processes.

Professional Aesthetics: Incorporating dynamic animations aligns with contemporary design trends, making our website appear more polished and professional.

Enhanced User Experience: Users often appreciate a visually appealing and interactive experience. Dynamic loaders contribute to a positive overall user impression.

**Comment by Rakesh9100** [comment]
Pls use the proper issue template and edit it @Navya-1212
