### ISSUE TITLE
[Feature] Enable Loaders with Dynamic Animations

### ISSUE THREAD

**Issue by Navya-1212** [Rakesh9100/CalcDiverse#255]
## Feature Request:
I suggest implementing loaders with dynamic animations to be displayed at the beginning and in-between transitions on our website. These loaders would not only serve a functional purpose by indicating the loading process but also add a visually pleasing element that contributes to a more modern and interactive user interface.

## Why is this important?

User Engagement: Dynamic loaders can capture user attention and provide visual feedback, reducing the perceived wait time during loading processes.

Professional Aesthetics: Incorporating dynamic animations aligns with contemporary design trends, making our website appear more polished and professional.

Enhanced User Experience: Users often appreciate a visually appealing and interactive experience. Dynamic loaders contribute to a positive overall user impression.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Navya-1212

**Comment by Rakesh9100** [comment]
Status of your PR @Navya-1212

**Comment by Navya-1212** [comment]
I am working on it

**Comment by Navya-1212** [comment]
Please give me 2 days more I will update you
