### ISSUE TITLE
NaN handling in Age Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#257]
Provide an alert to choose a valid date when clicked on Calculate without choosing any date in Age Calculator!!

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 would like to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
For JWOC, you need to make comment after 15th Jan 12:00 AM else considered invalid comment @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> For JWOC, you need to make comment after 15th Jan 12:00 AM, else considered invalid comment @SoumyadevSaha

In that case, please assign me this issue under IWOC 2.0 as well @Rakesh9100

**Comment by Rakesh9100** [comment]
Sure @SoumyadevSaha

**Comment by Bayyana-kiran** [comment]
I have been solved similar issue ...can I create a pr?

**Comment by Rakesh9100** [comment]
No @Bayyana-kiran

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 made the PR for handling NaN in Age Calculator
