### ISSUE TITLE
Keyboard functioning in Basic Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#258]
Describe a logic in Basic Calculator so that user can type the number on the calculator website using his/her PC keyboard!!

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 I would like to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
For JWOC, you need to make comment after 15th Jan 12:00 AM else considered invalid comment @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> For JWOC, you need to make comment after 15th Jan 12:00 AM, else considered invalid comment @SoumyadevSaha

okay, then I need to comment once more at 12.01 on 15th right ?

**Comment by Rakesh9100** [comment]
Yes @SoumyadevSaha

**Comment by Developer-Swati** [comment]
Hello @Rakesh9100  please assign me this project under SWOC'24

**Comment by Rakesh9100** [comment]
Proceed @Developer-Swati

**Comment by Developer-Swati** [comment]
Thankyou @Rakesh9100

**Comment by Rakesh9100** [comment]
@Developer-Swati Status of your PR pls

**Comment by Developer-Swati** [comment]
@Rakesh9100  please assign it to someone else. I am busy in my semester exams. I am really sorry for that

**Comment by SoumyadevSaha** [comment]
Would like to work on it under IWOC @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha
