### ISSUE TITLE
NaN handling in Length Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#259]
Provide an alert to enter a valid number when clicked on Convert without entering any number in Length Calculator!!

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 woud like to work on this issue under IWOC. Please do assign me this.

**Comment by Rakesh9100** [comment]
Proceed @SoumyadevSaha

**Comment by Bayyana-kiran** [comment]
Hi @Rakesh9100  actually I solved similar issue ....can I create a pr ?

**Comment by Rakesh9100** [comment]
No , you can't create a PR since you are not assigned to this issue @Bayyana-kiran

**Comment by SoumyadevSaha** [comment]
Made the PR fixing NaN exception in the Length Calculator @Rakesh9100
