### ISSUE TITLE
Logarithm Calculator

### ISSUE THREAD

**Issue by soumyaarya** [Rakesh9100/CalcDiverse#26]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100 I want to add new feature which calculates the log of the number taken as input. Please assign this issue to me

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @soumyaarya

**Comment by Shreyas-SAS** [comment]
Hey @soumyaarya, once you are done can I implement an antilog method for this as well if you are not implementing it.
Would that be alright @Rakesh9100 ?

**Comment by Shreyas-SAS** [comment]
I will create a new issue and you can please tag it as standby if you agree or close it otherwise

**Comment by soumyaarya** [comment]
Okay @Shreyas-SAS
