### ISSUE TITLE
Handle NaN in Differential Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#261]
Display an alert to enter a function when clicked on Calculate Derivative button without entering any function in Differential Calculator!!

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 please assign me this issue under IWOC 2.0

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
Made the PR for handling NaN in Differential Calculator @Rakesh9100
