### ISSUE TITLE
BMI Calculator 

### ISSUE THREAD

**Issue by krishnagitcontri** [Rakesh9100/CalcDiverse#265]
### What's the style idea?

The changes in BMI calculator is in the section overweight healthy and underweight is their
so Healthy=Green Color
Underweight = Yellow
Overweight = Red
which helps to make cautions
<img width="952" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/153177987/dc80e417-6dfc-46f7-bdda-3b544bf43edb">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @krishnagitcontri

**Comment by Rakesh9100** [comment]
Status of your PR @krishnagitcontri
