### ISSUE TITLE
[Feature] Add an Armstrong Number Calcultor for n-digit numbers

### ISSUE THREAD

**Issue by zul132** [Rakesh9100/CalcDiverse#268]
### Description

I would like to add a Armstrong Number Calculator which would input the number of digits 'n' from the user and calculates the Armstrong Number(s) for n-digit numbers. The proposed calculator would be created using HTML, CSS, and Javascript and will be added to the website as per the given guidelines.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zul132** [comment]
@Rakesh9100 I am willing to work on this issue under JWOC. Kindly assign it to me

**Comment by Rakesh9100** [comment]
Go ahead @zul132

**Comment by Rakesh9100** [comment]
Labels will be added after the merging based on the quality of the PR and the work done @zul132
