### ISSUE TITLE
GPA Calculator 

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/CalcDiverse#27]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a sgpa and cgpa calculator to this repo.

### Screenshots

![image](https://github.com/opencodeiiita/CalcDiverse/assets/92045934/53c6c288-6e65-44a3-93e6-dedbad72b419)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @kom-senapati

**Comment by Rakesh9100** [comment]
Looks good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @kom-senapati
