### ISSUE TITLE
[Feature] Harmonic Progression Calculator

### ISSUE THREAD

**Issue by hemant933** [Rakesh9100/CalcDiverse#270]
### Description

this calculator is used too calculate HP for a series

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hemant933** [comment]
assign it to me

**Comment by Rakesh9100** [comment]
Proceed @hemant933

**Comment by shivam101203** [comment]
sir @Rakesh9100 please assign the issue to me i will do it  within 3 days

**Comment by hemant933** [comment]
bro @shivam101203  this is already assigned to me because i generate the issue , i hope u understand

**Comment by shivam101203** [comment]
okk
