### ISSUE TITLE
[Feature] Quadratic Equation Roots calculator

### ISSUE THREAD

**Issue by daksh1210jain** [Rakesh9100/CalcDiverse#271]
### Description

I am willing to create a Quadratic equation roots calculator to the project under JWOC tag 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by daksh1210jain** [comment]
Kindly assign me this issue

**Comment by Rakesh9100** [comment]
This calculator is already present in the website. Pls create new issues @daksh1210jain
