### ISSUE TITLE
[Feature] Heart Rate Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#272]
### Description

A calculator which takes inputs as age and resting heart rate and gives the output as of heart rate of any person

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/58f32839-522a-4b1d-9580-e0cd7fb69573)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
