### ISSUE TITLE
[Feature] Real Estate Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#274]
### Description

Real Estate Calculators: Assist in real estate-related calculations, such as mortgage payments and property valuation.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/0e40e3c0-2480-4b9a-a7ed-2d8b35054ed5)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
