### ISSUE TITLE
[Feature] EMI (Equated Monthly Installments) Calculator

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/CalcDiverse#277]
### Description

I want to add a new EMI (Equated Monthly Installments) calculator to the list of calculators. Please assign me this issue under IWOC'24

### Screenshots

<img width="471" alt="Screenshot 2024-01-15 at 3 15 29 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/86418216/5b714799-61c0-43ba-b481-845926d2aebc">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue #14 is already open for this @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
Oh I see ... I think I missed it since I did not find any calulator named EMI in the list of calculators sorry for that.
