### ISSUE TITLE
[Feature] Binary to Decimal Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#278]
### Description

This calculator takes input as a binary number and gives output as a decimal number ..!

if you want then i can also do Decimal to Binary in the same code..( Lengthy Code).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
The issue to add `Number System Calculator` is already present in which this feature will be added @AbhineshJha

**Comment by AbhineshJha** [comment]
OOps!! sorry i just searching it on website @Rakesh9100
