### ISSUE TITLE
[Feature] Animations on home page

### ISSUE THREAD

**Issue by yashi-15** [Rakesh9100/CalcDiverse#279]
### Description

I want to add subtle floating effects for the website's home page when the page gets loaded,
this would make the website more interesting.
Please assign this issue to me under SWOC.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to add preloader to the website @yashi-15
