### ISSUE TITLE
Designing a good UI for the website

### ISSUE THREAD

**Issue by Shivangi015** [Rakesh9100/CalcDiverse#28]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I can make a good interface for the website, which is creative and add some effect to it to make it good looking and attractive, please assign this issue to me.

### Screenshots

![image](https://github.com/opencodeiiita/CalcDiverse/assets/115791035/670d8b3e-5239-4a92-852f-cb02c78908a9)
It needs good color combination and some good effects to make it look attractive.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by rishita0205** [comment]
I have the skills to completely overhaul your user interface, making it look more professional without compromising on responsiveness. consider assigning this to me.
I have a UI idea in my mind 
![image](https://github.com/opencodeiiita/CalcDiverse/assets/140805496/c817b8db-dd51-486a-b1f6-0ea383d25e72)
![image](https://github.com/opencodeiiita/CalcDiverse/assets/140805496/a5066d87-5e05-4eea-98dc-6bd89480e41e)

**Comment by sanketshinde3001** [comment]
I'll add  neumorphism effect to these calculators so that it looks attractive .Also suitable for both dark and normal theme. I am attaching sample of this effect i created.
![Screenshot 2024-01-01 015847](https://github.com/Rakesh9100/CalcDiverse/assets/126979961/071dee40-4139-424e-b981-49f7b514fdea)


consider assigning this to me ...

**Comment by kom-senapati** [comment]
Also, the cards of each calculator are of different sizes. So whoever is contributing can make them all of same size.

**Comment by Rakesh9100** [comment]
@Shivangi015 Assigning you, Go ahead!!

**Comment by Yatin12527** [comment]
@Shivangi015 would u like to collaborate on this one ?

**Comment by Rakesh9100** [comment]
@Shivangi015 Status of your work pls

**Comment by Rakesh9100** [comment]
@rishita0205 Do you want to work?

**Comment by Rakesh9100** [comment]
@rishita0205 Are you there and want to get assigned?

**Comment by rishita0205** [comment]
@Rakesh9100 please assign me. I want to work

**Comment by Rakesh9100** [comment]
Okay then proceed @rishita0205 
Keep providing updates on discord and provide me your discord handle.

**Comment by rishita0205** [comment]
> Okay then proceed @rishita0205 Keep providing updates on discord and provide me your discord handle.

Ok! my discord handle is rishita0205

**Comment by rishita0205** [comment]
@Rakesh9100 I shared a UI idea should can u look at whether is it good or suggest some changes

**Comment by Rakesh9100** [comment]
Yes, UI seems eye catching but what is the second screenshot about? @rishita0205

**Comment by rishita0205** [comment]
@Rakesh9100, I have tried implementing the new UI kindly review

https://github.com/Rakesh9100/CalcDiverse/assets/140805496/e1048f19-b15d-4015-8075-4f6304370b90

**Comment by rishita0205** [comment]
@Rakesh9100 should I send the PR

**Comment by Rakesh9100** [comment]
Create the PR, I will check the deploy preview and suggest the changes @rishita0205

**Comment by rishita0205** [comment]
> Create the PR, I will check the deploy preview and suggest the changes @rishita0205

ok! I am sending the PR
