### ISSUE TITLE
[Feature] Graphing Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#280]
### Description

Equipped with a graphical display, these calculators are commonly used in mathematics and science for graphing functions and equations.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/ab38a49a-cbf2-4ce5-8077-05ef035a0fa7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
