### ISSUE TITLE
[Feature] Search box to make calculator finding easy

### ISSUE THREAD

**Issue by bhos1242** [Rakesh9100/CalcDiverse#282]
### Description

I have added a fully functional search box to make it easier to find desired calculator

### Screenshots

![Screenshot 2024-01-15 174700](https://github.com/Rakesh9100/CalcDiverse/assets/92811935/b80be133-3395-4934-b0c7-53984e25bc31)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by bhos1242** [comment]
Assign me I made this search box feature fully functional

**Comment by bhos1242** [comment]
https://deploy-preview-283--calcdiverse.netlify.app/

**Comment by Rakesh9100** [comment]
Issue is already open. Pls work on new issues @bhos1242
