### ISSUE TITLE
[Feature] Use ReactJS increase code reusability

### ISSUE THREAD

**Issue by Divyanshgarg-04** [Rakesh9100/CalcDiverse#284]
### Description

Buttons are also not properly arranged so its better to use ReactJs.

I would love to work on this issue under JWOC'24. Please assign this issue to me

### Screenshots

<img width="805" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/120127517/55c3db91-9069-4f31-a706-7db9e864daaa">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
As many begineers are also contributing to this project in open source programs, so I have kept this project simple using HTML, CSS  and JavaScript @Divyanshgarg-04
