### ISSUE TITLE
[Feature] Search Bar/Tab for searching calculator

### ISSUE THREAD

**Issue by actron-git** [Rakesh9100/CalcDiverse#287]
### Description

Search feature using keyword searching for finding user required calculator. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by actron-git** [comment]
@Rakesh9100  As you told and coding phase started so can I proceed with feature.

**Comment by actron-git** [comment]
I would like to work on that issue under JWOC

**Comment by Rakesh9100** [comment]
Go ahead @actron-git

**Comment by vinayak3010** [comment]
sir may you assign me this issue, as I am an IWOC contributor, I would like to work on this issue

**Comment by actron-git** [comment]
Sure @Rakesh1900 . Thank You...

**Comment by Rakesh9100** [comment]
@actron-git Status of your PR

**Comment by actron-git** [comment]
@Rakesh9100  I am working on it. Will completed by tomorrow.

**Comment by Rakesh9100** [comment]
You are being unassigned now @actron-git

**Comment by Prince-kushwaha-2004** [comment]
Sir kindly assign this to me under IWOC2024

**Comment by Rakesh9100** [comment]
Go ahead @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Sir i had completed this work i will send demo video in 5 min.

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Sir kindly suggest is it ok ?

**Comment by Rakesh9100** [comment]
Seens fine, but can you change the background look as why to expand it to the full screen width @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
sir do you want all the calculators to be in search div box?

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/df787351-73b3-47d5-b015-bf4a17088e3b)

No, I mean to ask like why to expand its background till full left and full right, is it looking good? @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
![Screenshot 2024-01-21 021609](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/5057142f-0eae-45ee-b786-78fa630089eb)

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Is it looking good?

**Comment by Rakesh9100** [comment]
Yes fine! You can give some text animation or styling to text "Search Calculator" similar to UI.
Place the placeholder in center and make it bold @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Ok sir i will complete it and then open PR.
