### ISSUE TITLE
[Bug]  Not proper Responsive on mobiles

### ISSUE THREAD

**Issue by HarshitSharma4** [Rakesh9100/CalcDiverse#288]
### Description

this page is not responsive on mobile screen

[Screencast from 2024-01-15 19-49-18.webm](https://github.com/Rakesh9100/CalcDiverse/assets/106171546/5dfc14a9-6b5e-4df3-9535-e1ff8356da01)

### Checklist

- [x] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [x] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program you have opened the issue for @HarshitSharma4

**Comment by pranjal12-web** [comment]
@Rakesh9100  I would like to work on this issue under JWoC 24
