### ISSUE TITLE
[Feature] Allow Navigation Between Button Columns Using "Enter" Key

### ISSUE THREAD

**Issue by TheDarkW3b** [Rakesh9100/CalcDiverse#289]
### Description

**Description:**
In https://calcdiverse.netlify.app/calculators/matrix-calculator/matrix for a big matrix, it is so hard to navigate between columns using mouse.
The current implementation lacks the ability to navigate between different button columns using the "Enter" key. Users commonly expect to use the keyboard for efficient navigation, and enabling the "Enter" key for this purpose would improve the overall user experience.

**Expected Behavior:**
Pressing the "Enter" key should allow users to shift focus and navigate between different button columns, facilitating keyboard-friendly interaction.

https://github.com/Rakesh9100/CalcDiverse/assets/54339318/ee0cf20a-102d-4ad2-ab96-12aa021610ea

**Actual Behavior:**
Currently, pressing the "Enter" key does not result in any navigation between button columns.

**PS: Assign me this issue under `iwoc2024`**
---

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @TheDarkW3b
