### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by Shivangi015** [Rakesh9100/CalcDiverse#29]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Changing Fonts is really important as the fonts which are used initially does not fit with the website.
please assign this issue to me, if you find this issue relevant for swoc'24.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by rishicds** [comment]
Hi, I fulfill all the prerequisites, please assign me this issue, thanks :)

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @Shivangi015

**Comment by Rakesh9100** [comment]
UI enhancement issue is already open.
