### ISSUE TITLE
[Feature] Word Count Calculator

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/CalcDiverse#291]
### Description

I propose adding four new features to enhance the functionality of the word calculator:

1. **Total Word Count:** Include functionality to count and display the total number of words in the provided text.
2. **Unique Word Count:** Implement a feature to count and display the number of unique words in the text.
3. **Average Word Length:** Calculate and display the average length of words in the given text.
4. **Export Results:** Allow users to export the calculated results in different formats (e.g., CSV, JSON) for further analysis or documentation.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Tholkappiar
