### ISSUE TITLE
[Feature] Rectangle Area calculator

### ISSUE THREAD

**Issue by Smritigit1202** [Rakesh9100/CalcDiverse#295]
### Description

User gives sides of the rectangle and we calculate the area of it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have 2D Shapes Calculator. Pls create new issues @Smritigit1202
