### ISSUE TITLE
[Feature] Binary to Decimal code converter

### ISSUE THREAD

**Issue by Smritigit1202** [Rakesh9100/CalcDiverse#296]
### Description

Binary to Decimal code converter

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Smritigit1202** [comment]
Please assign me this issue

**Comment by Rakesh9100** [comment]
Number System Calculator is already present in which this feature is available. Pls create new issues @Smritigit1202
