### ISSUE TITLE
[Feature] Carbon Footprint Calculator

### ISSUE THREAD

**Issue by muskan42** [Rakesh9100/CalcDiverse#297]
### Description

I wish to add a Carbon Footprint Calculator that calculates an estimate of an individual's carbon footprint based on the miles driven per year. Kindly assign me the issue under SWOC @Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls edit the issue description and tick only that open source program for which you have opened the issue @muskan42

**Comment by muskan42** [comment]
@Rakesh9100 so sorry for this negligence. Done

**Comment by Rakesh9100** [comment]
Go ahead @muskan42

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha
