### ISSUE TITLE
Adding the mean and median calculator

### ISSUE THREAD

**Issue by shivam101203** [Rakesh9100/CalcDiverse#298]
### Description

The mean and are most important for statistics calculation point of view .It enhance beauty of maths

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shivam101203** [comment]
To me

**Comment by Rakesh9100** [comment]
Statistics Calculator is already present. Pls go through the exisiting issues andd the present calculators on the website and then create new issues @shivam101203
