### ISSUE TITLE
[Feature] Required Download Time Calculator

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/CalcDiverse#299]
### Description

Our users often need to estimate the time it will take to download a file based on its size and their internet connection speed. To enhance our platform's usability, we propose the development of a "Required Download Time Calculator." This tool would allow users to input the file size and their internet speed, providing them with an estimate of the time required for the download.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @JiyaGupta-cs

**Comment by Rakesh9100** [comment]
Status of your PR @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 I am working

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Please review the PR

**Comment by pb0126** [comment]
Hi @Rakesh9100, I'm up for the feature. I'll implement the new feature and create the PR.
I'll create a function in JavaScript that will perform the task of time-required calculation.
This function assumes that the file size is in megabytes (MB) and the internet speed is in megabits per second (Mbps).
As per the input, it will calculate the time and return it in hours, minutes, and seconds format.
I'll link this function to the frontend where the user can enter the inputs and get the desired answer.

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 
I have ready made the code for this PR
Just need to need
I'm waiting for another PR made to be merged

**Comment by Rakesh9100** [comment]
Which PR you are waiting for to be merged @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100
It's closed now I just saw
I'll grab up this one again
I have done it's code already
Please assign me back

**Comment by Rakesh9100** [comment]
Okay, proceed @JiyaGupta-cs
