### ISSUE TITLE
Add Bill Split Calculator

### ISSUE THREAD

**Issue by lipika1911** [Rakesh9100/CalcDiverse#30]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Add Bill Split Calculator which will take the following 
INPUTS:
1. Total Bill
2. No. of person 

OUTPUTS:
Bill per person

Screenshot attached below, UI will be adjusted according to original UI of the website.Kindly assign this issue to me!

### Screenshots

<img width="464" alt="image" src="https://github.com/opencodeiiita/CalcDiverse/assets/142097736/187c6e61-2d57-408b-b49d-397e301d0812">

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning you, Proceed!! @lipika1911

**Comment by Shreya111111** [comment]
@lipika1911 complete the work within 3-4 days after assigning

**Comment by Rakesh9100** [comment]
@lipika1911 Status of your PR or you will be unassigned today

**Comment by kom-senapati** [comment]
I can work on this.

**Comment by Rakesh9100** [comment]
Proceed @kom-senapati
