### ISSUE TITLE
[Feature] Tip Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#301]
### Description

Helps calculate tips and split bills in a restaurant or other shared expenses.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/9639b554-f6dc-4890-8b5e-09e98c6588e2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Bill Split Calculator is already present @AbhineshJha
