### ISSUE TITLE
[Feature] Pregnancy Due Date Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#302]
### Description

Estimates the due date for a pregnant woman based on the first day of her last menstrual period.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Will it use formula of 2D or 3D shapes to calculate area and volume @AbhineshJha

**Comment by Rakesh9100** [comment]
No, already 2D Shapes Calculator is present @AbhineshJha

**Comment by AbhineshJha** [comment]
i can work on this calculator which can find output of Perimeter , area and volume !! @Rakesh9100

**Comment by Rakesh9100** [comment]
We have 3D shapes Calculator as well for volume @AbhineshJha

**Comment by AbhineshJha** [comment]
what about this @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay go ahead @AbhineshJha
