### ISSUE TITLE
[Feature] Love Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#303]
### Description

Love Calculator: Calculates a percentage score of love compatibility based on names or birthdates 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/82412456-4374-4b91-a384-a3161bb5847e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What is the logic or formula that you will use in this @AbhineshJha

**Comment by AbhineshJha** [comment]
hey ! @Rakesh9100 
The Love Calculator is typically created for entertainment purposes and doesn't have any scientific basis. The idea is to generate a random or pseudo-random love percentage based on the names or other input parameters.

**Comment by AbhineshJha** [comment]
i can style better for that calc..

**Comment by Rakesh9100** [comment]
Okay go ahead and create a better UI @AbhineshJha
