### ISSUE TITLE
[Documentation] Add a Readme in Word Count Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#304]
Add a Readme.md file in the `Word-Count-Calculator` folder describing it, tech stacks used and screenshots.

**Comment by AftabMankapure** [comment]
Assign me

**Comment by Rakesh9100** [comment]
Go ahead @AftabMankapure

**Comment by Rakesh9100** [comment]
For which open source program you want to get assigned @AftabMankapure

**Comment by AftabMankapure** [comment]
under  jwoc and iwoc

**Comment by pranjal12-web** [comment]
@Rakesh9100 Please assign this to me under JWoC24

**Comment by AftabMankapure** [comment]
@pranjal12-web  already done this issue

**Comment by Shrishkumar22** [comment]
Please assign me this issue under SWOC

**Comment by AftabMankapure** [comment]
Add label iwoc
