### ISSUE TITLE
[Bug] Visibility of Invalid BMI (00.00) on Landing Page

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#306]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/a38a44d9-6a97-48ef-b880-9dde12d79032)

BMI (00.00) should not be visible when landing on BMI Calculator website!!

**Comment by AftabMankapure** [comment]
Assign me under iwoc and jwoc

**Comment by TanushreeBorase** [comment]
I would like to work on this issue under JWoC'24 @Rakesh9100 .Please assign me.

**Comment by Rakesh9100** [comment]
You are going to be assigned to one issue @AftabMankapure

Go ahead @TanushreeBorase
