### ISSUE TITLE
[Bug] NaN handling in Trigonometric Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#308]
Display an alert to enter a valid angle or value when clicked on Calculate without entering any value in Trigonometric Calculator!!

**Comment by AftabMankapure** [comment]
Assign me under iwoc and jwoc

**Comment by TheDarkW3b** [comment]
can you assign me this one under `iwoc`?

**Comment by Rakesh9100** [comment]
IWOC or JWOC @AftabMankapure

**Comment by AftabMankapure** [comment]
assign me under iwoc

**Comment by Rakesh9100** [comment]
Okay proceed @AftabMankapure
