### ISSUE TITLE
[Style] UI Enhancement of Percentage To Fraction Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/CalcDiverse#309]
Beautify and enhance the user interface of Percentage To Fraction Calculator!!

**Comment by TanushreeBorase** [comment]
I would like to work on this issue @Rakesh9100 under JWOC'24. Please assign me this issue.

**Comment by AftabMankapure** [comment]
Assign me under JWoC'24

**Comment by Rakesh9100** [comment]
Proceed @TanushreeBorase
