### ISSUE TITLE
Change the currency converter ouput when the input is no a number

### ISSUE THREAD

**Issue by SaranshBangar** [Rakesh9100/CalcDiverse#31]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The currency converter shows "NaN" as ouput when anything other than a number is input in the field, instead it should show an error message

### Screenshots

https://github.com/opencodeiiita/CalcDiverse/assets/114401238/fb498e82-4003-4f19-bbe9-88ef0c4a80c9

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
@SaranshBangar Assigning you, Proceed!!

**Comment by SaranshBangar** [comment]
Ok sir @Rakesh9100

**Comment by SaranshBangar** [comment]
The above issue is solved in PR #32
