### ISSUE TITLE
[Feature] Adding Intelligence Calculator

### ISSUE THREAD

**Issue by shivam101203** [Rakesh9100/CalcDiverse#311]
### Description

It is a calculator which tells how smart are you and gave the ip(Intelligency points )to user.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shivam101203** [comment]
Please assign this issue to me under iwoc

**Comment by Rakesh9100** [comment]
Proceed @shivam101203

**Comment by shivam101203** [comment]
Okk sir

**Comment by shivam101203** [comment]
Please add label of iwoc for me

**Comment by shivam101203** [comment]
Assign it to me sir

**Comment by shivam101203** [comment]
please merge pr

**Comment by shivam101203** [comment]
Please merge the pr

**Comment by shivam101203** [comment]
now please merge it
