### ISSUE TITLE
[Style] Styling Try Now button

### ISSUE THREAD

**Issue by pranjal12-web** [Rakesh9100/CalcDiverse#313]
### What's the style idea?

When we hover on Try now button it tilts through certain angle, instead of that it will look better if color and background color changes on hovering

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete the assigned issues for every projects first @pranjal12-web

**Comment by AftabMankapure** [comment]
Assign me under iwoc

**Comment by Rakesh9100** [comment]
@AftabMankapure What enhancement will you do?

**Comment by krittika2004** [comment]
Hi @Rakesh9100 
I want style it like a glassmorphism with hover effect
Please assign it to me under JWOC 2024

**Comment by Rakesh9100** [comment]
@pranjal12-web Do you want to work

**Comment by pranjal12-web** [comment]
yes sir

**Comment by Rakesh9100** [comment]
Go ahead @pranjal12-web
