### ISSUE TITLE
[Feature] Add a search bar in header

### ISSUE THREAD

**Issue by Yatin12527** [Rakesh9100/CalcDiverse#314]
### Description

As the number of calculators are too many so one would want to search about the calculator and so a search bar can be added on in the navbar .
PS:- I'm not capable enough to solve this issue so it can be put into up for grab !!

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/134225415/3796ced2-e97f-457a-b3e5-770cc00d38c5)
this is rough preview of how it might look like.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a IWOC'24 contributor.
- [x] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open for this @Yatin12527
