### ISSUE TITLE
[Feature] Smith Number Calculator

### ISSUE THREAD

**Issue by sagarbee** [Rakesh9100/CalcDiverse#318]
### Description

A Smith number is a composite number whose sum of digits is equal to the sum of the digits of its prime factors, excluding the digit 1. In other words, a Smith number can be expressed as the product of its prime factors, and when you add up the digits of both the original number and its prime factors, the sums are the same.

Here's an example to illustrate a Smith number:

Let's take the number 85.

Prime factorize 85: 
85=5×17
Sum the digits of 85: 
8+5=13
Sum the digits of its prime factors (excluding 1): 
5+1+7=13
Since the sum of the digits of 85 is equal to the sum of the digits of its prime factors, it is a Smith number.
So, 85 is a Smith number because 
8+5=13
8+5=13, and 
5+1+7=13

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me under iwoc

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program for which you have opened the issue @sagarbee

**Comment by Rakesh9100** [comment]
@sagarbee Status of your PR

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha
