### ISSUE TITLE
[Style] Toggle Scroll Bar

### ISSUE THREAD

**Issue by Harshil-Gupta21** [Rakesh9100/CalcDiverse#320]
### What's the style idea?

We need to improve Scroll Bar. It will be activated on page scroll and hide when page scroll is paused like in github.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Harshil-Gupta21** [comment]
Please assign me this issue under Swoc'24

**Comment by Rakesh9100** [comment]
Pls attach any scrrenshot or video reference @Harshil-Gupta21
