### ISSUE TITLE
[Style] Back to top button

### ISSUE THREAD

**Issue by Harshil-Gupta21** [Rakesh9100/CalcDiverse#322]
### What's the style idea?

We need to improve Back to top button. The icon in that button doesn't look good and shows there is error. It needs to be fixed and better icon should repalce it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Which error it is showing that you are talking about @Harshil-Gupta21

**Comment by Harshil-Gupta21** [comment]
@Rakesh9100 it is not showing an error but  a box with a cross and I want to change it to a better icon like upward arrow

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/a6881703-0b76-40a1-b642-2ca3f123d7cf)

It is showing up arrow only, no cross mark @Harshil-Gupta21

**Comment by Harshil-Gupta21** [comment]
Ok sorry, so it would be a mistake for my laptop only. Sorry for the inconveniences.
