### ISSUE TITLE
[Feature] GST calculator

### ISSUE THREAD

**Issue by Harshil-Gupta21** [Rakesh9100/CalcDiverse#324]
### Description

A GST calculator which calculates amount of tax on the user input amount and displays the the final price and tax involved. Also, user can select the tax percentage.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Harshil-Gupta21

**Comment by Rakesh9100** [comment]
@Harshil-Gupta21 Status of your PR

**Comment by Harshil-Gupta21** [comment]
Will be done by today

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
