### ISSUE TITLE
[Feature] Adding Speed Calculator

### ISSUE THREAD

**Issue by TheDarkW3b** [Rakesh9100/CalcDiverse#326]
## Speed Converter
Implement a speed converter which allows users to conveniently convert speeds between different units such as meters per second (m/s) to kilometers per hour (km/h).

One can select the conversion into different units and vice versa.

**Please assign me this issue under `iwoc2024`**

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
Sir please assign me this issue under iwoc @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead and name your folder `Speed-Calculator` @TheDarkW3b

**Comment by akash05pal** [comment]
@Rakesh9100 assign this issue to me...i can enhance this issue
