### ISSUE TITLE
[Feature] Equivalent Resistance Calculator

### ISSUE THREAD

**Issue by Smritigit1202** [Rakesh9100/CalcDiverse#327]
### Description

Equivalent Resistance Calculator for series and parallel resistance 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Smritigit1202** [comment]
Please assign me

**Comment by Sakshamjain98** [comment]
please assign me this issue under iwoc as i can made the equivalent resistence calculator with improved ui @Smritigit1202

**Comment by Rakesh9100** [comment]
Go ahead @Smritigit1202

**Comment by Rakesh9100** [comment]
@Smritigit1202 Status of your PR pls

**Comment by Smritigit1202** [comment]
Working on it

**Comment by Rakesh9100** [comment]
Hey @Smritigit1202 You have just created PR in your own repo and merged yourself!!

**Comment by Rakesh9100** [comment]
[Check this](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) and work accordingly @Smritigit1202

**Comment by Smritigit1202** [comment]
Ok thanks

**Comment by Smritigit1202** [comment]
I have created a pull request , Please tell If I have done correct so far?

**Comment by Jenis07** [comment]
Can you please assign me this issue under JWOC?

**Comment by Rakesh9100** [comment]
Go ahead @Jenis07

**Comment by Smritigit1202** [comment]
@Rakesh9100 , I had already made PR for this issue

**Comment by Rakesh9100** [comment]
I have already left the comment on your PR to fix an error 3 days back but no response so you are unassigned @Smritigit1202

**Comment by Smritigit1202** [comment]
> I have created a pull request , Please tell If I have done correct so far?

I fixed the PR, by adding the project to main , and then commented this .. , I received no reply afterwards

**Comment by Rakesh9100** [comment]
Check your PR again by scrolling down @Smritigit1202

**Comment by Smritigit1202** [comment]
@Rakesh9100 , It shows merged and closed

**Comment by Smritigit1202** [comment]
I have created a new pull request

**Comment by Rakesh9100** [comment]
You are already unassigned, no acceptance @Smritigit1202 

Take care from the next time!!

**Comment by Sakshamjain98** [comment]
Sir please assign. Me this issue under iwoc

**Comment by Rakesh9100** [comment]
Status of your PR @Jenis07

**Comment by Rakesh9100** [comment]
@Sakshamjain98 Do you want to work

**Comment by Sakshamjain98** [comment]
Yes sir

**Comment by Rakesh9100** [comment]
Proceed @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Sir Done

**Comment by Rakesh9100** [comment]
Seperate the css codes to `style.css`and js codes to `script.js` for quality code and clear understanding @Sakshamjain98
