### ISSUE TITLE
[Feature] Ellipse and Hyperbola Calculator

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/CalcDiverse#328]
### Description

# Feature Request: Ellipse and Hyperbola Calculator

## Description
I would like to request the addition of a feature for an Ellipse and Hyperbola Calculator. This tool will allow users to input the parameters of an ellipse or hyperbola and calculate  properties such as the Area nd Perimeter.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Tholkappiar
