### ISSUE TITLE
Trignometric Values Calculator

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/CalcDiverse#329]
### Description

A seperate trignometric values calculator is required in this project

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
Sir please assign me this issue under iwoc @Rakesh9100

**Comment by Rakesh9100** [comment]
Trigonometric calculator is already present. Pls create new issues @Sakshamjain98

**Comment by Sakshamjain98** [comment]
ok sir
