### ISSUE TITLE
Grade Calculator

### ISSUE THREAD

**Issue by pankhuri92** [Rakesh9100/CalcDiverse#33]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a grade calculator to the website. This is a basic one I have created for it. I will enhance it more.

Please assign me the issue.

### Screenshots

![Screenshot 2023-12-30 191605](https://github.com/opencodeiiita/CalcDiverse/assets/138357063/9f3d6e8d-7b36-4cc8-a79b-5535a2f2943f)
![Screenshot 2023-12-30 192106](https://github.com/opencodeiiita/CalcDiverse/assets/138357063/3fa31b40-068c-451f-9489-31331df4e5cb)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sumugowda** [comment]
Hi there, I would like to work on this issue and I am a participant in SWOC24. Could you please assign me this?

**Comment by Rakesh9100** [comment]
Assigned, proceed!! @pankhuri92
