### ISSUE TITLE
Short URL Calculator

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/CalcDiverse#330]
### Description

The project need a calculator that calculate the short url of any link 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
Sir please assign me this issue under iwoc @Rakesh9100

**Comment by Rakesh9100** [comment]
What do you mean by calculating the short url @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Short url mean when a person want to short their long url they use our short url calculator that convert the long link into short link using api

**Comment by Rakesh9100** [comment]
Okay go ahead @Sakshamjain98
