### ISSUE TITLE
[Feature] Conductivity and Resistivity Calculator

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/CalcDiverse#331]
### Description

this project requires a conductivity and resistivity calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
please assign me this issue under iwoc @Rakesh9100

**Comment by akarshi19** [comment]
I would love to work on this issue under JWOC'24. Please assign this issue to me

**Comment by Rakesh9100** [comment]
Proceed @Sakshamjain98
