### ISSUE TITLE
[Style] Design a better UI for the Color Code Calculator

### ISSUE THREAD

**Issue by tarnibalgoher5** [Rakesh9100/CalcDiverse#333]
### What's the style idea?

The current design is very plain and the background looks very dull. 
https://calcdiverse.netlify.app/calculators/color-code-calculator/

Solution:
The background color can be improved and the design of the calculator can also be improved.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @tarnibalgoher5
