### ISSUE TITLE
[Feature] Environmental Calculator

### ISSUE THREAD

**Issue by muskan42** [Rakesh9100/CalcDiverse#339]
### Description

The Environmental Calculator will consist of :
1. Energy Consumption Calculator that estimates the annual energy consumption based on the monthly average energy consumption.
2. Water Usage Calculator that computes the annual water usage based on the average water usage per day.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @muskan42

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
I would like to contribute on this issue.
Kindly assign this to me under IWOC2024

**Comment by Rakesh9100** [comment]
Proceed @Prince-kushwaha-2004
