### ISSUE TITLE
Improve the contact page UI.

### ISSUE THREAD

**Issue by Owais24code** [Rakesh9100/CalcDiverse#34]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello @Rakesh9100 , the contact page looks less impressive and dull.
want to enhance the contact page.
please assign this issue to me under SWOC24.

### Screenshots

![Screenshot 2023-12-31 204312](https://github.com/Rakesh9100/CalcDiverse/assets/112776960/de18105a-1ef1-4a66-b909-06012dc84c4e)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by sanketshinde3001** [comment]
Hello @Rakesh9100 sir 

I want to modify this page.
1 ) I will add validation check in this form.
2) Make it responsive 
3) use  neumorphism effect so that it will look so much impressive.here is sample of this effect
4)Make UI better
5)Try to add animation in it.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/126979961/44b61907-8ec1-4451-be9a-4c363c793183)

**Comment by kom-senapati** [comment]
@sanketshinde3001 All of the listed items are issues themselves. Check if they exist or create a separate issue for each.

**Comment by Rakesh9100** [comment]
@Owais24code Assigning you, Proceed!!

**Comment by Owais24code** [comment]
@Rakesh9100 here is a small update I want to show on the contact page detailing.
Do let me know if LGTY, has any more specifications to add to it.
I haven't made any changes to the nav bar and footer section as I'm not aware of what to add to
![Screenshot 2024-01-02 145759](https://github.com/Rakesh9100/CalcDiverse/assets/112776960/4d64ec66-b43b-4dfb-8b91-953ff5871120)
 it.

**Comment by Rakesh9100** [comment]
Pls change the black coloured text to some colors for clear visual @Owais24code
