### ISSUE TITLE
[Feature] Add new measures in Length Calculator

### ISSUE THREAD

**Issue by SilviuPe** [Rakesh9100/CalcDiverse#340]
### Description

Hello Rakesh!! I come with a new feature. I would like to add new measures in the [Length Calculator](https://calcdiverse.netlify.app/calculators/length-calculator/length). More exactly: **hectometre** | **decametre** | **decimetre**.
In different places or environments we need those three measures, and it might be helpful to implement in the length calculator. Also, it will give the calculator more flexibility and it will be more useful for students.

### Screenshots

**How the length will be calculated with the new measures:**

![contribution](https://github.com/Rakesh9100/CalcDiverse/assets/108179264/a3bb8add-ec98-4090-804c-787f2d1a5187)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SilviuPe
