### ISSUE TITLE
[Feature] Adding Taylor Series Calculator

### ISSUE THREAD

**Issue by hemant933** [Rakesh9100/CalcDiverse#341]
### Description

This calculator allows users to input a mathematical function, a center point (c), and the number of terms in the series (n). It then calculates and displays the Taylor Series expansion around the given center point.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hemant933** [comment]
assign it to me

**Comment by Rakesh9100** [comment]
Proceed @hemant933

**Comment by hemant933** [comment]
i will work on it

**Comment by Rakesh9100** [comment]
Proceed and try to create your PR asap @hemant933

**Comment by Rakesh9100** [comment]
Why are you closing the PRs again and again, refrain from such activity else you will not be assigned to any further issues @hemant933
