### ISSUE TITLE
[Feature] Adding Baye's Theorem Calculator

### ISSUE THREAD

**Issue by hemant933** [Rakesh9100/CalcDiverse#342]
### Description

This calculator allows users to input the probability of A (P(A)), the probability of B given A (P(B|A)), and the probability of not A (P(~A)). It then calculates and displays the probability of A given B (P(A|B)).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hemant933** [comment]
assign it to me

**Comment by hemant933** [comment]
assign it to me i already complete it

**Comment by hemant933** [comment]
this will to

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha

**Comment by hemant933** [comment]
I generated this issue and I already done with my work why are u assigning
this to others

**Comment by Rakesh9100** [comment]
You have not completed that issue properly, PR is not merged @hemant933

**Comment by hemant933** [comment]
Bro , I generated a pr of Taylor series calculator yesterday with updated
screenshot of working calculator in readme.md file check it .

**Comment by Rakesh9100** [comment]
Check the comment in the new PR of yours @hemant933
