### ISSUE TITLE
[Style] Improve the style of the scroll bar

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [Rakesh9100/CalcDiverse#345]
### What's the style idea?

We can change the colors of the scroll bar, as it is a little odd as compare to the background.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What color you want to put? @Muhammad-Owais-Warsi

**Comment by Rakesh9100** [comment]
Which color you want to put? @Muhammad-Owais-Warsi

**Comment by Rakesh9100** [comment]
Go with the second one @Muhammad-Owais-Warsi
