### ISSUE TITLE
[Feature] Adding Flashcard Quiz Generator

### ISSUE THREAD

**Issue by hemant933** [Rakesh9100/CalcDiverse#349]
### Description

Create a flashcard quiz generator where users can input questions and answers. The calculator then generates interactive quizzes.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls work on other issues @hemant933
