### ISSUE TITLE
BMI calculator UI Update

### ISSUE THREAD

**Issue by VardaPanchal005** [Rakesh9100/CalcDiverse#35]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I will make a BMI calculator where if you add your age, height and weight it will tell your BMI and whether you are healthy or not.
Please assign this issue to me @Rakesh9100 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It is already present [Check](https://calcdiverse.netlify.app/calculators/bmi-calculator/bmi-calculator). Pls create another unique issue and I will assign you @VardaPanchal005

**Comment by Rakesh9100** [comment]
You can enhance UI of this calculator if you want to @VardaPanchal005

**Comment by VardaPanchal005** [comment]
okay i will also add age

**Comment by Rakesh9100** [comment]
Assigning you, proceed @VardaPanchal005

**Comment by Rakesh9100** [comment]
@VardaPanchal005 Status of your PR
