### ISSUE TITLE
Mortgage Calculator

### ISSUE THREAD

**Issue by TanushreeBorase** [Rakesh9100/CalcDiverse#351]
### Description

The Mortgage Calculator is an online tool designed for easy estimation of mortgage-related figures. Users input key details such as loan amount, annual interest rate, loan term, and down payment percentage. Upon clicking "Calculate," the tool swiftly generates results, presenting users with their monthly EMI, total amount payable, interest component, down payment, and loan term. With a visually appealing interface featuring a background image, it provides a user-friendly experience for individuals seeking quick insights into their mortgage planning.

### Screenshots

<img width="686" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/130696335/cdc2d841-64b0-48e5-8219-c930a624367c">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TanushreeBorase** [comment]
I would like to work on this under SWOC'24

**Comment by Rakesh9100** [comment]
This calculator is already present. Pls create new issues @TanushreeBorase
