### ISSUE TITLE
[Feature] Adding Calorie Burnt Calculator

### ISSUE THREAD

**Issue by shivam101203** [Rakesh9100/CalcDiverse#352]
### Description

It is used to check how fit are you and helps to define the calories burned for the day

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This calculator is already present <https://calcdiverse.netlify.app/calculators/calorie-intake-calculator/> @shivam101203

**Comment by shivam101203** [comment]
sir it is calorie intake and calorie burned means that amount calorie burnt  by exercise .

**Comment by Rakesh9100** [comment]
Okay proceed @shivam101203

**Comment by shivam101203** [comment]
thanks sir
