### ISSUE TITLE
[Feature] Electricity Bill Calculator

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/CalcDiverse#355]
### Issue Description
Electricity Cost Calculator  to accurately calculate electricity costs based on user-supplied units, time, and cost parameters.

### Proposed Solution
Introduce features that allow users to input the following parameters:
- **Units Consumed:** Users can input the total electricity units consumed.
- **Time Period:** Users can specify the time duration for which the units were consumed.
- **Cost per Unit:** Users can input the cost per unit of electricity in their region.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Tholkappiar

**Comment by Tholkappiar** [comment]
Ihave  done the changes ,  Due to merge conflicts I have pr-red another  commit which includes the changes , Thank you for the time and consideration. The recent pr #391 which contains the recent changes Thank you !

**Comment by Rakesh9100** [comment]
WHy are you closing the PRs again and again, pls refrain from such activity @Tholkappiar

**Comment by Tholkappiar** [comment]
yes sorry for that , but in my pov you have said to rename the folders after finishing the changes which is assigned for me and which is proposed in the Feat Issue, because of that and to resolving conflicts leads to this ! If i resolve the changes and commit those things in the main branch that also leads to unuseful commit and also confuse devs who will work on the branch ! Hope this clarification clears your enquiry ! If all done please conside to merge the PR ! Thank you for time and consideration. @Rakesh9100
