### ISSUE TITLE
[Feature] Adding Power Calculator

### ISSUE THREAD

**Issue by TheDarkW3b** [Rakesh9100/CalcDiverse#357]
### Description

Implement a power converter which allows user to conveniently convert one form of power into another.
Eg: 
* watt to joule/s 
* watt to horsepower(hp)
Etc
***
Assign me this issue under `iwoc2024`

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Status of your PR @TheDarkW3b

**Comment by TheDarkW3b** [comment]
> Status of your PR @TheDarkW3b

@Rakesh9100 its on my local machine and i am at college rn, i will put it today.
