### ISSUE TITLE
[Bug]  Incorrect Age Calculation for Future Dates 

### ISSUE THREAD

**Issue by KeyurGK** [Rakesh9100/CalcDiverse#358]
### Description

The current age calculation in the age calculator project produces inaccurate results for future dates. For example, if the date of birth is 21/06/1999 and we calculate the age for 21/01/2024, the result should be 24 years 7 months. However, the current implementation returns 25 years and -5 months.

### Screenshots

<img width="473" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/56074740/237e9078-0ef2-4fa2-8616-482b81608f44">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by KeyurGK** [comment]
Hey @Rakesh9100, Looking forward to contributing to the issue.

**Comment by GarvVirmani** [comment]
Pls assign me

**Comment by Rakesh9100** [comment]
Go ahead @KeyurGK

**Comment by Rakesh9100** [comment]
Status of your PR @KeyurGK

**Comment by KeyurGK** [comment]
> Status of your PR @KeyurGK 

Thanks for assigning. Will be pulling a request by end of Friday.

**Comment by KeyurGK** [comment]
> Status of your PR @KeyurGK

Pulled a request #467
