### ISSUE TITLE
Adding Country names to Currency Calculator

### ISSUE THREAD

**Issue by Manisha0207** [Rakesh9100/CalcDiverse#36]
### Prerequisites

- [x] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello, @Rakesh9100, sir. I would like to make some changes to the currency converter. There are certain aspects that are missing and can be further modified. Kindly assign this task to me, sir.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/135628219/30574d86-e3b0-4738-99c2-87b0fde55f78)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
@Manisha0207 Proceed!!

**Comment by Rakesh9100** [comment]
@Manisha0207 Status of your PR

**Comment by Manisha0207** [comment]
@Rakesh9100, sir, the work is currently in progress. I need a little more time to complete it. Please wait .

**Comment by Rakesh9100** [comment]
Its already been 7 days you are assigned to, can't provide you with the more and more time.

Pls tell me by when you will complete @Manisha0207

**Comment by Manisha0207** [comment]
Please give me time till tomorrow only @Rakesh9100  sir.

**Comment by Rakesh9100** [comment]
Okay fine but you will be unassigned after tomorrow if not done @Manisha0207

**Comment by hemant933** [comment]
assign  it to me plz

**Comment by Rakesh9100** [comment]
Have you gone through this issue properly that what enhancement you have to do @hemant933 

And you are working for which program?

**Comment by hemant933** [comment]
iwoc
