### ISSUE TITLE
[Bug] BMI Calculator doesn't show result for edge cases

### ISSUE THREAD

**Issue by jatinsinghkatal** [Rakesh9100/CalcDiverse#360]
### Description

When the BMI Calculator encounters an edge case , it fails to print the result whether the person is heathy or overweight and same is the issue for other reults involving edge cases. 

### Screenshots

![Screenshot 2024-01-18 005329](https://github.com/Rakesh9100/CalcDiverse/assets/135840816/f08d1eaf-990d-4179-b09b-5e6347935d48)

For example, here when we input all the values, the BMI is 24.97 and it isn't printing any result.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

I would like to solve the issue. Kindly assign me.

**Comment by Rakesh9100** [comment]
Proceed @jatinsinghkatal
