### ISSUE TITLE
[Feature] Addition of vector calculator

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/CalcDiverse#362]
### Description

@Rakesh9100 I would like to add a vector calculator . plz assign it to me under swoc'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @GhoshAditi
