### ISSUE TITLE
[Feature] Unit Converter Calculator

### ISSUE THREAD

**Issue by arrx-03** [Rakesh9100/CalcDiverse#363]
### Description

I would like to add a unit converter feature to this project which converts cm to m, km and vice-versa.  Please assign this to me under SWOC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
Please assign me this issue under iwoc...

**Comment by Rakesh9100** [comment]
Length Calculator is already present @arrx-03
