### ISSUE TITLE
[Bug] Contact form Validation issue

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/CalcDiverse#366]
### Description

Validation issue in Contact form while sending message. When we enter numbers in place of username it is accepting.

### Describe the change you think might work

we can restrict this by typing valid user name (characters ) in username field.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
ISSUE NO : 366

**Comment by student-aditipaliwal** [comment]
it was actaually  PR no : 413 it was actually ISSUE NO : 366

**Comment by student-aditipaliwal** [comment]
sir I have updated this and corrected it, please check

**Comment by Rakesh9100** [comment]
> sir I have updated this and corrected it, please check

Check the comment in your PR @student-aditipaliwal

**Comment by Rakesh9100** [comment]
> sir I have updated this and corrected it, please check

Pls check the comment in your PR @student-aditipaliwal
