### ISSUE TITLE
[Bug] Form validation issue in Love Calculator

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/CalcDiverse#367]
### Description

When we are entering numeric values in place of Names in Love Calculator, it is calculating percentage, but name should consist of characters only.

### Screenshots
![calc](https://github.com/Rakesh9100/CalcDiverse/assets/147225647/0cf0865a-c3e9-4d21-9651-987196290e34)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by student-aditipaliwal** [comment]
PLEASE ASSIGN THIS ISSUE TO ME

**Comment by Rakesh9100** [comment]
Proceed @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
SORRY SIR IN MY MAIL IT WAS PR :413 but it was actually ISSUE #367
