### ISSUE TITLE
[Style] UI appearance of every calculator

### ISSUE THREAD

**Issue by Shantanu-Meta** [Rakesh9100/CalcDiverse#369]
### What's the style idea?

We need to improve the user interface of the appearance of the each calculator. You can check it out.

https://github.com/Rakesh9100/CalcDiverse/assets/117648930/b9ea1e41-f1f2-4c77-9fe4-471f349fb1a6

Hey @Rakesh9100 , I hope this will catch you fine, let me know if any improvement is required, or I am ready to commit.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Looks good, Go ahead @Shantanu-Meta

**Comment by AftabMankapure** [comment]
Bro it look good ,
if color  'TRY NOW ' button  should be change  it look better  all try now button color should be related color 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/ba3b3cdb-85d9-4f13-bba2-f1494b0619d8)

**Comment by Shantanu-Meta** [comment]
Hey @Rakesh9100 , I have made the PR for this feature, could you please check it once ?
