### ISSUE TITLE
Addition of a Matrix calculator

### ISSUE THREAD

**Issue by SharonIV0x86** [Rakesh9100/CalcDiverse#37]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to propose the addition of a new feature. Addition of a matrix calculator which can perform the following calculations

# Basic Operations: 
Multiplication, addition, subtraction of matrices and determinant. 
# Inverse and Transpose: 
Calculating the inverse or transpose of a matrix.
# Error Handling: 
Ensuring the calculator handles invalid inputs gracefully.
# Optimization: 
Implementing efficient algorithms for large matrices like 4x4.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by kom-senapati** [comment]
I like this idea. I would also like to help if you want in making the calculator.

**Comment by Rakesh9100** [comment]
@SharonIV0x86 Assigning you, Go ahead!!

**Comment by Rakesh9100** [comment]
@SharonIV0x86 Status of your PR pls

**Comment by SharonIV0x86** [comment]
> @SharonIV0x86 Status of your PR pls

@Rakesh9100 Apology for the delay due to some unavoidable circumstances, I will complete the feature by 8th January.

**Comment by Rakesh9100** [comment]
Okay but do it on time @SharonIV0x86

**Comment by Rakesh9100** [comment]
Why have you closed the issue? Should I close your PR as well if you don't want to work @SharonIV0x86

**Comment by SharonIV0x86** [comment]
> Why have you closed the issue? Should I close your PR as well if you don't want to work @SharonIV0x86

Apology I must have closed it accidentally.

**Comment by Rakesh9100** [comment]
Okay fine @SharonIV0x86

**Comment by pankhuri92** [comment]
Hi @Rakesh9100 , I would like to take up the issue

**Comment by Rakesh9100** [comment]
Go ahead @pankhuri92

**Comment by pankhuri92** [comment]
Thanks!
