### ISSUE TITLE
[Feature] Adding Logo in Navbar

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/CalcDiverse#370]
### Description

I would like to add logo in this project. Please assign this issue to me

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/133951716/77d1371c-770e-4569-b369-5782f26f4d46)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
Sir please assign me this issue under iwoc

**Comment by vishapraj** [comment]
Please assign this issue to me sir.

**Comment by Rakesh9100** [comment]
@mansi1309 Status of your PR
