### ISSUE TITLE
[Feature] Adding Sunrise and Sunset Calculator

### ISSUE THREAD

**Issue by antilneeraj** [Rakesh9100/CalcDiverse#372]
### Description

Create a Sunrise and Sunset Calculator that enables users to determine the approximate times of sunrise and sunset based on specified longitude and latitude coordinates.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by antilneeraj** [comment]
Please set the necessary labels and kindly assign this issue to me under JWOC.

**Comment by Rakesh9100** [comment]
Go ahead @antilneeraj
