### ISSUE TITLE
[Feature] Implement Dark Mode

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/CalcDiverse#374]
### Description

we can add dark mode : to switsh the modes in top right most corner  : in nav bar 

### Screenshots

![Screenshot 2024-01-19 193048](https://github.com/Rakesh9100/CalcDiverse/assets/147225647/68c34a1a-7d2c-4adb-a1c1-6d12ea0aee38)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need for this as UI enhancement issue is open.

Pls work on your assigned issues @student-aditipaliwal
