### ISSUE TITLE
[Feature] Adding Infix Prefix Postfix Calculator

### ISSUE THREAD

**Issue by arrx-03** [Rakesh9100/CalcDiverse#375]
### Description

I would like to add a infix expression to postfix expression converter feature to this project. Please assign me under JWOC'24 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by prakharsingh-74** [comment]
@arrx-03 I would like to contribute on this issue Please assign it to me under JWOC 24

**Comment by Rakesh9100** [comment]
Can you create a calculator which includes these features instead of creating a seperate Infix to Postfix

1. Infix to postfix
2. Postfix to infix
3. Prefix to postfix, and vice versa
and so on.

@arrx-03

**Comment by arrx-03** [comment]
Yes I can do that

**Comment by Rakesh9100** [comment]
What name you will provide to this calculator?

And edit the issue description and tick only that open source program for which you have opened the issue @arrx-03

**Comment by arrx-03** [comment]
For easy understanding  infix-postfix-prefix calculator can be a good name

**Comment by arrx-03** [comment]
I have made changes to issue description

**Comment by prakharsingh-74** [comment]
@Rakesh9100 what is the deadline you have set on this project?

**Comment by Rakesh9100** [comment]
It depends but generally 2-3 days @arrx-03

**Comment by Rakesh9100** [comment]
It depends but generally 2-3 days @prakharsingh-74

**Comment by Rakesh9100** [comment]
> For easy understanding infix-postfix-prefix calculator can be a good name

Go ahead @arrx-03

**Comment by thesri** [comment]
@Rakesh9100 can i work on this>? please assign this issue to me

**Comment by thesri** [comment]
> @Rakesh9100 can i work on this>? please assign this issue to me

under jwoc 2024

**Comment by antilneeraj** [comment]
@Rakesh9100  As the assignee passed the 3 day limit and hasn't pushed any Pull Request.
Can you assign this issue to me under JWOC.

**Comment by prakharsingh-74** [comment]
> @arrx-03 I would like to contribute on this issue Please assign it to me under JWOC 24

@Rakesh9100 I have requested you first to assign me this issue please assign it to me under JWOC

**Comment by Rakesh9100** [comment]
Status of your PR @arrx-03

**Comment by Rakesh9100** [comment]
Complete your assigned issue first properly @prakharsingh-74 

Do you want to work @thesri

**Comment by thesri** [comment]
> Complete your assigned issue first properly @prakharsingh-74 
> 
> 
> 
> Do you want to work @thesri 

Yes yes I will try to do it. Please assign this to me under jwoc

**Comment by Rakesh9100** [comment]
Proceed @thesri

**Comment by thesri** [comment]
> Proceed @thesri

how many days will i get to work on this @Rakesh9100

**Comment by Rakesh9100** [comment]
2-3 days @thesri
