### ISSUE TITLE
Enhancement Of Footer 

### ISSUE THREAD

**Issue by CodeByRajeev** [Rakesh9100/CalcDiverse#38]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

**Enhancement Of Footer** 

This issue is to make the footer of the website much more responsive and interactive.
The following features will be updated in this issue:
- Interactive
- Responsive
- Social Media Links
- Social Media Icons
- Hover Effects 
- 
The changes before and after the improvements can be seen below in the **Screenshots** section.

#SWOC 

### Screenshots

**Original Footer :** 

![CalcDiverse Before](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/d13867e7-76af-4886-b3ef-b9b871ead736)

**Footer after making Improvements:**

![CalcDiverse After 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/f41cb4ea-4718-4adb-84aa-141ff4916c40)

**Footer with Hover Effects :**

![CalcDiverse After 2 logo hover](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/5cf74ad3-9d12-4963-91de-c59153b85180)
![CalcDiverse After 3 text hover](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/242b54be-40a7-439c-84b0-feacadbcce8f)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by CodeByRajeev** [comment]
I am a beginner and would love to put my learnings to make your project better. Hope I get this issue assigned and start contributing.

**Comment by Rakesh9100** [comment]
@CodeByRajeev Assigning, Proceed!!
