### ISSUE TITLE
[Bug] Footer is not responsive on phones

### ISSUE THREAD

**Issue by SaranshBangar** [Rakesh9100/CalcDiverse#383]
### What's the style idea?

We need to improve the responsive of the footer for smaller screen sizes

![image](https://github.com/Rakesh9100/CalcDiverse/assets/114401238/963cecd1-07a1-43a7-bd7f-655b92037777)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SaranshBangar

**Comment by SaranshBangar** [comment]
The above issue was solved in PR #427
