### ISSUE TITLE
[Bug] Rectangular Polar Calculator is not responsive

### ISSUE THREAD

**Issue by SaranshBangar** [Rakesh9100/CalcDiverse#384]
### What's the style idea?

We need to improve the overall style of the "Rectangular to Polar Calculator" and make it responsive for smaller screen sizes

![image](https://github.com/Rakesh9100/CalcDiverse/assets/114401238/caa723ff-4535-4898-89fc-92d0234173cf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me under iwoc

**Comment by Rakesh9100** [comment]
Go ahead @SaranshBangar

**Comment by Rakesh9100** [comment]
Status of your PR @SaranshBangar

**Comment by SaranshBangar** [comment]
I am working on it, will raise a PR by today @Rakesh9100

**Comment by SaranshBangar** [comment]
The above issue is solved in PR #433

**Comment by SaranshBangar** [comment]
@Rakesh9100 I will raise a PR by afternoon today

**Comment by Rakesh9100** [comment]
No need to raise a new PR, push the changes and make the commits in your opened PR only @SaranshBangar

**Comment by SaranshBangar** [comment]
The above issue is solved in PR #433

**Comment by Yuvraj960** [comment]
@Rakesh9100, I did Like to work on this issue

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960

**Comment by Rakesh9100** [comment]
Pls mention in the comment you would like to work for which open source program @Yuvraj960

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960
