### ISSUE TITLE
[Feature] Loan Calculator

### ISSUE THREAD

**Issue by Y-ash-h** [Rakesh9100/CalcDiverse#386]
### Description

 Calculates loan payments based on principal, interest rate, and term.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
EMI Calculator is already present @Y-ash-h
