### ISSUE TITLE
Today's Date in Age Calculator

### ISSUE THREAD

**Issue by ivanMehvish** [Rakesh9100/CalcDiverse#39]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Today's Date appears as 01 on the age calculator. I would like to fix the issue under SWOC'24.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/87938552/64da6791-a85f-454d-badd-f5107668c304)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigning you, Sart working!! @ivanMehvish
