### ISSUE TITLE
[Feature] Electricity Bill Calculator

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/CalcDiverse#390]
### Description

**Calculates the bill according to:-**

Selected Country
Typical Appliance
Power Consumption
Hours Of Use Per Day
And 1kWh Cost

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This issue is already present. Work on your assigned issues @JiyaGupta-cs
