### ISSUE TITLE
[Feature] Adding Expenditure and savings calculator

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/CalcDiverse#393]
### Description

There is the requirement of a calculator that calculate the expenditure and savings of a person.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

##Screenshot 

![IMG-20240124-WA0000.jpg](https://github.com/Rakesh9100/CalcDiverse/assets/137368917/3d28602b-d642-4b0b-9b74-27b50a55387e)

**Comment by Rakesh9100** [comment]
Status of your PR @Sakshamjain98

**Comment by Rakesh9100** [comment]
Proceed @Sakshamjain98

**Comment by Rakesh9100** [comment]
Pls attach the screenshot in the PR description @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Done sir
