### ISSUE TITLE
[Feature] Adding Taxi Fare Calculator

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/CalcDiverse#399]
### Description

Calculates the cost of a taxi ride based on key input parameters such as base fare, distance traveled, rate per kilometer, time spent, and rate per minute.

### Screenshots

![screenshots](https://github.com/Rakesh9100/CalcDiverse/assets/116893970/4469aa7b-658c-4973-86d0-f622d01f71da)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abidsyed25** [comment]
please assign me this issue. I am ready with a pull request.

**Comment by Rakesh9100** [comment]
Pls edit the issue description and tick only that open source program for which you have opened the issue @Abidsyed25

**Comment by Abidsyed25** [comment]
Changes done. Please add the IWOC label to the issue and assign it to me.

**Comment by Rakesh9100** [comment]
Proceed @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @Abidsyed25
