### ISSUE TITLE
Bug : Equal size of Calculators Display

### ISSUE THREAD

**Issue by CodeByRajeev** [Rakesh9100/CalcDiverse#40]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

****Bug** :  Equal size of Calculator**

In the present interface the different calculators are in different size which gives an ODD look for the user.

So as a minor change has been done to resolve this  issue. 
Though the change is a minute one it adds:
-  a good interface to the project 
- maintains regularity

The changes made can be seen in the below attached screenshots.

#SWOC 

@Rakesh9100 @Mannxxx I hope as a beginner I can make some meaningful contribution to the project. So I hope I get assigned to make the above said improvements.

### Screenshots

** Irregular sizes Before making changes**

![Irregular size before](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/1a567898-18f7-42e8-ba80-46882aad1ee0)

**Regular and interactive interface after making changes**

![Same size after 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/01e370ca-cfb3-4248-aad2-ed9010a6686d)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by CodeByRajeev** [comment]
@Rakesh9100 I hope as a beginner I can make some meaningful contribution to the project.I hope you kindly assign the issue to make the above said improvements.

**Comment by Rakesh9100** [comment]
Pls complete your previously assigned issue first @CodeByRajeev

**Comment by MonuGit9** [comment]
Claim

**Comment by puwun** [comment]
Can you please assign me this issue?

**Comment by CodeByRajeev** [comment]
Hey @MonuGit9 @puwun I hope you kindly understand that I have raised the above issue and also done the code and improvements, just waiting to get assigned and create the PR. I hope that you both understand and work on any better issue of your choice.

**Comment by pb0126** [comment]
Hi @Rakesh9100, I'm Interested in the above issue, please assign this to me.

**Comment by CodeByRajeev** [comment]
@Rakesh9100 Bhai as I completed the previous issue please do assign this issue as I would work on this.

**Comment by pb0126** [comment]
Hi @CodeByRajeev as you have been assigned to other issues and the maintainer has asked you to complete that, let others work on this issue until you complete the previous issue

**Comment by CodeByRajeev** [comment]
@pb0126 Thank you for understanding but I would like to inform you that the previous issue as been completed and merged. And this issue also has been completed. just waiting to get assigned.

**Comment by Rakesh9100** [comment]
Assigning you, proceed!! @CodeByRajeev

**Comment by CodeByRajeev** [comment]
Thank You @Rakesh9100
