### ISSUE TITLE
[Feature] 2D Distance Calculator

### ISSUE THREAD

**Issue by surendar-05** [Rakesh9100/CalcDiverse#401]
### Description

The calculators below can be used to find the distance between two points on a 2D plane.

### Screenshots
![output](https://github.com/Rakesh9100/CalcDiverse/assets/103345824/943a2970-378a-47a6-b021-846b491acaf4)

### Checklist

- [x] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [x] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [x] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by surendar-05** [comment]
please assign me this issue it is Completely working. I am ready with a pull request.

**Comment by surendar-05** [comment]
I attached the screenshot of the page 2D calculator assign this issue to me

**Comment by surendar-05** [comment]
It's completely working

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program for which you have opened the issue @surendar-05

**Comment by surendar-05** [comment]
@Rakesh9100 Changes done. Please add the JWOC label to the issue and assign it to me.

**Comment by Rakesh9100** [comment]
You want to work for JWOC or IWOC as you have checked IWOC in issue description @surendar-05

**Comment by surendar-05** [comment]
Sorry I change it wait

**Comment by surendar-05** [comment]
Successfully Changed

**Comment by surendar-05** [comment]
I work under JWOC'24

**Comment by surendar-05** [comment]
I am ready with a pull request.

**Comment by Rakesh9100** [comment]
Proceed @surendar-05
