### ISSUE TITLE
[Feature]: Add codeql workflow for Javascript

### ISSUE THREAD

**Issue by harmeetsingh11** [Rakesh9100/CalcDiverse#402]
### Describe your improvement idea or feature request

The repository contains code in `javascript` , it does not have workflow for code scanning. 

### How would you like to see it implemented?

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Would you like to work on this issue?
Yes

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need of this automation as I am checking every code being pushed and since many beginners are contributing, so it will create a problem for them.. Pls work on good issues @harmeetsingh11

**Comment by Rakesh9100** [comment]
No need of this automation as I am checking every code being pushed and since many beginners are contributing, so it will create a problem for them. Pls work on good issues @harmeetsingh11
