### ISSUE TITLE
[Feature] GitHub action workflow for greeting contributors

### ISSUE THREAD

**Issue by harmeetsingh11** [Rakesh9100/CalcDiverse#403]
### Description

The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

**Proposed Changes:**
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Expected Behavior:**
When contributors create new PRs or issues, the GitHub Action should automatically trigger and post a welcoming message, acknowledging their contributions.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am willing to work on this issue
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by praptisharma28** [comment]
Assign me this @rakesh9100 I will add!

**Comment by praptisharma28** [comment]
> Assign me this @Rakesh9100 I will add!

@Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @harmeetsingh11
