### ISSUE TITLE
[Feature] Add a Random Password Generator

### ISSUE THREAD

**Issue by Nemesis-AS** [Rakesh9100/CalcDiverse#405]
### Description

Add a calculator that generates a random password based on the given input constraints like password length, and the applicable characters

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/56386613/c6598a52-66fd-4975-895d-508523e66400)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Hey @Nemesis-AS This is not any calculator. Pls create other good issues @Nemesis-AS

**Comment by Rakesh9100** [comment]
Hey @Nemesis-AS This is not any calculator. Pls create other good issues!

**Comment by Nemesis-AS** [comment]
Alright, thanks
