### ISSUE TITLE
Modifications in age calculators .

### ISSUE THREAD

**Issue by sanketshinde3001** [Rakesh9100/CalcDiverse#41]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The current UI and features of age calculator is too low.
I want to add features like - 
1) By default find age from current time and date.
2) we can find age in years, months, weeks, minutes, seconds...
3) As per the age , it will display appropriate images so that UI will look best.

As i'm beginner and first time doing this stuff . It's my pleasure to assign this issue to me .
Looking for positive response.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/126979961/63a6107b-c4d1-4a36-ad34-86ecf21aa998)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
@sanketshinde3001 Proceed!!
