### ISSUE TITLE
[Style] Enhancement of contact us page

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/CalcDiverse#415]
### Description

UI of Contact us page does not match with website.
I would like to change styling of contact page and add some hover effect.

Kindly assign this to me under IWOC2024.
And suggest if you want to do some changes in the UI mentioned in Screenshots

### Screenshots

BEFORE
![Screenshot 2024-01-21 141454](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/42c8bd3f-6527-4bdc-bad2-e149c76da24d)
AFTER
![Screenshot 2024-01-21 141308](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/d4221dc9-cf9c-4a45-8ff9-55c7d9eb9e46)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Paarisha1** [comment]
Can I contribute in this

**Comment by Rakesh9100** [comment]
Proceed @Prince-kushwaha-2004
