### ISSUE TITLE
[Bug] Space in footer of Contact page

### ISSUE THREAD

**Issue by sksinha2410** [Rakesh9100/CalcDiverse#419]
### Description

There is some space between footer which shouldn't be there.
Screenshots

### Screenshots

<img width="1708" alt="Screenshot 2024-01-21 at 4 45 39 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/108980694/4945b647-b1fd-41bf-b9f0-62f95966d9f1">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sksinha2410** [comment]
please Assign this issue to me under JWOC ' 24

**Comment by Rakesh9100** [comment]
No space is present. Pls check again and create good issues @sksinha2410
