### ISSUE TITLE
3D shape volume calculator not working

### ISSUE THREAD

**Issue by sanketshinde3001** [Rakesh9100/CalcDiverse#42]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Issue - When we select any shape , there no functionality further. So i want to modify this to work properly . Also improve UI

### Screenshots

https://github.com/Rakesh9100/CalcDiverse/assets/126979961/446eec6b-353e-4f3f-b4ec-03858dfed7c0

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
@sanketshinde3001 Proceed!!

**Comment by Rakesh9100** [comment]
It was just a minor issue in script tag in the file. Pls work on other good issues @sanketshinde3001
