### ISSUE TITLE
[Bug] Font Family inconsistentcy between Home and Contributor Page

### ISSUE THREAD

**Issue by amansgith** [Rakesh9100/CalcDiverse#421]
### Description

# Problem
I have checked the Font Family of the navbar elements of both home page and Contributor page
And i've found that there is difference in font family applied of the navigation bar elements.

## Home Page 

<img width="960" alt="home" src="https://github.com/Rakesh9100/CalcDiverse/assets/104363876/50fa6362-2cae-491c-b54e-969bceb89bcd">

## Contributors Page

<img width="1001" alt="contrib" src="https://github.com/Rakesh9100/CalcDiverse/assets/104363876/c4c337bf-ab24-4ce0-99d1-1d9bfc884434">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by amansgith** [comment]
Please assign this issue to me because i have figured out the problem and can fix it quickly
Thank you

**Comment by Rakesh9100** [comment]
Proceed @amansgith
