### ISSUE TITLE
[Feature] Investment Risk Tolerance Calculator

### ISSUE THREAD

**Issue by prakharsingh-74** [Rakesh9100/CalcDiverse#425]
### What would you like to share?

I would like to create a calculator that can measure risk tolerance for the investment this calculator measures it on the basis of Age, Investment horizon (in years), Financial Knowledge and investment Experience. Financial knowledge and investment experience will be measure on the scale of (0 - 10).

if you like my idea please assign me this issue @Rakesh9100 under JWOC

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by prakharsingh-74** [comment]
@Rakesh9100 if you are giving this issue to me please label the issue with JWOC and difficulty tag.

**Comment by Rakesh9100** [comment]
Proceed @prakharsingh-74

**Comment by prakharsingh-74** [comment]
Please add the difficulty level also for this project
