### ISSUE TITLE
[Feature] Adding Pronic number calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#426]
### Description

Pronic number

The pronic number can be defined as the number which is a product of two consecutive numbers. Mathematically, the Pronic number can be represented as

N x (N + 1)

### Screenshots

After assign i can style it 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/80a1e2a5-8e39-47bf-b46f-8aaedd3f7f46)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me under IWOC

**Comment by Rakesh9100** [comment]
Go ahead @AftabMankapure

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program for which you have opened the issue @AftabMankapure

**Comment by AftabMankapure** [comment]
Assign me under IWOC

**Comment by Rakesh9100** [comment]
Go ahead @AftabMankapure
