### ISSUE TITLE
[Feature] Adding Projectile Motion Calculator

### ISSUE THREAD

**Issue by Ishaparte** [Rakesh9100/CalcDiverse#428]
### Description

User can calculate max.height,Range,Time of Flight.

### Screenshots

![swoc6](https://github.com/Rakesh9100/CalcDiverse/assets/113294672/5143a749-d0d8-409e-ac7c-0337277fd29a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Ishaparte** [comment]
@Rakesh9100 Plz assign this issue to me.

**Comment by Rakesh9100** [comment]
Proceed @Ishaparte

**Comment by GarvVirmani** [comment]
@Rakesh9100 assign me pls
From SWOC

**Comment by Rakesh9100** [comment]
Status of your PR pls @Ishaparte

**Comment by Ishaparte** [comment]
@Rakesh9100 it is almost done I will create pr by tonight.

**Comment by Ishaparte** [comment]
I have created a pr #479 plz check
