### ISSUE TITLE
[Feature] Adding vice versa feature in Rectangular To Polar Calculator

### ISSUE THREAD

**Issue by pranjal12-web** [Rakesh9100/CalcDiverse#429]
### Description

Design a calculator which would convert polar co-ordinates to rectangular and vice versa.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

@Rakesh9100 Please assign me under JWoC 24

**Comment by hemant933** [comment]
assign it to me under IWOC plz

**Comment by Isha1031** [comment]
Please assign this issue to me under JWOC

**Comment by pranjal12-web** [comment]
okay !!
@Rakesh9100  But it has only rectangular to polar conversion and not polar to rectangular. So can I add polar to rectangular to polar in the existing calculator ?

**Comment by Rakesh9100** [comment]
Yes, you can add vice versa in this existing calculator @pranjal12-web
