### ISSUE TITLE
[Style] Add Animations to the Website

### ISSUE THREAD

**Issue by SohanRC** [Rakesh9100/CalcDiverse#430]
### What's the style idea?

Add animations to the website. Such as scrolling animations and others . I want to work under this issue. Please assign me under JWOC 2024.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SohanRC** [comment]
@Rakesh9100 I want to work under this issue. Please assign me under JWOC 2024.

**Comment by SohanRC** [comment]
@Rakesh9100  Please look into this Issue.

**Comment by Rakesh9100** [comment]
Provide some demo screenshots or explain more which type of animations you want to add @SohanRC

**Comment by SohanRC** [comment]
@Rakesh9100  Like while opening the webpage , the navbar should come from top , the cards should be visible on scrolling down , like this

**Comment by Rakesh9100** [comment]
No need, pls work on other issues @SohanRC
