### ISSUE TITLE
[Feature] Adding clock hands angle calculator

### ISSUE THREAD

**Issue by hemant933** [Rakesh9100/CalcDiverse#432]
### Description

It will calculates the the angle between clock hands to specified user given time.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hemant933** [comment]
assign it to me

**Comment by Rakesh9100** [comment]
Proceed @hemant933
