### ISSUE TITLE
[Bug] Navbar not covering entire page on mobile screen

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/CalcDiverse#434]
### What's the style idea?

We need to improve the navbar to cover the full length of the screen on mobile devices.
![image](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/6ef83127-fc29-4261-b0e6-1b3e9f0daba6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @pb0126
