### ISSUE TITLE
[Feature] Update the Design of CTC calculator

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/CalcDiverse#435]
### Description

I want to update the design of the CTC calculator (Net - Salary Calculator). Please assign me this issue under IWOC

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This [Calculator](https://calcdiverse.netlify.app/calculators/net-salary-calculator/) is already present @SoumyadevSaha

**Comment by Rakesh9100** [comment]
This [Calculator](https://calcdiverse.netlify.app/calculators/net-salary-calculator/) is already present @SoumyadevSaha 

You can enhance its UI if you want!!

**Comment by Rakesh9100** [comment]
Assigning you, edit the issue title and description accordingly @SoumyadevSaha
