### ISSUE TITLE
Adding Cricket Calculator

### ISSUE THREAD

**Issue by GarvVirmani** [Rakesh9100/CalcDiverse#437]
### Description

I want to add a cricket calculator in which it calculates following :
1.Batsman Strike Rate
2.Bowlers Economy Rate
3.Required Run Rate
4.Projected Score
5.Target

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GarvVirmani** [comment]
Please assign me

**Comment by Rakesh9100** [comment]
Go ahead @GarvVirmani
