### ISSUE TITLE
CSS : Add transition to buttons

### ISSUE THREAD

**Issue by SaranshBangar** [Rakesh9100/CalcDiverse#44]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The buttons the home page do not have any transitions and it looks a bit weird.

Please assign the issue to me, I have already solved it in my forked repository

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by SaranshBangar** [comment]
Unfortunately, I was unable to add media in the issue, so I am adding it here


https://github.com/Rakesh9100/CalcDiverse/assets/114401238/df47fc2c-f15b-44e9-a65b-472531faba65

**Comment by Rakesh9100** [comment]
Proceed @SaranshBangar

**Comment by SaranshBangar** [comment]
The issus is solved in PR #48

**Comment by alirafatartist** [comment]
i can't make clone with your code with ssh to make pull requests with edits i made

**Comment by SaranshBangar** [comment]
The issue is solved in PR #56
