### ISSUE TITLE
[Feature] Addition of a Remainder Calculator

### ISSUE THREAD

**Issue by SuvayuN** [Rakesh9100/CalcDiverse#440]
### Description

I want to contribute to this project through JWOC'24 by adding a remainder calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yuvraj960** [comment]
Hello @Rakesh9100, I did like to work on this issue under SWOC24

**Comment by Rakesh9100** [comment]
Do you want to work @Yuvraj960

**Comment by Yuvraj960** [comment]
Yes offcourse, I did want to work

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960

**Comment by Yuvraj2005** [comment]
@Rakesh9100 , I have attached one image of the calc please check for the additions to do.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/82519210/47963a8e-67d3-4c95-88e5-5da87365b535)

**Comment by Yuvraj960** [comment]
@Rakesh9100 , I have attached one image of the calc please check for the additions to do.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/146326636/8925973a-1588-4210-b699-a73275931caf)

**Comment by Rakesh9100** [comment]
Looks fine, you can enhance the UI and make sure to handle NaN value when `Calculate` is clicked without entering any value @Yuvraj960
