### ISSUE TITLE
[Feature] Add voice command Feature to search Bar

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/CalcDiverse#443]
### Description

I will Add **voice command** Feature to search Bar to **search calculators** based on voice input.

Kindly assign this issue to me under **IWOC2024.**

### Screenshots

![Screenshot 2024-01-23 175029](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/9926d5a1-32ef-4e3a-8ffa-c91be6cf1c6b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Prince-kushwaha-2004
