### ISSUE TITLE
[Style] Enhance Definite Integral Calculator 

### ISSUE THREAD

**Issue by tarnibalgoher5** [Rakesh9100/CalcDiverse#447]
### What's the style idea?

We need to improve the look of the calculator,it's left aligned and the design is very simple and plain which can be made better 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead but make sure to enhance nicely, just some margins or aligning in center or similar small changes will not be considered @tarnibalgoher5

**Comment by tarnibalgoher5** [comment]
Okay, I'll make a small design and add the ss here, so you can also take a look at it. Then I'll proceed with the final changes

**Comment by Rakesh9100** [comment]
Status of your work pls @tarnibalgoher5

**Comment by tarnibalgoher5** [comment]
Sorry, I've been running a little late, will update you by tonight

**Comment by tarnibalgoher5** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/92452739/4a13801d-5705-48fc-aec1-bb7ffeaa4a4a)
this is the base idea i've thought of and will refine more wherever possible, if you suggest any changes I will incorporate those as well

**Comment by tarnibalgoher5** [comment]
@Rakesh9100 any update

**Comment by Rakesh9100** [comment]
Looks fine @tarnibalgoher5
