### ISSUE TITLE
[Feature] Adding General Root Calculator

### ISSUE THREAD

**Issue by TheDarkW3b** [Rakesh9100/CalcDiverse#448]
### Description

Change `Square Root Calculator` to `Root Calculator`
From
![image](https://github.com/Rakesh9100/CalcDiverse/assets/54339318/f7817e12-8f70-407f-8138-4271b42b693f)
to
![image](https://github.com/Rakesh9100/CalcDiverse/assets/54339318/fc86c2b0-22a6-4dd8-8eae-c6e78d40b30d)
***
**Current Behavior**:
The current implementation of the calculator only allows users to calculate square roots.

**Desired Behavior:**
Modify the calculator to support roots of any degree, allowing users to calculate roots up to 'n'

***
*Assign me this issue under `iwoc2024`*, and please keep the medium label as it still require both html and script to be changed + i fixed some minor problems too(It's kind of new calculator now).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Create a new Root Calculator and let the square root calculator be separate @TheDarkW3b

**Comment by Rakesh9100** [comment]
Create a new General Root Calculator and let the square root calculator be separate @TheDarkW3b
