### ISSUE TITLE
[Bug] Make Environmental calculator responsive

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/CalcDiverse#455]
### Description

Environmental calculator is not responsive for all size of screen.

Kindly assign this to me under IWOC2024.

### Screenshots

![Screenshot 2024-01-24 131335](https://github.com/Rakesh9100/CalcDiverse/assets/149922307/6c2a1e43-af8a-4a09-9aa6-e42aa8ad9de5)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Carry on @Prince-kushwaha-2004
