### ISSUE TITLE
[Style] Redesign the Contact us form

### ISSUE THREAD

**Issue by Aadhya-Sharma** [Rakesh9100/CalcDiverse#456]
### What's the style idea?

We need to improve the Contact form.
The current contact Us form lacks visual appeal. I would like to enhance the contact us form by making it more effective using efficient color scheme.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Aadhya-Sharma** [comment]
@Rakesh9100 Kindly assign me this issue.

**Comment by Rakesh9100** [comment]
What enhancement you want to do @Aadhya-Sharma

**Comment by Aadhya-Sharma** [comment]
I would like to redesign the UI of the form.

**Comment by Rakesh9100** [comment]
Okay proceed @Aadhya-Sharma
