### ISSUE TITLE
[Style] Enhance 2D Shapes Calculator and Color Code Calculator

### ISSUE THREAD

**Issue by Hansawani** [Rakesh9100/CalcDiverse#458]
### What's the style idea?

All the pages of the calculators are very basic and are not at all visually appealing. So i suggest that i get assigned this issue and i will work on the styling of as many calculator pages as i can.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Which all calculators you want to redesign @Hansawani

**Comment by Yuvraj960** [comment]
Hello @Rakesh9100, I want to redesign the Basic Calculator and the multiplication table calculator as it has very basic or as the page says very *Old School Type* Calculator

**Comment by Hansawani** [comment]
i can modify three calculators for now which are the 2D shapes calculator, age calculator, and colour code calculator

**Comment by Rakesh9100** [comment]
You can go with 2D Shapes and Color Code calculators, make sure to redesign with good UI @Hansawani

**Comment by Rakesh9100** [comment]
You can go with 2D Shapes and Color Code calculators, make sure to redesign with good UI @Hansawani 

You can open up new issues if you want to contribute @Yuvraj960

**Comment by Hansawani** [comment]
Great! I will make the requested changes and send you a pr as soon as i
change the UI.

**Comment by Hansawani** [comment]
<img width="960" alt="colorcode" src="https://github.com/Rakesh9100/CalcDiverse/assets/114403339/0cf20061-f949-45ef-97b2-91b80693a562">
i have changed the ui, made it more visually attractive. the heading is animated and the buttons have shadow effect on hovering. it is alright or there has to be some changes done?

**Comment by Hansawani** [comment]
<img width="960" alt="2dshapes" src="https://github.com/Rakesh9100/CalcDiverse/assets/114403339/096e4f09-79f7-444d-93ac-62ba01daf2a4">
New UI of 2d shapes calculator. the heading has animation and the button has shadow effect on hovering. i have changed the font sizes,font family and colours too.

**Comment by Yuvraj960** [comment]
@Rakesh9100 , Please accept my Issue of enhancement of UI of calculator
