### ISSUE TITLE
Add Simple Interest Calculator

### ISSUE THREAD

**Issue by sagarbee** [Rakesh9100/CalcDiverse#46]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Add New Calculator which will calculate the Interest Rate which will take  principal amount, rate of interest, and time period (in years) as inputs and calculates the simple interest

### Screenshots

![Screenshot (139)](https://github.com/Rakesh9100/CalcDiverse/assets/65588552/1e193397-038c-4bca-b985-128b53390aac)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by MonuGit9** [comment]
Claim

**Comment by sagarbee** [comment]
> Claim

Sorry for inconvenience. i will close this issue.

**Comment by Rakesh9100** [comment]
Same issue already exists. Pls work on other issues.

**Comment by Rakesh9100** [comment]
Do you want to work @sagarbee

**Comment by Rakesh9100** [comment]
Do you want to get assigned @sagarbee

**Comment by Yatin12527** [comment]
I'd like to take this

**Comment by Rakesh9100** [comment]
Go ahead  @Yatin12527
