### ISSUE TITLE
[Feature] Adding Bouncy Number Calculator 

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#462]
### Bouncy Number
A positive integer that is neither in increasing nor decreasing number is called a bouncy number. It means they bounce between increasing and decreasing. In other words, we can say that if the digits of the number are unsorted.

For example, 123742, 101, 43682, etc. We observe that in the given number's digits are neither increasing nor decreasing if we traverse from left to right, hence they are called bouncy numbers.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/9beba0b4-516a-487d-9106-51af86260669)

![image](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/3542ee63-5da4-452c-a150-3fe0f8307f71)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
assign me under iwoc

**Comment by AftabMankapure** [comment]
assign me under iwoc

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure
