### ISSUE TITLE
[Feature] Degree to Fahrenheit Calculator

### ISSUE THREAD

**Issue by siddhant-2002** [Rakesh9100/CalcDiverse#464]
### Description

we can add degree to ferenhite conversion calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by siddhant-2002** [comment]
please assign this to me @Rakesh9100

**Comment by Rakesh9100** [comment]
Temperature Calculator is already present. Pls work on new issues @siddhant-2002
