### ISSUE TITLE
[Feature] Book Reading Time Calculator

### ISSUE THREAD

**Issue by hoozierdaddy17** [Rakesh9100/CalcDiverse#465]
## **Working of the Calculator**

Estimates the time required to read a book based on the user's reading speed and the book's page count. Users input their average reading speed (pages per minute), and the calculator provides an estimate of the total time needed to finish the book. This can be helpful for readers planning their reading schedules or setting reading goals.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hoozierdaddy17** [comment]
Please assign this issue to me!

**Comment by Rakesh9100** [comment]
Proceed @hoozierdaddy17

**Comment by Rakesh9100** [comment]
PR status pls @hoozierdaddy17

**Comment by hoozierdaddy17** [comment]
In progress would be completed by weekend positively

**Comment by Rakesh9100** [comment]
Provide your PR by today else you will be unassigned @hoozierdaddy17

**Comment by hoozierdaddy17** [comment]
It is almost complete sorry I was extremely unwell last week the submission would be made by me tonight only
