### ISSUE TITLE
[Bug] Spelling error in Age Calculator Title

### ISSUE THREAD

**Issue by KeyurGK** [Rakesh9100/CalcDiverse#468]
### Description

The page title of age calculator has a spelling error which needs to be fixed.

### Screenshots

<img width="402" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/56074740/90256bc3-5e51-40f0-ab2b-1fad9ccd0066">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @KeyurGK

**Comment by vaishnavi192** [comment]
@Rakesh9100 hey can you plz add labels for DWOC'24. i want to work on issues under it. Thanks

**Comment by KeyurGK** [comment]
> Proceed @KeyurGK

Thanks for assigning

**Comment by KeyurGK** [comment]
@Rakesh9100 closed in #506

**Comment by KeyurGK** [comment]
@Rakesh9100 pulled a request in #507
