### ISSUE TITLE
CGPA to Percentage Convertor

### ISSUE THREAD

**Issue by sagarbee** [Rakesh9100/CalcDiverse#47]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Converting CGPA (Cumulative Grade Point Average) to a percentage involves understanding the grading scale of your institution. Typically, institutions use different scales, and the conversion formula may vary.  allow the user to choose the grading scale while entering the CGPA

### Screenshots

![Screenshot (139)](https://github.com/Rakesh9100/CalcDiverse/assets/65588552/50e4bd63-91cc-4b9e-af30-1db9902f6e65)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Don't open too many issues at once. First complete your first issue and then go for the second one. We have enough time for contributions @sagarbee

**Comment by MonuGit9** [comment]
Claim
