### ISSUE TITLE
[Feature] Trigonometric Function Graphing Calculator

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/CalcDiverse#470]
### Description

**I want to add a Trigonometric Function graphing calculator which gives the solution with a  graph as per the given function**

**For example -**
**sin, cos, tan, etc.**

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/140608790/6cff2d9b-7068-4274-a6a8-073c966790f2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @JiyaGupta-cs
