### ISSUE TITLE
[Style] GPA calculator is not responsive

### ISSUE THREAD

**Issue by DKSingh1604** [Rakesh9100/CalcDiverse#471]
### What's the style idea?

We need to improve the responsiveness of GPA calculator for smaller screens.

![Screenshot 2024-01-26 064108](https://github.com/Rakesh9100/CalcDiverse/assets/142477664/fe1fd7f0-bbba-4295-b9be-d1839a57076c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DKSingh1604

**Comment by Rakesh9100** [comment]
Tick the open source program you want to work for in the issue description @DKSingh1604

**Comment by Yuvraj960** [comment]
Hello @Rakesh9100, I did like to work on this issue under SWOC24

**Comment by GarvVirmani** [comment]
Pls assign me this issue.

**Comment by DKSingh1604** [comment]
@Rakesh9100 I have selected the correct program

**Comment by Rakesh9100** [comment]
Do you want to get assigned @DKSingh1604

**Comment by DKSingh1604** [comment]
Yes @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @DKSingh1604

**Comment by AftabMankapure** [comment]
@Rakesh9100  Assign me under JWOC

Current 
![CGPA](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/262089df-cfca-4ebb-bd34-da1aac3f2422)



new 


![GPA1](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/bbf81e1c-eaa0-4695-879f-cc3a935baec9)


![GPA2](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/cf692551-1bb1-4803-a527-dd4081483dcf)


![GPA3](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/c06a7a11-f1ac-40ba-b78e-14e3eeb0163e)

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure
