### ISSUE TITLE
[Bug] Twitter Facebook links not working in footer

### ISSUE THREAD

**Issue by Shivam250702** [Rakesh9100/CalcDiverse#476]
### Description

The links that you have provided of Twitter and facebook is a general link and not your account link.
This bug needs to be resolved.
Kindly assign this issue to me.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/103785990/0ac30373-99cd-4504-9f12-0af8565e8e4d)

![image](https://github.com/Rakesh9100/CalcDiverse/assets/103785990/f7ec754b-4e33-4dc6-b2f6-c39ee77c8aed)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Shivam250702
