### ISSUE TITLE
[Feature] Make the navbar translucent

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/CalcDiverse#483]
### Description

what i propose is that we can make the navbar translucent giving it a glossy glass pane effect along with little border shadows at the bottom
and little bit darkened as well to make the navbar contents stand out.

Please assign this issue to me . I would like to work on it.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/133951716/2e4ea549-55a0-413f-bb37-ced3f26bdbc8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @mansi1309

**Comment by mansi1309** [comment]
okay
