### ISSUE TITLE
[Bug] Invalid Input in Thala For A Reason Calculator

### ISSUE THREAD

**Issue by GarvVirmani** [Rakesh9100/CalcDiverse#486]
### Description

While entering 0 as a first digit it is calculating result which may
or may not be 7.
But it should give an alert Invalid Input.

### Screenshots

![IMG_20240127_004849](https://github.com/Rakesh9100/CalcDiverse/assets/131982472/f2e1a65b-cd49-494e-8deb-8520efa390e6)
![IMG_20240127_004857](https://github.com/Rakesh9100/CalcDiverse/assets/131982472/598f0883-0192-4894-a065-a65db7b2c349)
![IMG_20240127_004904](https://github.com/Rakesh9100/CalcDiverse/assets/131982472/6d3dac5d-6899-4696-b35b-b496fe41cb7a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @GarvVirmani
