### ISSUE TITLE
[Feature] Add About Us Page

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Rakesh9100/CalcDiverse#488]
### Description

while going across the website ,I saw that the "About Us" page was missing . So I would like to add it into the navigation bar rather than the content which is written on the homepage which makes it look ugly.

### Screenshots

![Screenshot (822)](https://github.com/Rakesh9100/CalcDiverse/assets/117037441/8cc2b8bc-d8c0-425e-99d3-81d5719c5bfb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  kindly assign me this issue .I want to work on it under SWOC'24.

**Comment by Rakesh9100** [comment]
Go ahead @Soumya6Tiwari

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  thanku

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Rakesh9100** [comment]
Complete your previous PR and assigned issue first @AftabMankapure

**Comment by SohanRC** [comment]
@Rakesh9100 Please assign me this issue under JWOC 2024.

**Comment by VIDHISHAK15** [comment]
@Rakesh9100 can u assign me this under swoc

**Comment by AftabMankapure** [comment]
@Rakesh9100 Assign me under JWOC
![ab1](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/e055587c-5317-4696-a5bd-a7d9a6781939)
![ab2](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/f973ece7-2c0c-4f43-a36b-4a5fe94f33de)

**Comment by Rakesh9100** [comment]
Do you want to get assigned @SohanRC

**Comment by SohanRC** [comment]
Yes , assign me under JWOC 2024

**Comment by Rakesh9100** [comment]
Do you have an idea or any sample UI design @SohanRC

**Comment by SohanRC** [comment]
> Do you have an idea or any sample UI design @SohanRC

At present I do not have any sample but I can try ! If you have any design , you can provide me too !

**Comment by Rakesh9100** [comment]
Okay, you can give a try and go for the best @SohanRC
