### ISSUE TITLE
[Bug] Search bar shrinking on small devices

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/CalcDiverse#492]
### Description

The search bar is shrinking on small screen, the placeholder text is hiding and the voice button is also not aligned right

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/4fb66079-df84-476a-a277-fbfcd4d4ab13)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by pb0126** [comment]
Hi @Rakesh9100 , Please assign this issue to me

**Comment by Rakesh9100** [comment]
Proceed @pb0126
