### ISSUE TITLE
[Feature] Adding Cube Root Calculator

### ISSUE THREAD

**Issue by shivamm-verma** [Rakesh9100/CalcDiverse#493]
### Description

# Prerequisites

-  I am an Open Source Contributor.
- I follow the Contributing Guidelines.

# Description📃

Adding **Cube Root Calculator** to the Website.

# Screenshots📸

Screenshots and screen recording is mentioned below

### Screenshots

# Screenshots
![imageSS](https://github.com/Rakesh9100/CalcDiverse/assets/98605616/071dbf46-e83f-42d4-b955-ee6f3547fe61)

# Screen Recording
[!vidSS](https://github.com/Rakesh9100/CalcDiverse/assets/98605616/517f2b5e-f378-473f-9b76-412f2a0101da)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shivamm-verma** [comment]
Please Assign this Issue to me, so that I can work on it.
@Rakesh9100

**Comment by Rakesh9100** [comment]
This [Calculator](https://calcdiverse.netlify.app/calculators/square-cube-calculator/) is already present @shivamm-verma

**Comment by Rakesh9100** [comment]
Proceed @shivamm-verma
