### ISSUE TITLE
[Bug] Hamburger Menu not working on contact and contributors page

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/CalcDiverse#494]
### Description

The Hamburger menu appears on small devices but its functionality has been compromised in both the contributor and Contact Us page

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/a9b100db-83d6-4c82-8874-a7ebd097d28b)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/33122840/964cbd4a-6035-462e-9761-25a7d969bae8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by pb0126** [comment]
Hi @Rakesh9100, Please assign this issue to me

**Comment by pb0126** [comment]
Hi @Rakesh9100, Please assign this issue

**Comment by Rakesh9100** [comment]
Go ahead @pb0126
