### ISSUE TITLE
[Bug]:Backend logic for sending emails

### ISSUE THREAD

**Issue by Niharika0104** [Rakesh9100/CalcDiverse#496]
## Bug Description

**Describe the bug:**
I noticed that the contact form has a `netlify` property, but I couldn't find any backend logic for sending emails upon form submission. Could you please confirm if there is already backend logic in place for sending emails upon form submission? If the logic is present but not visible, kindly close this issue.

**Expected behavior:**
Upon submitting the contact form, the system should send an email using backend logic. If the backend logic is not yet implemented, I am willing to fix this issue using Nodemailer and Google App Passwords.

**Detailed Explanation:**
I am interested in contributing to fix this issue. If the backend logic for sending emails is not implemented, I propose to use Nodemailer and Google App Passwords for this functionality. Please provide guidance or access to the backend code.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This project is hosted on netlify and so form submission is managed by that platform directly to my email. Pls work on other issues @Niharika0104
