### ISSUE TITLE
[Feature] Adding Complex Number Calculator

### ISSUE THREAD

**Issue by Aashi19234** [Rakesh9100/CalcDiverse#497]
### Description

I would like to add a complex number calculator which Handles complex numbers and their operations, such as addition, subtraction, multiplication, and division, and provides both rectangular and polar forms of the result.
If u like this idea, then please assign me this under JWOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Aashi19234

**Comment by Aashi19234** [comment]
@Rakesh9100 Please also add the difficulty label.

**Comment by Rakesh9100** [comment]
Difficulty tag will be added based on the quality of your PR and the work done @Aashi19234

**Comment by Aashi19234** [comment]
Okay Thanks for clearing @Rakesh9100
