### ISSUE TITLE
[Style] Enhance Basic Calculator and Multiplication Table Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#498]
### What's the style idea?

Hello @Rakesh9100, I want to redesign the Basic Calculator and the multiplication table calculator as it has very basic UI

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @Yuvraj960

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, I do you like this Basic Calculator UI:

![image](https://github.com/Rakesh9100/CalcDiverse/assets/146326636/49973f35-e68a-4b2d-be6d-c3b2437a10b2)

(Equipped with Both Dark and Light mode functionality.)

**Comment by Rakesh9100** [comment]
Looks good @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, If you need any type of changes in the Basic Calculator, please let me know as I am now re-designing the Multiplication calculator.

**Comment by Rakesh9100** [comment]
UI is good but make sure to not remove or reduce any functionalities that is present now such as sin, cos, ^, √, etc. @Yuvraj960
