### ISSUE TITLE
[Feature] Adding Fuel Efficiency Calculator

### ISSUE THREAD

**Issue by sumugowda** [Rakesh9100/CalcDiverse#499]
### What would you like to share?

**Description**
Implements a Fuel Efficiency Calculator that calculates fuel efficiency based on distance and fuel usage.
**Screenshots**
No response

### Additional information

Please assign me this issue

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This [Calculator](https://calcdiverse.netlify.app/calculators/fuel-efficiency-calculator/) is already present @sumugowda
