### ISSUE TITLE
[Style] Add icons to the navbar

### ISSUE THREAD

**Issue by rajpootjyoti700** [Rakesh9100/CalcDiverse#502]
### What's the style idea?

i want to add icon in navbar content nd also the design of navbar r thicky so i want to make it translucent by giving it glossy glass pane effect 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rajpootjyoti700** [comment]
plz assign this issue to me i want to work on it

**Comment by Rakesh9100** [comment]
Proceed to add icons @rajpootjyoti700

**Comment by Rakesh9100** [comment]
Status of your PR @rajpootjyoti700

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  I want to add the icons. kindly let me proceed further

**Comment by Rakesh9100** [comment]
Go ahead @Soumya6Tiwari

**Comment by Rakesh9100** [comment]
Pls mention the open source program you want to get assigned for @Soumya6Tiwari

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100 under swoc 2024

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100 ok

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100  I have created the pull request for this issue
