### ISSUE TITLE
[Feature] Add Fuel Cost Calculator

### ISSUE THREAD

**Issue by Hansawani** [Rakesh9100/CalcDiverse#504]
### Description

This calculator will estimate fuel costs for a trip based on distance, fuel efficiency, and fuel price.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to work on this @Hansawani

**Comment by Rakesh9100** [comment]
Proceed @Hansawani

**Comment by Rakesh9100** [comment]
Status of your PR pls @Hansawani

**Comment by Hansawani** [comment]
My exams are currently going on and I still have a little work left to do
on the pr. They are getting over tomorrow. Please give me a little time and
I'll try to complete it ASAP. Thank you.

**Comment by Rakesh9100** [comment]
You are assigned to this issue a week back @Hansawani

**Comment by prakharsingh-74** [comment]
@Rakesh9100 i would like to contribute on this issue under JWOC 24

**Comment by Hansawani** [comment]
I'm really sorry for the delay. My exams have been going on for the last
three days. Will try to complete it by this weekend. Really sorry

**Comment by Rakesh9100** [comment]
Pls note that today is the last day to complete your issue @Hansawani

**Comment by Hansawani** [comment]
Please check. I have sent the pr for this issue. Sorry for the delay
