### ISSUE TITLE
[Feature] Molecular Weight Calculator

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/CalcDiverse#509]
### Description

The Molecular Weight Calculator simplifies chemistry by computing the total atomic weights of elements in a given chemical formula, helping users swiftly determine the molecular weight of compounds.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/92045934/12cc55d2-dfaf-47d8-8472-a122a11baadb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @kom-senapati
