### ISSUE TITLE
[Feature] Adding Disarium Number Calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#512]
### Description

Disarium number

A number is said to be the Disarium number when the sum of its digit raised to the power of their respective positions is equal to the number itself.

For example, 175 is a Disarium number as follows

11 + 72 + 53 = 1 + 49 + 125 = 175
Some of the other examples of Disarium number are 89, 135, 518 etc.

### Screenshots

![Screenshot 2024-01-29 235338](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/09f9d7ea-efdb-4d7c-b066-be8c3476f7c3)

Style is just for demo

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
assign me under jwoc

**Comment by AftabMankapure** [comment]
assign me

**Comment by Rakesh9100** [comment]
Go ahead @AftabMankapure
