### ISSUE TITLE
[Feature] Adding a FAQ Page for the website

### ISSUE THREAD

**Issue by antilneeraj** [Rakesh9100/CalcDiverse#514]
### Description

I want to create a FAQ page that answers a variety of questions regarding the project.

### Screenshots

![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/98269887/12b54893-f02d-4899-a070-913d71cc3326)
![image](https://github.com/Spandan-Bhattacharya/Solve_it/assets/98269887/07468c10-2fa7-4913-ac97-029b8a7df992)

I'll be referencing the above template for the FAQs

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by antilneeraj** [comment]
@Rakesh9100 Please assign this issue to me under JWOC.

**Comment by Rakesh9100** [comment]
Go ahead @antilneeraj
