### ISSUE TITLE
[Feature] Add dark mode functionality to the website

### ISSUE THREAD

**Issue by Manishak798** [Rakesh9100/CalcDiverse#515]
### Description

Implementing dark mode functionality in the website will ease the user's switch between the modes and enhance the user experience. I am a SWOC'24 Mentor raising this issue for contributors.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yuvraj960** [comment]
@Rakesh9100, @Manishak798, Can you please elaborate this issue.
As I think the CalcDiverse Website is already designed in the Dark Mode. I think we have to choose a darker wallpaper of the website to make it whole Dark Mode without altering anything else.
Yes I think, We can implement the Light Mode for the Website.
Please address me regarding this.

**Comment by Manishak798** [comment]
> @Rakesh9100, @Manishak798, Can you please elaborate on this issue. I think the CalcDiverse Website is already designed in the Dark Mode. I think we have to choose a darker wallpaper for the website to make it whole Dark Mode without altering anything else. Yes I think, We can implement the Light Mode for the Website. Please address me regarding this.

 We need to implement a light mode functionality on the website and also if you can you should consider changing the background for the main landing page.

**Comment by Yuvraj960** [comment]
Ok @Manishak798 , I will implement it, assign this to me under SWOC24

**Comment by Rakesh9100** [comment]
Complete your assigned issues quickly and efficiently so that you can be assigned and move on to other issues @Yuvraj960

**Comment by SohanRC** [comment]
@Rakesh9100 Please assign me this issue under JWOC 2024.

**Comment by Yuvraj960** [comment]
@Rakesh9100, I am completing my issues as fast as possible as I need to merge more and more PRs.

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, I have found the perfect light background for the website, just suggest me should I change the design of the cards also, as rest everything I am changing.
![image](https://github.com/Rakesh9100/CalcDiverse/assets/146326636/5b229958-5d64-4fe5-be83-2353a3a0ee2e)

If you take my opinion, then no changes are needed in the cards, but if you think any possible changes can be done in the cards in this background, then please let me know.

**Comment by Rakesh9100** [comment]
Looks good. You may proceed with making color adjustments to the text as much as possible as long it is visually appealing @Yuvraj960

**Comment by Gokilp** [comment]
please assign to me

**Comment by Rakesh9100** [comment]
Do you want to work @Gokilp

**Comment by Rakesh9100** [comment]
Do you want to be assigned under GSSoC @Gokilp

**Comment by Premonvitha-Sai** [comment]
@Rakesh9100  please assign to me I would like to work under GSSOC'24

**Comment by Rakesh9100** [comment]
Go ahead @Premonvitha-Sai

**Comment by Rakesh9100** [comment]
Are you working @Premonvitha-Sai

**Comment by Premonvitha-Sai** [comment]
@Rakesh9100  Yeah, I'm working on it.

**Comment by DiwareNamrata23** [comment]
I'm interested to work on this issue . I request @Rakesh9100 to assign this issue to me

**Comment by Gokilp** [comment]
Im interested working the issue please asssign to me

**Comment by Premonvitha-Sai** [comment]
Hi @Rakesh9100 I have done some changes regarding dark mode functionality.

https://github.com/Rakesh9100/CalcDiverse/assets/96629891/0f0841a5-1e8b-4516-ba30-daf24ca6d81b

Is it ok?

**Comment by Rakesh9100** [comment]
It's not clear properly, pls make video by screen recording by showing both the modes light and dark nicely and by scrolling all the pages @Premonvitha-Sai

**Comment by Premonvitha-Sai** [comment]
<img width="959" alt="Screenshot 2024-06-07 020101" src="https://github.com/Rakesh9100/CalcDiverse/assets/96629891/e1fb99c0-f0cb-43de-9ebd-397c6543f176">
I have add this background for light mode

**Comment by Premonvitha-Sai** [comment]
![Uploading Screenshot 2024-06-07 020119.png…]()
This one for dark mode.

**Comment by Premonvitha-Sai** [comment]
<img width="959" alt="Screenshot 2024-06-07 020119" src="https://github.com/Rakesh9100/CalcDiverse/assets/96629891/c46cfc1a-0fe9-4eeb-8799-a28e28057638">
This one for dark mode.

**Comment by Premonvitha-Sai** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/96629891/f9f05117-42f9-4f0c-9824-99fbc193142e

This is the implementation.

**Comment by Gokilp** [comment]
please assign to me

**Comment by Premonvitha-Sai** [comment]
@Rakesh9100 could you please label the issue with level 1,2,3. It would be really helpful.

**Comment by Rakesh9100** [comment]
Can you clarify which is the light and which one is the dark mode by changing the toggle icon to something good such as sun and moon @Premonvitha-Sai

**Comment by Premonvitha-Sai** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/96629891/46388cfb-4a9e-4088-8c79-25884a161125

@Rakesh9100 I have done the changes using sun icon for light mode and moon icon for dark mode.

**Comment by Rakesh9100** [comment]
Create your PR, will check the deploy preview and suggest changes if needed @Premonvitha-Sai

**Comment by Premonvitha-Sai** [comment]
@Rakesh9100 I have created PR.

**Comment by Rakesh9100** [comment]
Do you want to work @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
Yes

**Comment by Rakesh9100** [comment]
Pls share your brief idea on how will you implement dark mode on this website @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
In dark mode the whole website would be black or any dark color and the contents will be lighter so that it will get easier to see also where will be color gradient I will try to match out with light smoothing colors.

**Comment by Rakesh9100** [comment]
Sure, go ahead and show me @DiwareNamrata23

**Comment by Rakesh9100** [comment]
Provide your PR @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
@Rakesh9100 Providing the pr by today itself
