### ISSUE TITLE
[Feature] Adding PR template

### ISSUE THREAD

**Issue by pinak22dhir** [Rakesh9100/CalcDiverse#519]
### Description

can i add pr template ,assign this to me
it is for contributors to clearly mention the request

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
PR template is already present @pinak22dhir
