### ISSUE TITLE
[Feature] Adding Neon Number Calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#520]
### Description

A neon number is a number where the sum of digits of the square of the number is equal to the number. The task is to check and print neon numbers in a range.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me under jwoc

**Comment by AftabMankapure** [comment]
Assign me under jwoc

**Comment by AftabMankapure** [comment]
Assign me under JWOC 


bro it possible to change label already completed PR
i want JWOC label instead of IWOC
for PR number
https://github.com/Rakesh9100/CalcDiverse/pull/517
https://github.com/Rakesh9100/CalcDiverse/pull/461
https://github.com/Rakesh9100/CalcDiverse/pull/365
https://github.com/Rakesh9100/CalcDiverse/pull/323
https://github.com/Rakesh9100/CalcDiverse/pull/317

pls do it

**Comment by Rakesh9100** [comment]
Are the points being displayed on your IWOC dashboard or leaderboard, I suppose yes @AftabMankapure

**Comment by Rakesh9100** [comment]
Do you want to work @AftabMankapure

**Comment by AftabMankapure** [comment]
Yes assign me under jwoc

**Comment by AftabMankapure** [comment]
Assign me

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure
