### ISSUE TITLE
[Feature] Adding Circular Prime Calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#521]
### Description

Circular Prime : A prime number is said to be a circular prime if after any cyclic permutations of the digits, it remains a prime.
Examples: 

Input :  n = 113 
Output : Yes
All cyclic permutations of 113 (311
and 131) are prime. 

Input : 1193
Output : Yes

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
assign me under jwoc

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Rakesh9100** [comment]
Complete your assigned issues first @AftabMankapure

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by AftabMankapure** [comment]
Assign me under JWCO @Rakesh9100

**Comment by AftabMankapure** [comment]
Assign me under JOOC

**Comment by Rakesh9100** [comment]
Don't comment again and again, you will be assigned on completion of previously assigned issue @AftabMankapure

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure
