### ISSUE TITLE
[Feature] Add new results in Word Count Calculator

### ISSUE THREAD

**Issue by SilviuPe** [Rakesh9100/CalcDiverse#522]
### Description

I would like to add new outputs result in the [Word Count Calculator](https://calcdiverse.netlify.app/calculators/word-count-calculator/). The outputs will be "the shortest word count" showing the shortest word count and, of course, the "longest word count". showing the longest word count. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SilviuPe
