### ISSUE TITLE
[Bug] Negative result in Electricity Bill Calculator

### ISSUE THREAD

**Issue by GarvVirmani** [Rakesh9100/CalcDiverse#523]
### What would you like to share?

Units and Rate can't be negative in Electricity bill calculator.
It should give an alert for that input.
![IMG_20240127_175729](https://github.com/Rakesh9100/CalcDiverse/assets/131982472/793e9170-d9ab-4a33-9187-fd48f9a0198f)
![IMG_20240127_175735](https://github.com/Rakesh9100/CalcDiverse/assets/131982472/b966c62f-413a-4276-a529-f9d781ab5af6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @GarvVirmani
