### ISSUE TITLE
[Feature] Adding CGPA Percentage Calculator

### ISSUE THREAD

**Issue by srshah27** [Rakesh9100/CalcDiverse#524]
### Description

I would like to build Percentage to CGPA calculator which will take the users current CGPA as input and return the equivalent percentage. Based on the guidelines provided by mumbai university.

If you like this idea, then please assign me this under SWOC'24

### Screenshots

![conversion-Circular_2017](https://github.com/Rakesh9100/CalcDiverse/assets/83776946/05e7b7c9-ef88-482b-93e9-0cdb45219c9f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [x] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @srshah27
