### ISSUE TITLE
[Feature] Typing Speed Calculator

### ISSUE THREAD

**Issue by AlefiyaAbbas** [Rakesh9100/CalcDiverse#525]
### Description

A calculator  which provides users with a string as goal to type and starts a timer when the user clicks on the input box, and stop the timer when the input string matches the provided string. Upon completion, the calculator will calculate and display the typing speed in units of:
- words per second (words/sec) 
- characters per second (characters/sec).
    
Please assign this to me. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AlefiyaAbbas
