### ISSUE TITLE
[Feature] Resistor color code calculator

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/CalcDiverse#527]
### Description

I want to add a Resistor color code calculator which calculates the Resistance according to the color
that

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/140608790/455f66cb-6f44-4f4e-9341-9f7f0e0d7bc2)

![image](https://github.com/Rakesh9100/CalcDiverse/assets/140608790/f3efaf11-2486-4048-85e5-d37930f95daf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
I suppose this [Calculator](https://calcdiverse.netlify.app/calculators/4-band-resistance-calculator/) is already present. Is yours different from this? @JiyaGupta-cs
