### ISSUE TITLE
Enhancement In The Navbar Section Including Its Font And BackGround Color

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/CalcDiverse#53]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I Would Like To Enhance  The Navbar Section Including Its Font And BackGround Color

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
Proceed!! @Kapileswar-Moharana

**Comment by Shreya111111** [comment]
@Kapileswar-Moharana have u completed ur work and created PR

**Comment by Rakesh9100** [comment]
@Kapileswar-Moharana Status of your PR

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Almost Ready
