### ISSUE TITLE
[Feature] Home Renovation Budget Calculator

### ISSUE THREAD

**Issue by GarvVirmani** [Rakesh9100/CalcDiverse#531]
### Description

Input materials cost, labor cost, and desired finishes to calculate the total budget. Responsive and user-friendly design.

### Screenshots

![IMG_20240203_184907](https://github.com/Rakesh9100/CalcDiverse/assets/131982472/951ec6e2-0dda-441a-9677-818fd99f55e7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @GarvVirmani
