### ISSUE TITLE
Create A Attractive Footer With Proper Hover Property and Functions

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/CalcDiverse#54]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I Would Like To Modify The Footer With Fully Responsiveness And Proper Hover Property.

### Screenshots

![Screenshot 2024-01-02 122724](https://github.com/Rakesh9100/CalcDiverse/assets/129049677/fd63415d-5daf-457a-b147-8c28e59c2485)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
Footer is changed now as previous issue already existed @Kapileswar-Moharana
