### ISSUE TITLE
[Style] Enhance Percentage Calculator UI

### ISSUE THREAD

**Issue by prajwalghurde** [Rakesh9100/CalcDiverse#541]
### What's the style idea?

We need to improve Percentage calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

### Screenshot

![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/99469396-de75-4e4c-9dea-6b37dc0cd6e4)

**Comment by Rakesh9100** [comment]
Pls attach the issue supporting screenshots @prajwalghurde

**Comment by VIDHISHAK15** [comment]
@Rakesh9100 can you assign me this task under swoc

**Comment by AftabMankapure** [comment]
@Rakesh9100  Assign me under JWOC
![PC](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/09cc688f-4a2f-4ea7-8617-63838d9e88ca)

**Comment by VIDHISHAK15** [comment]
yeah can u assign me under swoc

**Comment by Rakesh9100** [comment]
Proceed @VIDHISHAK15
