### ISSUE TITLE
[Feature] Probability Calculator

### ISSUE THREAD

**Issue by NirbhayTiwari15** [Rakesh9100/CalcDiverse#546]
### Description

@Rakesh9100  I can add probability calculator, in which different probability such as chances of event to occur , chances of event not to occur, chances of one event occur and one event does not occur,etc. can be calculated.
Please assign me this under SWOC.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @NirbhayTiwari15
