### ISSUE TITLE
[Feature] Currency value calculator

### ISSUE THREAD

**Issue by NirbhayTiwari15** [Rakesh9100/CalcDiverse#547]
### Description

@Rakesh9100 I can add Currency value calculator, in which one countries currency value can be converted into another countries currency value.
Assign me  under this SWOC. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by prakharsingh-74** [comment]
@Rakesh9100 I would like to contribute in this issue under JWOC

**Comment by Rakesh9100** [comment]
This [Calculator](https://calcdiverse.netlify.app/calculators/currency-calculator/currency-calculator) is already present. Pls create and work on new issues @NirbhayTiwari15
