### ISSUE TITLE
[Feature] Adding Stress and Strain Calculator

### ISSUE THREAD

**Issue by Imbiber** [Rakesh9100/CalcDiverse#550]
### Description

I found out , this repo didn't contain stress and strain calculator, I would like to work on that and add that feature.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Imbiber
