### ISSUE TITLE
[Feature] Adding Vowel Consonant Calculator

### ISSUE THREAD

**Issue by ROSHNEEGOUDA** [Rakesh9100/CalcDiverse#552]
### Description

Calculator which counts number of vowels and consonants in a given paragraph. 

### Screenshots

![WhatsApp Image 2024-02-06 at 02 59 40](https://github.com/Rakesh9100/CalcDiverse/assets/120122742/427f0025-be45-4010-bd6b-4b6ac4ed1e96)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ROSHNEEGOUDA** [comment]
@Rakesh9100 Please assign this to me to add this feature (SWOC'24).

**Comment by Rakesh9100** [comment]
Proceed @ROSHNEEGOUDA
