### ISSUE TITLE
[Feature] Contact Page

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#553]
### Description

The current contact page, as I can guess from the Code didn't send the responses of the user to the website owner.
(If it sends and Please close the Issue). I have one Method of sending the user responses directly to the owner's mail.
That is by the use of SMTPJs. Every response will be sent to Mail registered and entered in the Code.

For the functionality to work, I need a Elastic Email account setup on the mail id on which we want to receive the mails of the responses. By implementation of this in the Website, We can collect the feedback data of the user experiencing our website for first time and can improve the Website according to it.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/146326636/30119916-79ac-457b-852c-044c7e5df024)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Mails are being received by me as Netlify manages the form responses @Yuvraj960
