### ISSUE TITLE
[Feature] Add Days Until Deadline Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#557]
### Description

Count down days until project deadlines or due dates.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Hey @Yuvraj960 Don't  open too many issues at once. You will not be assigned to any of them and also get banned from the program for this behaviour!!

**Comment by Yuvraj960** [comment]
Sorry @Rakesh9100 ,I was not aware of this, Please assign me two issues a time and rest as standby,  I will cover them all as fast as possible

**Comment by Yuvraj960** [comment]
@Rakesh9100, after Network Bandwidth calculator, please assign me this issue.

**Comment by kamalesh-og** [comment]
Hi @Yuvraj960 , I would like to work on this project 
Can you please assign it to me?
Thank you!

**Comment by Yuvraj960** [comment]
@Rakesh9100  Assign this issue to me under GSSoC24

**Comment by Rakesh9100** [comment]
Assigning you, go ahead @kamalesh-og
