### ISSUE TITLE
[Feature] Add Palindrome Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#558]
### Description

Inputs a string or a number and return True or False based on, it is palindrome or not

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kom-senapati** [comment]
I can work on this.

**Comment by prakharsingh-74** [comment]
@Rakesh9100  i would like to work on this issue under jwoc

**Comment by Rakesh9100** [comment]
Do you want to work @kom-senapati

**Comment by Yuvraj960** [comment]
@Rakesh9100, N-sided polygon calculator complete.
I request you to please assign me the issues that are opened by me, I will complete those faster as not much time needed in those issues that I have opened, Because I have done all the starter work of my all issues opened, only final works to be done, once issues assigned

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960

**Comment by Rakesh9100** [comment]
Are you working @Yuvraj960

**Comment by Yuvraj960** [comment]
Yes @Rakesh9100 I am working, due to my weekend exam,  I didn't replied
