### ISSUE TITLE
[Feature] Add Net Worth Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#559]
### Description

Input the Financial Assets of the user along with his/her liabilities to calculate it's NetWorth. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Paarisha1** [comment]
Can I contribute in this
Under swoc

**Comment by Yuvraj960** [comment]
@Rakesh9100, after time until next birthday calculator, please assign me this issue

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Yuvraj960** [comment]
@Rakesh9100 Assign this issue to me under GSSoC24

**Comment by Rakesh9100** [comment]
Assigning you, proceed @surendar-05
