### ISSUE TITLE
[Feature] Add Life Insurance Needs Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#560]
### Description

Calculate recommended amount of life insurance coverage based on financial obligations and dependents.
Inputs some financial parameters of the user and returns the Number for how much insurance amount did the user has to register

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Hey @Yuvraj960 Don't  open too many issues at once. You will not be assigned to any of them and also get banned from the program for this behaviour!!

**Comment by Gokilp** [comment]
please assign to me

**Comment by Yuvraj960** [comment]
@Rakesh9100 Assign this issue to me under GSSoC24

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960
