### ISSUE TITLE
[Feature] Adding vice versa in Percentage to Fraction Calculator

### ISSUE THREAD

**Issue by pinak22dhir** [Rakesh9100/CalcDiverse#565]
### Description

it will change fraction to percentage 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We have [Percentage to Fraction Calculator](https://calcdiverse.netlify.app/calculators/percentage-to-fraction-calculator/). So you can integrate the vice-versa in this Calculator only!!

Should I assign you? @pinak22dhir

**Comment by kom-senapati** [comment]
Do you want like another calculator to the right of it for converting fractions to percentages?

**Comment by Rakesh9100** [comment]
No not a new calculator, you have to implement the functionality in this same calculator by adding new input box which takes fraction and then proceed for the other logic implementations!!

Also rename the folder to `Percentage-Fraction-Calculator` @kom-senapati

**Comment by kom-senapati** [comment]
Ok assign me the issue
