### ISSUE TITLE
[Feature] Aspect Ratio Calculator

### ISSUE THREAD

**Issue by sumugowda** [Rakesh9100/CalcDiverse#567]
### What would you like to share?

**Description**
Implements an Aspect ratio calculator which provides the ratio of specified height and width.
**Screenshots**
No response

### Additional information

Can I work on this issue

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @sumugowda

**Comment by Rakesh9100** [comment]
Status of your PR @sumugowda

**Comment by sumugowda** [comment]
> Status of your PR @sumugowda 

Working on frontend will be ready by tomorrow.
