### ISSUE TITLE
[Style] Enhance Age Calculator Page

### ISSUE THREAD

**Issue by Nikitakandwal** [Rakesh9100/CalcDiverse#569]
### What's the style idea?

We need to improve styling of the container for age calculator page(such as Adding shadows). Along with styling I wish to add some prompt text that can be displayed when a negative age is drawn.

![Screenshot 2024-02-07 201115](https://github.com/Rakesh9100/CalcDiverse/assets/98966392/4e6a2f6f-44ac-4004-8c62-cc206232c961)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Nikitakandwal
