### ISSUE TITLE
Number Conversion Calculator

### ISSUE THREAD

**Issue by SohanRC** [Rakesh9100/CalcDiverse#573]
### Description

This is a calculator which will  perform conversion between corresponding binary , decimal , hexadecimal numbers , octal numbers. Please assign me this issue under JWOC 2024.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have [Number System Calculator](https://calcdiverse.netlify.app/calculators/number-system-calculator/number-system). Pls create new issues @SohanRC
