### ISSUE TITLE
[Feature] Adding Period cycle calculator

### ISSUE THREAD

**Issue by Aniketmehraa** [Rakesh9100/CalcDiverse#575]
### Description

I propose adding a period tracker calculator to the project to help users monitor their menstrual cycle and manage related information more effectively.
Below is the reference to what type of calculator I wish to contribute.

### Screenshots

![Screenshot (9)](https://github.com/Rakesh9100/CalcDiverse/assets/141115744/7e403ba9-3e10-410c-ada8-96f113c8b032)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have one [Calculator](https://calcdiverse.netlify.app/calculators/pregnancy-due-date-calculator/) for this. You can add more features in this if you want @Aniketmehraa

**Comment by Aniketmehraa** [comment]
while both calculators involve dates related to reproductive health, the pregnancy due date calculator focuses on estimating the due date for childbirth during a pregnancy, while the period cycle calculator predicts the start date of menstrual periods for tracking menstrual cycles. @Rakesh9100

**Comment by Aniketmehraa** [comment]
Kindly assign me this issue @Rakesh9100

**Comment by Rakesh9100** [comment]
You can do enhancements and add new features in that calculator only instead of creating a new one @Aniketmehraa
