### ISSUE TITLE
[Bug] Navbar elements not readable in mobile devices

### ISSUE THREAD

**Issue by Abhishek-465** [Rakesh9100/CalcDiverse#581]
### What's the style idea?

The navbar elements are not readable.The background's CSS must be adjusted. I want to work on this issue. Kindly assign me.

![Screenshot_20240212_003932_Chrome](https://github.com/Rakesh9100/CalcDiverse/assets/127030695/5779159c-6c06-48e5-8c7e-2869df15ff18)

Under JWOC.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Abhishek-465

**Comment by yashi-15** [comment]
I can work on this.. Assign it to me under SWOC @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @yashi-15

**Comment by Aanyaa26** [comment]
Please assign me under JWOC'24 as the navbar still doesn't look good on mobile screens!
I wanted to fix this bug and will give my best!
This will be my first open-source task!

**Comment by yashi-15** [comment]
> Status of your PR pls @yashi-15

Will be creating the PR by today. @Rakesh9100
