### ISSUE TITLE
[Feature] Adding Love Compatibility Calculator

### ISSUE THREAD

**Issue by pinak22dhir** [Rakesh9100/CalcDiverse#584]
### Description

Adding questions ,then checking score regarding same.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls describe your issue more @pinak22dhir

**Comment by pinak22dhir** [comment]
to add questions , for example about hobby and interest , then evaluating compatibility on basis of interest matched

**Comment by Rakesh9100** [comment]
Proceed @pinak22dhir
