### ISSUE TITLE
[Style] Center the "Search bar"

### ISSUE THREAD

**Issue by Nitinshukla88** [Rakesh9100/CalcDiverse#585]
### What's the style idea?

We need to improve the position of Search bar. If we see it's alignment, it's not in the proper middle which ruins user experience. So I would suggest to position it properly.
![Screenshot (24)](https://github.com/Rakesh9100/CalcDiverse/assets/143546627/0b55df46-739a-49dd-a81f-32e3debf54fa)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nitinshukla88** [comment]
Hey @Rakesh9100 assign me. I would like to work on this issue.

**Comment by Rakesh9100** [comment]
The Search and Mic button is considered together and is centered so it seems like this @Nitinshukla88
