### ISSUE TITLE
Adding icons 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Rakesh9100/CalcDiverse#587]
### Description

I want to add icons for the components  present on the navbar

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Soumya6Tiwari** [comment]
@Rakesh9100 kindly assign me this issue

**Comment by Rakesh9100** [comment]
You can comment in same opened issue 502 to get assigned @Soumya6Tiwari
