### ISSUE TITLE
[Feature] Unit convertor

### ISSUE THREAD

**Issue by akanshaBharti** [Rakesh9100/CalcDiverse#589]
### Description

Adding a feature that allows users to convert between different units of measurement.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Length Calculator. Pls create new issues @akanshaBharti
