### ISSUE TITLE
[Feature] Add N sided polygon calculation in 2D Shapes Calculator

### ISSUE THREAD

**Issue by Abhishek-465** [Rakesh9100/CalcDiverse#591]
### Description

I want to add an option to calculate the area and perimeter of any n sided polygon with the help of some basic logics using Javascript.
If this feature can be added, i will be happy if you assign me this issue.
Thank you.

### Screenshots

![Screenshot (17)](https://github.com/Rakesh9100/CalcDiverse/assets/127030695/19b0c043-9644-49c6-8eb8-e63ad07f3262)

Here only hexagon is there in the options. Other polygons like hepta or octagon's area and perimeter cannot be calculated.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @Abhishek-465

**Comment by Yuvraj960** [comment]
@Rakesh9100, Assign this to me under SWOC24, after merging the PR for Credit card payoff calculator, as I want to complete more and more small issues faster, because the SWOC24 date is approaching to its end.

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960
