### ISSUE TITLE
[Feature] Add Cuban Prime Calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#595]
### Description

A cuban prime is a [prime number](https://en.wikipedia.org/wiki/Prime_number) that is also a solution to one of two different specific equations involving differences between third powers of two integers x and y.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me under JWOC
Previous PR is done

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure

**Comment by AftabMankapure** [comment]
![Cuban](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/61d9e288-e8bd-4be2-8a09-babb2bac3f1b)
