### ISSUE TITLE
[Style] Remove border radius from the navbar

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#598]
### Description

Remove border radius form navbar

### Screenshots

Current 

![CNAV](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/f45ed596-3046-42f3-9472-742dad51d5d2)

New 

![newNavcal](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/8d2c2997-6bb3-43ad-816a-1ac1b4bb3e79)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls upload the issue supporting screenshot properly @AftabMankapure

**Comment by AftabMankapure** [comment]
Current 

![CNAV](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/f45ed596-3046-42f3-9472-742dad51d5d2)


New 

![newNavcal](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/8d2c2997-6bb3-43ad-816a-1ac1b4bb3e79)

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure
