### ISSUE TITLE
[Feature] Add Yarn Density Calculator

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/CalcDiverse#601]
### Description

To calculate the density of the yarn in different systems like,
- Tex
- English count
- worsted count
- woolean count, etc.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 Assign it to me under SWOC'24

**Comment by Rakesh9100** [comment]
Go ahead @Avdhesh-Varshney
