### ISSUE TITLE
[Feature] Add Disarium Number Calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#604]
### Description

Disarium number
         ( A number is said to be the Disarium number when the sum of its digit 
		   raised to the power of their respective positions is equal to the number
		   itself.
			For example, 175 is a Disarium number as follows
			1^1 + 7^2 + 5^3 = 1 + 49 + 125 = 175

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
You have already added this calculator, check and create new issues!! @AftabMankapure
