### ISSUE TITLE
[Feature] Add Happy Number Calculator

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/CalcDiverse#605]
### Description

Happy number

The happy number can be defined as a number which will yield 1 when it is replaced by the sum of the square of its digits repeatedly. If this process results in an endless cycle of numbers containing 4, then the number is called an unhappy number.

For example, 32 is a happy number as the process yields 1 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
pls assign me under JWOC

**Comment by Rakesh9100** [comment]
Go ahead @AftabMankapure

**Comment by Rakesh9100** [comment]
Hold on for now @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100  why Rakesh today is last day

**Comment by Rakesh9100** [comment]
You have just copied the code and created the PR in my another project, so you will not be assigned to any issues now and I will review all of your PRs now as this plagiarism incident also happened previously by you @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100  ok go and all my PR as well as other PR also who copy code form any where

**Comment by AftabMankapure** [comment]
also i can help you to find which PR is copied from which resource

**Comment by Rakesh9100** [comment]
No need of that, team will look into it @AftabMankapure

**Comment by Rakesh9100** [comment]
At least you can just take reference from websites and then modify and enhance it but direct copy pasting the codes is not allowed @AftabMankapure

**Comment by Rakesh9100** [comment]
Okay, proceed if you are saying right. If found false claim, then all the PRs and scores will be cancelled @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100  check is SohanRC  also copy the code 

![co1](https://github.com/Rakesh9100/Beautiify/assets/125949765/eb7a5b47-cf25-4e8c-90db-366c70081100)


![copy1](https://github.com/Rakesh9100/Beautiify/assets/125949765/8f0a502f-07de-4b45-9f3f-a6727f658445)


https://www.programmingkakeeda.com/2024/02/create-animated-sign-in-page-using-html-and-css.html

**Comment by Rakesh9100** [comment]
Okay will check and forward to the team @AftabMankapure

**Comment by AftabMankapure** [comment]
![Happy](https://github.com/Rakesh9100/CalcDiverse/assets/125949765/515bdefd-d7d8-4e9e-9497-b4521a9a7f2c)
