### ISSUE TITLE
[Style] Center align the Search Bar

### ISSUE THREAD

**Issue by Aanyaa26** [Rakesh9100/CalcDiverse#608]
### Description

The search bar given is not center-aligned which can be improved by aligning it properly!
It's my first issue. I hope you assign me!
I am looking forward to working on this project.

### Screenshots

![Screenshot 2024-02-23 143321](https://github.com/Rakesh9100/CalcDiverse/assets/128315909/ce584034-018f-42bc-92a2-3ce3e89522aa)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Aanyaa26** [comment]
In this screenshot, it might look correct but while surfing the website, it doesn't look good which must be properly aligned!

**Comment by Rakesh9100** [comment]
I would like to clarify you that the Search and Mic button is considered together and is centered so it seems like this @Aanyaa26

**Comment by Aanyaa26** [comment]
Yes, I agree with your point that search bar and mic are altogether but if you look from the user perspective they are not center-aligned with respect to the heading above!
So, the whole section can be shifted a little bit to the right which will make it look better!

**Comment by Rakesh9100** [comment]
Okay, proceed!
Will see after it's done @Aanyaa26
