### ISSUE TITLE
UI Changes in SGPA Calculator

### ISSUE THREAD

**Issue by krishnagitcontri** [Rakesh9100/CalcDiverse#61]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I can make a better UI in Sgpa calculator with hover text animation.

### Screenshots

<img width="850" alt="SGPA" src="https://github.com/Rakesh9100/CalcDiverse/assets/153177987/6dec9693-c611-495c-9a92-8082d3de9056">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @krishnagitcontri

**Comment by Rakesh9100** [comment]
@krishnagitcontri Status of your PR

**Comment by krishnagitcontri** [comment]
WIl Send you PR tommorow I was gone Outside So I didn't Get Back.

**Comment by krishnagitcontri** [comment]
<img width="959" alt="sgpa changes" src="https://github.com/Rakesh9100/CalcDiverse/assets/153177987/db9e7935-ab8f-42d8-ac47-f390cb22de4e">
Changes done in calculator
