### ISSUE TITLE
[Bug] About us Page Bottom Menu Links are Broken

### ISSUE THREAD

**Issue by shakti177** [Rakesh9100/CalcDiverse#619]
### Description

The Button Menu links of the About page are broken.

### Screenshots

<img width="1440" alt="image" src="https://github.com/Rakesh9100/CalcDiverse/assets/57393413/8405c632-474d-4409-ace2-ab2c3dab8e1c">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shakti177** [comment]
Can You Please Assign this Issue to Me?

**Comment by JAProgramming** [comment]
I can also do this.

**Comment by Rakesh9100** [comment]
You have opened this issue for which open source program @shakti177

**Comment by shakti177** [comment]
SWOC

**Comment by Rakesh9100** [comment]
SWOC concluded on February 28th, 2024 @shakti177
