### ISSUE TITLE
Develop Responsive and Interactive Contact Us Form 

### ISSUE THREAD

**Issue by Wadgaonkarprathameshdeepak** [Rakesh9100/CalcDiverse#620]
### What's the style idea?

I will create the contact us form by creating a responsive design that seamlessly adjusts to different screen sizes and interactive user interfaces.

![Screenshot 2024-02-20 113941](https://github.com/Rakesh9100/CalcDiverse/assets/95523666/372f641d-6427-4e28-a687-4a17e8165bbe)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
JWOC is already over @Wadgaonkarprathameshdeepak
