### ISSUE TITLE
[Feature] Add Salary To Hourly Calculator

### ISSUE THREAD

**Issue by betelhemdemsis** [Rakesh9100/CalcDiverse#622]
### Description

The Salary to Hourly Wage Calculator enables users to convert their salary across various timeframes. whether you have an annual, monthly, weekly, daily, or hourly wage, this tool provides a seamless conversion to understand your earnings in different formats.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Jithendranath8** [comment]
plese assign me this issue , i know how to solve this

**Comment by TechSenseiX** [comment]
Hi @Rakesh9100 , I believe I'm well-equipped to tackle this issue effectively. I've also taken the time to thoroughly understand the problem and have some ideas on how to approach it. 
So, please assign this issue to me.

**Comment by betelhemdemsis** [comment]
@Rakesh9100 I've already solved it and made the calculator that's why I created the issue

**Comment by amishah1110** [comment]
Hello. I already have this program ready with me, please assign me this

**Comment by drashtiv03** [comment]
Hi,I am drashti.Can I get this issue under the label GSSoC'24?

**Comment by Rakesh9100** [comment]
Have you created this issue under GSSoC @betelhemdemsis

**Comment by betelhemdemsis** [comment]
> Have you created this issue under GSSoC @betelhemdemsis

Yes I did

**Comment by Rakesh9100** [comment]
Okay, then proceed @betelhemdemsis

**Comment by betelhemdemsis** [comment]
sure thank you
