### ISSUE TITLE
[Feature] Add Number System Calculator

### ISSUE THREAD

**Issue by Durgesh-Vaigandla** [Rakesh9100/CalcDiverse#623]
### Description

I will be add decimal to binary converter binary to decimal converter as well as hexadecimal to binary conversions and more.
Please assign me for this as GSSoC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a IWOC'24 contributor.
- [x] I am a JWOC'24 contributor.
- [x] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Damini2004** [comment]
Please assign this issue to me i can make several betterment in this particular section even though add responsiveness functionality and many more mathematical calculations.

**Comment by amishah1110** [comment]
Please assign this to me, I can make the UI better and also give a better user experience

**Comment by Rakesh9100** [comment]
We already have Number System Calculator for this, please create new issues @Durgesh-Vaigandla
