### ISSUE TITLE
[Style] Enhance font color of heading in About Us page

### ISSUE THREAD

**Issue by Disha-Hati** [Rakesh9100/CalcDiverse#625]
### What's the style idea?

We need to improve the font color of the headings in about us issue. It is not visible. 
@Rakesh9100  I'm GSSOC'24 contributor, Can you please assign this to me?

![image](https://github.com/Rakesh9100/CalcDiverse/assets/70029959/007e8e97-9597-4cb9-a5e9-ea7d42163d49)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sathya-reddy1658** [comment]
i can solve the issue !!!, could you please assign

**Comment by niteshbca** [comment]
Please assign this task to me. And solved the problem.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Rakesh9100** [comment]
What exactly problem you are facing in this issue as it is properly visible on the website @Disha-Hati
