### ISSUE TITLE
[Bug] Center the search box

### ISSUE THREAD

**Issue by Ayush-may** [Rakesh9100/CalcDiverse#627]
### Description

this search input field isnt at the center of the screen 

### Screenshots

![Screenshot from 2024-05-09 22-15-20](https://github.com/Rakesh9100/CalcDiverse/assets/112775332/ff348999-368a-4c07-8673-1ab1a346bb0b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
For which screen size are you facing this as I can see it is in the center on the website @Ayush-may
