### ISSUE TITLE
[Feature] Add Tip Calculator

### ISSUE THREAD

**Issue by Archit-Ash** [Rakesh9100/CalcDiverse#629]
### Description

The Tip Calculator will Allow users to calculate tip amount on basis of bill amount, and it will display tip amount and total bill amount.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nayanika1402** [comment]
Hey @Archit-Ash ,I will be obliged to work on the tip-calculator part.I can assure you I can do my task properly.

**Comment by Nayanika1402** [comment]
Hey @Rakesh9100  ,I will be obliged to work on the tip-calculator part.I can assure you I can do my task properly.

**Comment by Rakesh9100** [comment]
Proceed @Archit-Ash

**Comment by m3kvt** [comment]
I would like to work on this

**Comment by Archit-Ash** [comment]
hey @Rakesh9100 ,i have completed the code for the calculator, but i cant figure out how to add screenshots in the readme.md , are there  any resource that might help me?

**Comment by Rakesh9100** [comment]
You can just take the screenshot and paste in the Readme file using Ctrl+V !!
Or copy any image or screenshot and do Ctrl+V, it will upload directly @Archit-Ash

**Comment by Archit-Ash** [comment]
Almost completed @Rakesh9100 , I'll wrap things up today.
