### ISSUE TITLE
Statistics Calculator

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/CalcDiverse#63]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Maximum, minimum, mean, median, mode, standard deviation, variance, range, sum, and count calculations.
A list of integers/floats can be taken as input and all of these statistics can be shown.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/92045934/c0dd6f32-b33b-4cc9-897c-6f87fa78c447)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @kom-senapati
