### ISSUE TITLE
[Bug] Fix negative input in Logarithm Calculator

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#630]
### Description

In the logarithm calculator input section, the inputs are being taken through numeric sliders.
Now since we know that logarithm of negative numbers can't be calculated nor the base could be negative or one so rather than generating alert after we press **Calculate Log** option, how about we **_restrict the sliders_** to go beyond.
Also we can apply a simultaneous check which won't let us enter non-positive numbers through keyboard input as well.
[https://calcdiverse.netlify.app/calculators/logarithm-calculator/]

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Aarzookhunger** [comment]
@Rakesh9100 
Kindly assign this issue to me for GSSoC'24 contribution.
I'll be glad to resolve this issue and make my contribution to open-source community.

Thanks!

**Comment by Rakesh9100** [comment]
Go ahead @Aarzookhunger

**Comment by Aarzookhunger** [comment]
@Rakesh9100 
Kindly add label regarding the level as well.

Thankyou!
