### ISSUE TITLE
[Bug] Fix card hover animation size

### ISSUE THREAD

**Issue by pankaj-bind** [Rakesh9100/CalcDiverse#632]
### Description

When you hover over the card the hover effect height is different for different cards. It must be same it is looking quite odd.
Please assign me this task under GSSoC'24 I will correct it.

### Screenshots

![2](https://github.com/Rakesh9100/CalcDiverse/assets/73558583/2d5c3f39-6438-46b9-8bcc-0551255ff49b)
![tg](https://github.com/Rakesh9100/CalcDiverse/assets/73558583/6e5963e0-34c7-46e4-981a-c89f2ac96873)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Rakesh9100** [comment]
Proceed @pankaj-bind
