### ISSUE TITLE
[Style] Add hover effect on inputs in Basic Calculator

### ISSUE THREAD

**Issue by shivangi-singhjha** [Rakesh9100/CalcDiverse#633]
### What's the style idea?

**Description**
On mouseover the border color of the inputs will be changed.
Please assign me this task under GSSoC'24 Contributor.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by DaminiTechie** [comment]
Please assign me this task under GSSoC'24 Contributor.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by aashkaaaaaa** [comment]
I am really interested in contributing to GSSoC'24 as a contributor and I was wondering if you could assist me by assigning me a task under the program.

**Comment by nsk6704** [comment]
I kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/

**Comment by Rakesh9100** [comment]
Which inputs are you talking about, pls clarify with the supporting screenshots @shivangi-singhjha

**Comment by shivangi-singhjha** [comment]
**Sir, on hovering any inputs like any digit 1,2,3... or operator +, - .... a border will appear.**

Here I am hovering on 9 , a border is appearing.
![WhatsApp Image 2024-05-10 at 03 57 06_470770c6](https://github.com/Rakesh9100/CalcDiverse/assets/92207397/f537d0c1-777f-4bc0-b45f-8d6ea5b46c9e)

**Comment by shivangi-singhjha** [comment]
> **Sir, on hovering any inputs like any digit 1,2,3... or operator +, - .... a border will appear.**
> 
> Here I am hovering on 9 , a border is appearing. ![WhatsApp Image 2024-05-10 at 03 57 06_470770c6](https://private-user-images.githubusercontent.com/92207397/332966750-f537d0c1-777f-4bc0-b45f-8d6ea5b46c9e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjI2MDEsIm5iZiI6MTcxNjY2MjMwMSwicGF0aCI6Ii85MjIwNzM5Ny8zMzI5NjY3NTAtZjUzN2QwYzEtNzc3Zi00YmMwLWI0NWYtOGQ2ZWE1YjQ2YzllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MzgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Yzg5YWM4ZDc0MzU3NGM3ZGZiYWY3NTc4YzQ2ZmMyNGI2MzViNThlMDRiMjE5NWZjOGRiNzk1ODBlNmEzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2wu7lu5ocSVibAGQH0C-tuYeHG93pyEHMeLgHa_foTs)

Sir kindly look into it.

**Comment by Rakesh9100** [comment]
Go ahead @shivangi-singhjha
