### ISSUE TITLE
[Style] Enhance the footer UI

### ISSUE THREAD

**Issue by AlaynaShaheen** [Rakesh9100/CalcDiverse#636]
### What's the style idea?

We need to improve the UI of footer by dividing footer into sections and align the links in specific columns.

![Screenshot 2024-05-10 085738](https://github.com/Rakesh9100/CalcDiverse/assets/111679498/51643450-b755-4cfa-b100-dfe41487f9fe)

I am a contributor under GSSoC'24 and I have a good experience in development. I can resolve this issue. Please assign this to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nayanika1402** [comment]
@AlaynaShaheen can you like a bit explain how do you want the footer to look like.You can give example of any website then I can work on this matter.

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by AlaynaShaheen** [comment]
> @AlaynaShaheen can you like a bit explain how do you want the footer to look like.You can give example of any website then I can work on this matter.

I am also a contributor in GSSoC'24 . And the idea is to divide the footer into 3 columns and add navbar and its tagline in one section then the other links in second section and social media links in third section

**Comment by Rakesh9100** [comment]
Do you have any supporting screenshot for your idea @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
Yes @Rakesh9100. Below screenshot represents my idea. I think the below design looks much better if we don't add the row at the last having mobile number, email and address. 
![Screenshot 2024-05-21 085423](https://github.com/Rakesh9100/CalcDiverse/assets/111679498/9055aa45-26bc-4d64-bca8-0d1853274822)
Instead of subscribe to newsletters we can add send message functionality which makes the footer more interactive.
Let me know if there are any further changes that can be made in this design.

**Comment by Rakesh9100** [comment]
Design seems good, but what would be the alternative to newsletter. I don't think Send message would be applicable because for that we need Name, Email and Message inputs @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
![Screenshot 2024-05-27 105301](https://github.com/Rakesh9100/CalcDiverse/assets/111679498/6d346e78-10a0-48e3-997d-42207c6019c1)
We can add it this way and it correctly fits in the third column. Please check this once or else we can add JOIN US section in the third row.
![Screenshot 2024-05-27 110327](https://github.com/Rakesh9100/CalcDiverse/assets/111679498/163f2e90-797e-4a81-9483-f2274cce4280)
For this we can add a join us which redirects people to the github repo.
![Screenshot 2024-05-27 110648](https://github.com/Rakesh9100/CalcDiverse/assets/111679498/fc23176b-d0fd-4e1c-a910-c31e8c44c21e)
Please let me know which one would be better @Rakesh9100

**Comment by Rakesh9100** [comment]
Status of your PR pls @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
Yes I have started working on the footer @Rakesh9100. I'll raise a PR soon.

**Comment by Rakesh9100** [comment]
Provide your PR @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
Raised a PR #1168. Please check the PR and let me know if there are any changes that can be made further @Rakesh9100

**Comment by Nihal4777** [comment]
@AlaynaShaheen Are you currently working on this or not?
