### ISSUE TITLE
Enhance Header Design and Functionality

### ISSUE THREAD

**Issue by vaishnavisingh095** [Rakesh9100/CalcDiverse#637]
### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by juniorcoder02** [comment]
hi project admin @Rakesh9100 i'm participant in Gssoc'24 and i am thrilled to be contributing to CalcDiverse. after reviewing the open issues, i'm particularly interested in enhance header design and functionality as it aligns well with my skills and interests.                                                                                                                                       Could you please assign this issue to me? I'm eager to dive in and make a meaningful contribution to the project.

**Comment by Rakesh9100** [comment]
Issue is not clear as description is not mentioned properly, hence closing the issue @vaishnavisingh095
