### ISSUE TITLE
[Feature] Add Averages Calculator

### ISSUE THREAD

**Issue by its-kumar-yash** [Rakesh9100/CalcDiverse#638]
### Description

The Mathematical Averages Calculator takes a set of values and finds the Arithmetic Mean, Geometric Mean and Harmonic Mean of the same.
Kindly assign this to me

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/97521394/0cae8eb3-c15c-4830-a54b-8384dfce83cf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by amishah1110** [comment]
Hi, I'd like to take on the task of implementing the Mathematical Averages Calculator feature. I believe it aligns well with my skills and interests, and I'm excited to contribute to its development. Assigning this to me would be greatly appreciated. 

Thanks!

**Comment by Rakesh9100** [comment]
Go ahead @its-kumar-yash
