### ISSUE TITLE
[Feature] Add Calorie Calculator

### ISSUE THREAD

**Issue by amishah1110** [Rakesh9100/CalcDiverse#639]
### Description

Calorie Calculator Plus is a user-friendly mobile app designed to assist users in tracking and controlling their daily calorie intake. By considering individual factors like age, gender, weight, height, and activity level, the app employs renowned formulas such as the Harris-Benedict Equation or the Mifflin-St Jeor Equation to compute Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE). This results in tailored calorie suggestions, aiding users in weight management or attaining particular objectives such as weight loss or muscle gain.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by YazhiniVenkatesan12** [comment]
Hi @Rakesh9100 , I'm yazhini , a participant in GSSoC24. I would like to contribute to this project. I have experience with HTML,CSS,JAVASCRIPT and I'm interested in helping with calorie calcular feature. May I be assigned to the task?

Thank you!

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by Rakesh9100** [comment]
We already have a Calorie Burnt Calculator & Calorie Intake Calculator. What is different in your issue @amishah1110
