### ISSUE TITLE
[Bug] Fix the footer broken links on About page

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#640]
### Re-directing links missing and links broken

As we head to the website, then go to About section in the header, scroll down towards the end and go to footer where Home About Calculators etc. links are mentioned, Now as we click on the _Home, Calculators_ it **doesn't re-direct** us to the home page or calculator section .
For _Contributors, FAQ and Contact_ it shows that the **link is broken.**

This issue needs to be fixed and appropriate re-directing links need to be added. Kindly assign this issue.

### Screenshots

Broken link : 
![LinkBroken](https://github.com/Rakesh9100/CalcDiverse/assets/116306749/911102ad-a318-4076-9f05-29e903a53853)

For Home, Calculators no re-direction happens!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by nishant0708** [comment]
hey please assign me this issue i can fix this issue

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Rakesh9100** [comment]
Go ahead @Aarzookhunger
