### ISSUE TITLE
reCAPTCHA v3 Integration in "Contact" page form

### ISSUE THREAD

**Issue by Sushanth-Hebri** [Rakesh9100/CalcDiverse#642]
### Description

Hello @Rakesh9100 
I have noticed a security vulnerability in contact page - https://calcdiverse.netlify.app/assets/contact/contact
In contact form there is possibility of "**form spam attack**" by bots.

By incorporating reCAPTCHA, we can verify that form submissions originate from legitimate human users, effectively thwarting automated bot attacks. This measure will bolster the security of our open source project and improve the overall user experience.

Given my background in web security and **reCAPTCHA integration**, I'm eager to contribute to this initiative and help safeguard our project against malicious activities.

I look forward to your response and the opportunity to collaborate on this important enhancement.

### Screenshots

![Screenshot 2024-03-14 195302](https://github.com/Rakesh9100/CalcDiverse/assets/117469085/49137cac-ab65-4b2f-bb7d-bf291f0086cd)
This is my project where i successfully integrated reCAPTCHA v3 .
Looking forward to contribute ❤️

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sushanth-Hebri** [comment]
❤️

**Comment by Rakesh9100** [comment]
Form submissions are handled by Netlify platform, so I can turn on the captcha functionality directly if I want to. Pls work on other issues @Sushanth-Hebri
