### ISSUE TITLE
[Style] Equal the size of social media icons

### ISSUE THREAD

**Issue by raghavawasthi24** [Rakesh9100/CalcDiverse#644]
### What's the style idea?

Same width and height of all social media icons

![Screenshot (218)](https://github.com/Rakesh9100/CalcDiverse/assets/113261155/9705e6c2-3f71-497e-b98a-5b4015abd275)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sajiyasiddiqui** [comment]
I would like to work on this project .please assign to me

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by Rakesh9100** [comment]
For which page are you talking about @raghavawasthi24

**Comment by Rakesh9100** [comment]
Do you want to work @Sajiyasiddiqui @Anou25

**Comment by Anou25** [comment]
Yes I want to work

**Comment by Rakesh9100** [comment]
Proceed @Anou25

**Comment by Anou25** [comment]
@Rakesh9100 please can you also add the level

**Comment by Rakesh9100** [comment]
Will add once your PR is merged @Anou25

**Comment by Sajiyasiddiqui** [comment]
yes I want to work.

**Comment by Rakesh9100** [comment]
There is just negligible difference, so no need to work on this issue!!
