### ISSUE TITLE
[Feature] Implement smooth scrolling using locomotive scroll

### ISSUE THREAD

**Issue by rajkrsingh9** [Rakesh9100/CalcDiverse#646]
### Description

I want to implement smooth scrolling into the website and also will work over other styling. Please assign me this issue!

### Screenshots
[screen-capture (1).webm](https://github.com/Rakesh9100/CalcDiverse/assets/143270207/a3c73e15-f529-4b71-ae7f-d585b8c78743)

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by FatemaBaig** [comment]
Hii, i would like to work on this styling part of the project. Assign it to me

**Comment by Mandar007007** [comment]
i can fix it using locomotive scrolling. please assign it to me

**Comment by rajkrsingh9** [comment]
Please assign me this issue. I will work over this issue under GSSOC'24.

**Comment by Rakesh9100** [comment]
Scrolling is already smooth, what more changes you want to make @rajkrsingh9

**Comment by GauriGA** [comment]
@Rakesh9100 Could you please assign this issue to me under the GSSOC'24 label?

**Comment by Rakesh9100** [comment]
What do you want to work in this issue @FatemaBaig @Mandar007007 @GauriGA

**Comment by Mandar007007** [comment]
I can add smooth scrolling with using locomotive js

**Comment by Rakesh9100** [comment]
But scrolling is already smooth by default, I don't think we need any other JS library @Mandar007007

**Comment by Rakesh9100** [comment]
Okay go ahead @Mandar007007

**Comment by GauriGA** [comment]
@Rakesh9100 I would like to add JavaScript Libraries like SmoothScroll.js, ScrollMagic and Glide.js

**Comment by Rakesh9100** [comment]
Provide your PR @Mandar007007

**Comment by Mandar007007** [comment]
Work is done but I am away with my lap. I will provide it by Sunday or monday

**Comment by Mandar007007** [comment]
PR is added please checkout

**Comment by justmirr** [comment]
Can you assign this to me as it's up for grab and I'm sure I can work on it ASAP.

**Comment by Rakesh9100** [comment]
Go ahead @justmirr

**Comment by Rakesh9100** [comment]
Provide your PR @justmirr

**Comment by Atharvverma1234** [comment]
Hi, I would like to work on this issue. Please assign it to me. Thank you!

**Comment by Rakesh9100** [comment]
Is this required now, as pagination feature is already present? @Atharvverma1234

**Comment by Rakesh9100** [comment]
Any update @Atharvverma1234

**Comment by Atharvverma1234** [comment]
> Any update @Atharvverma1234

As you said Sir the pagination feature is already present so I moved forward and chose to work on other issues which are assigned to me.

**Comment by Rakesh9100** [comment]
Okay @Atharvverma1234
