### ISSUE TITLE
[Style] Enhance SIP Calculator UI

### ISSUE THREAD

**Issue by roysammy123** [Rakesh9100/CalcDiverse#649]
### Description

# Mutual Fund Returns Calculator with Visually Attractive Design and Investment Type Selection

**Feature Description:**
Improve the user interface of the mutual fund returns calculator by implementing a visually attractive design and providing an intuitive way for users to select between lumpsum and SIP (Systematic Investment Plan) investment options.

**Expected behaviour:**
1. **Stylish UI:** Implement modern CSS styling to enhance the visual appeal of the calculator, making it more engaging for users.
2. **Investment Type Selection:** Replace the current plain dropdown menu with a more visually appealing selection interface, such as radio buttons or toggle switches, to improve usability and user experience.
3. **Responsive Design:** Ensure that the calculator is responsive and displays well on different devices, including desktops, tablets, and mobile phones, to cater to a wider audience.

I would like to work on this as part of GSSoC'24. I will be really thankful if you kindly assign this to me. Thanks!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Rakesh9100** [comment]
Go ahead @roysammy123

**Comment by roysammy123** [comment]
@Rakesh9100 Thanks for assigning. Will get started on this right away. In the meantime, can you please attach label for level 1/2/3 to this issue?
