### ISSUE TITLE
Try Now buttons for calculators are not functioning

### ISSUE THREAD

**Issue by Kavyam172** [Rakesh9100/CalcDiverse#65]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Clicking the try now buttons shows an error. I would like to resolve this bug.

### Screenshots

https://github.com/Rakesh9100/CalcDiverse/assets/124245507/0c1122f0-7d93-4f29-8835-740da3c74b07

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
It was some error from a contributor which is fixed now. Pls work on other issues and get it assigned @Kavyam172
