### ISSUE TITLE
[Feature] Add background images

### ISSUE THREAD

**Issue by Chelseasingla1** [Rakesh9100/CalcDiverse#651]
### Description

I want to add background images in when a specific calculator is added or maybe adding some GUI effects in it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Chelseasingla1** [comment]
Please assign me this issue

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by FatemaBaig** [comment]
Hello, I am interested into this part (GUI) graphical user interface 
i would like to work on this project. Assign it to me

**Comment by Rakesh9100** [comment]
Can you elaborate your issue properly @Chelseasingla1
