### ISSUE TITLE
[Bug] Fix overflowing of textarea in Contact page

### ISSUE THREAD

**Issue by vedanshipathak** [Rakesh9100/CalcDiverse#652]
### What's the style idea?

Here in the Contact section when you increase the size of the TEXTAREA manually you will find that the width of input box for name and email also increases .In addition to that, the text area gets overflowed of the contact-container.

![Screenshot 2024-05-10 201008](https://github.com/Rakesh9100/CalcDiverse/assets/141757766/b441f86a-d904-4287-8cc1-6f0f97359c43)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AtharvKasar04** [comment]
@Rakesh9100 Can you assign me this issue under GSSoC'24, I can make those input, text area fields more appealing and fix that resizing issue. I have worked with manier FrontEnd projects.

**Comment by YazhiniVenkatesan12** [comment]
Hi @Rakesh9100 , I'm yazhini , a participant in GSSoC24. I would like to contribute to this project. I have experience with HTML,CSS,JAVASCRIPT and I'm interested in improving TextArea changes in Contact Us Form . May I be assigned to the task?

Thank you!

**Comment by Rakesh9100** [comment]
Go ahead @vedanshipathak
