### ISSUE TITLE
[Feature] Add Basal Metabolic Rate Calculator

### ISSUE THREAD

**Issue by Nayanika1402** [Rakesh9100/CalcDiverse#653]
### Description

We can add BMR-Calculator which will basically calculate the Basal Metabolic Rate. I want to address the issue under GSSOC'24. Kindly approve this idea so that I can start working on it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Svastik73** [comment]
Hello  ,I'd like to resolve this issue.

**Comment by Nayanika1402** [comment]
@Rakesh9100 Kindly assign me this issue as I proposed the idea of adding this feature.

**Comment by Rakesh9100** [comment]
Proceed @Nayanika1402
