### ISSUE TITLE
[Bug] Fix the displayed html tag in Armstrong Number Calculator

### ISSUE THREAD

**Issue by ishaa18** [Rakesh9100/CalcDiverse#655]
### Description

Fix the html code being displayed in the Armstrong Number Calculator as:
</label>

### Screenshots

![Screenshot (19)](https://github.com/Rakesh9100/CalcDiverse/assets/145281412/694872a2-c461-495a-8b42-7213e269d337)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Stranger1298** [comment]
Hey Can I move with this issue?

**Comment by VedaVarxha** [comment]
I would like to work on this issue under GSSOC'24. Please assign it to me

**Comment by YazhiniVenkatesan12** [comment]
Hi, I'm yazhini , a participant in GSSoC24. I would like to contribute to this project. I have experience with HTML,CSS,JAVASCRIPT and I'm interested in improving the armstrong calculator display html code. May I be assigned to the task?

Thank you!

**Comment by Rakesh9100** [comment]
Proceed @ishaa18

**Comment by ishaa18** [comment]
the pull request has already push on these issue the pr number is  #656
