### ISSUE TITLE
[Feature] Add ASCII Value Calculator

### ISSUE THREAD

**Issue by BagchiShreya** [Rakesh9100/CalcDiverse#657]
### Description

ASCII numbers prove to be really helpful in programming. This calculator would by a good addition to the website and people can come here and get the ASCII number of their desired characters.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by BagchiShreya** [comment]
I would like to work on this feature. This is for GSSoC'24 contribution.

**Comment by AshutoshVerma140404** [comment]
Good evening @Rakesh9100 Assign this project to me. I will make a nice calculator

**Comment by drashtiv03** [comment]
Hi,I am drashti.Can I get this issue under the label GSSoC'24?

**Comment by Rakesh9100** [comment]
Go ahead @BagchiShreya

**Comment by Rakesh9100** [comment]
Status of your PR pls @BagchiShreya

**Comment by umangpatel8123** [comment]
> Status of your PR pls @BagchiShreya

Can you assign mw this?

**Comment by Rakesh9100** [comment]
Do you want to be assigned @AshutoshVerma140404

**Comment by umangpatel8123** [comment]
Yess sir

**Comment by AkhilaSunesh** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24

**Comment by Rakesh9100** [comment]
Do you want to work @umangpatel8123

**Comment by Rakesh9100** [comment]
Go ahead @umangpatel8123
