### ISSUE TITLE
[Style] Enhance Palindrome Calculator UI

### ISSUE THREAD

**Issue by AkshaySobti** [Rakesh9100/CalcDiverse#659]
### Description

Hello @Rakesh9100 Sir,
Please assign me this issue.
I would like to change the design of the page for the palindrome checker, I will make changes to the background and the form that is currently being used to take input from the user.

This is for GSSoC'24 contribution.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by drashtiv03** [comment]
Hi,I am drashti.Can I get this issue under the label GSSoC'24?

**Comment by Rakesh9100** [comment]
Proceed @AkshaySobti

**Comment by Rakesh9100** [comment]
Status of your PR pls @AkshaySobti

**Comment by Rakesh9100** [comment]
Do you want to be assigned @drashtiv03

**Comment by AkhilaSunesh** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24

**Comment by Yuvraj960** [comment]
@Rakesh9100 Please assign this issue to me

**Comment by diyaaa19** [comment]
@Rakesh9100 I'd like to work on this issue,please assign it to me under gssoc'24,
thanks

**Comment by Rakesh9100** [comment]
Go ahead @diyaaa19
