### ISSUE TITLE
4 Band Resistance Calculator

### ISSUE THREAD

**Issue by amansgith** [Rakesh9100/CalcDiverse#66]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Overview
The Calculator will calculate the theoritical value of Resistance of a resistor using the 4 colour bands present on it.

Interface of Calculator
The UI of Calculator will have:
a) 4 drop down sections to select the colour of the bands.
b) Submit button

Functioning of Calulator
The calculator then will return the output resistance + tolerance value of the selected colour bands of a resistor with appropriate units inside a popup box.

Please assign this issue to me to work under the program of SocialWinterofCode'24
Thank you!!

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead!! @amansgith

**Comment by amansgith** [comment]
@Rakesh9100 will there be any problem in points calculation by quine for SWOC if you do not assign me this issue and I create the pr for it?

**Comment by Rakesh9100** [comment]
Assigned @amansgith
