### ISSUE TITLE
[Feature] Add Net Present Value Calculator

### ISSUE THREAD

**Issue by Manav173** [Rakesh9100/CalcDiverse#661]
### Description

The Net Present Value (NPV) calculator is a powerful financial tool designed to help users evaluate the profitability of an investment by calculating the present value of future cash flows.
Stylish UI: Implement modern CSS styling to improve the aesthetic appeal of the calculator, making it more visually engaging for users.
Responsive Design: Ensure that the NPV calculator is responsive and adapts well to various screen sizes and devices, including desktop computers, tablets, and mobile phones, to cater to a broader audience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Carry on @Manav173
