### ISSUE TITLE
[Bug] <write a small description here>

### ISSUE THREAD

**Issue by sahajoydeep** [Rakesh9100/CalcDiverse#662]
### Description

In the Armstrong Number Calculator for N-Digits calculation section, there is a bug where in the display text the <label> tag is showing.

I am Joydeep Saha, contributor from GSOC '24, and would love to work on your project and I can surely fix it, please allow me to do so.

### Screenshots

<img width="1440" alt="Screenshot 2024-05-11 at 1 20 43 AM" src="https://github.com/Rakesh9100/CalcDiverse/assets/88198830/3c32b5d3-30bc-41c4-b889-2db8c139a39e">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already opened before for this, please create new issues @sahajoydeep
