### ISSUE TITLE
[Feature] Add Reverse Polish Notation Calculator

### ISSUE THREAD

**Issue by animex007** [Rakesh9100/CalcDiverse#664]
### Description

# Title: Reverse Polish Notation (RPN) Calculator 

##   Overview
I'm proposing the development of a Reverse Polish Notation (RPN) calculator. RPN is a mathematical notation in which every operator follows all of its operands, providing a unique and efficient way of performing calculations. 

## Project Goals
The primary goal of this project will be to create a fully functional RPN calculator that can handle basic arithmetic operations as well as more complex mathematical functions. 

## Features
- Support for basic arithmetic operations (addition, subtraction, multiplication, division)
- Implementation of additional mathematical functions (trigonometric functions, logarithms, exponentiation)
- Error handling for invalid input and operations
- User-friendly interface (command-line or graphical)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by juniorcoder02** [comment]
hi project admin @Rakesh9100  i'm participant in Gssoc'24 and i am thrilled to be contributing to CalcDiverse. after reviewing the open issues, i'm particularly interested in rpn calculator as it aligns well with my skills and interests.                                                                                                                                       Could you please assign this issue to me? I'm eager to dive in and make a meaningful contribution to the project.

**Comment by Rakesh9100** [comment]
Proceed @animex007

**Comment by Rakesh9100** [comment]
Status of your PR pls @animex007

**Comment by animex007** [comment]
Almost complete ! ,Hitting the PR ASAP!
