### ISSUE TITLE
[Style] Change the font

### ISSUE THREAD

**Issue by aashkaaaaaa** [Rakesh9100/CalcDiverse#665]
### What's the style idea?

We need to improve
![image](https://github.com/Rakesh9100/CalcDiverse/assets/138461600/9a96cc5e-e328-4737-bb9b-46b1f3c4f3ca)

i can help with this , can assign me for this

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by YazhiniVenkatesan12** [comment]
Hi, I'm yazhini , a participant in GSSoC24. I would like to contribute to this project. I have experience with HTML,CSS,JAVASCRIPT and I'm interested in improving the font style. May I be assigned to the task?


Thank you!

**Comment by drashtiv03** [comment]
Hi, I am drashti.Can i get this issue for contributing in the project under the  GSSoC'24?

**Comment by hpishwe** [comment]
I have good command on HTML,CSS kindly assign it to me for GSsoc'24
