### ISSUE TITLE
[Feature] Add Travel Distance Calculator

### ISSUE THREAD

**Issue by AvinashShrivastav** [Rakesh9100/CalcDiverse#666]
### Description

This calculator provides users with the ability to calculate the distance between two locations, facilitating travel planning and route optimization. It offers a clear and concise solution for determining travel distances, aiding users in making informed decisions about their journeys.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AvinashShrivastav

**Comment by Rakesh9100** [comment]
How will you put the locations and what all factors will decide the calculation @AvinashShrivastav
