### ISSUE TITLE
[Adding conversion of units calculator] <A unit conversion expresses the same property as a different unit of measurement.>

### ISSUE THREAD

**Issue by bhavya-D** [Rakesh9100/CalcDiverse#667]
### Description

A unit conversion expresses the same property as a different unit of measurement. For instance, time can be expressed in minutes instead of hours, while distance can be converted from miles to kilometers, or feet, or any other measure of length

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by bhavya-D** [comment]
Please assign this task to me under GSSOC 24 
Thankyou

**Comment by Rakesh9100** [comment]
We already have Length Calculator, Weight Calculator and Time Calculator for these conversions, pls create new issues @bhavya-D
