### ISSUE TITLE
[Bug] Fix the link to open Currency Calculator

### ISSUE THREAD

**Issue by nagamukesh** [Rakesh9100/CalcDiverse#668]
### Description

I am unable to access the currency calculator as the page is not found
I can fix this issue
please assign this issue to me under GSSoC 2024

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/112798996/00b4d5c5-6e2b-4724-98e5-0ef9d5cd2f66)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @nagamukesh
