### ISSUE TITLE
[SWOC'24] Add contributors section

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/CalcDiverse#67]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- Enlist all the contributors on the main website
- Showcase them into a hexagonal grid structure of all the contributors

### Screenshots

Solution steps

- Using Javascript, fetching all the data of the contributors
- using css, maintain their styling and giving them a hexagonal grid structure of all the profiles

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this issue to me to work on it and contribute under SWOC'24
/assign

**Comment by Rakesh9100** [comment]
Go ahead @Avdhesh-Varshney
