### ISSUE TITLE
[Feature] Add Recipe Cost Calculator

### ISSUE THREAD

**Issue by EshaalakshmiDS** [Rakesh9100/CalcDiverse#670]
### Description

Enables users to input ingredients and quantities to calculate the total cost of a recipe, facilitating budget-friendly meal planning.

**Project Goals:**

Facilitate Budget-Friendly Meal Planning: The primary goal of the Recipe Cost Calculator is to empower users to plan meals within their budget by accurately estimating the total cost of a recipe based on the ingredients and quantities required.

**Features:**

- Ingredient Database: Maintain a comprehensive database of common ingredients along with their average prices, allowing users to select ingredients from a predefined list to streamline the input process.

- Custom Ingredient Input: Provide users with the flexibility to add custom ingredients not available in the database, enabling them to input specific items they have on hand or prefer to use.
- Quantity Adjustment: Allow users to adjust ingredient quantities based on their recipe variations or serving size preferences, with the cost dynamically updating to reflect the changes.
- Cost Calculation: Implement algorithms to calculate the total cost of the recipe based on the selected ingredients and their respective quantities, considering factors such as unit prices and measurement conversions.
- Cost Breakdown: Display a detailed breakdown of the recipe cost, showing the individual cost contribution of each ingredient as well as the total cost per serving or for the entire recipe.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by EshaalakshmiDS** [comment]
@Rakesh9100 I request you to please review and assign me this issue under GSSOC'24 label.

**Comment by Rakesh9100** [comment]
Go ahead @EshaalakshmiDS
