### ISSUE TITLE
[Feature] Add Shortest Path Calculator

### ISSUE THREAD

**Issue by nagamukesh** [Rakesh9100/CalcDiverse#671]
### Description

Given some points in a graph, one can calculate the single source shortest path using Dijkstra algorithm.
I can add this feature.
Please give me this issue under gssoc 2024.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/112798996/a408ae64-0d23-422c-9abb-f95a7917e461)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Status of your PR pls @nagamukesh

**Comment by nagamukesh** [comment]
Bro i am doing these calculators and I will try to complete them by tomorrow eod

**Comment by Yuvraj960** [comment]
@Rakesh9100 Please assign this issue to me

**Comment by Rakesh9100** [comment]
Carry on @Yuvraj960
