### ISSUE TITLE
[Feature]  Tip Calculator-Calculates the tip amount

### ISSUE THREAD

**Issue by m3kvt** [Rakesh9100/CalcDiverse#672]
### Description

The tip calculator will allow users to input the total bill amount and the desired tip percentage. Upon submission, it will calculate the tip amount and display the total bill amount including the tip. This feature will allow users to calculate tips quickly and accurately, streamlining their dining experience or any other scenario where tipping is involved.

User Interface:
- input fields for the bill amount and tip percentage
- button to calculate the tip
- accessible across different devices and screen sizes

### Screenshots

![Screenshot 2024-05-11 154801](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/09ae9d12-1328-41f9-90a5-4c7adce22e22)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by m3kvt** [comment]
Please add the gssoc and level tags on this issue and kindly assign me this issue.

**Comment by Rakesh9100** [comment]
Issue 629 is already open for this, you can comment there if you want to @m3kvt
