### ISSUE TITLE
[Style] Enhance social media icons with dynamic glow effect

### ISSUE THREAD

**Issue by ankitsinghbisht8** [Rakesh9100/CalcDiverse#673]
### Description

Adding a feature like a social media logo popup with glowing effects in different colors could enhance user engagement and interactivity on your platform. 
Right now it looks good right now but I can be enhanced with some tweaks by adding Dynamic Glow Effect , Hover Animation.
![Screenshot 2024-05-11 155441](https://github.com/Rakesh9100/CalcDiverse/assets/132978008/a4f21fd2-7d7b-4039-945b-bf8fd3ceafab)
![Screenshot 2024-05-11 155450](https://github.com/Rakesh9100/CalcDiverse/assets/132978008/b4faf9a0-b19b-4bbd-84f4-ad3f1b46378a)

### Screenshots

https://github.com/Rakesh9100/CalcDiverse/assets/132978008/94cffa00-ffc0-4939-9d5b-026f7fd6d2be

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Currently, it is looking good, but if you want to enhance then pls show some supporting screenshots @ankitsinghbisht8

**Comment by ankitsinghbisht8** [comment]
Yes, I agree it looks good, but it can be improved by changing the colors to match the social media icons. Additionally, making them pop up on hover would enhance the appearance.
![Screenshot 2024-05-23 135625](https://github.com/Rakesh9100/CalcDiverse/assets/132978008/ad6564b3-663f-43e5-a658-3c0594304981)
Something like this

**Comment by Rakesh9100** [comment]
Okay proceed @ankitsinghbisht8
