### ISSUE TITLE
[Feature] Add Depth Of Field Calculator

### ISSUE THREAD

**Issue by AtharvKasar04** [Rakesh9100/CalcDiverse#676]
### Description

This calculator helps photographers determine the depth of field (the range of distance that appears acceptably sharp in a photograph) based on factors such as aperture, focal length, subject distance, and sensor size.

@Rakesh9100 Can you please assign me this issue under GSSoC'24. 
I would love to work on this addition.

Thank You!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AtharvKasar04

**Comment by Rakesh9100** [comment]
Status of your PR pls @AtharvKasar04

**Comment by DiwareNamrata23** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24 @Rakesh9100

**Comment by diyaaa19** [comment]
@Rakesh9100 I'd like to work on this issue,please assign it to me under gssoc'24,
thanks

**Comment by Rakesh9100** [comment]
Proceed @diyaaa19
