### ISSUE TITLE
[Feature] Add Savings Goal Calculator

### ISSUE THREAD

**Issue by AtharvKasar04** [Rakesh9100/CalcDiverse#677]
### Description

This calculator assists users in determining how much they need to save regularly to reach a specific financial goal within a desired timeframe.

### Features:

- Goal setting
- Saving frequency, etc

@Rakesh9100 Can I please work on this addition under GSSoC'24. It would be great for me to work on this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AtharvKasar04

**Comment by ThakurPrad33p** [comment]
Assign me to improve the issues occured.

**Comment by Rakesh9100** [comment]
Status of your PR pls @AtharvKasar04

**Comment by AkhilaSunesh** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24

**Comment by Rakesh9100** [comment]
Hey @AkhilaSunesh Pls don't comment in each and every issue, complete your assigned issues first @AkhilaSunesh

**Comment by diyaaa19** [comment]
@Rakesh9100 I'd like to work on this issue,please assign it to me under gssoc'24,
thanks

**Comment by Rakesh9100** [comment]
Go ahead @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 please review and merge, thanks

**Comment by Rakesh9100** [comment]
Savings Calculator is already present, pls work on new issues @AtharvKasar04
