### ISSUE TITLE
[Feature] Add more units in Weight Calculator

### ISSUE THREAD

**Issue by Nehayp21242929** [Rakesh9100/CalcDiverse#678]
### Description

In Weight Calculator, there are only two units available, i would like to add some more units ,please assign this task to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24 @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @Nehayp21242929

**Comment by Rakesh9100** [comment]
Status of your PR pls @Nehayp21242929

**Comment by AkhilaSunesh** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24

**Comment by DiwareNamrata23** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24 @Rakesh9100

**Comment by diyaaa19** [comment]
@Rakesh9100 I'd like to work on this issue,please assign it to me under gssoc'24,
thanks

**Comment by Rakesh9100** [comment]
Go ahead @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
Thank you for assigning 😊 @Rakesh Roshan sir

**Comment by DiwareNamrata23** [comment]
[https://github.com/Rakesh9100/CalcDiverse/pull/1086](url)
