### ISSUE TITLE
[Feature] Add Weather Calculator

### ISSUE THREAD

**Issue by anagha-chaudhari** [Rakesh9100/CalcDiverse#679]
### Description

I wish to add the weather calculator which includes functions such as temperature conversion, calculating wind chill factor, dew point, heat index, human thermal comfort. Please assign this issue to me under GSSOC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @anagha-chaudhari
