### ISSUE TITLE
[Style]Changing the size of contact icon

### ISSUE THREAD

**Issue by alok1304** [Rakesh9100/CalcDiverse#681]
### What's the style idea?

The size of contact icon is not match with other icons which is present  at the bottom of the page. This looks not good. 

I attached the screenshot of that contact icon.
![Screenshot 2024-05-11 182829](https://github.com/Rakesh9100/CalcDiverse/assets/143247433/46215635-5977-4c71-9aff-e18df5d3d066)

Can you please assign me this issue under GSSoC'24, I really want to improve size of contact icon . If these contact icon size is matching with other icons then our website looks more better than previous ones..

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vardhini3103** [comment]
Hi. I have experience in HTML, CSS and Javascript. I would like to work on this project. Please assign it to me.

**Comment by SanaAzeem512** [comment]
@alok1304 Please assign this issue to me under GSSOC24

**Comment by hasmithagunda123** [comment]
Hey I am GSSOC COntributor Please assign me this issue to work on

**Comment by Rakesh9100** [comment]
Issue 644 is already open for this, pls create new issues @alok1304
