### ISSUE TITLE
[Style] Enhance Circular Prime Calculator UI

### ISSUE THREAD

**Issue by AnandK-pm** [Rakesh9100/CalcDiverse#682]
### Description

Making the circular prime calculator a bit more artistic and feature rich.

Currently the page looks out of alignment and haven't used the functionalities of CSS effectively. 
Please assign me the task so that i can make the page exquisite. (requesting as a part of GSSoC 2024)

### Screenshots

![Screenshot 2024-05-11 185349](https://github.com/Rakesh9100/CalcDiverse/assets/142206618/84fc79ac-863a-4b70-94e5-57683f68c08a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24 @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @AnandK-pm
