### ISSUE TITLE
[Bug] Fix the link to open Currency Calculator

### ISSUE THREAD

**Issue by AnandK-pm** [Rakesh9100/CalcDiverse#683]
### Description

currency calculator page is showing as not found .
Please assign me this issue so that i can make the currency calculator back to work. 
(Requesting as a part of GSSoC 2024 contribution)

### Screenshots

![Screenshot 2024-05-11 190134](https://github.com/Rakesh9100/CalcDiverse/assets/142206618/6b90ef49-2d16-4b5f-8194-2c6bf151e185)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 668 is already open for this, pls create new issues @AnandK-pm
