### ISSUE TITLE
[Bug] Fix multiple operators in Basic Calculator

### ISSUE THREAD

**Issue by tanu-agarwal0101** [Rakesh9100/CalcDiverse#685]
### Description

![basicCalc](https://github.com/Rakesh9100/CalcDiverse/assets/162132053/f62d8dee-e284-40f6-9735-ac1705d59c9f)
Multiple operators
Please assign me to fix this issue
(Under GSSOC'24 contributions)

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/162132053/57431436-981f-483b-862d-02899a63caff)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Suruchibharti** [comment]
hii @Rakesh9100 ,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by SoumyajitPr** [comment]
Hi, I would like to contribute on this project. I can help to fix this issue. Assign me this task, and I won't disappoint you. Thank you.

**Comment by Rakesh9100** [comment]
Go ahead @tanu-agarwal0101

**Comment by tanu-agarwal0101** [comment]
Thank you @Rakesh9100

**Comment by Rakesh9100** [comment]
Status of your PR pls @tanu-agarwal0101
