### ISSUE TITLE
[Feature] Add Loan Amount Calculator

### ISSUE THREAD

**Issue by manishh12** [Rakesh9100/CalcDiverse#686]
### Description

Generates an amortization schedule for loans, showing how payments are applied to principal and interest over the loan term.

1. Input Collection: Start by designing a form where users can input relevant details about their loan, including the loan amount, interest rate, loan term (in years or months), and start date.

2. Data Validation: Implement validation checks to ensure that users provide valid inputs, such as numerical values for loan amount and interest rate, and appropriate formats for dates.

3. Display Loan Amount : Display the loan amount after calculation.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rish-tech1** [comment]
kindly assign me this issue under gssoc'24
