### ISSUE TITLE
[Feature] Add relative grading option in Grade Calculator

### ISSUE THREAD

**Issue by A-b-i-r-a-m-i-G-S** [Rakesh9100/CalcDiverse#687]
### Description

@Rakesh9100 I would like to contribute to this repository as part of GSSOC'24. Currently the grade calculator only has absolute grading (based solely on an individual's score). I propose to add a relative grading calculator option which calculates the grade based on the average and standard deviation of the class' score. I believe it would be beneficial to provide users both options to calculate their grades.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @A-b-i-r-a-m-i-G-S

**Comment by Rakesh9100** [comment]
Status of your PR pls @A-b-i-r-a-m-i-G-S

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@Rakesh9100 it'll be ready by tomorrow...just finalizing the ui part
