### ISSUE TITLE
[Feature] Add Savings Calculator

### ISSUE THREAD

**Issue by krishan-07** [Rakesh9100/CalcDiverse#688]
### Description

Savings are very important in life.
A saving calculator is tool that helps you to estimate how much money you can accumulate over time by saving a certain amount regularly with a fixed interest rate

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by krishan-07** [comment]
please assign this task to me as GSSOC'24 contributor

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me under GSSoc'24 @Rakesh9100

**Comment by hasmithagunda123** [comment]
Hey I am GSSOC COntributor Please assign me this issue to work on

**Comment by Rakesh9100** [comment]
We already have `Expenditure And Savings Calculator`, what do you want to add @krishan-07

**Comment by krishan-07** [comment]
It will forecast how much money you can save in your bank(savings account) with periodical deposits (monthly, quarterly, yearly) with interest rate (specified by your bank) in some estimated time.

**Comment by Rakesh9100** [comment]
Okay, go ahead @krishan-07
