### ISSUE TITLE
[SWOC'24] Issue Templates

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/CalcDiverse#69]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Issue templates for your project like,
- Calculator Requrest
- Styling Request
- Documentation Request
- Bug Report
- New Features Request, etc.

### Screenshots

This will help contributors and maintainers both to segregate which are related either styling, new features, bug, etc.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this work to me to contribute in your repo under SWOC'24

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this task to me to contribute under SWOC'24 in your repository

**Comment by Rakesh9100** [comment]
Good thought, Go ahead @Avdhesh-Varshney

**Comment by Shaba1406** [comment]
This PR is reviewed and can be merged @Rakesh9100
