### ISSUE TITLE
[Style] Improving the Design of the Cards and the Specific Calculators

### ISSUE THREAD

**Issue by jasjeev013** [Rakesh9100/CalcDiverse#690]
### What's the style idea?

I will improve the cards with a background effect and a drop shadow. I will also design specific calculators page which  seems to be very normal. I will make them designer
Please Assign this issue to me & to add Gssoc, level1 labels

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Suruchibharti** [comment]
hii @Rakesh9100 ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by Rakesh9100** [comment]
Do you have any supporting screenshot @jasjeev013
