### ISSUE TITLE
[Style]: Address Layout and Functionality Issues in Individual Calculators on All-in-One Calculator Website

### ISSUE THREAD

**Issue by anurag-jaiswal-aj** [Rakesh9100/CalcDiverse#691]
### What's the style idea?

While the main website of the All-in-One Calculator functions properly, issues arise when navigating to individual calculators. These issues may include layout inconsistencies, functionality errors, or other usability concerns specific to each calculator. This issue aims to identify and address such issues within the individual calculator pages to ensure a seamless and reliable user experience across all sections of the website. By resolving these issues, we can enhance the overall usability and effectiveness of the All-in-One Calculator website. Kindly assign this task to me, and I'll work on identifying and rectifying the issues present within the individual calculator pages. Thank you for considering my contribution!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What issues exactly are you talking about, do you have any supporting screenshots @anurag-jaiswal-aj
