### ISSUE TITLE
[Feature] Add Air Quality Index Calculator

### ISSUE THREAD

**Issue by anusha7530** [Rakesh9100/CalcDiverse#692]
### Description

The Air Quality Index (AQI) Calculator will be a tool designed to provide users with real-time information about the air quality in their area. The calculator takes into account various air pollutants such as particulate matter (PM2.5 and PM10), ozone (O3), nitrogen dioxide (NO2), sulfur dioxide (SO2), and carbon monoxide (CO), and converts their concentrations into a single numerical value representing the overall air quality.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anjankumarkamalapur** [comment]
Hi, I would like to work on this, Could you please assign this to me?

**Comment by Rakesh9100** [comment]
This calculator is already present on the website, you can enhance that or add more features if you want @anusha7530
