### ISSUE TITLE
[Style] Add icons in BMI Calculator

### ISSUE THREAD

**Issue by Vikashchou-dhary** [Rakesh9100/CalcDiverse#693]
### What's the style idea?

we can add icons of male and female in BMI calculator webpage to improve user experience

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vikashchou-dhary** [comment]
hello sir,
I can solve this issue,please assign it to me

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me.

**Comment by Rakesh9100** [comment]
Proceed @Vikashchou-dhary

**Comment by Rakesh9100** [comment]
Status of your PR pls @Vikashchou-dhary
