### ISSUE TITLE
cpi/cgpa calculator

### ISSUE THREAD

**Issue by abhay-sen** [Rakesh9100/CalcDiverse#695]
### Description

this calculator would simply add a new calculator that would calculate a students cpi based on the total number of credits and then for each subject would take the total credits and the score recieved out of 10 and give the cpi for that

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Tanishka023** [comment]
Hey there! I am excited to contribute to this project; please assign it to me. @Rakesh9100

**Comment by savyaaa** [comment]
Hi! I'd like to contribute to this project under GSSOC'24. Please assign this to me.

**Comment by govinddwivedigit** [comment]
Can you assign this to me ?

**Comment by SoumyajitPr** [comment]
Hi, I would like to contribute on this project. I can help to fix the issue. Assign me this task, and I won't disappoint you. Thank you.

**Comment by Rakesh9100** [comment]
We already have GPA Calculator for this, pls create new issues @abhay-sen
