### ISSUE TITLE
[Feature] Add join us form

### ISSUE THREAD

**Issue by sau-mili** [Rakesh9100/CalcDiverse#696]
### Description

A form with basic details below, join us option for user. Please assign this issue

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ankiiitagupta** [comment]
@Rakesh9100 please assign this task to me under GSSOC'24. I would love to work on this project's issue and will not disappoint you.

**Comment by aasthax1** [comment]
Please assign this task to me under GSSOC'24. I am very much confident that i will solve this isuue in a very good manner. 
Thank you.

**Comment by Rakesh9100** [comment]
What exactly are you trying to specify @sau-mili

**Comment by sau-mili** [comment]
A form that collects email address to send updates

**Comment by Rakesh9100** [comment]
No need of this, pls create and work on good issues @sau-mili
