### ISSUE TITLE
Create a login and Signp page for the whole site

### ISSUE THREAD

**Issue by Sayanmaity2003** [Rakesh9100/CalcDiverse#697]
### What's the style idea?

I am capable of building a responsive and interactive login page for the site please assign this to me with lebels

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by savyaaa** [comment]
Hi! It's an amazing project and I'd like to contribute to it under GSSOC'24. Please assign this to me.

**Comment by drashtigit** [comment]
I would like to contribute .Can you please assign me this issue under GSSOC'24.

**Comment by Ashishranjan0901** [comment]
I would like to contribute in this issue .Can you please assign it to me .

**Comment by Rakesh9100** [comment]
We don't need this, pls work on good issues @Sayanmaity2003
