### ISSUE TITLE
Triangle Calculator

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/CalcDiverse#70]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The user can input any three values among the six values representing angles and sides in a triangle.

**Output:**
- Upon entering these values, the calculator will compute and output the remaining three values.
- The system will also provide the following details:
  - Type of triangle
  - Visual representation of the triangle
  - Area
  - Perimeter
  - Semiperimeter
  - Inradius
  - Circumradius
  - Height of the triangle from its three bases
  
  I am attaching the screenshots below, their UI is not that great. Styling can be improved too.

### Screenshots

Input:
![image](https://github.com/Rakesh9100/CalcDiverse/assets/92045934/c121b6d8-f54d-4d2b-ba4f-6823fb2bb4c4)

Output:
![image](https://github.com/Rakesh9100/CalcDiverse/assets/92045934/a4ec9b71-fa5f-4f80-af2d-473f07f94ac2)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Yatin12527** [comment]
Assign it to me

**Comment by Rakesh9100** [comment]
Go ahead @kom-senapati

**Comment by Rakesh9100** [comment]
Unassigning you as told @kom-senapati 

Assigning you @Yatin12527 Proceed
