### ISSUE TITLE
[Feature] Add 5 Band Resistance Calculator

### ISSUE THREAD

**Issue by AkhilaSunesh** [Rakesh9100/CalcDiverse#700]
### Description

It is useful for Electrical and electronics engineering.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AkhilaSunesh

**Comment by Rakesh9100** [comment]
Pls provide your PR for this issue @AkhilaSunesh
