### ISSUE TITLE
[Feature] Add Capacitor Conversion Calculator

### ISSUE THREAD

**Issue by AkhilaSunesh** [Rakesh9100/CalcDiverse#701]
### Description

Highly useful for calculating the Capacitance values offered by a capacitor

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Carry on @AkhilaSunesh

**Comment by Rakesh9100** [comment]
Status of your PR @AkhilaSunesh

**Comment by AkhilaSunesh** [comment]
In progress. I will complete by the end of this week
