### ISSUE TITLE
[Bug] Fix the visibility of scroll to top icon

### ISSUE THREAD

**Issue by gaddevinay** [Rakesh9100/CalcDiverse#703]
### Description

Here scroll to top button symbol is not showing
Can you please assign to me and label it.

I am a GSSOC'24 contributor 

### Screenshots

![Screenshot_20240512-085308](https://github.com/Rakesh9100/CalcDiverse/assets/128584849/501eb4ee-409d-4f28-b7be-2e122670d9bd)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Suruchibharti** [comment]
hey,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/92800790-4678-4ece-9c81-f8328725db98)

The button is clearly visible on my end. Please check from your side using a different browser; there might be an issue on your end @gaddevinay
