### ISSUE TITLE
[Feature] Add Net Run Rate (NRR) option in Cricket Calculator

### ISSUE THREAD

**Issue by Ashish-1020** [Rakesh9100/CalcDiverse#704]
### Description

Add a new option to calculate the net run rate for a match.
Pls assign me this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Ashish-1020
