### ISSUE TITLE
[Feature] Add more operations in Bitwise Calculator

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#705]
### Description

I want to add feature for calculating NAND, NOR, & XNOR operations. Could you please assign it to me under gssoc label.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Status of your PR @agastya3636

**Comment by agastya3636** [comment]
Working
