### ISSUE TITLE
[Feature] Add more functionality in Vector Calculator

### ISSUE THREAD

**Issue by MohiniMehta** [Rakesh9100/CalcDiverse#706]
### Description

I just checked the vector calculator. The vector calculator is only calculating the dot product between 2 vectors. But operations like cross product between the 2 vectors, addition and subtraction can be done on it. 
I request to assign this task to me.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/98202405/ace75a3e-8c4d-446f-a25e-3937deb299a8)
here it is showing only the dot product and angle between it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @MohiniMehta
