### ISSUE TITLE
[binary to decimal or other operations] <write a small description here>

### ISSUE THREAD

**Issue by prajwaldp223** [Rakesh9100/CalcDiverse#707]
### Description

converting the binary to hexa, octa or deci  

### Screenshots

![Screenshot 2024-05-12 172323](https://github.com/Rakesh9100/CalcDiverse/assets/145866141/f9ead545-86e7-4a55-b0be-02cf6f812d3d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Number System Calculator for this, pls create new issues @prajwaldp223
