### ISSUE TITLE
[Feature] Add the wave generator of Fourier series

### ISSUE THREAD

**Issue by AnujaG1** [Rakesh9100/CalcDiverse#708]
### Description

https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Fourier_series_square_wave_circles_animation.gif/224px-Fourier_series_square_wave_circles_animation.gif.   the output looks like the link provided above.

### Screenshots

![Screenshot from 2024-05-12 17-56-17](https://github.com/Rakesh9100/CalcDiverse/assets/132633159/3ae55b41-3764-4279-a4e0-23b215254d93)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Can you specify clearly that where do you want to add this @AnujaG1
