### ISSUE TITLE
[Bug] Fix performance degradation when scrolling

### ISSUE THREAD

**Issue by khandelwalaastha** [Rakesh9100/CalcDiverse#709]
### Description

I've noticed a performance issue with our website when scrolling, particularly when loading multiple types of calculator cards. The scrolling behavior feels sluggish, and there's a noticeable delay in loading the calculator cards, leading to a poor user experience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by khandelwalaastha** [comment]
pls assign this issue to me under gssoc24

**Comment by Rakesh9100** [comment]
What exactly problem are you facing as it seems fine on the website @khandelwalaastha
