### ISSUE TITLE
Trigonometric Calculator

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/CalcDiverse#71]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

A calculator can be developed for the following calculations.
Basic Trigonometric Functions:
- sine (sin)
- cosine (cos)
- tangent (tan).
- cosecant (csc)
- secant (sec)
- cotangent (cot).
Inverse Trigonometric Functions:
- arcsine (asin)
- arccosine (acos)
- arctangent (atan).
- arccosecant (acsc)
- arcsecant (asec)
- arccotangent (acot).

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/92045934/a99b816c-2850-4e79-8675-e2d289f946f9)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed!! Try making good UI and use some spacings as well @kom-senapati
