### ISSUE TITLE
[Feature] Add Pipe Flow Calculator

### ISSUE THREAD

**Issue by nehavaishnav** [Rakesh9100/CalcDiverse#710]
### Description

A pipe flow calculator will solve for fluid velocity, flow rate, and diameter of the pipe. This will be beneficial in fluid dynamics-related calculations. I am a GSSOC contributor. Kindly assign this issue to me

### Screenshots
![image](https://github.com/Rakesh9100/CalcDiverse/assets/142627015/71348e92-636b-4364-a71e-00b98e346917)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the name of your calculator @nehavaishnav

**Comment by nehavaishnav** [comment]
@Rakesh9100 It will be named as pipe flow calculator.

**Comment by Rakesh9100** [comment]
Go ahead @nehavaishnav

**Comment by Yuvraj960** [comment]
@Rakesh9100 Please assign this issue to me

**Comment by Rakesh9100** [comment]
Go ahead @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 I have checked the PR commits of the previous contributor. I understand that his code is copied. But want you to clarify that what if I optimize the code of the previous contributor by deleting the waste blocks of code as his code is alright but needs some repairs. If you want, then I can code it from scratch also.
