### ISSUE TITLE
[Feature] Number of moles of substance & number of electron , proton and neutron calculator.

### ISSUE THREAD

**Issue by govinddwivedi-git** [Rakesh9100/CalcDiverse#712]
### Description

1. Input: The user inputs the mass of the substance and its molar mass (in grams per mole).

2. Calculate Moles: The calculator calculates the number of moles of the substance.

3. Calculate Number of Electrons, Protons, and Neutrons: This part depends on the substance. If the substance is an atom (not an ion), you can determine the number of electrons, protons, and neutrons based on its atomic number (Z) and mass number (A).

   - Number of protons (Z) = atomic number (provided for each element)
   - Number of electrons (Z) = number of protons (for a neutral atom)
   - Number of neutrons (N) = mass number (A) - number of protons (Z)

4. Output : The calculator displays the number of moles of the substance, as well as the number of electrons, protons, and neutrons.

5. Optional Features:
   - Error Handling: Ensure the user inputs valid values and handle any potential errors gracefully.
   - Support for Ions: Extend the calculator to handle ions by allowing the user to input the charge, which would affect the number of electrons.
   - Interactive Interface: Develop a user-friendly interface that guides the user through the process step by step.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by govinddwivedigit** [comment]
Can you assign this issue to me ?

**Comment by Rakesh9100** [comment]
Can you pls tell the proper name for your calculator @govinddwivedi-git

**Comment by govinddwivedi-git** [comment]
"Atomic Composition Calculator" @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @govinddwivedi-git

**Comment by Rakesh9100** [comment]
Pls provide your PR @govinddwivedi-git

**Comment by Rakesh9100** [comment]
Go ahead @debangi29

**Comment by Rakesh9100** [comment]
Pls provide your PR @debangi29

**Comment by bharat-c27** [comment]
Hello @Rakesh9100, please assign me the issue I can work on this.

**Comment by Rakesh9100** [comment]
Go ahead @bharat-c27

**Comment by Rakesh9100** [comment]
Pls provide your PR @bharat-c27

**Comment by bharat-c27** [comment]
Sure, I am working on it.
I will provide you tomorrow
