### ISSUE TITLE
Search Bar can be added

### ISSUE THREAD

**Issue by AyushShukla3466** [Rakesh9100/CalcDiverse#714]
### Description

A search bar at top right corner can be added to easily search and find the desired one

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rish-tech1** [comment]
kindly assign me this issue under gssoc'24

**Comment by Suruchibharti** [comment]
hii @Rakesh9100 ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by Rakesh9100** [comment]
A search bar is already present which is fine, we don't need a more search bar anywhere! Pls work on other issues @AyushShukla3466
