### ISSUE TITLE
[Feature] Add the feedback section to the website

### ISSUE THREAD

**Issue by AyushShukla3466** [Rakesh9100/CalcDiverse#715]
### Description

A feedback section will make this site more engaging for the users visiting this site

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls describe your idea properly with supporting screenshots @AyushShukla3466
