### ISSUE TITLE
[Docs] Open Source Programs list update

### ISSUE THREAD

**Issue by d1vyadharsh1n1** [Rakesh9100/CalcDiverse#716]
### Category of documentation update

Update the Open Source Programs in README.

### Describe the change you think might work

I would like to add that the project comes under GSSoc'24 in the Open Source Programs.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by 21atha** [comment]
I am a gssoc contributor, I would like to work on this issue, it will be helpful , if you add the label for gssoc and level of issue

Thank you

**Comment by Akshitha28112004** [comment]
Hey, I've already done this for another project. Please feel free to check it out in my profile. So can you please assign me this issue under gssoc'24?

**Comment by Rakesh9100** [comment]
Proceed @d1vyadharsh1n1

**Comment by d1vyadharsh1n1** [comment]
I sincerely apologize for the delay. Let me know for any changes @Rakesh9100
