### ISSUE TITLE
[Style] Add a little hover effect

### ISSUE THREAD

**Issue by karishmaaa101** [Rakesh9100/CalcDiverse#717]
### Description

On bringing the arrow to the icons and headings of the navbar, it would look good if there was a little animation and a hover effect.

Tasks:
I'm a GSSOC'24 contributor

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/104766763/61dae06b-a405-4ff5-826a-c9199ef9fa9f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by karishmaaa101** [comment]
Assign me this issue.

**Comment by AyushiiiJain** [comment]
Please assign me this issue.

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot that what kind of hover effect you want to add @karishmaaa101
