### ISSUE TITLE
[Style] Improve the text color in Contact form

### ISSUE THREAD

**Issue by dhruv8433** [Rakesh9100/CalcDiverse#718]
@Rakesh9100 
### What's the style idea?

We need to improve
![image](https://github.com/Rakesh9100/CalcDiverse/assets/114583978/0e8d3bfe-726a-4623-b88d-e9f179fde45b)

we can create something like this 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/114583978/d137abcb-3a2d-4cc1-a2aa-7034e3ccc709)

i'm GSSOC'24 Contributor

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GauriGA** [comment]
@Rakesh9100 Could you please assign this issue to me under the GSSOC'24 label?

**Comment by dhruv8433** [comment]
@Rakesh9100 please response !!!

**Comment by Rakesh9100** [comment]
Okay proceed but make sure to match the UI @dhruv8433

**Comment by Amrapali06** [comment]
@Rakesh9100 can you please assign me this issue if not completed

**Comment by dhruv8433** [comment]
@Rakesh9100 thank you
