### ISSUE TITLE
[Style] Enhance CGPA Percentage Calculator UI

### ISSUE THREAD

**Issue by KanodiaKash** [Rakesh9100/CalcDiverse#719]
### What's the style idea?

We need to improve css for cgpa-percentage-calculator page as there is none currently. This will enhance user experience and uniformity.
I am a GSSOC'24 contributor

Can you please assign this task to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by KanodiaKash** [comment]
<img width="1470" alt="Screenshot 2024-05-13 at 4 15 48 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/143932704/46568106-02d0-498c-9d0c-8feb96ee1e82">
Attaching current layout for https://calcdiverse.netlify.app/calculators/cgpa-percentage-calculator/

**Comment by KanodiaKash** [comment]
Can you please assign this task to me.

**Comment by AmruthaPariprolu** [comment]
hey can you pls assign me with this issue under gssoc'24

**Comment by rounakdey6** [comment]
Please assign this work to me, I would love to contribute to this issue

**Comment by KanodiaKash** [comment]
@Rakesh9100 - Can you please assign this to me
