### ISSUE TITLE
Enhance UI of Days Calculator

### ISSUE THREAD

**Issue by pankhuri92** [Rakesh9100/CalcDiverse#72]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The background is not that subtle and uniformity in styling. I would like to enhance it. @Rakesh9100 kindly assign me the issue under SWOC'24

### Screenshots

![Screenshot 2024-01-03 134934](https://github.com/Rakesh9100/CalcDiverse/assets/138357063/92da9023-b1e0-4c5b-a82c-4daf0ff176aa)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @pankhuri92

**Comment by pankhuri92** [comment]
Thanks @Rakesh9100 !
