### ISSUE TITLE
[Style] Enhance the navbar and logo

### ISSUE THREAD

**Issue by 39palakved** [Rakesh9100/CalcDiverse#721]
### Category of documentation update

Navbar

### Describe the change you think might work

I will reduce padding and add hover and change  font and will add good logo 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by 39palakved** [comment]
Thank you so much @Rakesh9100

**Comment by SantoshiVerma** [comment]
hey @Rakesh9100 I would like to work on this issue under gsssoc2024.Please assign this to me.

**Comment by Ipeeka** [comment]
I would like to work on this project.please assign to me.

**Comment by AmruthaPariprolu** [comment]
hey @Rakesh9100 
can you pls assign me with this issue  under gssoc'24

**Comment by AyushiiiJain** [comment]
I would love to contribute in this project. @Rakesh9100 please assign me this issue.

**Comment by rounakdey6** [comment]
I would love to work on this issue , Please assign this work to me

**Comment by Rakesh9100** [comment]
Logo and nav bar styling is good, pls work on good issues @39palakved
