### ISSUE TITLE
[Feature] Add Velocity Acceleration Calculator

### ISSUE THREAD

**Issue by PriyanshuValiya** [Rakesh9100/CalcDiverse#722]
### Description

I Want To Add Simple Physics Calculator, Which Can Takes Distance And Returns Velocity And Acceleration To Users.

### Screenshots
![Screenshot 2024-05-14 215708](https://github.com/Rakesh9100/CalcDiverse/assets/147643182/1d5d2fde-5f7b-46d5-8bea-cf04c95c1677)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the name for your calculator @PriyanshuValiya

**Comment by PriyanshuValiya** [comment]
Name : Distance - Velocity Converter.
