### ISSUE TITLE
[Feature] Add rupees value in Real Estate Calculator

### ISSUE THREAD

**Issue by Vedanshi-Arya** [Rakesh9100/CalcDiverse#723]
### Description

The real estate calculator calculates the mortgage value only in dollars. I want to add a feature of providing the value also in rupees for better understanding.  @Rakesh9100 please assign me this issue so that I can proceed further for better output.

### Screenshots

<img width="960" alt="real estate" src="https://github.com/Rakesh9100/CalcDiverse/assets/142818538/ee034a9c-cc3f-4d83-9726-2ea31af8d6ff">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Vedanshi-Arya

**Comment by Rakesh9100** [comment]
Status of your PR @Vedanshi-Arya

**Comment by Rakesh9100** [comment]
Status of your PR pls @Vedanshi-Arya

**Comment by Vedanshi-Arya** [comment]
I will do it tomorrow for sure

**Comment by Rakesh9100** [comment]
Provide your PR @Vedanshi-Arya

**Comment by HJ2207** [comment]
I would like to work on this issue. Can you please assign it to me under gssoc and also provide level tag.

**Comment by Rakesh9100** [comment]
Proceed @HJ2207 

Level label will be added after the PR is up!

**Comment by Vedanshi-Arya** [comment]
I am ready with my pr.I was facing some issues that are resolved. please
again assign me this issue
