### ISSUE TITLE
[Feature] Add Resonant Frequency Calculator, Power Factor Calculator

### ISSUE THREAD

**Issue by Prerna200-ctr** [Rakesh9100/CalcDiverse#724]
### Description

There are some more calculators that can be added to the above list

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Prerna200-ctr** [comment]
Please assign these tasks to me. I am new to open source world, and want to contribute in such projects

**Comment by Rakesh9100** [comment]
You can add one calculator in this issue, so which calculator do you want to add @Prerna200-ctr
