### ISSUE TITLE
[Feature] Add the testimonial section

### ISSUE THREAD

**Issue by Anamika-Ratna** [Rakesh9100/CalcDiverse#726]
### Description

I would like to add a testimonial section, kindly assign me this issue under gssoc tag.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Kiran-pande-30** [comment]
@Rakesh9100 Can we labels for GSSOC'24 for all the issues...

**Comment by Chanc2206** [comment]
![Screenshot 2024-05-15 004230](https://github.com/Rakesh9100/CalcDiverse/assets/123469088/903bc298-770a-41f2-b480-ab07e0bda3fa)
Hello @Rakesh9100 , I’ve created a basic testimonial. Please assign me the issue so I can continue working on it.

**Comment by Anamika-Ratna** [comment]
Hi @Rakesh9100 , Kindly review the changes I have made.
#809

**Comment by Rakesh9100** [comment]
We don't need testimonial section for now, pls work on other issues @Anamika-Ratna
