### ISSUE TITLE
[Feature] Add theme change in Aspect Ratio Calculator

### ISSUE THREAD

**Issue by Bindusree1515** [Rakesh9100/CalcDiverse#727]
### Description

Currently, the Aspect Ratio Calculator only supports a dark mode interface. To enhance user experience and accommodate different preferences, it would be beneficial to implement a light mode option.

### Screenshots

![Screenshot 2024-05-14 173512](https://github.com/Rakesh9100/CalcDiverse/assets/91887086/46ccbf6e-bd47-4c38-b7ec-0835c4de40b6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Bindusree1515** [comment]
@Rakesh9100 Please assign this issue to me under GSSOC'24.

**Comment by Rakesh9100** [comment]
Go ahead @Bindusree1515

**Comment by Bindusree1515** [comment]
I sir , I am currently out of station , im unable to clone the project due
to network issues here , please give me 3-4 days, I will complete.

I am so sorry for the inconvenience sir

Thank you so much !

**Comment by Rakesh9100** [comment]
Provide your PR @Bindusree1515

**Comment by Bindusree1515** [comment]
I am so sorry for the inconvenience,  I am stuck in a village,
I am really so so sorry,even I want to contribute but I tried my best but I
am unable to ... so sorry n thank you for understanding

**Comment by Yuvraj960** [comment]
@Rakesh9100 Please assign this issue to me

**Comment by Rakesh9100** [comment]
Proceed @Yuvraj960
