### ISSUE TITLE
[Feature] <Adding new Calculator> Number to Binary Form

### ISSUE THREAD

**Issue by sshivangi882** [Rakesh9100/CalcDiverse#728]
### Description

Adding a calculator which will convert numbers to binary form.
Assigned me under GSSOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ShahHetviIT** [comment]
I'm eager to lead the CalcDiverse project. With a solid background in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to make substantial contributions to this project. Could you please assign me to this issue through GSSOC?

**Comment by Rakesh9100** [comment]
We already have Number System Calculator for this, pls create new issues @sshivangi882
