### ISSUE TITLE
[Feature] Add Black Hole Number Calculator

### ISSUE THREAD

**Issue by nilamkumari11** [Rakesh9100/CalcDiverse#729]
### Description

Black Hole number Calculator is a simple fun calculator that takes whatever number you give and at last always the ends at four. Number 4 is referred to as Black Hole number because every word you spell will end in Four.

For Example :
User input : 6
6 in Words : Six
Count of Letters : 3
3 in Words : Three 
Count of Letters : 5
5 in Words : Five
Count of Letters : 4
4 in Words : Four 

Please assign me under  GSSOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @nilamkumari11
