### ISSUE TITLE
Enhance UI of multiplication calculator

### ISSUE THREAD

**Issue by pankhuri92** [Rakesh9100/CalcDiverse#73]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100 can you please assign me the issue to fix the styling of this page.

### Screenshots

![Screenshot 2024-01-03 135217](https://github.com/Rakesh9100/CalcDiverse/assets/138357063/5905111d-f7b8-4f73-90c8-9ee5d388a507)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @pankhuri92

**Comment by pankhuri92** [comment]
Okay thanks @Rakesh9100 !

**Comment by Shaba1406** [comment]
@pankhuri92 Hey, how is the work going on ? What's the update ?
