### ISSUE TITLE
[Feature] Add Anagram Calculator

### ISSUE THREAD

**Issue by ImmidiSivani** [Rakesh9100/CalcDiverse#730]
### Description

Anagram Calculator is used to check for 2 strings whether one string can be rearranged to get another string and vice versa
for example:
string 1:listen
string 2:silent
we can rearrange the letters in string 1 to get string 2, and we can rearrange the letters in string 2 to get string 1
so the output will be ANAGRAM

 Please assign me under GSSOC'24 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by usharani222** [comment]
assign me this issue

**Comment by Rakesh9100** [comment]
Proceed @ImmidiSivani
