### ISSUE TITLE
[Style] Enhance 2D Distance Calculator UI

### ISSUE THREAD

**Issue by KaushikaDash04** [Rakesh9100/CalcDiverse#734]
### What's the style idea?

We need to add few animations to make the individual calculators attractive

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by KaushikaDash04** [comment]
I want to work on this

**Comment by Rakesh9100** [comment]
For which calculator you want to add the animation, pls specify properly @KaushikaDash04

**Comment by KaushikaDash04** [comment]
The distance calculator so that it can be visualized easily.And different ranges of people can use the website.

**Comment by Rakesh9100** [comment]
Provide your PR @KaushikaDash04

**Comment by Rakesh9100** [comment]
Go ahead @Rishikesh63
