### ISSUE TITLE
[Feature] Add root calculator

### ISSUE THREAD

**Issue by Sandhyarani23** [Rakesh9100/CalcDiverse#736]
### Description

equation details are taken and result we give roots real,distinct and the roots

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Quadratic and Cubic Equation Calculators, you can add any feature in those if you want to @Sandhyarani23
