### ISSUE TITLE
[Bug]PAGE NOT FOUND ERROR

### ISSUE THREAD

**Issue by Sp-177** [Rakesh9100/CalcDiverse#737]
### Description

trying out the currency calc but the page not found error

### Screenshots

![Screenshot 2024-05-16 021548](https://github.com/Rakesh9100/CalcDiverse/assets/138980314/8f1c1780-e25c-4e4e-957d-460f1f8252c6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sp-177** [comment]
@Rakesh9100 please let me grab this opportunity and let me fix this error ,and please label it GSSOC

**Comment by Rakesh9100** [comment]
Issue is already opened previously for this, pls check properly before creating new one @Sp-177
