### ISSUE TITLE
[Feature] Add icons in the footer links

### ISSUE THREAD

**Issue by SadafKausar2025** [Rakesh9100/CalcDiverse#738]
### Description

This features beautify the footer section.

### Screenshots

before
![Screenshot 2024-05-16 125317](https://github.com/Rakesh9100/CalcDiverse/assets/137484958/6dde8d4e-a2cf-4a9d-9245-af2132b1b66e)

after
![Screenshot 2024-05-16 125258](https://github.com/Rakesh9100/CalcDiverse/assets/137484958/8344a51f-a54e-47fa-bfeb-f73e86339b7c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.\
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SadafKausar2025** [comment]
can you please assign this issue to me #738?

**Comment by suhani-sharmaa** [comment]
can you please assign me this issue

**Comment by mb-aarfi** [comment]
@Rakesh9100 can you assign this issue to me please. I will be very thankful to you.

**Comment by Rakesh9100** [comment]
Proceed @SadafKausar2025
