### ISSUE TITLE
[Style] Enhance the color of a card

### ISSUE THREAD

**Issue by aaryancodeshere** [Rakesh9100/CalcDiverse#745]
### What's the style idea?

# The light green background is making the text on the main page unreadable.

We need to improve the background and text of the middle section below the search calculator section on the home page.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aaryancodeshere** [comment]
<img width="380" alt="Screenshot 2024-05-16 at 5 17 09 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/124273822/b5878577-43c3-45bb-9572-a35bb0960e2c">

**Comment by S2103aumya** [comment]
please assign this to me as  GSSOC'24 contributor

**Comment by Rakesh9100** [comment]
Which color combination do you want to use @aaryancodeshere

**Comment by aaryancodeshere** [comment]
<img width="271" alt="Screenshot 2024-05-24 at 1 54 32 AM" src="https://github.com/Rakesh9100/CalcDiverse/assets/124273822/8fbca69c-c081-4295-b10d-d602cadecba8">
<img width="403" alt="Screenshot 2024-05-24 at 1 55 22 AM" src="https://github.com/Rakesh9100/CalcDiverse/assets/124273822/dfbe70f1-4c89-4ee4-b391-cb577c16a24c">
This could work @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay proceed @aaryancodeshere
