### ISSUE TITLE
Adding Day and night toggle button

### ISSUE THREAD

**Issue by Suvam3456** [Rakesh9100/CalcDiverse#746]
### Description

I would like to add icons of day and night in the navbar which can be used by user for dark or light background.

### Screenshots

Example from any random website how icon of sun and moon will look,

![image](https://github.com/Rakesh9100/CalcDiverse/assets/99579881/7d65fe05-4858-4c4c-90d2-275aed7be00d)

![image](https://github.com/Rakesh9100/CalcDiverse/assets/99579881/ff42faf2-8622-47e4-90bd-8e54c2ee8b48)

I can customise UI according to your demands. 

@Rakesh9100  Assign me under GSSOC'24 and add label of level as well .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.

**Comment by Rakesh9100** [comment]
Issue 515 is already open for this, you can comment there and tell your implementation idea @Suvam3456
