### ISSUE TITLE
[Feature] Implement navbar and footer in each calculator's page

### ISSUE THREAD

**Issue by Suvam3456** [Rakesh9100/CalcDiverse#747]
### Description

Hello Project Admin,
On using any Calculator, we are directed to a page which lacks Navbar and Footer which causes difficulty for user to go back to main/Home page. I can add Navbar and Footer in all the Calculator pages.

### Screenshots

Example : In below image No navbar is there, so user cannot go back to Home page directly from this page.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/99579881/63bab109-dc8e-4a61-9104-104f74eaec28)

@Rakesh9100 Assign me under GSSOC'24 and add label of level as well so that i can get points for my work.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Since there are many calculator and new calculators also keeps on adding, so it is not advised to put nav bar and footer on each calculator's page @Suvam3456
