### ISSUE TITLE
Improve the UI of the website

### ISSUE THREAD

**Issue by priyankaa-2004** [Rakesh9100/CalcDiverse#75]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I can improve the website interface and make it more visually appealing and user-friendly by using:
Better color pallet
Simple and minimalistic fonts and icons
Smooth transitions and hover effects and a,
Responsive Design.
![Tic tac toe old](https://github.com/Rakesh9100/CalcDiverse/assets/127417192/55c23340-b879-4767-91ea-345fcec65c3c)
![Tic tac toe new](https://github.com/Rakesh9100/CalcDiverse/assets/127417192/14274961-ad3f-4fb5-aa8f-80fd70d93369)

### Screenshots

These are some before and after screenshots of a project and it shows how I improved the UI of the game website by making suitable changes.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by PARKER-X** [comment]
@Rakesh9100 Assign This issue

**Comment by Rakesh9100** [comment]
Can you provide some kind of samples enhancements you have done to any proper website or provide any screenshot of ideas you are having to change this website UI @priyankaa-2004

**Comment by Rakesh9100** [comment]
Do you want to work @priyankaa-2004

**Comment by priyankaa-2004** [comment]
@Rakesh9100  Yes I want to work on it and here are some of the projects I did on my own:-
A coffee shop website: priyankaa-2004.github.io/the-coffee-nook/
My Portfolio: priyankaa-2004.github.io/portfolio/

**Comment by Rakesh9100** [comment]
These website are showing "Site not found" @priyankaa-2004 
Provide me the proper link.

**Comment by Rakesh9100** [comment]
Okay, I saw your websites. Looking forward for the best UI!!

Assigning you, proceed @priyankaa-2004

**Comment by priyankaa-2004** [comment]
Thank you sir!

**Comment by priyankaa-2004** [comment]
Sir, Should I change the footer style and the card style (when you open the card) ?

**Comment by Rakesh9100** [comment]
Yes, you can do every necessary changes which suits and according to your new UI @priyankaa-2004 

Modify contact page as well @priyankaa-2004

**Comment by priyankaa-2004** [comment]
Okay, I will!
