### ISSUE TITLE
Links not working on home page

### ISSUE THREAD

**Issue by kashisharora9462** [Rakesh9100/CalcDiverse#753]
### Description

Links on home page are not working . Please assign me the job ,i can rectify it.

### Screenshots

![im](https://github.com/Rakesh9100/CalcDiverse/assets/153215875/4339a77f-88fb-492d-bf41-a9e39f8cf8af)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Manish12-verma** [comment]
Please assign me the job ,i can rectify it.

**Comment by Aarzookhunger** [comment]
This issue has already been opened. Look into previous issues before opening new ones! 
check #640

**Comment by Rakesh9100** [comment]
Links on the home page are working properly, please create valid issues @kashisharora9462
