### ISSUE TITLE
[Style] Enhance the heading in Contact form

### ISSUE THREAD

**Issue by ayush-848** [Rakesh9100/CalcDiverse#754]
### What's the style idea?

![image](https://github.com/Rakesh9100/CalcDiverse/assets/126975547/ce64d3ad-da30-4694-9467-0a6285c3218f)

I will give it a darker effect and hover effect in styling.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @ayush-848
