### ISSUE TITLE
[Feature] Add the scroll to top button in Contributors page

### ISSUE THREAD

**Issue by Scrapper700** [Rakesh9100/CalcDiverse#755]
### Description

Add the scroll to top button in Contributors page for better UI.

### Screenshots

![Screenshot (234)](https://github.com/Rakesh9100/CalcDiverse/assets/113296663/fea340fe-8523-42d5-b9eb-40056419c233)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Scrapper700** [comment]
@Rakesh9100 can you please assign this issue under gssoc

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/ca21f544-484d-4467-83b4-7c0b857ca93f)

We already have the good clear visible button, closing the issue @Scrapper700

**Comment by Rakesh9100** [comment]
Proceed and make sure to add the same button which is on the home page @Scrapper700

**Comment by Scrapper700** [comment]
Okay!! @Rakesh9100 please assign the level

**Comment by Rakesh9100** [comment]
Provide your PR pls @Scrapper700

**Comment by Scrapper700** [comment]
@Rakesh9100 I was not getting time to do this..Will it be a problem if i give after 2days since my exams are going on
