### ISSUE TITLE
[Style] Enhance the navbar color

### ISSUE THREAD

**Issue by yogita-github** [Rakesh9100/CalcDiverse#756]
### What's the style idea?

We need to change the color of Navbar.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by yogita-github** [comment]
@Rakesh9100 please assign me this issue by including labels to it.

**Comment by Rakesh9100** [comment]
What color combination you want to use, as it is perfectly alright now @yogita-github

**Comment by yogita-github** [comment]
Can I change the color of navbar to something like this ? If it works for you!
![Screenshot (3058)](https://github.com/Rakesh9100/CalcDiverse/assets/103029645/4bf1cc76-9aa7-4a2d-ab59-fb635e409769)

**Comment by Rakesh9100** [comment]
No, pls work on other good issues @yogita-github

**Comment by yogita-github** [comment]
okay
