### ISSUE TITLE
[Feature] Implement classification of Calculators

### ISSUE THREAD

**Issue by saketh-05** [Rakesh9100/CalcDiverse#757]
### What's the style idea?

As there are too many calculators, I want to classify them into several categories, so that users can access them easily without going through all of the calculators. This makes website look more modern. Please assign this issue to me under GSSoC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saketh-05** [comment]
More importantly, when viewing website from mobile, the scrolling time to end of website will become short and easy. So please assign this issue to me.

**Comment by Rakesh9100** [comment]
Do you have any supporting screenshots @saketh-05

**Comment by saketh-05** [comment]
Yes sir, I have few ideas. 
![Screenshot 2024-05-24 061339](https://github.com/Rakesh9100/CalcDiverse/assets/134281589/2bb242ad-6345-4b6f-81de-15cf1472e395)
![Screenshot 2024-05-24 061400](https://github.com/Rakesh9100/CalcDiverse/assets/134281589/9a810c72-e7fd-4740-9086-d26e8b67505e)
![Screenshot 2024-05-24 061426](https://github.com/Rakesh9100/CalcDiverse/assets/134281589/1b33918f-415b-4e56-b645-3d00179e9bd8)
![Screenshot 2024-05-24 061432](https://github.com/Rakesh9100/CalcDiverse/assets/134281589/6f189d10-bb9f-4588-b37e-fbcd2622f5a0)
![Screenshot 2024-05-24 061303](https://github.com/Rakesh9100/CalcDiverse/assets/134281589/7cdf4c95-8274-436d-b8eb-f1aa4e21f9d9)

**Comment by saketh-05** [comment]
Please assign me this issue under GSSOC'24.

**Comment by Rakesh9100** [comment]
Implementing this idea will change the current UI which I don't want as it looks good @saketh-05

**Comment by saketh-05** [comment]
@Rakesh9100  Sir, I want to classify them and classified title are added to header and footer only. But the Main UI will not change, changes will only be added header and footer.

**Comment by AkhilaSunesh** [comment]
I have an idea, it is better to create a drop-down menu or a filter to resolve this issue. It can be segregated based on the subjects and fields related.
![WhatsApp Image 2024-05-27 at 21 59 29_100632ac](https://github.com/Rakesh9100/CalcDiverse/assets/140897461/8790ef96-f648-4495-a477-94fdf418406f)
I can resolve this issue in such a way that the UI would not get affected and it will increase the user experience. 
Pls assign me with this issue.

**Comment by Rakesh9100** [comment]
> @Rakesh9100 Sir, I want to classify them and classified title are added to header and footer only. But the Main UI will not change, changes will only be added header and footer.

Header and footer that means navbar and footer or below the navbar, there would be any section? @saketh-05

**Comment by saketh-05** [comment]
@Rakesh9100 There would be sections, below the navbar and above the footer just as in above mentioned screenshots for idea.

**Comment by Rakesh9100** [comment]
Take a look, review this issue and provide your suggestions @jessicachawla @Nihal4777

**Comment by jessicachawla** [comment]
@saketh-05 the footer is just the all calculators button? Also will you be putting the home/back button and how will you segregate math calculator from algebra because algebra is a subset of math? 
Regarding the UI, will you be keeping the same colors and theme as in the current website?
