### ISSUE TITLE
Differential Calculator

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/CalcDiverse#76]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This calculator evaluates the Differential equations like sin(x) into cos(x)
Can your assign me this issue under SWOC'24 

### Screenshots

![Screenshot 2024-01-03 214322](https://github.com/Rakesh9100/CalcDiverse/assets/142514166/138c31c7-9ad8-47fe-a0b4-a4c665037384)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
