### ISSUE TITLE
[Feature] Add Binary Decimal Calculator

### ISSUE THREAD

**Issue by ChhaviRohilla** [Rakesh9100/CalcDiverse#763]
### Description

A calculator to convert binary to decimal.
@Rakesh9100 assign this to me

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by 90firoj** [comment]
I would like to work on this project . please assign it to me .

**Comment by ChhaviRohilla** [comment]
@Rakesh9100 or project admin kindly assign this task so I can open a pull request

**Comment by ChhaviRohilla** [comment]
Hi @Rakesh9100 
I would like to be assigned to this issue and add this feature to the website. This contribution is for GSSoC'24.

**Comment by Rakesh9100** [comment]
We already have Number System Calculator for this, pls create new issues @ChhaviRohilla

**Comment by ChhaviRohilla** [comment]
> We already have Number System Calculator for this, pls create new issues @ChhaviRohilla
okay , I have raised another issue as well

check the issue https://github.com/Rakesh9100/Beautiify/issues/792
