### ISSUE TITLE
[Docs] Add Code of Conduct & Contributing guidelines file

### ISSUE THREAD

**Issue by aasthakourav20** [Rakesh9100/CalcDiverse#769]
### Category of documentation update

A Code of Conduct is crucial for maintaining a respectful and inclusive community. It sets clear expectations for behavior and outlines the steps for reporting and addressing unacceptable behavior. Here’s why it’s important:

-Sets Behavioral Expectations: It clearly defines acceptable and unacceptable behavior, helping to create a welcoming and inclusive environment for all participants.
-Promotes Respect and Inclusivity: It encourages respect and inclusivity, ensuring that everyone feels safe and valued within the community.
-Conflict Resolution: It provides guidelines on how to handle conflicts and what actions will be taken in response to violations, promoting fairness and transparency.

The Contributing file provides guidelines for how to contribute to the project. This includes everything from coding standards and style guides to how to submit pull requests and report issues. Here’s why it’s essential:

-Encourages Contributions: It provides clear instructions on how to get involved, making it easier for newcomers to start contributing.
-Maintains Quality: It sets standards for contributions, ensuring that new code and documentation meet the project's quality requirements.
-Streamlines the Process: It outlines the process for submitting contributions, reducing friction and confusion for contributors and maintainers alike.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have these both, pls go through the repository properly and then create your issues @aasthakourav20 

[Check here](https://github.com/Rakesh9100/CalcDiverse/tree/main/.github)!!
