### ISSUE TITLE
[SWOC'24] Factorial Calculator

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/CalcDiverse#77]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- Enter the number, project will return the factorial of that entered number instantly.
- Card and colouring effect to attract users.
- Animated effects.

### Screenshots

This calculator will help user to calculate large number factorials in a very little period of time.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this project to work on it and contribute in your repo under SWOC'24

**Comment by Rakesh9100** [comment]
Go ahead @Avdhesh-Varshney

**Comment by Yuvraj960** [comment]
hello @Avdhesh-Varshney, I would like to work on this issue
