### ISSUE TITLE
[Feature] Add Binomial Distribution Calculator

### ISSUE THREAD

**Issue by Sara1428** [Rakesh9100/CalcDiverse#773]
### Description

I made a calculator on values of probability distribution function of a random binomial variable. It was a new kind of calculator from the existing ones. Please review my request.

### Screenshots

![calc](https://github.com/Rakesh9100/CalcDiverse/assets/146193518/66b52ecf-5243-4398-9138-e86b83e42b4a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Sara1428
