### ISSUE TITLE
[Style] Equal the card size

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/CalcDiverse#777]
### What's the style idea?

It would be great if we make all card of similar size.

![Screenshot 2024-05-22 041725](https://github.com/Rakesh9100/CalcDiverse/assets/142779809/6b992ec8-81c0-4b75-b1f8-5c39847a228e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GauriGA** [comment]
@Rakesh9100 Could you please assign this issue to me under the GSSOC'24 label?
