### ISSUE TITLE
[Bug] Fix the alignment of contributor icon

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/CalcDiverse#778]
### Description

As the alignment of the contributor's profile image in not well-defined, I will fix it.

![Screenshot 2024-05-22 042059](https://github.com/Rakesh9100/CalcDiverse/assets/142779809/f56ddec3-49ac-4c5c-a475-a21a7b09126a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls specify clearly what is not well-defined @root-0101

**Comment by root-0101** [comment]
- As you can all the images are not in straight row some are little bit up and down and also is has extra negative space

![Screenshot 2024-05-22 042059](https://github.com/Rakesh9100/CalcDiverse/assets/142779809/c237a0a2-71a0-46e0-b6d6-11e8de6f8ad2)

**Comment by Rakesh9100** [comment]
Okay, go ahead @root-0101
