### ISSUE TITLE
[Bug] Fix the scroll to top button overlap for small devices

### ISSUE THREAD

**Issue by kapilG0** [Rakesh9100/CalcDiverse#780]
### Description

![Screenshot_20240522_121728](https://github.com/Rakesh9100/CalcDiverse/assets/59639410/9959f6a1-0b19-48cd-a02a-d628e2f6591e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kapilG0** [comment]
Hello @Rakesh9100 please assign this issue to me under gssoc 24

**Comment by ShrutiSaw** [comment]
I want to contribute to this project. please assign this to me.
Thankyou.

**Comment by Rakesh9100** [comment]
Pls specify in the description properly that what do you want to fix @kapilG0

**Comment by kapilG0** [comment]
> Pls specify in the description properly that what do you want to fix @kapilG0

@Rakesh9100 as you can see in footer there is icon which is overlapping footer content that things I want to fix

**Comment by Rakesh9100** [comment]
Okay proceed and just do the changes for small devices as that is Scroll to top button @kapilG0

**Comment by kapilG0** [comment]
Hello @Rakesh9100 . i have raised pr https://github.com/Rakesh9100/CalcDiverse/pull/909 for this issue. please check

**Comment by kapilG0** [comment]
> Hello @Rakesh9100 . i have raised pr #909 for this issue. please check

Hello @Rakesh9100 . i modified changes and added in same pr please check

**Comment by kapilG0** [comment]
Hello @Rakesh9100 please closed this issue as pr already merged and please add label gssoc as well
