### ISSUE TITLE
[Style] Equal the card size

### ISSUE THREAD

**Issue by Nikhil11200** [Rakesh9100/CalcDiverse#782]
### What's the style idea?

There is some difference in the size of the boxes of different calculators . Please assign me this issue to fix this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already opened for this, pls create new issues @Nikhil11200
