### ISSUE TITLE
[Docs] Fix the typo in readme

### ISSUE THREAD

**Issue by ishap11** [Rakesh9100/CalcDiverse#783]
### Category of documentation update

The change falls under the category of Typo error
![Screenshot 2024-05-22 224906](https://github.com/Rakesh9100/CalcDiverse/assets/128213933/c7e4bdc5-e25a-4c1a-a661-5559e3984a7e)

### Describe the change you think might work

Hello, my name is Isha Prajapati.
I noticed a small typo in the "Getting Started" section. "Perfom" should be corrected to "Perform." This change will make the instructions clearer and improve the overall quality of the documentation.
I'm eager to contribute under GSSOC'24 and would like to request the assignment of this task.
Thank you!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @ishap11
