### ISSUE TITLE
[Feature] Add the favicon to each calculator's page

### ISSUE THREAD

**Issue by Meetjain1** [Rakesh9100/CalcDiverse#786]
### Description

Favicon is not there in all the calculators , It is only there in the home page 
@Rakesh9100 assign this issue to me I will make it in all the pages

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Meetjain1

**Comment by Rakesh9100** [comment]
Status of your PR @Meetjain1

**Comment by Meetjain1** [comment]
Working @Rakesh9100 will raise PR soon .
