### ISSUE TITLE
[Feature]  Add Productivity Calculator

### ISSUE THREAD

**Issue by EshaalakshmiDS** [Rakesh9100/CalcDiverse#789]
### Description

This calculator could help users estimate the time saved or productivity gained by implementing various productivity techniques or habits. By helping users quantify the potential benefits of productivity techniques and habits, the Productivity Calculator could empower individuals to make informed decisions about how to optimize their time and achieve their goals more efficiently.

**Features:**

1. Technique Selection: Choose from a range of productivity methods.
2. Customizable Parameters: Input specific parameters for accurate calculations.
3. Instant Results: Receive immediate insights into time saved or productivity gained.
4. Goal Setting: Set ambitious productivity goals based on calculated outcomes.
5. Actionable Insights: Receive personalized recommendations for maximizing productivity.
6. User-Friendly Interface: Navigate the intuitive interface effortlessly.
7. Trackable Progress: Monitor productivity evolution over time for continuous improvement.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by EshaalakshmiDS** [comment]
@Rakesh9100 I request you to please review and assign me this issue under GSSOC'24 label, and also to assign level label.

**Comment by Rakesh9100** [comment]
Go ahead @EshaalakshmiDS
