### ISSUE TITLE
[Feature] Enhance General Root Calculator UI

### ISSUE THREAD

**Issue by manishh12** [Rakesh9100/CalcDiverse#795]
### Description

This calculator would enable users to find the nth root of a given number, providing a convenient tool for various mathematical and scientific calculations. With this calculator, users could easily compute roots of any degree, expanding the range of mathematical operations they can perform.
@Rakesh9100  please assign me this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have General Root Calculator for this, you can enhance its UI if you want @manishh12

**Comment by manishh12** [comment]
> We already have General Root Calculator for this, you can enhance its UI if you want @manishh12

Yeah it's actually there. Okay i will work on the ui enhancement. 
Features: 
1) will make responsive for different sizes screen. 
2) ui enhancement
@Rakesh9100 kindly assign me.

**Comment by Rakesh9100** [comment]
Provide your PR @manishh12
