### ISSUE TITLE
[Bug] Fix the footer broken links

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#799]
### Description

Footer links are not working or are wrong most of the pages

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/6e119bb5-ae1b-42dc-b40d-a03ab44a459d)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/9f22c86f-a8b9-4021-82c4-9ef782e3c288)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls create new issues @agastya3636
