### ISSUE TITLE
[SWOC24] Time Calculator

### ISSUE THREAD

**Issue by shivamm-verma** [Rakesh9100/CalcDiverse#80]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- Enter Time in any format (hours, minutes, seconds), this will show other two formats of time.
- better UI by adding shadows, and background.

### Screenshots

*screenshot*

![ss1](https://github.com/Rakesh9100/CalcDiverse/assets/98605616/1b8bc2de-0239-47b7-92a0-af3eb7bc8990)

*screen recording* 

https://github.com/Rakesh9100/CalcDiverse/assets/98605616/b44638ec-ecbe-42ff-a8d7-99153b1db151

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by shivamm-verma** [comment]
Please Assign this ISSUE to me so that I can work on this.

**Comment by Rakesh9100** [comment]
Proceed @shivamm-verma
