### ISSUE TITLE
[Bug] Make Compound Interest Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#801]
### Description

Compound Interest Calculator is not responsive . I would like to make it responsive.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/66cefe9c-def8-4737-8ba3-ece99555d5eb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @agastya3636

**Comment by Rakesh9100** [comment]
Status of your PR @agastya3636
