### ISSUE TITLE
[Bug] Currency calculator is not loading

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#802]
### Description

Currency calculator is not loading.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/e71cb533-df04-4a5f-8215-3643f72455dc)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anmolgupta2004** [comment]
i will work on it

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls check the existing issues before creating a new one @agastya3636
