### ISSUE TITLE
[Style] Make Bill Split Calculator responsive

### ISSUE THREAD

**Issue by Kashishgarg248** [Rakesh9100/CalcDiverse#808]
### What would you like to share?

![IMG_20240523_234848](https://github.com/Rakesh9100/CalcDiverse/assets/153218193/2f49b6f1-846d-47d2-a584-3801a48b257a)

### Additional information

In Split bill calculator, the background box is very small and the letters are getting out of it. So, I request you to assign me this issue. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to work on responsiveness of this calculator @Kashishgarg248

**Comment by Kashishgarg248** [comment]
Yes sir

**Comment by Rakesh9100** [comment]
Okay, go ahead @Kashishgarg248

**Comment by Rakesh9100** [comment]
Provide your PR pls @Kashishgarg248
