### ISSUE TITLE
[Feature] Add Roman Numeral Calculator

### ISSUE THREAD

**Issue by sweta-singh28** [Rakesh9100/CalcDiverse#810]
### Description

This calculator would convert numbers written in the roman number system to decimal number system.

Please assign me this issue so I can start working on it

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @sweta-singh28
