### ISSUE TITLE
[Feature] Add Astrological Age Calculator

### ISSUE THREAD

**Issue by abhay-sen** [Rakesh9100/CalcDiverse#811]
### Description

i want to add a calculator that would convert a persons age based on the time the planets take to revolve around the solar system and hence converting a persons age from earth years to some other planets years
please assign me this issue so that i can start working on this 
@Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @abhay-sen

**Comment by abhay-sen** [comment]
thank you @Rakesh9100 i will start working on this asap!
