### ISSUE TITLE
[Feature] Add Time Complexity Calculator

### ISSUE THREAD

**Issue by Janani-m17** [Rakesh9100/CalcDiverse#815]
### Description

I will add a time complexity calculator which will tell the time complexity of a program which is given as input. The output will the time complexity based of programming techniques.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124059957/cda2b29b-59db-46fe-a708-ab2607ceb196)
Time complexity calculator is not in the list.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

@Rakesh9100

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by Rakesh9100** [comment]
Proceed @Janani-m17

**Comment by Janani-m17** [comment]
@Rakesh9100 
Thank you sir.
