### ISSUE TITLE
[Bug] Display No results found message

### ISSUE THREAD

**Issue by Janani-m17** [Rakesh9100/CalcDiverse#816]
### Description

If the user is searching a calculator and it is not found in the predefined calculators in websites it should display the message "no results found". By customizing the html and css code i will solve this issue.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124059957/88dbb595-a3ca-4eca-a6b9-3a22a7d4a3ec)
Here time complexity calculator is not found. But it is not displaying any message.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

@Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @Janani-m17
