### ISSUE TITLE
[Bug] Correct the calculation in CGPA Percentage Calculator

### ISSUE THREAD

**Issue by nehashekhawat255** [Rakesh9100/CalcDiverse#819]
### Description

To Convert CGPA into percentage we need to multiply the cgpa with 9.5 and for percentage to cgpa we need to divide percentage with 9.5 then we get the correct percentage and cgpa.
I have attached the screenshots. Please check that when I have given the percentage 88.6 it is giving cgpa 10.93 which is not a correct cgpa.

Please assign this issue to me under GSSoC'24, I will correct these issues and will also update your cgpa percentage calculator's readme as well.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/114082299/8be2496b-9b34-41f1-9aab-22691eb2fe2b)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/114082299/a9382f31-4fc3-404f-b588-207036ad1a36)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @nehashekhawat255
