### ISSUE TITLE
[Feature] Add Retirement Calculator

### ISSUE THREAD

**Issue by kamalesh-og** [Rakesh9100/CalcDiverse#822]
### Description

Hello Project Admin @Rakesh9100,
Adding a Retirement Calculator to CalcDiverse, enables users to estimate the amount needed for retirement planning. This calculator will help individuals by allowing them to input their current age, desired retirement age, current savings, annual contribution, and expected annual return on investment. Based on this information, the calculator will provide an estimate of the amount needed to save for retirement.

I've already worked with CalcDiverse and imposed a calculator before and I want to contribute further to this amazing repository.

@Rakesh9100 Can you assign me this project, I would like to work on this Calculator.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/163159351/9b51dcea-5083-4ade-bc38-b4f385d66dd1)
This is just the outline of the page, for reference
I'll further add the CSS and Javascript for this page to make it dynamic and more efficient.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed and make a good UI @kamalesh-og
