### ISSUE TITLE
[Feature] Add Debt-To-Income Ratio Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#827]
### Description

Debt-to-income ratio (DTI) is the ratio of total debt payments divided by gross income (before tax) expressed as a percentage, usually on either a monthly or annual basis.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yuvraj960** [comment]
@Rakesh9100 Please assign this issue to me, I have already started working on this issue with submit the pull request as fast as possible

**Comment by Rakesh9100** [comment]
Proceed and keep the folder name as `DTI-Ratio-Calculator` @Yuvraj960
