### ISSUE TITLE
[Feature] Add Average Calculator

### ISSUE THREAD

**Issue by Janani-m17** [Rakesh9100/CalcDiverse#829]
### Description

When user set of n number of values and after clicking calculate it will display the average of the set of values.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124059957/97ac82b8-b726-42dd-886c-bfcd06a273e0)
There is no average calculator available.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

Please assign this issue to me sir.
@Rakesh9100

**Comment by Rakesh9100** [comment]
We already have `Averages Calculator`. Pls create new issues and first work on previously assigned issues @Janani-m17
