### ISSUE TITLE
[Feature] Add Random Number Calculator

### ISSUE THREAD

**Issue by Janani-m17** [Rakesh9100/CalcDiverse#830]
### Description

The random number generator gets two input from user upper limit and lower limit. And then user will click generate a random number button which will generate a random number in that limit.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124059957/8bd7eda8-e276-4fc5-afca-eb4d8eac3ca5)

Please assign this issue to me sir.
@Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your previous assigned issues @Janani-m17

**Comment by AkhilaSunesh** [comment]
I am confident that I can work on this. Please assign me this issue

**Comment by Janani-m17** [comment]
@Rakesh9100 Sir i have completed the previous issues. Kindly assign me this issues.

**Comment by Janani-m17** [comment]
@Rakesh9100 Kindly assign this issue sir

**Comment by Rakesh9100** [comment]
Go ahead @Janani-m17

**Comment by Janani-m17** [comment]
@Rakesh9100 Thank you sir for assigning this issue to me
