### ISSUE TITLE
[Feature] Add Password Strength Calculator

### ISSUE THREAD

**Issue by Janani-m17** [Rakesh9100/CalcDiverse#831]
### Description

If the user enters a password and then click the button calculate the strength. The strength is calculated based on certain criteria such as Uppercase, symbols, numbers, length of password.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124059957/36a8a832-6fbe-4b20-8c44-5fd6801714a3)

Please assign this issue to me sir.

@Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls don't open too many issues at once before completing previous opened issues @Janani-m17

**Comment by AkhilaSunesh** [comment]
I am confident that I can work on this. Please assign me this issue

**Comment by Janani-m17** [comment]
@Rakesh9100 sir, I have completed the previous assigned issues. Please assign this issue to me.

**Comment by Janani-m17** [comment]
@Rakesh9100 Thank you sir for assigning this issue to me
