### ISSUE TITLE
[Feature] Add Random Word Generator Calculator

### ISSUE THREAD

**Issue by Dhevamuthu** [Rakesh9100/CalcDiverse#832]
### Description

This feature involves adding a random word generator tool to GitHub issues, allowing users to generate unique and random words for use in issue titles or descriptions. The tool will help users who struggle with naming or describing issues by providing them with creative and diverse word choices, improving the clarity and specificity of issue communication.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
CalcDiverse contains different mathematical calculators but I don't think a Random Word Generator is a kind of mathematical calculator @Dhevamuthu

**Comment by Rakesh9100** [comment]
Do you want to be assigned @Dhevamuthu

**Comment by Dhevamuthu** [comment]
> Do you want to be assigned @Dhevamuthu

Yes @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @Dhevamuthu

**Comment by Dhevamuthu** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/123234572/5ed5261e-9fc0-4120-8b3d-cb32417f68cf)
 if I enter w and 99 count,
 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/123234572/0f7813f1-8c62-4b21-b48a-fc45cd39fce1)

please check through it and say me if changes required.. @Rakesh9100
