### ISSUE TITLE
[Feature] Add Random Letter Generator Calculator

### ISSUE THREAD

**Issue by swetha5157** [Rakesh9100/CalcDiverse#833]
## Description
A random letter generator is a tool or software designed to produce a random letter from a specific alphabet set, such as the English alphabet (A-Z). The generation process is typically driven by a randomization algorithm, which ensures that each letter has an equal probability of being selected.

## Feature
* Randomization Algorithm: Utilizes a computational method to ensure true randomness, often based on pseudo-random number generators (PRNGs).

* Customizable Alphabet Sets: Allows users to choose different alphabets or character sets, including uppercase letters, lowercase letters, or even non-Latin scripts.

* Frequency Settings: Some generators let users adjust the frequency or probability of specific letters appearing, which can be useful for language-based studies or games.

* Applications of this calculator:
  * Educational Tools: For learning and teaching alphabets or phonics.
  * Games and Puzzles: To create random challenges or for use in word games like Scrabble or Boggle.
  * Creativity and Writing: To provide prompts or inspirations for writers and artists.
  * Data Sampling: For creating randomized data sets in scientific and statistical research.

* User Interface: Typically features a simple button to generate a letter, with results displayed prominently. Advanced tools may include options for generating multiple letters at once or exporting results.

 
Kindly assign to me @swetha5157  under gssoc'24

### Screenshots

![Screenshot 2024-05-24 155157](https://github.com/Rakesh9100/CalcDiverse/assets/123291594/b71b5582-a796-4c7c-bb6c-f9a49c6820e1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
CalcDiverse contains different mathematical calculators but I don't think a Random Letter Generator is a kind of mathematical calculator @swetha5157

**Comment by Rakesh9100** [comment]
Okay, go ahead, don't be sorry @swetha5157

**Comment by swetha5157** [comment]
Thankyou @Rakesh9100 and kindly add level labels.
Thankyou
