### ISSUE TITLE
[Feature] Add Nutrition Calculator

### ISSUE THREAD

**Issue by Dhevamuthu** [Rakesh9100/CalcDiverse#835]
### Description

This project involves creating a web-based nutrition calculator using HTML, CSS, and JavaScript. The nutrition calculator will allow users to input the quantity and nutritional information (such as calories, protein, fat, carbohydrates, etc.) of various food items. It will then calculate and display the total nutritional values based on the input provided by the user. The calculator will offer a simple and intuitive interface for users to track their nutritional intake and make informed dietary choices.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Dhevamuthu

**Comment by Dhevamuthu** [comment]
Can u assign level label for it @Rakesh9100

**Comment by Rakesh9100** [comment]
Label will be added after the PR is up! @Dhevamuthu

**Comment by Dhevamuthu** [comment]
https://github.com/Rakesh9100/CalcDiverse/assets/123234572/e87312b8-5dbc-4d05-9638-f00e792b638c

please check to this, and say me for alteration if needed @Rakesh9100

**Comment by Rakesh9100** [comment]
Where is the option to add more food items and then calculate at last, will user calculate for a single food only @Dhevamuthu

**Comment by Dhevamuthu** [comment]
Okay.
Can I do like this in such a way that when user enters the details for food item 2 , it should be displayed at the bottom of food item 1 details results

**Comment by Rakesh9100** [comment]
Yes you can @Dhevamuthu
