### ISSUE TITLE
[Bug] Fix the email validation in Contact form

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [Rakesh9100/CalcDiverse#836]
### Description

The user can submit the contact form with any email extensions , so that it would be an trouble. If we don't validate the mail it will leads to decrease in trust of the user about the website and it will lead to data leakage. So that I can do that validation and I request you to assign me this issue.

### Screenshots

![WhatsApp Image 2024-05-24 at 12 43 20_b3638cf2](https://github.com/Rakesh9100/CalcDiverse/assets/125359008/1acff811-bb0a-4a87-8cdd-95c6601792b3)

![WhatsApp Image 2024-05-24 at 12 43 32_35d0ea5a](https://github.com/Rakesh9100/CalcDiverse/assets/125359008/79626a5c-10ee-42ae-a7ad-47bdd328f066)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Since Netlify manages the form submission, so how will you validate the email @GnanariddhikaRavikumar

**Comment by Rakesh9100** [comment]
Do you want to be assigned @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
Yes @Rakesh9100 .

**Comment by Rakesh9100** [comment]
Go ahead @GnanariddhikaRavikumar

**Comment by Rakesh9100** [comment]
Status of your PR @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
Working on it will update you soon @Rakesh9100

**Comment by GnanariddhikaRavikumar** [comment]
I resolved this issue and raised the PR @Rakesh9100
