### ISSUE TITLE
[Style] Make CGPA Percentage Calculator responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/CalcDiverse#838]
### Description

 CGPA To percentage calculator is not responsive so In mobile view it is not clearly visible

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124435030/edf24265-4d52-4d3f-99fd-0591c4820356)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by Rakesh9100** [comment]
Provide your PR @agastya3636

**Comment by agastya3636** [comment]
I am facing issue i will soon resolve it and send the pr

**Comment by Rakesh9100** [comment]
Is your issue resolved @agastya3636

**Comment by agastya3636** [comment]
No working on it
