### ISSUE TITLE
[Feature] Add Salary Estimation Calculator

### ISSUE THREAD

**Issue by mythri1010** [Rakesh9100/CalcDiverse#839]
### Description

The salary estimation calculator is a tool designed to give users an approximate idea of the salary they might expect based on the key factors such as Years of Experience, Education Level, Location (City, State, Country), Industry, and Skills/Certifications. 
The calculator utilizes a multiple linear regression model to estimate salary. The formula used here includes a term representing the fixed base salary and coefficients for each input variable, reflecting the additional salary increase associated with variable changes. This model implements coefficients for each input variable to estimate its impact on salary based on the change in the input factors. 

Purpose: The calculator aims to assist individuals in estimating salaries for various job roles. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by mythri1010** [comment]
hi @Rakesh9100, pls assign me this issue under GSSOC'24, i would like to implement this feature with the help of HTML, CSS and Javascript.
Thank you

**Comment by Rakesh9100** [comment]
Are you going to use any ML model? Which tech stacks are you going to use for this calculator @mythri1010

**Comment by mythri1010** [comment]
No, I'm planning not to use ML for this, but I will be implementing predefined data estimated as Coefficients for each variable mentioned above like years of experience, education, and so on, basically it's a formula multiplied with a general increase in salary hike for every variable. This efficiently estimates basic expected salaries. Coming to the tech stacks, for frontend, i ll be using HTML, CSS and for backend, I will use js  
@Rakesh9100

**Comment by Rakesh9100** [comment]
Okay, go ahead @mythri1010

**Comment by mythri1010** [comment]
> Okay, go ahead @mythri1010 

Okay thank you
