### ISSUE TITLE
[Feature] Add Running Pace Calculator

### ISSUE THREAD

**Issue by priyavratamohan** [Rakesh9100/CalcDiverse#840]
### Description

The Running Pace Calculator can estimate the pace for a variety of activities, including running, walking, and biking. The calculator can also be used to estimate the time taken or distance traveled with a given pace and time or distance.

The Calculator will take in **Time in HH:MM:SS** and **Distance** in desired units _(Kilometers, Miles, Meters, Yards)_, including some predefined units like _Marathon, Half-Marathon etc._, and calculate the Running Pace.

The same calculator can be again used to calculate time and distance using Pace and Distance & Pace and Time, if provided, respectively.

Please assign me this Issue under the Label of **GSSoC '24 and add label 'level 1'/'level 2'/'level 3' according to your discretion**. I will use HTML, CSS and JavaScript to implement it. Thank you!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by priyavratamohan** [comment]
Hi @Rakesh9100, could you please assign me this Issue under the Label of GSSoC '24. I will use HTML, CSS and JavaScript to implement it. Thank you!

**Comment by Rakesh9100** [comment]
Proceed @priyavratamohan 

Label will be added after your PR is up!

**Comment by Rakesh9100** [comment]
Provide your PR @priyavratamohan

**Comment by priyavratamohan** [comment]
I'll just take a little more while, please wait. 🙏🏼
