### ISSUE TITLE
[Feature] Add Profit Loss Calculator

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [Rakesh9100/CalcDiverse#842]
### Description

Here we have many calculator in our website. In this if we add **Profit Loss Calculator** it will be a added advantage. In this Calculator we will be able to calculator whether the product sold was profit or loss. Kindly allow me to do this and assign this issue to me along with Gssoc and level labels @Rakesh9100 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/125359008/58b105b6-75bb-471c-a651-59850c837dba)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
Ok sir. thank you

**Comment by GnanariddhikaRavikumar** [comment]
Sir. I have assigned with two issues.I have completed one and raised the PR. Once after merging it can I commit and raise PR sir. Since the commits will be conflicting. @Rakesh9100

**Comment by Rakesh9100** [comment]
Yes, you can raise your PR one by one but complete ASAP @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
Ok @Rakesh9100

**Comment by GnanariddhikaRavikumar** [comment]
@Rakesh9100  I'm having a doubt that I can create the fork of the repository only once then if i make changes it will affect the already raised PR . Then how can I raise the PR Separately??

**Comment by Rakesh9100** [comment]
That is why it is said to create every PR with new changes in a separate branch and not in the main branch of your forked repo which avoids these conflicts, you can go through the steps to how to create a PR in new branch in the Readme file @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
Ok thank you
