### ISSUE TITLE
[Feature] Calcuating Area

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [Rakesh9100/CalcDiverse#843]
### Description

Here we have many calculator in our website. Now we are going to add Area calculator. Area Calculator will be used to calculate area based on the shapes. It will be helpful for school Students who can verify their answers. I can able to work on this so kindly assign me this issue @Rakesh9100 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/125359008/1f5aef39-8409-4c49-b47d-9aecb912fb1c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have 2D Shapes Calculator for the same @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
Ok sir
