### ISSUE TITLE
[Feature] Implement workflow for closing old PRs

### ISSUE THREAD

**Issue by Asymtode712** [Rakesh9100/CalcDiverse#844]
### Description

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Screenshots

![Close Old PRs](https://github.com/Rakesh9100/CalcDiverse/assets/115717746/e9e64e15-9a35-4194-b516-b2b3c609d9ca)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Asymtode712** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
I don't think there is a need of this workflow as I am active towards Open Source checking issues and PRs in timely manner, pls work on other issues @Asymtode712
