### ISSUE TITLE
[Feature] Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [Rakesh9100/CalcDiverse#845]
### Description

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Screenshots

![Close Old Iss](https://github.com/Rakesh9100/CalcDiverse/assets/115717746/a0c3b0a0-a5db-4647-a499-cc8948ae28f6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Asymtode712** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
I don't think there is a need for this workflow as I am active towards Open Source checking issues and PRs in a timely manner, pls work on other issues @Asymtode712
