### ISSUE TITLE
[Feature] Add auto commenting workflow when an issue is closed

### ISSUE THREAD

**Issue by Asymtode712** [Rakesh9100/CalcDiverse#846]
### Description

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Screenshots

![issue closed](https://github.com/Rakesh9100/CalcDiverse/assets/115717746/9e446663-16c5-457b-b97c-66aa9cb17bce)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Asymtode712** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @Asymtode712

**Comment by Rakesh9100** [comment]
Provide your PR @Asymtode712

**Comment by Asymtode712** [comment]
@Rakesh9100 Done
