### ISSUE TITLE
[Feature] Add Leap Year Calculator

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [Rakesh9100/CalcDiverse#847]
### Description

Adding Leap Year calculator- **Leap Year**, **people says that it comes once in 4 years** but there are some exceptional cases, where leap year doesn't occur like in same pattern. For eg: **1896 is a leap year but after 4 years 1900 is not a leap year**. So we are adding the calculator which says whether the year entered is leap year or not . I can able to do this so kindly assign me this issue @Rakesh9100 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/125359008/88727a21-b4b0-4edd-a4af-fad12a16d09e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by Rpokhariya** [comment]
Please assign gssoc24 tags to the issue, I would like to resolve the issue.

**Comment by Rakesh9100** [comment]
Go ahead @GnanariddhikaRavikumar
