### ISSUE TITLE
Segregate Data into a JSON file

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/CalcDiverse#85]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to say, 
- Keep the data of the calculators in a seprate JSON file.
- Segregate the data into a seprate `data.json` file which keeps project link, project, description, title, etc.
- Fetch everything from that json file using script.
- Finally, render the card into index.html file or website.

### Screenshots

This will helps,
- In maintaining the code in a seprate file.
- Code will be cleaned.
- More readable project.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 i would like to work on this issue and hoping a positive response from your side.
This also helps for the contributor to just add the data into a seprate file like `data.json` file.
This will a great contribution of mine under SWOC'24.

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign it to me. This will be a great contribution under SWOC'24

**Comment by Rakesh9100** [comment]
Pls hold for now and work on other issues assigned to you @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this task to me now.

**Comment by Rakesh9100** [comment]
Currently, I want to keep the project code simple without JSON as there are many new contributors in this program @Avdhesh-Varshney
