### ISSUE TITLE
[Bug] Fix scroll to top icon for small devices

### ISSUE THREAD

**Issue by sharmi4590** [Rakesh9100/CalcDiverse#856]
### Description

The icon's missing in scroll to top button.

### Screenshots

![Screenshot_20240524-225853](https://github.com/Rakesh9100/CalcDiverse/assets/102676949/f896796f-f2b7-4fd1-bb30-83a0029ee425)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/73993775/55cc7bf9-7fa9-4243-b0ed-79e7a275bf15)

It is properly visible to me @sharmi4590

**Comment by sharmi4590** [comment]
@Rakesh9100 Once check by opening the link in your mobile , you will get to see that there's no icon. The reason behind this is mobile browser's can't infer width/height like desktop does. I know how to solve this.

**Comment by Rakesh9100** [comment]
Go ahead then @sharmi4590
