### ISSUE TITLE
[Feature] Add Calorie Consumed Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#862]
### Description

We have
1. Calorie burnt calculator
2. Calorie intake calculator to calculate the required amount of food intake 

But we don't have the calculator to **calculate the actual amount of calorie consumed by a person**

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/117537653/3671f710-79fe-4e92-a476-f62df8f14116)

I think we should add a calorie consumed calculator

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by debangi29** [comment]
Please assign me the issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @debangi29
