### ISSUE TITLE
[Feature] Removing duplicacy in root calculators.

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#863]
### Description

There exists square root, cube root calculator and also the nth root calculator in the website.
Both of the square root and cube root calculator can be removed as they're just adding up to the redundancy and not providing any unique functionality.
This will help in reducing redundancy present.

Instead only nth root calculator should be present.

Kindly assign this issue to me under GSSOC'24.
Thanks!

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/116306749/97d97d8e-b1f2-4cb2-80ce-8d56b7f4b520)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We're keeping all three calculators to provide users with specific tools for quick calculations and ensure ease of use for all preferences, so pls work on other issues @Aarzookhunger
