### ISSUE TITLE
[Feature] Hydration Calculator

### ISSUE THREAD

**Issue by Nayanika1402** [Rakesh9100/CalcDiverse#864]
### Description

This calculator will recommend daily water intake based on weight and activity level.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have `Water Intake Calculator`. Pls create new issues @Nayanika1402
