### ISSUE TITLE
[Feature] Remove duplicacy in Square & Cube Calculator and Exponent calculator.

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#866]
### Description

The Exponent Calculator already exists so there's no point of keeping separate Square and Cube calculator.
It is only adding up to the redundancy and hence can be removed.

Exponent Calculator can serve the purpose of Square and Cube calculator.

Kindly assign this issue to me under GSSOC'24.
Thanks!

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/116306749/638835fa-75f6-4c72-932a-85c82734c5aa)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/116306749/3809380e-65e2-4e89-a8bc-17f9c57ec71e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We will keep both as square and cube is the most used common calculator, whereas exponent one can be used for degree more than 3 @Aarzookhunger
