### ISSUE TITLE
[Feature] Add Inverse Function Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#867]
### Description

Given a function calculate its inverse. Given f(x); find f^(-1)(x)
For example,
f(x)=8x-7
then f^(-1) x= (x+7)/8

### Screenshots

Not applicable

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by debangi29** [comment]
Please assign me the issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @debangi29

**Comment by debangi29** [comment]
@Rakesh9100 ,
Calculating the inverse function of all basic functions manually is not possible
Since many of them don't have an inverse.
Only basic Function can be implemented in that way

Is it fine if I use the API key of WolframAlpha to calculate the inverse of functions or should I implement the basic functions?

**Comment by debangi29** [comment]
![image](https://github.com/Rakesh9100/CalcDiverse/assets/117537653/155d068f-fdca-4030-9211-f7efb799475e)

If I use API, We can get a detailed output like this of all types of functions

**Comment by Rakesh9100** [comment]
You can proceed with the API key if it don't have any request limit @debangi29

**Comment by debangi29** [comment]
Okay!! Thanks :). I have added the calculator

**Comment by debangi29** [comment]
I have done the required changes. Thank you
