### ISSUE TITLE
[Feature] Add Dora Calculator

### ISSUE THREAD

**Issue by Tamilkumaran17** [Rakesh9100/CalcDiverse#868]
### Description

Dora have some issues in her eyes so that she can't able to see the things which is nearby or faraway from her eye site.
for that i like to make an calculator to check if the entered distance can be visible by dora or not.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Tamilkumaran17** [comment]
"Dora the Explorer" is a famous cartoon character beloved by children. In the show, Dora often asks viewers for help finding objects that are right in front of her. It can be quite frustrating how she sometimes fails to notice things that are nearby. To improve this, Dora could use help from her friend, Map, who can guide her to see the objects clearly within her line of sight.
With the help of map, the map can give the distance of the object. with that we can calculate the distance from Dora to that thing which can be visible by her or not is the motive of this issue.

**Comment by Rakesh9100** [comment]
Go ahead @Tamilkumaran17
