### ISSUE TITLE
Enhance Navbar 

### ISSUE THREAD

**Issue by CodeByRajeev** [Rakesh9100/CalcDiverse#87]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This issue is to enhance the nav bar and make it more responsive for the user.
- Good styling.
- Effective hover effects.
- Interactive color balance.

The changes can be seen in the below attached screenshots.

### Screenshots

**Present Navbar :**

![Navbar 1 before](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/fc108476-1cf2-4a76-aa0b-08cfeda10e04)

![Nav before 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/5c4f5f47-a2f8-4c78-9daa-7451b5ce1ce7)

![Nav logo before 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/7402e317-06d0-401a-8c5a-4914ca9caa35)

**Navbar after making improvements :**

![Navbar 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/29fcf9e0-5771-49a7-839a-99a0948ba5d7)

![Nav after 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/0f3cf77c-409d-4c15-a9f8-cdcf09252783)

![Nav logo after 1](https://github.com/Rakesh9100/CalcDiverse/assets/112249927/7d4e8178-3a83-4f99-a3df-7fe018d8198c)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by CodeByRajeev** [comment]
@Rakesh9100 sir I hope this issue enhances the present navbar and adds value to the project. Hope I get this issue assigned and start working on it.

**Comment by sonappatil** [comment]
I would like to contribute on this issue can you plz  assign this to me under swoc'2024

**Comment by CodeByRajeev** [comment]
Hey @sonappatil , I hope you understand that I have raised the issue and also the coding part has been done. I am waiting for the issue to be assigned. I kindly request you to work on any better issue.

**Comment by Rakesh9100** [comment]
Proceed @CodeByRajeev
