### ISSUE TITLE
[Feature] Add Ideal Gas Law Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#870]
### Description

Various parameters can be calculated for an ideal gas; pressure, volume, moles, temperature, density, concentration, molecular mass, and many more, also in different units
I guess adding an ideal gas calculator would be useful

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by debangi29** [comment]
Please assign me the issue @Rakesh9100

**Comment by debangi29** [comment]
Since, I have finished doing the tasks I was assigned, can I start working on this issue?
@Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @debangi29
