### ISSUE TITLE
[Feature] Add Ohms Law Calculator

### ISSUE THREAD

**Issue by Swarnav-Kumar** [Rakesh9100/CalcDiverse#871]
### Description

1.The calculator dynamically computes the missing values when at least two input values are provided.
2.The result section updates to display the calculated values in a clear and formatted manner.
3.The page includes basic styling to make it visually appealing and user-friendly.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GauriGA** [comment]
@Rakesh9100 I would like to work on this issue, could you assign me this under the GSOC'24 label?

**Comment by Rakesh9100** [comment]
Proceed @Swarnav-Kumar

**Comment by Rakesh9100** [comment]
Provide your PR @Swarnav-Kumar

**Comment by Rakesh9100** [comment]
Go ahead @snigudkar
