### ISSUE TITLE
[Feature] Implement length constraint for message in Contact Us form

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#872]
### Description

In the contact us form, a check over message length should be there such as length of message should be greater than 100.
It'll help to avoid receiving empty 1-2 character messages which others may send without any purpose.

This may help in decluttering the message piles being received.

Kindly assign this issue to me under GSSOC'24!
Thanks..

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GauriGA** [comment]
@Rakesh9100 I would like to work on this issue, could you assign me this under the GSOC'24 label?

**Comment by Rakesh9100** [comment]
Go ahead @Aarzookhunger
