### ISSUE TITLE
[Feature] Add multilingual support to the website

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [Rakesh9100/CalcDiverse#873]
### Description

On exploring the CalcDiverse, I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.

### Screenshots

The below image of the website represents that it is only available in English language
![WhatsApp Image 2024-05-25 at 16 06 32_c5244dce](https://github.com/Rakesh9100/CalcDiverse/assets/139578011/9065a161-7dbd-46f3-9fa1-32dbe1515aeb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GauriGA** [comment]
@Rakesh9100 I would like to work on this issue, could you assign me this under the GSOC'24 label?

**Comment by Rakesh9100** [comment]
Go ahead @Anjankumarkamalapur

**Comment by Anjankumarkamalapur** [comment]
Done with Implementing Multilingual support. Once check it out. Thank you.
[image: image.png]

**Comment by Anjankumarkamalapur** [comment]
Can you please check it out

**Comment by m3kvt** [comment]
Hi i would like to work on this issue.

**Comment by Rakesh9100** [comment]
Go ahead @m3kvt

**Comment by m3kvt** [comment]
@Rakesh9100 Could you guide on  how to start? Like what tools to use?

**Comment by Rakesh9100** [comment]
You can utilize the Google Translation API, which supports all languages and automatically translates the website based on the user's chosen language. This is widely supported solution for multilingual website @m3kvt

**Comment by Ojas-Arora** [comment]
@Rakesh9100 I want to work on this issue
