### ISSUE TITLE
[Feature] Implement search result suggestion

### ISSUE THREAD

**Issue by sivaprasath2004** [Rakesh9100/CalcDiverse#875]
### Description

- In this project `Enter Calculator Name` search box calculator name give that has been suggest the `calculator` names.
- Example :  

### Screenshots

[Screencast from 2024-05-12 08-10-53.webm](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/121082414/efcadc0b-8489-40f7-b35b-94ed18c7b182)

- please assign me .
- I will ready for work..

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sivaprasath2004** [comment]
Hello @Rakesh9100, I'm telling about if `searcchbox` to search the name give suggesstion the available calculator's name - 

- Example for the in `search bar of the google ` if search something can `suggest` this will implement the project.
-

**Comment by Rakesh9100** [comment]
How and what kind of suggestion you will provide here when searching for any calculator @sivaprasath2004

**Comment by sivaprasath2004** [comment]
@Rakesh9100 if I want to search `A` that is matching calculator names can be showed for searching results.

**Comment by Rakesh9100** [comment]
Okay proceed @sivaprasath2004

**Comment by Rakesh9100** [comment]
Provide your PR @sivaprasath2004

**Comment by sivaprasath2004** [comment]
@Rakesh9100 i will finish it ..

**Comment by Rishikesh63** [comment]
@Rakesh9100  i wants to work on it could you please assign to me
