### ISSUE TITLE
[Style] Make Unit Calculator responsive

### ISSUE THREAD

**Issue by m3kvt** [Rakesh9100/CalcDiverse#878]
### Description

- The Unit Calculator interface is not properly adjusted for mobile screens.
- Text and input fields are cut off on the sides, making it hard to interact with the calculator effectively.
- Lack of margin results in a cluttered appearance

### Screenshots

![WhatsApp Image 2024-05-25 at 22 55 41_e379146b](https://github.com/Rakesh9100/CalcDiverse/assets/98379619/7120a786-3216-45a8-953b-51a8a46be938)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @m3kvt
