### ISSUE TITLE
[Feature] Add Buzz Number Calculator

### ISSUE THREAD

**Issue by vedanshipathak** [Rakesh9100/CalcDiverse#885]
### Description

I can add a buzz number calculator which can check a number is buzz or not.
A number is said to be Buzz Number if it ends with 7 OR is divisible by 7. The task is to check whether the given number is buzz number or not. Examples: Input : 63 Output : Buzz Number Explanation: 63 is divisible by 7, one of the condition is satisfied.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @vedanshipathak

**Comment by bheemajayashreee** [comment]
Please assign this issue to me @Rakesh9100
