### ISSUE TITLE
[Style] Make the color of logo text same on hover

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#887]
### What's the style idea?

We need to change the color of CalcDiverse in the navbar on the main page to make the color on whole navbar similar.
This will help in maintainability of the website in the same color throughout.

![image](https://github.com/Rakesh9100/CalcDiverse/assets/116306749/14c5358e-e814-4f64-8daa-84c02be49a45)
![image](https://github.com/Rakesh9100/CalcDiverse/assets/116306749/2450a0fa-46a9-44b2-b2cb-a387ec2d8984)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GauriGA** [comment]
@Rakesh9100 I would like to work on this issue, could you assign me this under GSOC'24 label?

**Comment by Rakesh9100** [comment]
Proceed @Aarzookhunger
