### ISSUE TITLE
UI Enhancement of Contact Us page

### ISSUE THREAD

**Issue by Rishav9911** [Rakesh9100/CalcDiverse#89]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to make some relevant changes to improve the UI of the contact us page as it looks a little dull right now. Kindly assign me this issue under SWOC'24 tag.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ayan-joshi** [comment]
@Rishav9911 Can you show demo or any part of the page which you want to change or any of your work

**Comment by Rishav9911** [comment]
I want to improve the ui of this page as it looks a little old fashioned and distorted.

![Screenshot 2024-01-05 204050](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/de2b8fe3-4dcc-471d-b303-8a93ab52d1b0)


One of the contact us page i created few days back for my portfolio website is below.

![Screenshot 2024-01-05 204214](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/5261a763-b66e-4166-9275-373b7f09a777)

**Comment by Rakesh9100** [comment]
Proceed @Rishav9911

**Comment by Shaba1406** [comment]
@Rishav9911 Hey, how is the work going on ? What's the update ?

**Comment by Rishav9911** [comment]
hey there, am still working on it , i'll share some samples soon !!

**Comment by Rishav9911** [comment]
I have come up with some samples, does any of the below looks feasible or do i need to make some improvements?

1.
![Screenshot (40)](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/0bb03ff3-2192-44ca-9a06-a2c0de1e7b60)

2.
![Screenshot (41)](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/eeb83642-d760-4e77-835c-aa287df99388)

3.
![Screenshot (42)](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/33fd3e47-270f-4abb-bb0b-b5a7021f2b74)

![Screenshot (43)](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/a5df35db-7f64-4f94-abcc-85f6988c34fb)

**Comment by Shaba1406** [comment]
In my Opinion 2nd one looks Better

**Comment by Shaba1406** [comment]
@Rakesh9100 Please Have a look on these designs

**Comment by Rakesh9100** [comment]
Yes, you can go with the second one but make the background of that character purple @Rishav9911

**Comment by Rishav9911** [comment]
I tried different colours for the background which also match the UI of the overall website. Does any of it looks suitable so i can proceed to commit. kindly provide with the feedback.

1. 
![Screenshot 2024-01-07 193615](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/cea22bad-f170-4366-a71d-275bcede165e)


2.
![Screenshot 2024-01-07 193440](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/efcd68d9-144d-40fe-b89b-da16002be55d)


3.
![Screenshot 2024-01-07 193245](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/d9a6cbe8-26ce-473e-950e-0133280afb80)

**Comment by Rakesh9100** [comment]
1. You can go with the first one.
2. Center the SEND button and increase it font a little.
3. Add good animation and hover effect to SEND button.
4. Scrollbar should not come in Message box.

**Comment by Rakesh9100** [comment]
1. You can go with the first one.
2. Center the SEND button and increase it font a little.
3. Add good animation and hover effect to SEND button.
4. Scrollbar should not come in Message box.

Pls work on these @Rishav9911

**Comment by Rishav9911** [comment]
I have made the desired changes as you have mentioned. 


![Screenshot 2024-01-07 200147](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/93e91be6-3ec7-42ea-833d-89dedb8f4d5c)

on hover send button:

![Screenshot 2024-01-07 200535](https://github.com/Rakesh9100/CalcDiverse/assets/133174630/47b5384f-32df-4d07-a6cd-ad00eb821b09)
