### ISSUE TITLE
[Feature] Introduce mode change

### ISSUE THREAD

**Issue by Coding-Charvi** [Rakesh9100/CalcDiverse#891]
### Description

change dark and light mode

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Amrapali06** [comment]
hey,  can you assign me this issue as i can fix this

**Comment by Rakesh9100** [comment]
Issue 515 is already open for this, you can comment on that if you want to work @Coding-Charvi
