### ISSUE TITLE
[Style] Enhance Explore Calculators button

### ISSUE THREAD

**Issue by sakshi261203** [Rakesh9100/CalcDiverse#894]
### What's the style idea?

Adding a glowing button effect to the button is a great way to enhance the user experience on the website. It can improve the button's visibility, especially for users with certain visual impairments, and add a touch of interactivity that can make the process feel more engaging.
I'd like to propose adding a subtle glowing button effect to the Explore Calculators button. This could be implemented with pure CSS and would involve adding a hover effect that creates a glowing animation around the button when a user hovers their mouse over it.
I think this would be a great way to [ e.g. improve the button's visibility, make the login process more engaging] and I'm confident that I can implement this change using my skills in CSS. I've been working on similar effects recently, and I'm confident I can deliver a high-quality solution.

Here's are some samples of the button:
![Screenshot (6891)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/82ccc33e-c83d-4e94-8b3f-f7c6ea6d0485)
![Screenshot (6892)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/a13a9020-116d-4666-ba4f-45f8925edaae)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sakshi261203** [comment]
Hi Rakesh Roshan, Could you please assign this task to me..

**Comment by Rakesh9100** [comment]
Which login button are you talking about as we don't have any such button on our website @sakshi261203

**Comment by Rakesh9100** [comment]
Proceed @sakshi261203

**Comment by sakshi261203** [comment]
Sorry, there is a typo error . Actually I want to change the hover effect
of Explore Calculators button.

**Comment by sakshi261203** [comment]
Could you please help me....

**Comment by Rakesh9100** [comment]
What kind of error are you facing, share the screenshot on my social handle @sakshi261203
