### ISSUE TITLE
[Style] Enhance social media icons

### ISSUE THREAD

**Issue by sakshi261203** [Rakesh9100/CalcDiverse#895]
### What's the style idea?

**Highlight the user experience (UX) benefits**: "I'd like to propose adding hover effects to the social media icons. This would make the icons more interactive and engaging for users, and it would also provide a clearer visual cue that the icons are clickable links."

![Screenshot (6897)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/ac7693e9-15d0-41fa-9054-16e2a474fb0e)
![Screenshot (6900)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/819f7776-4968-4e1a-8bca-a7f5fbf18fb4)
![Screenshot (6901)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/903f3066-f8a6-428e-b5b4-ae1300c7b820)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sakshi261203** [comment]
Hi Rakesh Roshan, Could you please assign me this issue..

**Comment by Shobhitsingh-2503** [comment]
@Rakesh9100 can this issue be assigned to me ?

**Comment by Amrapali06** [comment]
hey , i can contribute on this issue

**Comment by sakshi261203** [comment]
Hi Rakesh Sir, could you please assign this task to me..

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @sakshi261203

**Comment by Rakesh9100** [comment]
Do you want to work on this @sakshi261203

**Comment by sakshi261203** [comment]
Yes, I would.

**Comment by sakshi261203** [comment]
Yes Sir

**Comment by Rakesh9100** [comment]
Go ahead @sakshi261203

**Comment by sakshi261203** [comment]
Sir, there is a doubt 
Whenever i open CalcDiverse website in netlify  it will show like this
![Screenshot (7231)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/cb70b76d-4448-411b-9e7a-c00fb9e32472)
and when i clone the repo and open the website it will show like this
![Screenshot (7230)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/f4aa87b8-4693-4049-8a49-c4b38ec88a53)
so what should I do because after cloning the repo the footer icons were less than it show in netlify app link which is given to the main page.

**Comment by Rakesh9100** [comment]
The repo fork on your GitHub handle is not updated, do update your forked branch and then clone the repo @sakshi261203

**Comment by sakshi261203** [comment]
Ok sir

**Comment by sakshi261203** [comment]
Sir I have created a pull request but it shows like this...
![Screenshot (7239)](https://github.com/Rakesh9100/CalcDiverse/assets/163162219/f1cf8c11-4834-4390-95e9-38cabe9c7994)
Could you please tell me what should I do?

**Comment by Rakesh9100** [comment]
You have not added and committed your changes nicely, pls message me on LinkedIn or discord project channel @sakshi261203
