### ISSUE TITLE
[Feature] Add Electric Power Calculator

### ISSUE THREAD

**Issue by manishh12** [Rakesh9100/CalcDiverse#896]
### Description

An electrical power calculator is a tool used to compute the power dissipated or consumed by an electrical circuit or device. It typically requires input values such as voltage and current and calculates the resulting power output or consumption. 

The calculation of electrical power is governed by Ohm's Law, which states that the power (P) in an electrical circuit is equal to the product of the voltage (V) across the circuit and the current (I) flowing through it. Mathematically, this relationship can be expressed as:

 $$ \[ P = V \times I \]$$

Where:
- \( P \) is the power in watts (W).
- \( V \) is the voltage in volts (V).
- \( I \) is the current in amperes (A).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by manishh12** [comment]
@Rakesh9100 please assign me the above issue.

**Comment by Rakesh9100** [comment]
Go ahead @manishh12
