### ISSUE TITLE
[Style] Enhance Antilog Calculator UI

### ISSUE THREAD

**Issue by AnandK-pm** [Rakesh9100/CalcDiverse#897]
### What's the style idea?

We need to improve
* Overall UI
* Responsiveness
* Color aesthetics
* Hover, animation effects.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AnandK-pm** [comment]
Currently the webpage uses primitive HTML CSS Styling. I intend to improve the overall UI of it to ensure a user-friendly experience.
Please assign me this issue so that i can work on it.

![Screenshot 2024-05-26 224712](https://github.com/Rakesh9100/CalcDiverse/assets/142206618/144e2a16-d7ff-447a-aca7-3da63155d932)

**Comment by GauriGA** [comment]
@Rakesh9100 Can you assign me this issue?

**Comment by Shobhitsingh-2503** [comment]
@Rakesh9100, can this issue be assigned to me ?

**Comment by Rakesh9100** [comment]
Go ahead @AnandK-pm

**Comment by Rakesh9100** [comment]
Provide your PR @AnandK-pm

**Comment by AnandK-pm** [comment]
> Provide your PR @AnandK-pm 

Working has almost finished. Requesting some more time as I'm unable to provide the PR now,  being out of station.

**Comment by Rakesh9100** [comment]
Okay but do complete ASAP @AnandK-pm

**Comment by AnandK-pm** [comment]
> Okay but do complete ASAP @AnandK-pm 

Sure. Will do.
