### ISSUE TITLE
[Feature] Add Planetary Motion Calculator

### ISSUE THREAD

**Issue by Sara1428** [Rakesh9100/CalcDiverse#902]
### Description

This calculator feature enables user to calculate various parameters of planetary motion, such as orbital time period, lengths of semi-major and semi-minor axes and areal velocity, based on Kepler's laws of planetary motion. 
Please consider this issue.

### Screenshots

![page1](https://github.com/Rakesh9100/CalcDiverse/assets/146193518/3b50e746-6193-4e24-9d9a-2779c5c89706)
![page2](https://github.com/Rakesh9100/CalcDiverse/assets/146193518/014457ee-85a8-43ba-86aa-991ad791d7ed)
![page3](https://github.com/Rakesh9100/CalcDiverse/assets/146193518/593bdd52-275e-4e6b-8f48-6031ccd020b2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Sara1428
