### ISSUE TITLE
[Feature] Add Resistor Color Code Calculator

### ISSUE THREAD

**Issue by Uday2902** [Rakesh9100/CalcDiverse#903]
### Description

Resistor Color Code Calculator allows users to determine the resistance value of resistor by selecting the appropriate color bands, multiplier, and tolerance options.

For reference, please visit the - [Digi-Key Resistor Color Code Calculator](https://www.digikey.in/en/resources/conversion-calculators/conversion-calculator-resistor-color-code).

I would like to work on adding this calculator. 

I request you to assign this issue to me.

Below is a screenshot for reference : 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/127274394/ee700d1d-4bc8-40a1-8b9d-a9e18fe75d2c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have 4 Band Resistor Calculator and issue is already opened for 5 Band @Uday2902

**Comment by Uday2902** [comment]
I apologize for the oversight. Please go ahead and close this issue as it was my mistake.
