### ISSUE TITLE
[Style] Enhance Air Quality Index Calculator UI

### ISSUE THREAD

**Issue by Adv1919** [Rakesh9100/CalcDiverse#916]
### What's the style idea?

We need to improve the background interface of the calculator as it interferes with the text and makes it look clustered.
We can change the background image as well as text color to make it look user appealing.

![Screenshot (119)](https://github.com/Rakesh9100/CalcDiverse/assets/146080896/9e1d5d46-16aa-48ab-ace2-63fe59dd859d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Adv1919
