### ISSUE TITLE
[Other] Fix grammar errors in the About Us section

### ISSUE THREAD

**Issue by sandy-queen** [Rakesh9100/CalcDiverse#917]
### What would you like to share?

There are a few grammatical errors and issues with sentence structures in the "About" section. For example, the beginning sentence of the "OUR MISSION" part is very long and complex. Its length can be reduced to make it easy to read and understand. 

There are also a few punctuation errors in the paragraphs. 

I can rework the sentences, and fix the grammar. This will make the website more user-friendly and easy to use. 

Please assign this issue to me. 

### Additional information

![about section](https://github.com/Rakesh9100/CalcDiverse/assets/147652780/1512e3ff-6b4e-4905-92eb-f3bfee1157cf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @sandy-queen
