### ISSUE TITLE
Adding a Definite Integral Calculator 

### ISSUE THREAD

**Issue by Devanshu53** [Rakesh9100/CalcDiverse#92]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Want to contribute by a adding a calculator that takes input as a integral and limits and give output or answer

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @Devanshu53
