### ISSUE TITLE
[Feature] Add Hexadecimal Calculator

### ISSUE THREAD

**Issue by Yashgabani845** [Rakesh9100/CalcDiverse#923]
### Description

propose the addition of a hexadecimal calculator feature to our application. The hexadecimal calculator will enable users to perform arithmetic operations, conversions, and manipulations specifically with hexadecimal numbers.

### Screenshots

![Screenshot (138)](https://github.com/Rakesh9100/CalcDiverse/assets/127788321/f1a8510f-fa53-44f8-b387-7b72f9a757da)
![Screenshot (139)](https://github.com/Rakesh9100/CalcDiverse/assets/127788321/8bcbdaac-4f04-4055-a5c9-6853bc54cc87)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yashgabani845** [comment]
@Rakesh9100 kindly assign me this issue this is demo i will add more operation like bitwise or,and etc.

**Comment by Yashgabani845** [comment]
@Rakesh9100 response to this issue please

**Comment by Rakesh9100** [comment]
Proceed @Yashgabani845
