### ISSUE TITLE
[Feature] Add Amortization Calculator

### ISSUE THREAD

**Issue by Yashgabani845** [Rakesh9100/CalcDiverse#928]
### Description

 financial tool used to determine the repayment schedule of a loan, typically a mortgage or car loan. It calculates the periodic payments and the distribution of those payments between principal and interest over the life of the loan.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yashgabani845** [comment]
@Rakesh9100 
please remove it from standby i have done my previous isue checkout PR an assign me please

**Comment by Rakesh9100** [comment]
Proceed @Yashgabani845
