### ISSUE TITLE
[Feature] Add Body Fat Percentage Calculator

### ISSUE THREAD

**Issue by manishh12** [Rakesh9100/CalcDiverse#929]
### Description

To calculate body fat percentage, you can use various methods,One of the more accessible methods for many people is using body circumference measurements along with formulas such as the U.S. Navy Method.

Here is how you can calculate your body fat percentage using the U.S. Navy Method:

### For Men:
1. Measure the circumference of your neck (below the larynx, with the tape sloping slightly downward to the front).
2. Measure the circumference of your waist (at the level of your navel).
3. Measure your height.

### For Women:
1. Measure the circumference of your neck (below the larynx, with the tape sloping slightly downward to the front).
2. Measure the circumference of your waist (at the narrowest point).
3. Measure the circumference of your hips (at the widest point).
4. Measure your height.

### Formulas:
- **For Men:**
  $$\text{Body Fat Percentage} = 86.010 \times \log_{10}(\text{waist} - \text{neck}) - 70.041 \times \log_{10}(\text{height}) + 36.76\$$
  
- **For Women:**
  
  $$\text{Body Fat Percentage} = 163.205 \times \log_{10}(\text{waist} + \text{hips} - \text{neck}) - 97.684 \times \log_{10}(\text{height}) - 78.387$$
  

Here, the measurements for waist, neck, hips, and height should be in the same units (either all in inches or all in centimeters).

@Rakesh9100 Please assign me this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rashi0409** [comment]
@Rakesh9100 Please assign me this issue. I am a GSSOC'24 contributor.

**Comment by Yashgabani845** [comment]
@rashi0409 i have implemented much part of this calculator 
so you can work on any other issue

**Comment by manishh12** [comment]
> ### Description
> To calculate body fat percentage, you can use various methods,One of the more accessible methods for many people is using body circumference measurements along with formulas such as the U.S. Navy Method.
> 
> Here is how you can calculate your body fat percentage using the U.S. Navy Method:
> 
> ### For Men:
> 1. Measure the circumference of your neck (below the larynx, with the tape sloping slightly downward to the front).
> 2. Measure the circumference of your waist (at the level of your navel).
> 3. Measure your height.
> 
> ### For Women:
> 1. Measure the circumference of your neck (below the larynx, with the tape sloping slightly downward to the front).
> 2. Measure the circumference of your waist (at the narrowest point).
> 3. Measure the circumference of your hips (at the widest point).
> 4. Measure your height.
> 
> ### Formulas:
> * **For Men:**
>   Body Fat Percentage=86.010×log10⁡(waist−neck)−70.041×log10⁡(height)+36.76
> * **For Women:**
>   Body Fat Percentage=163.205×log10⁡(waist+hips−neck)−97.684×log10⁡(height)−78.387
> 
> Here, the measurements for waist, neck, hips, and height should be in the same units (either all in inches or all in centimeters).
> 
> @Rakesh9100 Please assign me this issue.
> 
> ### Screenshots
> _No response_
> 
> ### Checklist
> * [x]  I have checked the existing issues.
> * [x]  I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
> * [x]  I am a GSSOC'24 contributor.
> * [ ]  I am a IWOC'24 contributor.
> * [ ]  I am a JWOC'24 contributor.
> * [ ]  I am a SWOC'24 contributor.
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

@Rakesh9100 Kindly assign this issue so that i can start working on that

**Comment by manishh12** [comment]
@Rakesh9100 kindly assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead @manishh12
