### ISSUE TITLE
[Feature] Add Military Time Calculator

### ISSUE THREAD

**Issue by skshrinaya** [Rakesh9100/CalcDiverse#940]
### Description

This update adds a new feature to the calculator project: a Military Time Converter. This feature allows users to convert standard 12-hour time format (AM/PM) to 24-hour military time format and vice versa. This functionality is particularly useful for users who need to work with different time formats in various professional and personal contexts.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @skshrinaya

**Comment by Rakesh9100** [comment]
Provide your PR @skshrinaya

**Comment by skshrinaya** [comment]
As my exams are going on I will it submit it tomorrow
