### ISSUE TITLE
[Feature] Add Magic Number Calculator

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/CalcDiverse#941]
### Description

I can add a magic number calculator which can check a number is magic number or not.
A number is said to be a magic number, if the sum of its digits are calculated till a single digit recursively by adding the sum of the digits after every addition. If the single digit comes out to be 1,then the number is a magic number.
1252
1+2+5+2=10 => 1+0=1

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by debangi29** [comment]
Please assign me the issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @debangi29
