### ISSUE TITLE
[Feature] Add download result functionality to Age Calculator

### ISSUE THREAD

**Issue by coderiksenthil** [Rakesh9100/CalcDiverse#944]
### Description

This PR adds a new feature to the age calculator web application: the ability to generate a PDF document containing the calculated age results. When the user clicks the "Share Results" button, a PDF document is generated with the age, months, weeks, days, hours, minutes, and seconds displayed. This functionality enhances the usability of the age calculator by providing users with a convenient way to save and share their age calculations.

Additionally, the code is already prepared and ready for implementation, I kindly request to be assigned to this task.

### Screenshots

Before
![image](https://github.com/Rakesh9100/CalcDiverse/assets/66522620/95b0fe5f-626a-4853-91a6-44d5859e128b)
After 
![image](https://github.com/Rakesh9100/CalcDiverse/assets/66522620/6a847729-9bf2-4272-b77e-58c8958106cc)
PDF
![image](https://github.com/Rakesh9100/CalcDiverse/assets/66522620/90fe67ba-3535-4d8e-aea8-0ea4896c8be2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @coderiksenthil

**Comment by coderiksenthil** [comment]
Thank You for merging my PR @Rakesh9100 🙂
