### ISSUE TITLE
[Feature] Add Sleep Cycle Calculator

### ISSUE THREAD

**Issue by anagha-chaudhari** [Rakesh9100/CalcDiverse#946]
### Description

I wish to add a Sleep Cycle Calculator which calculates ideal time to go to bed and to wake up based upon the scientific 90-minute sleep cycles. 

- Desired wake up time will be taken as input and it will return few optimal timings at which user should fall asleep in order to achieve a complete healthy sleep cycle. It will also return number of sleep cycles one will cover with respect to each bedtime respectively

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by anagha-chaudhari** [comment]
Hi @Rakesh9100 can you assign this issue to me?

**Comment by Rakesh9100** [comment]
Go ahead @anagha-chaudhari
