### ISSUE TITLE
Mass to Weight Converter

### ISSUE THREAD

**Issue by AryanKhokhar1** [Rakesh9100/CalcDiverse#949]
### Description

In this feature we will convert mass to weight and  weight to weight based on different different planet.
like weight of a person on earth is 75kg  this his/her weight on Jupiter will be 189.53

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Astrological Age Calculator, pls create new issues @AryanKhokhar1
