### ISSUE TITLE
[Feature] Inclusion of Length Conversion Calculator

### ISSUE THREAD

**Issue by swetha5157** [Rakesh9100/CalcDiverse#951]
### Description

# Description
A Length Conversion Calculator is a tool designed to convert measurements from one unit of length to another. It is widely used in various fields such as science, engineering, construction, and everyday life to ensure accurate measurement and compatibility across different unit systems.
# Features:
## User-Friendly Interface:
* The calculator typically features a straightforward interface where users can input the value they wish to convert.
* A dropdown menu or selection buttons allow users to choose the units they are converting from and to.
## Wide Range of Units:
* Supports a comprehensive list of length units including meters, kilometers, centimeters, millimeters, inches, feet, yards, miles, nautical miles, and more.
* Some calculators also include lesser-known units like micrometers, nanometers, angstroms, and astronomical units.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/123291594/f2aa6828-013f-4d11-b043-5fe44b2793cc)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Calculator named Length Calculator, pls create new issues @swetha5157
