### ISSUE TITLE
improve the hover effect at social media icon....and changr the hover color on its

### ISSUE THREAD

**Issue by shuhaki** [Rakesh9100/CalcDiverse#952]
### Description

added a hover effect on this social media icon
and improve the hover color on its

### Screenshots

<img width="333" alt="Screenshot 2024-05-28 at 11 58 54 PM" src="https://github.com/Rakesh9100/CalcDiverse/assets/145912232/127b3fa8-4b85-47c5-accc-07bb5e2b92e8">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Priyamjain1105** [comment]
Hi @shuhaki ,

I'd like to work on issue #952. Can you please assign it to me?

Thanks

**Comment by Rakesh9100** [comment]
Issue is already open for it, pls work on good issues @shuhaki
