### ISSUE TITLE
[Feature] Add 6 Band Resistance Calculator

### ISSUE THREAD

**Issue by AkhilaSunesh** [Rakesh9100/CalcDiverse#953]
### Description

**Usage:** Electrical and Electronics
It is a 6 band color code resistor
More info in the table attached below.
![image](https://github.com/Rakesh9100/CalcDiverse/assets/140897461/5eb1fabd-cdab-4c4f-8768-986f20165176)

Pls assign me with this issue

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/140897461/aa150d7e-6fc1-42e5-8ccf-b36ec613aba7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AkhilaSunesh

**Comment by Rakesh9100** [comment]
Any update of your PR @AkhilaSunesh

**Comment by ANKeshri** [comment]
@Rakesh9100 @jesssicacha  can i work on this issue please assign me he is not active i will create this

**Comment by anijit18** [comment]
@Rakesh9100  Please assign me this issue under GSSOC. I would like to work on it.

**Comment by SakshiLingwal** [comment]
Hey @Rakesh9100 I'd successfully added this calculator along with other calculators .And it's working absolutely fine. If you allow i'll raise PR for this issue.
![image](https://github.com/user-attachments/assets/87996760-bf02-4f1e-baa1-3b142413bde5)

**Comment by Rakesh9100** [comment]
Sure go ahead @SakshiLingwal

**Comment by suhanipaliwal** [comment]
Could you please assign this issue to me
