### ISSUE TITLE
[Feature] Add TNEA Cut Off Calculator

### ISSUE THREAD

**Issue by dharshini2022** [Rakesh9100/CalcDiverse#955]
### Description

Engineering admissions in Tamil Nadu are based on TNEA cut-offs. In this calculator, with the student's scores, the cut-off will be calculated. Please assign labels and assign me this issue under GSSOC 24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @dharshini2022

**Comment by Rakesh9100** [comment]
Pls provide your PR @dharshini2022

**Comment by dharshini2022** [comment]
@Rakesh9100 Can you pls give 2 days. I'll submit within a couple of days

**Comment by Rakesh9100** [comment]
Ok but try to but complete ASAP @dharshini2022

**Comment by Rakesh9100** [comment]
Will close the issue by tomorrow if PR is not up @dharshini2022

**Comment by dharshini2022** [comment]
Sorry for posting the PR late. I had University exams. Please review my pull request and if any changes to be made, I'm happy to work on them. It was great working on your project! Thanks for providing me with this opportunity @Rakesh9100 .
