### ISSUE TITLE
[Feature] Split bill amount and Tip Calculator

### ISSUE THREAD

**Issue by MadMax1311** [Rakesh9100/CalcDiverse#957]
### Description

This calculator is designed to compute the total cost of bill, add tip (like %5, %20, etc), and split bill according to members enter (like 2, 4, etc) 

Please @Rakesh9100 assign labels and assign me this issue under GSSOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have `Bill Split Calculator` and `Tip Calculator`. Pls create new issues @MadMax1311

**Comment by MadMax1311** [comment]
ok my mistake sorry for that
