### ISSUE TITLE
[Feature] Add Curve Fitting Calculator

### ISSUE THREAD

**Issue by DivyaVijay1234** [Rakesh9100/CalcDiverse#962]
### Description

Greetings @Rakesh9100,
I propose to create a calculator that aims to provide the best-fitting curve (straight line, quadratic, cubic, exponential, etc.) of a given set of points or coordinates using regression libraries and other functions.
Please assign this issue to me under Gssoc24. I look forward to working with you and contributing towards your organization.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DivyaVijay1234

**Comment by Rakesh9100** [comment]
Status of your PR @DivyaVijay1234

**Comment by DivyaVijay1234** [comment]
@Rakesh9100 
I am nearly done with it. I am just trying to enhance a few features. I will submit it shortly.
