### ISSUE TITLE
[Feature] Add Height Calculator

### ISSUE THREAD

**Issue by Aarzookhunger** [Rakesh9100/CalcDiverse#963]
### Description

Converts height from feet and inches to centimeters and meters and vice versa.

Kindly assign this issue to me under GSSOC'24!
Thanks.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Aarzookhunger
