### ISSUE TITLE
[Feature] Add Marks Percentage Calculator

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/CalcDiverse#967]
### Description

User Enter how many subject is there.
Then Enter marks of each 
In last click Submit and get Percentage of that marks.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What would be the name of your calculator @zalabhavy

**Comment by zalabhavy** [comment]
@Rakesh9100  Marks to Percentage

**Comment by Rakesh9100** [comment]
Okay proceed, keep the name as `Marks-Percentage-Calculator` @zalabhavy
