### ISSUE TITLE
[Feature]Tip Calculator

### ISSUE THREAD

**Issue by Aditi22Bansal** [Rakesh9100/CalcDiverse#968]
### Description

Calculates tip amount based on the bill total and tip percentage.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142652964/f238a4f4-899e-4069-be14-df4adb52497c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Tip Calculator, pls create new issues @Aditi22Bansal
