### ISSUE TITLE
[Feature] Add Entropy Calculator

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Rakesh9100/CalcDiverse#971]
### Description

 Adding an entropy calculator 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the description of what this calculator will do clearly @SuhainaFathimaM

**Comment by Rakesh9100** [comment]
Any update on this @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
Entropy Calculator calculates the entropy from the probabilities which is the input..

Eg : 
You tell the function the probabilities of picking each color: 
For example, you might tell it that there's a 25% chance of picking a red ball, a 50% chance of picking a blue ball, and a 25% chance of picking a green ball.
The function calculates the entropy: 

probabilities = [0.25, 0.5, 0.25]  ---> Input

1. entropy = 0
2. probability = 0.25
   - 0.25 * math.log2(0.25) = 0.5
   - entropy = 0 + 0.5 = 0.5
3. probability = 0.5
   -  0.5 * math.log2(0.5) = 0.5
   - entropy = 0.5 + 0.5 = 1.0
4. probability = 0.25
   - 0.25 * math.log2(0.25) = 0.5
   - entropy = 1.0 + 0.5 = 1.5

Output: entropy = 1.5


High entropy: Means a lot of uncertainty.
Low entropy: Means less uncertainty

**Comment by Rakesh9100** [comment]
Go ahead @SuhainaFathimaM
