### ISSUE TITLE
[Feature] Add Cut Off Calculator

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Rakesh9100/CalcDiverse#972]
### Description

Adding engineering and medical cut off calculator

The calculator would input 3 subject marks{
Physics, Chemistry, Maths/ Biology}
and will give the cut off as output..

(Physics/2+Chemistry/2)+(Maths)==Output
(Physics/2+Chemistry/2)+(Biology)==Output

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the description of what this calculator will do clearly @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
Adding engineering and medical cut off calculator

The calculator would input 3 subject marks{
Physics, Chemistry, Maths/ Biology}
and will give the cut off as output..

(Physics/2+Chemistry/2)+(Maths)==Output
(Physics/2+Chemistry/2)+(Biology)==Output


@Rakesh9100 I have given the description.. Please assign me this issue

**Comment by Rakesh9100** [comment]
What would be the name of your calculator and the folder name @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100  Cutoff calculator

**Comment by Rakesh9100** [comment]
Proceed @SuhainaFathimaM
