### ISSUE TITLE
[Docs] Add all the calculator names to the Readme file

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Rakesh9100/CalcDiverse#973]
### Category of documentation update

Adding All types of calculator names to the readme documentation

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
How do you want to add it @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
Yes @Rakesh9100 .. I would like to work

**Comment by Rakesh9100** [comment]
> How do you want to add it @SuhainaFathimaM

?? In which format do you want to add, is it tabular format @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 In tabular format

**Comment by Rakesh9100** [comment]
Okay proceed @SuhainaFathimaM
