### ISSUE TITLE
[Feature] Add Number System Calculator

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/CalcDiverse#975]
### Description

This calculator is used to convert the Decimal, octal, hexadecimal and octal numbers and vice versa.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Yuvraj960** [comment]
@Rakesh9100 I have made the pull requests to my recent 2 issues. Please verify those and merge if it's all correct. 😊

**Comment by Rakesh9100** [comment]
We already have Number System Calculator, pls create new issues, or you can check `up-for-grab` issues to work @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 I have commented to 4 `up-for-grab` issues. Please assign those all to me, as I can complete 2-3 issues in one day only. I want to contribute more and more in open source with a fast pace so please help me by assigning those issues. I am sure you will like all the PRs I make in those PRs
