### ISSUE TITLE
[Feature] Add Pet Age Calculator

### ISSUE THREAD

**Issue by Archiesachin** [Rakesh9100/CalcDiverse#978]
### Description

The Pet Age Calculator  converts a pet's chronological age into an equivalent human age. This feature will be useful for pet owners to better understand their pets' ages in human terms, which can vary based on the type of pet and, in some cases, the breed.

<h3>Steps to Implement</h3>
1. Identify the Pets
Determine the types of pets to include (e.g., dogs, cats, rabbits, birds).
For dogs and cats, consider including specific breeds since age conversion can differ.

2. Age Conversion Formulas
Dogs:
The American Veterinary Medical Association suggests:
15 human years for the first year of a medium-sized dog’s life.
9 human years for the second year.
5 human years for each subsequent year.
Cats:
Generally accepted conversion:
15 human years for the first year.
9 human years for the second year.
4 human years for each subsequent year.

3. Similarly we can convert the age of other pets depending on such age conversations. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have `Pet Age Calculator` @Archiesachin

**Comment by Rakesh9100** [comment]
We already have `Pet Age Calculator`, pls create new issues, or you can enhance and improve that if you want @Archiesachin
