### ISSUE TITLE
Calculator for binary/hexadecimal (base) conversions.

### ISSUE THREAD

**Issue by aaryancodeshere** [Rakesh9100/CalcDiverse#979]
### Description

# Calculator for base conversion

In today's scenario, there is a very much requirement for base conversion calculators.
It can be beneficial for a lot of students as well.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/124273822/eb41f823-2de0-4c4e-8047-f2f0d7c4fd63)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aaryancodeshere** [comment]
@Rakesh9100 please assign this to me. It is very much useful for mass.

**Comment by Rakesh9100** [comment]
We already have `Number System Calculator`, pls create new issues @aaryancodeshere
