### ISSUE TITLE
[Feat] : Add a 'day from the date' calculator

### ISSUE THREAD

**Issue by SulagnaKundu** [Rakesh9100/CalcDiverse#98]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to create a new calculator. Like, if the date, month and year is specified , we instantly get the day.
**For eg. : date : 16/01/2016
              day : Saturday**
We can name the calculator as  - **Day from the Date Calculator**

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @SulagnaKundu

**Comment by Rakesh9100** [comment]
@SulagnaKundu Status of your PR

**Comment by SulagnaKundu** [comment]
I am working on the feature. 
Will be completing it soon.
