### ISSUE TITLE
[Feature] Add Recipe Cost Calculator

### ISSUE THREAD

**Issue by Nikitakandwal** [Rakesh9100/CalcDiverse#980]
### Description

Creating a user-friendly tool to estimate meal preparation costs based on ingredients, frequency, and servings, aiding budget-conscious individuals in efficient meal planning.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
`Recipe Cost Calculator` is already present, pls create new issues @Nikitakandwal
