### ISSUE TITLE
[Feature] Add Home Security Cost Calculator

### ISSUE THREAD

**Issue by Nikitakandwal** [Rakesh9100/CalcDiverse#981]
### Description

Developing a tool to estimate the total cost of home security systems based on user inputs, assisting homeowners in planning and budgeting for their security needs.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Nikitakandwal

**Comment by Nikitakandwal** [comment]
> Proceed @Nikitakandwal

I've sent a PR. Can you please add a level label too under gssoc.
