### ISSUE TITLE
[Feature] Add Water TDS Calculator

### ISSUE THREAD

**Issue by diyaaa19** [Rakesh9100/CalcDiverse#985]
### Description

Water TDS  calculator would enable people to assess the quality of water and henceforth deciding it's drinkable or not. Almost everyday people fall ill due to consumption of contaminated water, so this calculator could help a lot of people. I would like to make this calculator, please assign this issue to me @Rakesh9100 .
thanks

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @diyaaa19

**Comment by diyaaa19** [comment]
@Rakesh9100 please add the (level ) label as well so my contribution counts towards the leaderboard.
thanks
