### ISSUE TITLE
[Feature] Add Arithmetic Geometric Progression Calculator

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#987]
### Description

AGP is a sequence where each term is the product of the terms of an Arithmetic Progression and a Geometric Progression. For example- 1+2r+3r^2+4r^3+...........upto n terms.
It will allow user to calculate the sum of the n terms of the AGP and also give the nth term of AGP  given initial term (𝑎), common difference (𝑑 ),common ratio (r) and the number of terms(n).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anshika14528** [comment]
@Rakesh9100 sir, please assign me this issue i have completed the previous issue.

**Comment by Rakesh9100** [comment]
Go ahead @Anshika14528
