### ISSUE TITLE
[Feature] : Calculate the Answer to everything

### ISSUE THREAD

**Issue by Anshika14528** [Rakesh9100/CalcDiverse#988]
### Description

There will a input box where user will type the question and then their will be a button for answer after clicking the answer button we will show "calculating..." for a short while and then this image will pop-up, with a text -- the answer to life, universe and everything is "42".
![flat,750x,075,f-pad,750x1000,f8f8f8](https://github.com/Rakesh9100/CalcDiverse/assets/168436423/cc61eff5-e1a2-40d5-b059-afe61dd1f027)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What is this calculator about @Anshika14528
