### ISSUE TITLE
[Feature] Add Twin Prime Number Calculator

### ISSUE THREAD

**Issue by Pujan-sarkar** [Rakesh9100/CalcDiverse#989]
### Description

The Twin Prime Number Calculator identifies pairs of prime numbers that have a difference of 2, known as twin primes. It checks each number up to a specified limit to determine if it and the number two greater are both prime. By iterating through numbers and verifying their primality, the calculator compiles a list of all such twin prime pairs within the given rang

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Pujan-sarkar
