### ISSUE TITLE
[BUG] : Automate the copyright year

### ISSUE THREAD

**Issue by SulagnaKundu** [Rakesh9100/CalcDiverse#99]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to change the copyright year and automate it.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by SulagnaKundu** [comment]
I want to work on this issue. Can you please assign me this issue under SWOC S4 ?

**Comment by Rakesh9100** [comment]
Proceed @SulagnaKundu

**Comment by Rakesh9100** [comment]
@SulagnaKundu Provide the status of your PR pls

**Comment by SulagnaKundu** [comment]
I am working on it.
Will complete it by today.
