### ISSUE TITLE
[Style] Improve the footer sentence

### ISSUE THREAD

**Issue by vaishali-gupta32** [Rakesh9100/CalcDiverse#990]
### What's the style idea?

We need to improve the sentence in the footer. To be precise with the professional working, the correct punctuation should be used. 

![Screenshot 2024-05-31 021016](https://github.com/Rakesh9100/CalcDiverse/assets/144541888/325e1bed-85ce-4e85-8c52-739b7c9305a4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vaishali-gupta32** [comment]
@Rakesh9100 please assign this issue to me. I'm willing to contribute in it.

**Comment by Rakesh9100** [comment]
Pls create good issues rather than just irrelevant issue @vaishali-gupta32
