### ISSUE TITLE
[Feature] Add Momentum Calculator

### ISSUE THREAD

**Issue by vaishali-gupta32** [Rakesh9100/CalcDiverse#992]
### Description

It will calculate momentum using given mass and velocity.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vaishali-gupta32** [comment]
@Rakesh9100 please assign this issue to me

**Comment by vaishali-gupta32** [comment]
@Rakesh9100 could u pls assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead @vaishali-gupta32
