### ISSUE TITLE
[Feature] Binary to Decimal and vice versa Calculator

### ISSUE THREAD

**Issue by Damini2004** [Rakesh9100/CalcDiverse#993]
### Description

A binary to decimal and decimal to binary calculator can be implemented using Python, leveraging built-in functions (int(binary, 2) and bin(decimal)[2:]). Alternative solutions include developing a web-based tool using JavaScript for broader accessibility or a mobile app with frameworks like React Native. Key features include input validation, error handling, step-by-step explanations, and support for large numbers. These options ensure user-friendly interfaces, accurate conversions, and educational value. Enhancing the tool with additional base conversions (octal, hexadecimal) could further increase its utility.

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/119414762/8757cc6c-576c-404a-83ce-9b71038ec63d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have `Number System Calculator`, pls create new issues @Damini2004
