### ISSUE TITLE
[Bug] Fix the API request on fetching contributors

### ISSUE THREAD

**Issue by pandeyji711** [Rakesh9100/CalcDiverse#996]
### Description

@Rakesh9100 While fetching contributor api is not working , it rate limit is exceeded, 
**I can fix it , please assign this to me** Mark gssoc24

### Screenshots

![Screenshot 2024-05-31 100113](https://github.com/Rakesh9100/CalcDiverse/assets/154527778/bd7c6929-3472-44a6-a64f-1571dfcc6a26)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by pandeyji711** [comment]
@Rakesh9100  please assign

**Comment by Rakesh9100** [comment]
The contributors tab is displaying all the contributors perfectly, as I can see @pandeyji711

**Comment by pandeyji711** [comment]
@Rakesh9100 but Api has only 60 request per hr ,

**Comment by pandeyji711** [comment]
@Rakesh9100 after that it show rate limit exceeded , i will use authentication , it has 5000 request per hr

**Comment by Rakesh9100** [comment]
Okay, go ahead @pandeyji711

**Comment by pandeyji711** [comment]
@Rakesh9100 can you please connect with me on linkedin for talk
